- spec.html
Fixes #1681.
Note that this races with https://github.com/tc39/ecma262/pull/2125. Whichever lands second will need to be updated to ensure the link introduced in this PR points to the right place (probably by adding a step label to the relevant section of `PropertyDefinitionEvaluation` introduced in #2125).
There's actually a second, more subtle difference, which is that `{ "__proto__": 0, "__proto__": 0 }` is valid JSON but, while it matches the `PrimaryExpression` grammar, it is not legal ECMAScript due to the early error for duplicate `__proto__` properties. ~I didn't think that worth mentioning, but I am happy to if people think it's warranted.~ Edit: that is noted as well.
cc @erights
> Editorial: note that JSON is not a semantic subset of ECMAScript

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
> Editorial: Add ECMA-402 as a Downstream dependency

- spec.html
This is a very small tweak. I find the explicit loop to be easier to understand than the previous "if there exists ... such that for all ..." prose.
> Editorial: reword StringIndexOf in terms of substring

- spec.html
Introduce `Yield` and `CreateIteratorFromClosure`, `CreateAsyncIteratorFromClosure` in the spec to make it easier to define builtin generators.
Diff: https://arai-a.github.io/ecma262-compare/?pr=2045
> Editorial: Add Yield, CreateIteratorFromClosure, CreateAsyncIteratorFromClosure abs op.

- spec.html
Move Section 25.6 Promise Objects up to become Section 25.2, below
Section 25.1 Iteration and Section 25.3 GeneratorFunction Objects,
thus also moving Sections 25.5 AsyncGenerator Objects and 25.7
AsyncFunction Objects together.
Fixes: https://github.com/tc39/ecma262/issues/1170
> Editorial: move Section 25.6 Promise Objects

- package-lock.json
- package.json
- spec.html
See commits for details. These commits can be landed individually.
This also fixes #2183 by replacing the two usages of `÷` with `/`. I couldn't find any usages of `*` for multiplication, so I think we're good there.
> Meta: bump ecmarkup (and related tweaks)

- spec.html
For consistency with `Number::signedRightShift` and `Number::unsignedRightShift`, the result of a left or right shift is a Number, so it doesn't make sense to get "the Number value for" that result.
> Editorial: Delete "the Number value for" in Number::leftShift

- spec.html
Fixes #1950. Fixes #2251.
This ensures every SDO is defined in a single place (modulo tweaks in Annex B, and excepting Early Errors and Evaluation). That way usages of SDOs can be automatically linked to their definition site, as is done for other abstract operations. This makes the spec _much_ easier to navigate, I think.
That was generally just a matter of moving things around and some minor tweaking or renaming. Most SDOs had a natural place to live: `ExportEntries` can go in the `Exports` section, say. We introduced a new top-level "Syntax-Directed Operations" clause to hold some more broadly applicable operations.
However, in a few cases @michaelficarra and I judged that the result would have separated sections which logically ought to be grouped, which we resolved by introducing new …
> Editorial: consolidate each SDO's definition

- spec.html
Seems good to call out, even if it is already said in prose.
> Editorial: List the [[Construct]]-requires-[[Call]] invariant in the list of invariants

- spec.html
The `IterationStatement` nonterminal has gotten pretty unwieldy, with 14 right-hand sides. The only comparably large nonterminals are `PrimaryExpression` and `Statement`, and the right-hand sides in those cases are trivial, having one or two symbols each (compared to as many as 10 for `IterationStatement`, plus constraints, parameters, and lookahead restrictions). This PR splits it up so that `IterationStatement` produces `DoWhileStatement`, `WhileStatement`, `ForStatement`, and `ForInOfStatement`, which are defined in the relevant sections.
Commits can be squashed before merging.
> Editorial: split up IterationStatement

- package-lock.json
- package.json
- spec.html
The main feature is [support for listing the SDOs associated with a production](https://github.com/tc39/ecmarkup/pull/276) - when you hover a production's definition, you should get a tooltip which will let you pop up a pane containing the SDOs defined over that production.
The breaking change is the [bump of highlight.js](https://github.com/tc39/ecmarkup/pull/284), hence the changed stylesheet.
> Meta: bump ecmarkup to 6.0.0

- spec.html
The nonterminals:
- FunctionExpression
- ClassExpression
- GeneratorExpression
- AsyncGeneratorExpression
are all defined with a single RHS involving an optional BindingIdentifier.
But AsyncFunctionExpression is defined with two RHSs, one with a BindingIdentifier and one without. (It's been that way since it was introduced in PR #692.) I can't see any reason for it to be not like the others.
> Editorial: Merge the RHSs of AsyncFunctionExpression

- spec.html
Published snapshots such as https://262.ecma-international.org/11.0/ include the exact same text. This patch tweaks the text so that the sentence still makes sense even when it’s being read from a snapshot copy. It also hardcodes the link’s target URL so that the link text and destination are always in sync and point to the expected location.
Context: https://github.com/tc39/Reflector/issues/349#issuecomment-763624846
> Editorial: improve “About this Specification” section

- spec.html
In the definition for `Array.prototype.find`, we have
> ```md
> _predicate_ should be a function that accepts three arguments and returns a value that is coercible to a Boolean value.
> ```
In several other places like `Array.prototype.findIndex`, we have
> ```md
> _predicate_ should be a function that accepts three arguments and returns a value that is coercible to the Boolean value *true* or *false*.
> ```
While `find` is the odd-one-out, I think it uses cleaner language, and this PR makes other locations more consistent.
Alternatively, I can amend the definition of `find`.
> Editorial: swap phrasing to indefinite article for Boolean-coercibles.

- spec.html
_Draft_ to fix #2179
* Number::exponentiate
* Number::multiply
* Number::divide
* Number::remainder
* Number::add
> Editorial: convert Number abstract operations to algorithmic steps

- package-lock.json
- package.json
- spec.html
Fixes https://github.com/tc39/ecma262/issues/570. Also has a drive-by fix to spell <= as ≤.
> Meta: bump ecmarkup to 6.0.1

- spec.html
_tl;dr This PR intends to nail down some parts of `Array.prototype.sort` to reduce the amount of cases that result in an implementation-defined sort order._
The `Array.prototype.sort` procedure that this PR proposes, can be summarized as follows:
1. Collect all existing, non-`undefined` values in the range of `[0, [[length]])` into a temporary list using `[[Get]]` (let the length of this list be `n`). `undefined`s are counted and not added to this temporary list (let this count be `m`).
1. Sort this temporary list using an implementation-specific sort algorithm.
1. Write back `n` sorted values using `[[Set]]`.
1. Write back `m` `undefined`s.
1. Perform `[[Delete]]` on integer-indexed properties in the range of `[n + m, [[length]])` as holes are moved to the end of the sorting range.
The …
> Normative: A more precise Array.prototype.sort

- spec.html
This ought to be editorial, but it's possible that it requires consensus due to the underspecification at play.
There are 12 %TypedArray% methods which refer to their Array counterparts without giving an explicit algorithm. This isn't so much delegation as it is hand-waving: [`map`](https://tc39.es/ecma262/#sec-%typedarray%.prototype.map) and [`filter`](https://tc39.es/ecma262/#sec-%typedarray%.prototype.filter) happen to be spelled out and, in particular, do not perform per-iteration HasProperty checks (because typed arrays can't have holes). This is not called out in the current explanatory text for, e.g., [`reduce`](https://tc39.es/ecma262/#sec-%typedarray%.prototype.reduce), but I argue that it is being assumed and not consciously omitted.
The foregoing behavior in SM and V8 diverges …
> Normative: Give %TypedArray% methods explicit algorithms.

- spec.html
Both S and R are Strings, and both are asserted in the prose, so either both or neither should be asserted in the steps. I chose neither.
> Editorial: remove unnecessary assertion

- spec.html
This is solving the problem that the term "TypedArray element type" appears 8 times in the spec as an implied assertion on AO arguments and similar, but is not auto-linked or explicitly defined anywhere.
This first attempt is making the table column name a `<dfn>`, but this might look a little weird since it italicizes the column name.
The other alternative is to change the prose from `supported element types` to `supported <dfn>TypedArray element type<dfn>s` or something similar, but i'm not sure of the cleanest way to do that.
> Editorial: add <dfn> for "TypedArray element type"

- spec.html
This PR is normative as it defines the order in which the `length` and `name` properties are added to built-in functions.
I’ve added `name` as a parameter, since abstract closures don’t have names, which would make using them to create non‑anonymous functions impossible.
It also preserves compatibility [for WebIDL](https://heycam.github.io/webidl/#create-an-interface-object), which uses inline definitions for steps.
**Tests:** <https://github.com/tc39/test262/pull/2921>
- <https://github.com/tc39/ecma262/pull/2109>
- <https://github.com/tc39/ecma262/pull/2216>
- <https://github.com/tc39/ecma262/pull/2115>
- <https://github.com/tc39/ecma262/pull/2118>
- <https://github.com/tc39/ecma262/pull/2219>
---
[Preview](https://ci.tc39.es/preview/tc39/ecma262/pull/2116) …
> Normative: Set function `name` and `length` in `CreateBuiltinFunction`

- spec.html
... using the format established in PR #1914.
> Editorial: Standardize preambles for host-defined abstract operations

- package-lock.json
- package.json
- spec.html
Notable changes:
- https://github.com/tc39/ecmarkup/pull/292, which also entailed dropping the inline CSS here (as [promised](https://github.com/tc39/ecma262/pull/2215#pullrequestreview-545222381))
- https://github.com/tc39/ecmarkup/pull/291, which fixes an overflow observable in e.g. in [RegExp.prototype [ @@split ]](https://tc39.es/ecma262/#sec-regexp.prototype-@@split)
- https://github.com/tc39/ecmarkup/pull/290, which makes it so that if you copy-paste an algorithm step (by triple-clicking to select the whole line) it will include the step number
I've also added a `dfn` to "Normative Optional", so that you can click on the label in the heading of such clauses to be taken to its definition.
> Meta: bump ecmarkup to 6.1.0

- spec.html
This fixes the definitions of `WeakRef.prototype` and `FinalizationRegistry.prototype` to match <https://github.com/tc39/ecma262/pull/2131> and adds a `<dfn>` for `%WeakRef%`.
> Editorial: Fix `<dfn>`s for `WeakRef` and `FinalizationRegistry`

- spec.html
Fixes https://github.com/tc39/ecma262/issues/2034, raised by @waldemarhorwat a year ago (sorry for the delay). See the [linked slides](https://docs.google.com/presentation/d/1POaK3AQxbdeDIq5M1RVjH1YIHe3fSxOCPPALTHIaLyo/edit) for context. This makes `for (async of [1,2,3]);` a syntax error, as it is in all major engines except V8.
We said [at the time](https://github.com/tc39/notes/blob/425ab0e16a32f8199b5521a1cf7439d10d4c8a83/meetings/2019-12/december-3.md#async-of-grammar-ambiguity) that we could resolve this with a single token of lookahead, presumably by just preventing for-of loops where the first token is `async`. Unfortunately, `let async = {x: 0}; for (async.x of [1,2,3]);` is a legal program with no ambiguities and we probably shouldn't forbid it. So I've used a two token …
> Normative: forbid for-of loops with variable named async

- spec.html
As discussed, let's swap these sections.
> Editorial: swap "about" and "contributing" sections in the intro

- spec.html
I noticed that https://tc39.es/ecma262/#sec-asi-cases-with-no-lineterminator-here seems oddly sitting as a sibling of https://tc39.es/ecma262/#sec-interesting-cases-of-automatic-semicolon-insertion, whereas it feels like 12.10 should be the container section for all ASI-related content.
> Editorial: nest ASI sections under "ASI" section

- spec.html
> Normative: Define default constructors using spec steps

- spec.html
I corrected a few mistakes such as `ECMASCript` (instead of `ECMAScript`) and `arbritary` (instead of `arbitrary`).
> Editorial: Fix mistakes

- spec.html
In the second commit (drop "non-negative"), you could certainly achieve consistency by going in the reverse direction
(add "non-negative" to all the "For each integer" steps); I just chose the smaller delta.
In the third commit (drop "in original [key] insertion order"), we could also add Notes to the effect that List order is insertion order, if you think it would be helpful. However, note that CreateMapIterator and CreateSetIterator don't bother pointing this out.
> Editorial: Consistify some "For each" steps

- spec.html
With the current spec, if an engine precisely implements [`ValidateAndApplyPropertyDescriptor`](https://tc39.es/ecma262/#sec-validateandapplypropertydescriptor) and module namespace object's [`[[DefineOwnProperty]]`](https://tc39.es/ecma262/#sec-module-namespace-exotic-objects-defineownproperty-p-desc) method, with descriptive error message for each failure, it would report different errors (given there is > 1 cause of failure) for the same `(CurrentDescriptor, Descriptor)` pair when called on ordinary object vs module namespace object.
<details>
<summary>Test case:</summary>
```js
export let test = 42;
```
```js
import("module.js").then(ns => {
const desc = { get() {}, configurable: true };
Object.defineProperty(ns, "test", desc); // => TypeError: Cannot change module namespace object's …
```
> Editorial: Align checks order in [[DefineOwnProperty]] overrides with ordinary method

- package-lock.json
- package.json
- scripts/publish-preview.js
By compressing the whole archive (as a tarball) instead of compressing each file individually, and using brotli instead of gzip, we can considerably reduce the number of bits on the wire. This particularly matters for [multipage builds](https://github.com/tc39/ecma262/pull/2339).
Corresponding tc39-ci PR [here](https://github.com/ljharb/tc39-ci/pull/11). Marked as draft until that lands.
> Meta: better compression during preview uploads

- spec.html
The order in which the non-numeric properties are created (i.e. those from named capturing groups) is observable with `Object.keys`.
This matches all the engines I have on hand. It's only very technically normative, and test262 already tests for this behavior ([x](https://github.com/tc39/test262/blob/c8daa32e48f05b9438f28df20ec0787807b230b3/test/built-ins/RegExp/named-groups/groups-properties.js#L18-L20), [x](https://github.com/tc39/test262/blob/c8daa32e48f05b9438f28df20ec0787807b230b3/test/built-ins/RegExp/named-groups/lookbehind.js#L43-L46)). Thanks to @jmdyck for pointing this out and linking the tests.
> Normative: specify creation order for capturing group properties

- spec.html
This aligns FinalizationRegistry callbacks with Promise callbacks in
allowing web browsers to perform additional steps to save and restore
the correct incumbent settings object.
Context is that one of the blockers in the HTML integration PR is proper handling of backup incumbent settings objects. I won't recapture that horror here, but we went over it for the Promise machinery and got consensus to add the HostJobCallback machinery. This PR just makes use of that machinery too.
/cc @codehag since Firefox is the only one that implements this behavior. Chrome is interested in aligning with the spec here, but is not prioritizing the implementation work.
(I meant to do this before Stage 4, but I... guess I forgot.)
> Normative: Use HostJobCallbacks for FinalizationRegistry callbacks

- spec.html
Resolves #2285.
The first 3 commits (which could be squashed before merging) add a parameter to `NewObjectEnvironment` that supplies the value for the new environment's _withEnvironment_ flag, as suggested [in whatwg PR 6086](https://github.com/whatwg/html/pull/6086#issuecomment-762150191). The HTML spec has 3 calls to `NewObjectEnvironment` that would need to add an argument.
The 4th commit introduces fields `[[BindingObject]]` and `[[WithEnvironmentFlag]]` where formerly algorithms would refer to `the binding object for _envRec_` and `the _withEnvironment_ flag of _envRec_` respectively.
The 5th commit just renames `_bindings_` to `_bindingObject_` when it receives a `[[BindingObject]]`.
> Editorial: Object Environment Record improvements

- spec.html
I noticed this when reviewing [the ResizableArrayBuffer proposal](https://tc39.es/proposal-resizablearraybuffer/), which has this same pattern.
> Editorial: use target alias name instead of "it"

- package-lock.json
- package.json
- spec.html
There was some discussion on removing it here: https://github.com/tc39/ecma262/pull/2339#discussion_r585946339 So I wanted to offer this patch in case this was overlooked.
> Editorial: remove redundant `index.html`

- spec.html
Obsoletes #2294. I moved a few paragraphs outside of the `<emu-note>` because they weren't notes, they were summaries of the method.
> Editorial: clean up wording of Array methods

- spec.html
In [14.6.1 Static Semantics: Early Errors](https://tc39.es/ecma262/#sec-if-statement-static-semantics-early-errors), first production of `IfStatement` contains two `Statement`. However, early error rule of `IfStatement` only mentions about single `Statement`, which seems to be fixed by this PR.
> Editorial: Fix early error rules of 'IfStatement'

- spec.html
When the first two of these were introduced (in ES6), they were useful because they encapsulated a sizeable amount of pseudocode. But after successive rewordings (in PRs #692, #971, #890), the underlying pseudocode is almost as brief as invoking the SDO. So I think their benefit (in terms of conciseness or encapsulation) is now outweighed by their cost (in terms of indirection); eliminating them will make it slightly easier to understand how the spec uses cover grammars.
(For comparison, note that we don't bother to define similar SDOs for:
`the |AssignmentPattern| that is covered by |LeftHandSideExpression|`
or
`the |AssignmentPattern| that is covered by |DestructuringAssignmentTarget|`
We just use those phrases directly in algorithms.)
This PR undefines the following ids, because there …
> Editorial: Eliminate `CoveredFoo` SDOs

- spec.html
In algorithm steps, it seems to be common to use value notation when creating TypeError object(e.g. [5.2.3.2 Throw an Exception](https://tc39.es/ecma262/#sec-throw-an-exception), ...). Therefore, it'd be better to use same notation for AggregateError object.
> Editorial: Consistent notation of newly created error object

- spec.html
There are some algorithms where same variable is defined twice :
- [8.2.1 Static Semantics: ContainsDuplicateLabels](https://tc39.es/ecma262/#sec-static-semantics-containsduplicatelabels)
- [8.2.2 Static Semantics: ContainsUndefinedBreakTarget](https://tc39.es/ecma262/#sec-static-semantics-containsundefinedbreaktarget)
- [8.2.3 Static Semantics: ContainsUndefinedContinueTarget](https://tc39.es/ecma262/#sec-static-semantics-containsundefinedcontinuetarget)
- [10.4.2.1 \[\[DefineOwnProperty\]\]](https://tc39.es/ecma262/#sec-array-exotic-objects-defineownproperty-p-desc)
- [10.4.2.4 ArraySetLength](https://tc39.es/ecma262/#sec-arraysetlength)
- [10.4.4.7 CreateMappedArgumentsObject](https://tc39.es/ecma262/#sec-createmappedargumentsobject)
Plus, for notation consistency, it might be better …
> Editorial: Correct usage of 'Let'/'Set' in various algorithms

- spec.html
Formerly, CreateDynamicFunction would parse the text for the parameters and body *separately*, so we didn't have a complete function decl/expr, so the Early Error rules for the function decl/expr production didn't apply automatically, so we had to apply them "manually".
Instead, parse the text of a complete function expr (which text already exists in `_sourceText_`!), so that all the relevant Early Error rules apply automatically.
I left a Note for the benefit of anyone who wonders where all the error-checking went, but it might be deemed unnecessary. (No other call to ParseText is accompanied by such a Note.)
This change has a side-benefit in that it will allow a simplification of the definition of "function code" (and strict function code). Currently, it's complicated by this one case …
> Editorial: Simplify CreateDynamicFunction

- spec.html
There seems to exist bug in step 3 of `ClassTail : ClassHeritage_opt { ClassBody }` case of [8.4.1 Static Semantics: Contains](https://tc39.es/ecma262/#sec-static-semantics-contains). Since `ClassHeritage` may not be defined, I think checking whether `ClassHeritage` is present is needed before invoking `Contains` of `ClassHeritage`.
> Editorial: Fix Contains algorithm of ClassTail

- spec.html
> Editorial: more explicit validation in CreateDynamicFunction

- spec.html
This includes changes from https://tc39.es/proposal-class-fields/.
> (ignore) Normative: Add public and private class fields

- spec.html
This includes changes from https://tc39.es/proposal-static-class-features/.
> Normative: Add public and private class fields, static class features, private methods & getters/setters

- spec.html
SharedArrayBuffer.length is 1 on all web engines (as is
ArrayBuffer.length). Unsure why this was made optional.
eshost output for `print(SharedArrayBuffer.length)`:
```
1
1
1
1
```
> Normative: Make SharedArrayBuffer's sole parameter required

- package-lock.json
- package.json
- spec.html
The main thing this introduces is the ability to toggle between single-page and multipage versions of the spec by pressing `m`.
> Meta: bump ecmarkup to 7.1.0

- spec.html
See https://github.com/tc39/ecma262/pull/2355#issuecomment-815296498
Downstream: No uses of ValidateTypedArray in WebIDL, HTML, Intl.
Note that ValidateIntegerTypedArray also returns the buffer, so you might want that handled similarly.
Also, ValidateAtomicAccess returns a value, but changing it to not return that value would be more disruptive. Perhaps it should change its name to something that emphasizes the value it computes, rather than any validation it does.
> Editorial: Change ValidateTypedArray to not return the buffer

- spec.html
> Editorial: `meta` should be listed alongside `target`

- spec.html
As pointed out [here](https://stackoverflow.com/questions/67855714/eval-declaration-instantiation-when-calling-context-is-evaluating-formal-param), this note in `PerformEval` no longer reflects the specified behavior, which changed in #1046.
> Editorial: fix note about var decls in eval in parameter initializers

- spec.html
Specifically:
- Abstract Relational Comparison
- Abstract Equality Comparison
- Strict Equality Comparison
See https://github.com/tc39/ecma262/pull/545#issuecomment-815314218 (third bullet).
Downstream: HTML refers to Abstract Equality Comparison and Strict Equality Comparison. (But the link will still work.)
> Editorial: Recast comparison algorithms as proper abstract operations

- CONTRIBUTING.md
- Differentiate "Issue" (uppercase, as in the GitHub concept) from "issue" (lowercase, the problem). Same for "Pull Request".
- Link the mailing list.
- Minor word changes.
- Use code font for file names and branch names (Are you considering switching from `master` to `main`?).
- Add new line after headings.
> Meta: CONTRIBUTING.md: Some changes to make the doc more beginner-friendly

- spec.html
Part of <https://github.com/tc39/ecma262/issues/1894>.
I’ve also converted [`Object.fromEntries`](https://tc39.es/ecma262/#sec-object.fromentries) to use it, as it’s the only built‑in anonymous function that has no internal slots apart from [`CreateListIteratorRecord`](https://tc39.es/ecma262/#sec-createlistiteratorRecord), but built‑in iterators are being converted to use [Abstract Closures](https://tc39.es/ecma262/#sec-abstract-closure) in <https://github.com/tc39/ecma262/pull/2045>.
---
[Preview](https://ci.tc39.es/preview/tc39/ecma262/pull/2109) ([#sec-createbuiltinfunction](https://ci.tc39.es/preview/tc39/ecma262/pull/2109#sec-createbuiltinfunction), [#sec-object.fromentries](https://ci.tc39.es/preview/tc39/ecma262/pull/2109#sec-object.fromentries))
> Editorial: Add support for Abstract Closures to `CreateBuiltinFunction`

- spec.html
Followup to #2109. Fixes #1894, fixes #933, fixes #1077 (in passing, in the "less handwaving" commit).
There's still six places where I haven't adopted the new style: two ([x](https://tc39.es/ecma262/multipage/#sec-promise-reject-functions), [x](https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-promise-resolve-functions)) in [CreateResolvingFunctions](https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-createresolvingfunctions) (used mainly in the Promise constructor), [one](https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-promise.all-resolve-element-functions) in [PerformPromiseAll](https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-performpromiseall), two …
> Editorial: use abstract closures for anonymous functions in more places

- package-lock.json
- package.json
- spec.html
This includes a few small tweaks, including notably https://github.com/tc39/ecmarkup/pull/327 which unblocks #545 and https://github.com/tc39/ecmarkup/pull/330 which unblocks https://github.com/tc39/ecma262/pull/2125.
> Meta: bump ecmarkup to 8.0.0

- spec.html
See more complete discussion in https://es.discourse.group/t/execution-context-suspension-and-resumption/756. I'll summarize:
[GeneratorStart](https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-generatorstart) manipulates the code evaluation state of the running execution context, and also stores that context on the generator object. Prior to https://github.com/tc39/ecma262/pull/2045, the sole caller of GeneratorStart was in [EvaluateGeneratorBody](https://tc39.es/ecma262/multipage/#sec-runtime-semantics-evaluategeneratorbody) (although it wasn't called that at the time). So, in particular, GeneratorStart was only invoked in step 7 of [[[Call]] for ordinary functions](https://tc39.es/ecma262/multipage/ordinary-and-exotic-objects-behaviours.html#sec-ecmascript-function-o …
> Editorial: have CreateIteratorFromClosure provide a new execution context to GeneratorStart

- spec.html
AsyncGenerators are complicated, but at the root there's a relatively straightforward state machine. I find that it's difficult to see the shape of that machine with the current spec text, which routes every operation through [AsyncGeneratorResumeNext](https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-asyncgeneratorresumenext).
I've rewritten all the logic here. The main reason I prefer this text is that each AO does one thing and returns, instead of kicking off a chain of self-recursive AOs which you have to follow for quite a while, keeping track of the state, before you figure out what's actually going to happen. For example, I think this PR makes it much more obvious that AsyncGeneratorYield might not return control to the rest of the program, and under what …
> Editorial: Clarify the AsyncGenerator state machine

- spec.html
It's analogous to `string-concatenation`.
I've made separate commits for ease of reviewing. You could squash them all except perhaps the last.
> Editorial: Define+use `list-concatenation`

- spec.html
... since they aren't mentioned by the associated algorithm/rule.
> Editorial: Drop grammatical parameters from 'use' productions

- spec.html
This PR contains three commits: the first fixes #2449, the second fixes #2444, and the third fixes #2443.
> Editorial: Miscellaneous math fixes

- spec.html
In step 4.d, 4.e of [7.2.13 IsLessThan](https://tc39.es/ecma262/#sec-islessthan) algorithm, current spec use `!` assertion on `ToNumeric` call. However, it seems that abrupt completion can be returned from `ToNumeric` calls in step 4.d and step 4.e. `px` and `py` can be symbol objects and `ToNumber` call in `ToNumeric` algorithm emits an abrupt completion, which is a `TypeError` exception. Here is JS code triggering assertion failure in current specification:
```js
Object.defineProperty(Symbol.prototype, Symbol.toPrimitive, { value: undefined });
Object(Symbol()) <= ""; // should throw TypeError, but assertion fail in spec
```
According to test262 and chrome browser, the above code should throw `TypeError` exception. Changing `!` to `?` in step 4.d and 4.e seems to be a plausible fix. …
> Editorial: Fix wrong assertion in IsLessThan

- spec.html
~~This PR is based on top of #1668. Please review by commit. As #1668 is updated and/or merged, I'll rebase this one.~~
> Normative: add `#x in obj` syntax

- spec.html
Following up on issue 253, specifically https://github.com/tc39/ecma262/issues/253#issuecomment-164852263
For each abstract operation (241 in all), I have taken the information in the prose preamble (or failing that, in the section's h1), and recast it into a structure of the following form:
```
<emu-operation-header>
name: ExampleOperation
parameters:
* _foo_ : an Object
* _bar_ : (optional) an integer that indicates something or other
also has access to:
* _qux_ : ...
returns:
* normal : an Object
* abrupt : throw *TypeError*
description: does something exemplary to the given object.
</emu-operation-header>
```
This structure is just a strawman. If you like the idea but not this particular structure, I should be able to regenerate the info in a different structure. (So far, the …
> Replace each abstract op's preamble with a structured 'header'.

- spec.html
As discussed during the March 2021 plenary, this note on "is designed to
be subclassable" can be read as an encouragement or value judgement on
whether it is desirable to subclass built-in classes like Boolean. We
don't want to actively encourage this.
> Editorial: Remove 'designed to be subclassable'

- spec.html
This normatively constrains implementations to not have functions return control-flow altering completions other than `~throw~`. I expect nailing this down to be both a universal truth in all implementations and uncontroversial: calling a function shouldn't be able to e.g. break out of a loop.
> Normative: Restrict completion values callables can return

- spec.html
... into the if-else cascade in CreateDynamicFunction, as @Bakkot suggested [here](https://github.com/tc39/ecma262/pull/2348#discussion_r606347643)
> Editorial: Inline "Dynamic Function SourceText Prefixes" table

- spec.html
Formerly, the procedure for applying ToNumber to the String type was spread over three widely-separated prose paragraphs in two different clauses.
This commit brings all that together, expresses it as an actual algorithm, and gives it the name StringToNumber.
Similarly, the prose underlying the syntax-directed operation NumericValue (to get the value of a NumericLiteral) is expressed more algorithmically.
> Editorial: Define + use StringToNumber

- spec.html
I believe that the `&ne;` (≠) notation should be used when comparing array lengths in [10.4.2.4 ArraySetLength](https://tc39.es/ecma262/#sec-arraysetlength)'s step `5`.
According to [test262/test/built-ins/Object/defineProperties/15.2.3.7-6-a-127.js](https://github.com/tc39/test262/blob/master/test/built-ins/Object/defineProperties/15.2.3.7-6-a-127.js), a `RangeError` must not be thrown, meaning that `newLen` and `numberLen`, which are `0` and `-0.0` in this case, should be "the same value". 
From what I've seen in #1963 and [one of the discussions](https://github.com/tc39/ecma262/pull/2007/files#r501329621) when the phrase "the same value" was first introduced, the likes of `=`, `≠` seem to be used for mathematical equality, which is what I think is a more suitable notation to express …
> Editorial: Validate array length using `SameValueZero` in `ArraySetLength` and `Array`

- spec.html
This supersedes #2433.
This PR also makes the prose around requirements for host hook
implementations consistent to the template "An implementation of
HostHook must conform to the following requirements:".
> Normative: Constrain all host hooks to return either normal or throw completions

- spec.html
> Normative: move __proto__ out of annex b

- spec.html
This was split out from #2435. I took issue with the way the usage of parentheses here implied that we were defining terms that were interchangeable (for example, wherever you use TV you may replace it with Template Value, and vice versa). In the process of removing these, I believe I also simplified the descriptions of the SDOs to get more to the point with less clutter.
> Editorial: don't imply that SV, TV, and TRV are shorthands

- spec.html
These fields were not initialized at all, although they are present on every ordinary function according to table 33. Depending on how you view internal slots this either caused creating the object to be invalid, or it caused InitializeInstanceFields to be invalid.
> Editorial: initialize missing slots in OrdinaryFunctionCreate

- spec.html
The inverse of #2327. I find this easier to understand.
> Markup: prefer `&notin;` over `&lt;!`

- spec.html
~~The way <code>[CreateBuiltinFunction]</code> is currently specified would’ve resulted in it not having the `[[Prototype]]`, `[[Extensible]]`, `[[Realm]]` and `[[ScriptOrModule]]` internal slots unless they were explicitly passed using <code>[CreateBuiltinFunction][]\(<var>steps</var>, « [[Prototype]], [[Extensible]], [[Realm]], [[ScriptOrModule]] »\)</code>.~~
~~I’ve also made it optional in preparation for converting many of the built‑in functions to use abstract closures after <https://github.com/tc39/ecma262/pull/2109>.~~
[CreateBuiltinFunction]: https://tc39.es/ecma262/#sec-createbuiltinfunction
- <https://github.com/tc39/ecma262/pull/2109>
- <https://github.com/tc39/ecma262/pull/2116>
---
[Preview](https://ci.tc39.es/preview/tc39/ecma262/pull/2115) …
> Editorial: Define required internal slots in `CreateBuiltinFunction` steps

- spec.html
... one for TV and one for TRV.
(This duplicates 4 cases, but they're very simple.)
In the status quo rendering, uses of TV and TRV aren't autolinked. With this change, they are.
Alternatively, @bakkot suggested having the two new clauses nested within the current clause 12.8.6.1, with the prose (and the final NOTE?) remaining in 12.8.6.1. I can do it that way if the editors prefer.
> Editorial: Split the "TV and TRV" clause into 2 clauses

- spec.html
For the first commit: The `_enumerable_` parameter for `PropertyDefinitionEvaluation` was always true; the parameter of the same name for `ClassElementEvaluation` was always false. Prior to #1668 PropertyDefinitionEvaluation was used for both object literals and classes. When it was split, the parameter because redundant.
The second commit just fixes an oversight of mine from fe6b5ef37b0b740e1d66be671137a6161035021a (part of #2271).
> Editorial: tweak PropertyDefinitionEvaluation and ClassElementEvaluation

- spec.html
#1668 introduced a `DefineMethodProperty` method for use when creating plain methods, generator methods, async methods, and async generator methods. In that PR it included a call to `SetFunctionName`, which was correspondingly factored out of the evaluation semantics of plain methods and async methods, but not generator methods or async generator methods. In the evaluation semantics for generator (and async generator) methods, there's another property (`.prototype`) which is added between the call to `SetFunctionName` and `DefineMethodProperty`, and since property creation order is observable dropping the first call and just letting it happen in `DefineMethodProperty` would be an observable change.
Instead, just remove `SetFunctionName` from `DefineMethodProperty`, and restore it to the …
> Editorial: avoid duplicate SetFunctionName in {async,}generator methods

- spec.html
It's cleaner and (IMO) more comprehensible to have a single Let.
> Editorial: Fix alias use in IteratorBindingInitialization

- spec.html
This PR comprises the first 2 commits of PR #1651, which I gather are "non-controversial".
> Normative: Make B.1.{1,2} normative

- spec.html
Hi folks, 
The goal of this pr is to address the concern brought up in #1224 -- which has become more pressing. With the introduction of private fields, [implementations will again diverge on this point from the specification](https://github.com/tc39/ecma262/issues/1224#issuecomment-747779307). 
There were two suggested solutions to this, one was re-evaluation, which was rejected in past meetings. The other was reordering. 
This pr allows `null` and `undefined` as values in Reference Records. This means that throwing is moved to ToObject in most cases.
We are not too sure about the super code though, and could use some extra eyes. See the past discussion [here](https://github.com/codehag/ecma262/pull/3)
> Normative: Allow null or undefined in Reference Records

- img/module-graph-cycle-async.svg
- spec.html
This PR introduces the necessary changes to the spec for [top-level await](https://github.com/tc39/proposal-top-level-await/)
I hit a couple of conflicts (you will notice while reviewing) and I am not sure if that is the new style of the spec. I tried to resolve most of them but I sometimes wasn't sure. If the original is intended, let me know and I will update the spec accordingly.
Since the last meeting, [one editorial change](https://github.com/tc39/proposal-top-level-await/commit/3b732b937f79a28e2b91fb1e3ba9accaf8022e42) was merged in, introducing prose around what happens when an error is thrown during async evaluation. We are discussing a further clarification with @guybedford , but it doesn't affect the normative spec text. It will hopefully make it more readable. What is the best …
> Normative: Top-level Await

- spec.html
This makes the parameter more easily searchable while clarifying its meaning.
This came up while working on the draft spec for [the RegExp set notation proposal](https://github.com/tc39/proposal-regexp-set-notation), which introduces another RegExp grammar parameter that is related to Unicode. Rather than sticking to single letters, it seems nicer to move to more descriptive names. 
If the editors are open to this change, I’d be happy to work on a patch that renames `N` as well (perhaps to `WithNamedCaptureGroups`).
cc @markusicu @markusicu @sffc
> Editorial: Clarify RegExp grammar parameter U → UnicodeMode

- spec.html
... in the early error rule for ObjectLiteral. When you're deciding whether to apply the rule, "this |PropertyDefinition|" isn't well-defined.
(This was introduced in PR #2125. It's probably just a copypasta of similar text in [13.2.5.5 PropertyDefinitionEvaluation](https://tc39.es/ecma262/#sec-runtime-semantics-propertydefinitionevaluation), where "this |PropertyDefinition|" *is* well-defined.)
> Editorial: Change |PropertyDefinition| to |ObjectLiteral|

- spec.html
... as regular abstract operations.
See
- https://github.com/tc39/ecma262/pull/1142#discussion_r175863099 and following
- https://github.com/tc39/ecma262/issues/2384#issuecomment-818404645 and following
> Editorial: Recast NormalCompletion + ThrowCompletion

- package-lock.json
- package.json
- spec.html
I [just added](https://github.com/tc39/ecmarkup/pull/346) support in ecmarkup for `dfn` tags to define other forms of the terms they define. This PR bumps ecmarkup to that version and makes use of the new attribute as appropriate for plural forms of defined nouns and noun phrases.
> Markup: auto-link plural forms of terms

- spec.html
https://github.com/tc39/ecma262/pull/2483 proposes to change a few occurrences of "TypedArray object" to "TypedArray". (There were some usages of the latter form already.) That seems better, so we might as well do that everywhere it makes sense to do so.
I've changed most uses of "an X object" to be "an X", with the following exceptions:
- when referring to an exotic object in a context which emphasizes its exotic nature, I've left it as "an X exotic object"
- "Set object" remains as-is, to distinguish from the built-in type of the same name (I've also added a note calling attention to this)
- "Error object" and variants remain as-is, to make it clear it's talking about a value rather than an exceptional condition
- the various boxed primitive types remain "a Boolean object" (etc), to …
> Editorial: "an Array", not "an Array object" [etc]

- spec.html
This adds the specification text from https://github.com/tc39/proposal-class-static-block, currently at Stage 3.
> Normative: Add class `static` initialization blocks

- spec.html
In https://github.com/tc39/ecma262/issues/2409, https://github.com/tc39/ecma262/issues/2400, https://github.com/tc39/ecma262/pull/2429, https://github.com/tc39/ecma262/pull/2413, and other issues, we've been trying to clarify how execution contexts work within the spec. I think I have a good handle on how to clarify all of the sources of confusion with some editorial tweaks, with the exception of [PrepareForTailCall](https://tc39.es/ecma262/#sec-preparefortailcall).
PrepareForTailCall is particularly strange. Unlike everywhere else in the spec (as of #2413), it pops the execution context stack without immediately resuming the execution context which is now at the top of the stack, leaving the spec's abstract machine in an odd state where the "running execution context" (defined to be the …
> Normative: phrase tail calls as discarding resources rather than popping execution context stack

- spec.html
The "_The following are the only restricted productions in the grammar_" note has fallen out of date; it is missing many `[no LineTerminator here]` productions. This PR adds them, along with corresponding additions to practical effects and practical advice. It also incidentally improves consistency in the relative ordering of Declaration/Expression/Method productions.
> Editorial: Update restricted productions summary

- spec.html
Adds Array#at, String#at, and %TypedArray%#at.
> Normative: Add relative indexing method at()

- spec.html
`AggregateError` is not listed in section 19.3, while it is specd as available on the global object in section 20.5.7.1.
> Editorial: add missing constructor property of the global object

- spec.html
Fixes #2481. Without this, the spec permits `lbl : { for ( ;; ) continue lbl ; }`, contrary to all implementations I have on hand.
There's a few different productions which would work here - adding a definition for any of `BlockStatement : Block`, `Block : { StatementList }`, `StatementList : StatementListItem`, or `StatementListItem : Statement` would work, in addition to `Statement : BlockStatement` as chosen in this PR. I think `Statement : BlockStatement` is clearest, but it doesn't really matter.
> Normative: `continue` labels should not pass through blocks

- spec.html
I noticed in [this thread](https://es.discourse.group/t/why-are-parameter-bindings-of-non-strict-functions-instantiated-in-a-new-environment-if-default-value-initialisers-exist/941/12) that [FunctionDeclarationInstantiation](https://tc39.es/ecma262/multipage/ordinary-and-exotic-objects-behaviours.html#sec-functiondeclarationinstantiation) step 19.a is misleading. It reads
> 19. If strict is true or if hasParameterExpressions is false, then
>   a. NOTE: Only a single Environment Record is needed for the parameters and top-level vars.
The NOTE is identical to that in step 27.a, from which it was presumably copied:
> 27. If hasParameterExpressions is false, then
>    a. NOTE: Only a single Environment Record is needed for the parameters and top-level vars.
But the conditions are different, …
> Editorial: tweak note in FunctionDeclarationInstantiation

- spec.html
Various of the abstract operations introduced in #1668 took their parameters in the order (key, object) or (key, object, value), rather than the prevailing convention of (object, key) or (object, key, value) respectively (as in [Get](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-get-o-p), [Set](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-set-o-p-v-throw), etc). (Thanks to @devsnek for [pointing this out](https://matrixlogs.bakkot.com/TC39_General/2021-07-17#L10).)
This PR swaps the order of the parameters for those methods to match the prior convention.
> Editorial: make the order of parameters for class field AOs more consistent

- spec.html
Fixes #2508.
Hopefully the last typo from #2122. I've checked all the boundary cases again, but I did that before and clearly managed to miss this one, so there might well still be some lurking.
I'm calling this editorial because that's what we've been doing in #2185, #2450, etc.
> Editorial: fix typos in Math.cos and Math.cosh

- spec.html
Every time I encounter a reference to one of the two operations, there's a momentary pause while I remember with differentiates +0 from -0. This should shorten that time by a bit, and make the text slightly more approachable for everyone (especially since `::sameValue` and `::sameValueZero` are not currently links).
> Editorial: Make the behavior of SameValue and SameValueZero a little more clear

- spec.html
Add some needed SDO definitions.
Drop some unused SDO definitions.
Fixes #2354.
> Editorial: Fix some SDOs

- spec.html
Currently, the spec sends mixed signals to programmers about the `with` statement; this PR attempts to clear up the ambiguity by adding text that explicitly discourages the use of the `with` statement in new ECMAScript code.
This is an attempt to solve a specific problem: developers and technical writers are unclear about the status of the `with` statement. See [this StackOverflow question](https://stackoverflow.com/questions/48810592/is-the-javascript-keyword-with-really-deprecated) or [this discussion in MDN Web Docs's browser-compat-data project](https://github.com/mdn/browser-compat-data/issues/10490) to get a taste. This makes it difficult to document on MDN Web Docs and elsewhere.
By forbidding `with` in strict mode code and cutting it off from many contemporary language features, …
> Editorial: disambiguate `with` statement's status

- spec.html
ContainsArguments, added in #1668, is used to forbid class field initializers which refer to the outer `arguments` binding. It's not intended to descend into non-arrow functions, since those introduce their own binding for `arguments`, which is fine. Unfortunately it was accidentally missing the `AsyncGenerator` cases, meaning that, as written, `(class { x = async function*(){ arguments } })` was an Early Error, unlike `(class { x = function*(){ arguments } })` or `(class { x = async function(){ arguments } })`.
Engine262 actually implements the specified behavior, but no other engine I tested did.
This is technically normative, because the current semantics are coherent, but I think we need not seek consensus for it - it was definitely just an oversight.
The first commit is just a …
> Normative: add missing AsyncGenerator cases to ContainsArguments

- CONTRIBUTING.md
This pull request updates CONTRIBUTING.md to link to the [Matrix guide](https://github.com/tc39/how-we-work/blob/master/matrix-guide.md) instead of referring to IRC Freenode.
> CONTRIBUTING.md: Update IRC to Matrix

- .github/ISSUE_TEMPLATE/config.yml
- .github/workflows/deploy.yml
- FAQ.md
- LICENSE.md
- README.md
- scripts/check-commit.js
- scripts/check-form.js
- spec.html
- stage0.md
- withdrawn-proposals.md
This only leaves the word "master" hardcoded in build scripts, and contributor instructions prose.
> Meta: update static default branch name to a dynamic one

- spec.html
- BigInt::bitwiseNOT
- BigInt::multiply
- BigInt::add
- BigInt::subtract
- BigInt::lessThan
- BigInt::equal
(In most cases, the algorithm just rephrases the description, so there's no need to keep the description.)
Resolves #2522.
> Editorial: Provide `<emu-alg>` for 6 BigInt methods

- package-lock.json
- package.json
- spec.html
~Depends on https://github.com/tc39/ecmarkup/pull/358 and will not build until that's upstreamed. I've uploaded a rendered version built with that PR [here](https://bakkot.github.io/ecma262-previews/sdo-structured-header/multipage/).~
This now includes ecmarkup 9.2.0, which introduces support for this.
In a followup, now that the format accommodates it, I'll start adding descriptions and parameter types.
> Markup: have SDOs use structured headers

- spec.html
There were 6 occurrences of "ECMAScript value". The term "ECMAScript language value" has 127 occurrences and a `<emu-dfn>`.
> Editorial: "ECMAScript value" -> "ECMAScript language value"

- spec.html
Module Namespace's [`[[GetPrototypeOf]]`](https://262.ecma-international.org/6.0/#sec-module-namespace-exotic-objects-getprototypeof) method, introduced in ES6, was replaced with a `[[Prototype]]` slot in #748 because [`SetImmutablePrototype`](https://tc39.es/ecma262/#sec-set-immutable-prototype) didn't call `[[GetPrototypeOf]]` at the time (fixed in #841).
This change makes definition of Module Namespace's `prototype` consistent with its definition of (non-)extensibility.
AWB argued for this approach in https://github.com/tc39/ecma262/pull/858#discussion_r136681103.
> Editorial: Define Module Namespace's [[GetPrototypeOf]] method

- .github/workflows/deploy.yml
- scripts/auto-deploy.sh
I updated the [gh-pages branch](https://github.com/tc39/ecma262/tree/gh-pages) with es2016-es2021 subdirectories (including some minor tweaks, which I pushed to the corresponding branches).
This updates the auto-deploy script to preserve those subdirectories.
It also fixes it - #2521 changed the branch name for the workflow to `$default-branch`, which [was a good idea](https://github.blog/changelog/2020-07-22-github-actions-better-support-for-alternative-default-branch-names/), but apparently that syntax [only works in workflow templates](https://github.com/actions/starter-workflows/pull/590#issuecomment-672360634). So we haven't been updating the rendered spec since that PR landed.
Fixes #2529.
> Meta: Keep old years in gh-pages

- spec.html
Currently, the algorithm for `StringValue` of _IdentifierName_ has the step:
```
Let _idTextUnescaped_ be the result of
replacing any occurrences of `\\` |UnicodeEscapeSequence| in _idText_
with the code point represented by the |UnicodeEscapeSequence|.
```
(And the algorithm for `CapturingGroupName` of _RegExpIdentifierName_ has something quite similar.)
In https://github.com/tc39/ecma262/pull/1552#discussion_r338854947, @michaelficarra said of this step:
> This language is a little less precise than I would prefer. Could we define a syntax-directed operation [to specify "the code point represented by the |UnicodeEscapeSequence|"]
This PR does so.
The first commit refactors the grammar slightly, and the second introduces 4 SDOs.  The first makes the second easier, but it also has …
> Editorial: Improve specification of [RegExp]IdentifierNames

- spec.html
See also, https://github.com/tc39/ecma262/pull/2258
> Editorial: `String.prototype.lastIndexOf`: use explicit algorithm steps

- spec.html
Thanks to @jmdyck for pointing this out.
> Editorial: `lastIndexOf`: fix typo from #2536

- spec.html
... to match all the other "Properties of the Foo Constructor" clauses (e.g., [Properties of the Number Constructor](https://tc39.es/ecma262/#sec-properties-of-the-number-constructor)).
> Editorial: Reformat "Properties of the BigInt Constructor"

- spec.html
Replaces/ closes #2155.
There are four special strings used in the import/export machinery, one of which is used in three different ways:
- `"*"`, used in the [[ImportName]] field of an ExportEntry to mark an `export * from 'mod'`; this has been renamed to `~all-but-default~`
- `"*"`, used in the [[ImportName]] field of an ExportEntry to mark an `export * as foo from 'mod'` export; this has been renamed to `~all~`
- `"*"`, used in the [[ImportName]] field of an ImportEntry to mark an `import * as foo from 'mod'` import; this has been renamed to `~namespace-object~`
- `"*namespace*"`, used in the [[BindingName]] field of a ResolvedBinding to mark a `export * as foo from 'mod'`; this has been renamed to `~namespace~`
- `"ambiguous"`, used in the return value for `ResolveExport` when …
> Editorial: mostly stop using strings for special values

- spec.html
Each of these clauses:
- [Function.prototype[@@hasInstance]](https://tc39.es/ecma262/#sec-function.prototype-@@hasinstance)
- [Symbol.prototype[@@toPrimitive]](https://tc39.es/ecma262/#sec-symbol.prototype-@@toprimitive)
- [Date.prototype[@@toPrimitive]](https://tc39.es/ecma262/#sec-date.prototype-@@toprimitive)
has a pair of paragraphs of the form:
```
<p>The value of the *"name"* property of this function is *"[...]"*.</p>
<p>This property has the attributes { [[Writable]]: *false*, ...}.</p>
```
In the second para, "This property" appears to refer to the `name` property mentioned in the preceding para. But I'm pretty sure that it's supposed to refer to the `@@hasInstance` or `@@toPrimitive` property that is the subject of the whole section.
To avoid this ambiguity, this PR puts the …
> Editorial: Disambiguate "This property"

- spec.html
I do not believe this affects any integration downstream.
This PR aims to allow:
```mjs
import {"\0 any unicode" as foo} from "";
export {foo as "\0 any unicode"};
```
This matches the restriction that WASM has that the string names for exports must be valid Unicode.
Depends on #2155
> Normative: Arbitrary module namespace identifier names

- spec.html
- [Table 39](https://tc39.es/ecma262/#table-white-space-code-points) explicitly lists \<SP> and \<NBSP> to be later used as a right-hand side of `WhiteSpace`. However, they are already implicitly included there by neighbour \<USP> because of their `Zs` category and need no repetition (see <https://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt>).
*This repetition is minor, but deduplication need to be done manually or by a generator while creation of a parser. A simple removal of explicit \<SP> and \<NBSP> allows to avoid such a step.*
Also I added a note explaining where space and NBSP characters have gone:
> U+0020 (SPACE) and U+00A0 (NO-BREAK SPACE) code points are part of \<USP>.
but I can remove it if a reader would not care about where the grammar introduces spaces.
- In …
> Editorial: Remove <SP> and <NBSP> as the ones already included by <USP>

- .github/workflows/enforce-format.yml
- package-lock.json
- package.json
- spec.html
Automatic formatting of the markup using [a ~WIP~ ecmarkup formatter](https://github.com/tc39/ecmarkup/pull/367).
You can see that it mostly uses the same style we already do, i.e. does not change anything, with a few exceptions:
- useless `<tbody>` tags are dropped
- when referring to an optional nonterminal in prose, it's written `|Nonterminal?|` rather than `|Nonterminal_opt|`. We use both styles currently, but the `_opt` form more frequently; I decided to go with the less frequent style anyway because it matches how it's spelled in the grammar (which does not support the `_opt` suffix in source)
- when there's an `emu-grammar` which references the same LHS twice, those are collapsed into a single multiline production
- when there's an `emu-grammar` with some items expanded, all of the …
> Markup: auto-format

- spec.html
- "an arguments objects" -> "an arguments object"
- remove reference to `export *;`, which is not a thing
> Editorial: fix a couple typos

- spec.html
We already have a "source text matched by" definition for use with productions; this PR extends it to be used with Parse Nodes as well.
> Editorial: Increase precision for referencing source text of a Parse Node

- spec.html
Say we parsed some source text according to a grammar, and we then want to use the verb "match". The question is, which 'way' does "match" go? The spec isn't consistent.
That is, given 'prod' (a nonterminal, production, or Parse Node) and 'text' (some source text, source code, or code points), the spec has both:
- A) prod matches text / text is matched by prod
and
- B) text matches prod / prod is matched by text
Almost always, the 'text' comes before the 'prod', so it's largely a choice between:
- A) text is matched by prod
and
- B) text matches prod
I looked through the spec and found about
- 65 occurrences of A
and
- 28 occurrences of B
Moreover, the only `<dfn>` we have involving "match" is "The <dfn>source text matched by</dfn> a grammar production", i.e. sense A.
So this PR changes …
> Editorial: Be consistent about the sense of "match" (and other phrasing)

- spec.html
Use consistent prose when the initial values of two intrinsic-properties are the same object.
> Editorial: Consistify prose for same-value properties

- spec.html
Resolves #2479.
I tried various ways to express the table as algorithm steps; I think this is the clearest.
The PR consists of:
- <strike>3</strike> 2 commits of preliminary refactoring,
- 1 commit where I fix a type-assertion,
- 6 squashable commits that gradually transfer stuff over, and
- 1 more refactoring commit (that could be preliminary).
> Editorial: Incorporate GetSubstitution's table into the algorithm

- spec.html
I could also hoist up the `actualDeleteCount` logic, and get rid of the if/elseif/else chain entirely, but I'm not as convinced that one would be an improvement.
Noticed this while reviewing/implementing https://tc39.es/proposal-change-array-by-copy/#sec-array.prototype.toSpliced
> Editorial: simplify Array.prototype.splice

- spec.html
This makes the invocation form consistent for the user-code effect propagation in #2548.
> Editorial: Use "SDO of |Foo|" form for all SDO invocations

- spec.html
- table-unicode-script-values.html
The following new values for the already-supported properties `Script` and `Script_Extensions` are added:
- Cypro_Minoan (Cpmn)
- Old_Uyghur (Ougr)
- Tangsa (Tnsa)
- Toto (Toto)
- Vithkuqi (Vith)
Issue: https://github.com/tc39/ecma262/issues/2514
Tests: https://github.com/tc39/test262/pull/3199
> Normative: List new Unicode v14 `Script`/`Script_Extensions` values

- spec.html
(Salvaged from PR #1612.)
(GitHub's diff is not very helpful: most of the apparent diff arises from a change of indentation.)
> Editorial: Give TypedArraySortCompare its own sub-clause

- package-lock.json
- package.json
- spec.html
This PR adds an annotation to call sites of AOs and SDOs that can call user code, possibly transitively.
Ecmarkup starts with a set of "roots" that can call user code, and propagates the effect to all reachable AO and SDO invocations.
For spec authors:
- Roots and false negatives can be manually tagged with `<emu-meta effects="user-code">root cause</emu-meta>`.
- Most invocations of internal methods (e.g. [[Get]]) are roots.
- The phrase "the result of evaluating" is automatically considered a root.
- False positives can be manually suppressed with `<emu-meta suppress-effects="user-code">suppressed</emu-meta>`.
- Steps can be manually fenced with `1. [fence-effects="user-code"] Step`, which fences any child step effects from propagating.
- Some spec constructs in algorithm steps are like …
> Editorial: Can-call-user-code annotation

- spec.html
In tables that 'declare' the fields of a Record schema, reword the 'types' (in the `Value` or `Value Type` column) to use the same (or similar) style as the parameters of abstract operations.
(Currently, they're in a variety of styles.)
> Editorial: Reword field 'types'

- spec.html
In a phrase such as "the String value of a string literal", we understand that the string literal is not a String value, but we do something to it to get a String value, the value denoted by the phrase.
By analogy, we would expect that in "the code point value of X", X is not a code point, but we do something to it to get a code point value, which is the value denoted by the phrase.  However, that's not the case: the intent is that X *is* a code point, and the phrase denotes its underlying integer value.
(Exception: The phrase "the code point value of |SourceCharacter|" *does* appear to denote a code point, namely the one matched by |SourceCharacter|.)
I think this phrasing (which goes back to ES3) is confusing, so this PR eliminates it.
Notes:
- The phrase "code point value" is okay if …
> Editorial: Eliminate "the code point value of X"

- spec.html
Fixes #2466
Commits can be reviewed sequentially, but the [build preview](https://ci.tc39.es/preview/tc39/ecma262/pull/2468) is probably best:
* [merged Property Attributes table](https://ci.tc39.es/preview/tc39/ecma262/pull/2468#sec-property-attributes)
* [indirect Record field references](https://ci.tc39.es/preview/tc39/ecma262/pull/2468#sec-list-and-record-specification-type) ([[\<_fieldName_>]])
* [ValidateAndApplyPropertyDescriptor](https://ci.tc39.es/preview/tc39/ecma262/pull/2468#sec-validateandapplypropertydescriptor)
* [Proxy [[GetOwnProperty]] note clarifications](https://ci.tc39.es/preview/tc39/ecma262/pull/2468#sec-proxy-object-internal-methods-and-internal-slots-getownproperty-p)
> Editorial: Cleanup ValidateAndApplyPropertyDescriptor and own prop operations

- spec.html
In the current spec, step 14 of RegExpInitialize says:
> Set _obj_.[[RegExpMatcher]] to the Abstract Closure that evaluates _parseResult_ by applying the semantics provided in [22.2.2](https://tc39.es/ecma262/#sec-pattern-semantics) using _patternCharacters_ as the pattern's List of _SourceCharacter_ values and _F_ as the flag parameters.
This PR examines that step and proposes 3 simplifications.
----
(1)
> the Abstract Closure that evaluates _parseResult_ by applying the semantics provided in 22.2.2
The Abstract Closure in question doesn't evaluate _parseResult_, rather it's the **result** of evaluating _parseResult_ (using 22.2.2's sense of "evaluate").
So we could change the quoted phrase to
> the Abstract Closure that results from evaluating _parseResult_ by applying [...]
However, I …
> Editorial: Simplify RegExpInitialize

- spec.html
The early error rules:
- It is a Syntax Error if _P_ is not covering an _N_.
- All Early Error rules for _N_ and its derived productions also apply to the _N_ that is covered by _P_.
always occur together, so replace them with the single rule:
- _P_ must cover an _N_.
> Editorial: Introduce the term "must cover" (replaces "is [not] covering")

- spec.html
I believe that all syntax-directed operations (SDOs) should have `type` attribute with `"sdo"` in their `emu-clause` HTML elements. So, I searched all the missing parts and added `type` attributes with `"sdo"` to them.
> Markup: add `sdo` types to `emu-clause` in missing parts

- spec.html
From original discussion at https://github.com/tc39/ecma402/pull/624#discussion_r754010696 .
> Editorial: Use `<code>` for values from other specifications

- spec.html
Fixes 3 places where the given parameter type is too restrictive.
> Editorial: Fix parameter type in InnerModuleLinking

- spec.html
This adds the note I suggested [here](https://github.com/tc39/ecma262/pull/2484#discussion_r684597033).
It's a bit wordy because the edge case can only happen in very specific circumstances. I'm very open to suggestions for improved wording here.
> Editorial: Note how edge case in GetSubstitution can arise

- spec.html
Fixes #2611.
Added the line suggested by @michaelficarra. I changed the phrase “is negative” to “&lt; +0<sub>𝔽</sub>” for the consistency with other part of the spec.
> Editorial: Fix sign of zero in Number::remainder

- package-lock.json
- package.json
To add shortcut help dialog: https://github.com/tc39/ecmarkup/pull/400
Also bumps the package-lock.json while I'm at it.
> Meta: bump ecmarkup to 9.8.0

- spec.html
I added missing `example` attributes to algorithms that are clearly used for example.
> Markup: add missing `example` attributes to example algorithms

- spec.html
Currently, "return Completion" links to the Completion() AO, which isn't what's happening here.
> Editorial: NormalCompletion/ThrowCompletion create a Completion Record

- spec.html
Marked as editoral due to current text being nonsensical and new text matching implementations.
> Normative: Fix out-of-range NaNs in date set methods

- spec.html
This adds a `<dfn>` and `<emu‑table>` for “[Iterator Records](https://ci.tc39.es/preview/tc39/ecma262/pull/2591#sec-iterator-records)”.
---
Part of <https://github.com/tc39/ecma262/issues/2486>
> Editorial: Add `Iterator Record` type

- spec.html
When processing the merge of PR #2620, I noticed that although it had taken care of `_rec_.[[Field]] is present`, there were also cases of `_rec_.[[Field]] is absent` that should probably be handled similarly. And then I noticed that that still left some references to "present" and "absent" fields. So this PR is to clean all that up. And the last commit is a bonus.
There's actually one place left that uses "present" when talking about a field, and that's in [Table 9: PrivateElement Fields](https://tc39.es/ecma262/#table-privateelement-fields), where one of the column-headers is "Values of the [[Kind]] field for which it is present" (where "it" is the field that a given row is declaring). I couldn't think of a good way to change that to the "record has a field" wording.
> Editorial: Eliminate "present" and "absent" fields

- spec.html
Extracted from https://github.com/tc39/ecma262/pull/2547#discussion_r808600292
> Editorial: disambiguate NotifyWaiter calls

- package-lock.json
- package.json
- spec.html
Ready for review. Based on #2546. Fixes #1796. Fixes #497. Fixes #496. Closes #1916. Fixes #253. Fixes #1572. Closes #486. Closes #2612. Fixes #2645.
1. [x] remove the provision for implicit wrapping in normal completion
1. [x] remove the provision for treating normal completions as their [[Value]]
1. [x] annotate return types
1. [x] make sure every AO has a return type specified; figure out what to do with any remaining explicit "unknown" returns
1. [x] see if we can replace any `~empty~` returns with `~unused~`
1. [x] make sure all internal methods with the same name have matching return types
1. [x] make sure all concrete methods with the same name have matching return types
1. [x] call sites for AOs that return completion records should use `?`/`!`/`Completion()`; call sites for AOs …
> Editorial: remove implicit wrapping/unwrapping of completion records

- spec.html
> Editorial: "a new empty List" -> "&laquo; &raquo;"

- .github/workflows/publish-biblio.yml
- biblio/README.md
- biblio/package.json
- scripts/publish-biblio.sh
Fixes https://github.com/tc39/ecmarkup/issues/251. Fixes https://github.com/tc39/ecma262/issues/2321.
I haven't tested this, but it will probably work.
~Also, we need to pick a name for it. `ecma262-biblio` seems like an obvious choice. We could choose to scope it under the `@tc39` namespace, but to my understanding we can have it be controlled by that organization even if we place it at the top-level scope.~ Edit: went with `@tc39/ecma262-biblio`.
As for version numbers, ~right now I'm just using the number of seconds since 1970 as the patch version~ edit: went with number of commits on the branch, with an explicit callout in the readme that the package does not follow semver (since the biblio can change at any time, which can break your build if you depend on it for ecmarkup and build …
> Meta: publish biblio to npm

- spec.html
... i.e., uses of "completion" that aren't preceded by "normal", "abrupt", "throw", etc., and aren't just using it in its usual English sense. This includes 8 occurrences of "completion value".
I left the 'Meaning' for `[[Type]]` ("The type of completion that occurred") as it's maybe the usual English sense. (A Completion Record doesn't "occur".) It's debatable though.
I handled the occurrences of "completion value" in various ways, depending on the context.
In cleaning up "completion value" in the description of HostImportModuleDynamically, I merged 2 list items, which is a bit surprising, so look at that one carefully.
In the Annex F cases of "completion value", I also changed 3 occurrences of `a normal completion whose value is ~empty~` to `a normal completion containing ~empty~`.
This …
> Editorial: Eliminate 'bare' uses of "completion"

- spec.html
The first commit shows my initial plan: factor out 2 operations that, while simple, improve the readability of the algorithms in which they appear.
But then a different approach occurred to me: since the results of these operations are fixed for the lifetime of a Typed Array object, compute them just once when the object is created, and put them in new internal slots.
I've kept them separate in case you prefer the first, but I prefer the second.  If you do too, the two commits can be squashed.
> Editorial: Simplify getting the Element Type/Size for a TypedArray

- spec.html
Specifically, create abstract operation `SortArrayLike` that is invoked by both `Array.p.sort` and `%TypedArray%.p.sort`.
This addresses the discussion [here](https://github.com/tc39/ecma262/pull/1585#discussion_r571709906).
This is an alternative to PR #2302: if you're interested in this PR, then that one is mostly just churn.
It turned out that I needed a lot of preliminary refactorings: if you try to factor out SortArrayLike without any preliminaries, its clause ends up with lots of references to `_comparefn_`. This doesn't make sense, because `_comparefn_` is now hidden within the closure that is the `_SortCompare_` parameter, so SortArrayLike has no access to it.
I've included the preliminaries as separate commits to aid review. (You might want to also keep them at merge-time, I …
> Editorial: Factor out common `sort` functionality

- biblio/package.json
- scripts/publish-biblio.sh
This will allow `npm show @tc39/ecma262-biblio@X specSHA` to print out the sha it's built from, for any version X after this is merged.
> Meta: biblio: add `commit` field to package.json every publish

- spec.html
This adds the specification text from https://github.com/tc39/proposal-regexp-match-indices, currently at Stage 3.
> Normative: add RegExp Match Indices

- spec.html
Ecmarkup currently doesn't number steps nicely when replacing one step with multiple. See https://github.com/tc39/ecmarkup/issues/418. This uses the workaround described in that issue. Additionally, I changed the phrasing in [B.3.6.2](https://tc39.es/ecma262/#sec-IsHTMLDDA-internal-slot-aec) to match the phrasing used to replace steps elsewhere in Annex B.
> Editorial: work around ecmarkup limititation with replacement step numbering

- spec.html
The [DestructuringAssignmentEvaluation](https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#sec-runtime-semantics-destructuringassignmentevaluation) SDO is defined over the the various Object and Array assignment patterns. Some of the Object cases were before the Array cases and some of them were after, presumably reflecting the fact that [Object rest was added later](https://github.com/tc39/proposal-object-rest-spread). This PR makes all the Object cases be consecutive.
> Editorial: tweak DestructuringAssignmentEvaluation

- spec.html
Similar to PR #2602, which used 'type' syntax when declaring record fields, this PR uses it when declaring:
- the require/optional properties of interfaces, and
- the internal slots of objects.
Also, there's a bonus commit that fixes up the field types of a recently added record.
> Editorial: Expand the use of 'type' syntax

- spec.html
This allows the call sites to be much less verbose.
> Editorial: Add ToZeroPaddedDecimalString abstract operation.

- spec.html
In [Number::multiply](https://tc39.es/ecma262/#sec-numeric-types-number-multiply), it seems that it evaluates `(-0) * (+0)` to `+0` which is different to [previous specification](http://262.ecma-international.org/11.0/#sec-numeric-types-number-multiply). Currently, it fails following test262 tests according to our implementation [ESMeta](https://github.com/es-meta/esmeta):
- test/language/expressions/multiplication/S11.5.1_A4_T2.js
> Editorial: Handled -0 case in 'Number::multiply'

- spec.html
This is currently a _potential_ spec bug, not an actual one. This AO is not called such that this would be an error, but there are no assertions to prevent it from being one.
> Editorial: MakeMatchIndicesIndexPairArray: avoid creating a property on undefined

- spec.html
`ToZeroPaddedDecimalString(-1, 3)` would produce `0-1`, for example, prior to this change.
> Editorial: `ToZeroPaddedDecimalString`: this AO is nonsensical on a negative integer

- spec.html
PR #1713 changed the signature of the Abstract Closure created+returned by CompilePattern, but didn't make the corresponding change to the return-type in the section heading.
(No uses in downstream specs.)
> Editorial: Fix the return-type of CompilePattern

- package-lock.json
- package.json
- scripts/publish-biblio.sh
- spec.html
This includes [a breaking change to the biblio format](https://github.com/tc39/ecmarkup/pull/425), so it also bumps the version number of the published biblio file.
Also, effects are now put into the biblio. Since the rendering of effects in proposals would be wrong unless they do extra work to manually mark any effects, they are not rendered by default, and `markEffects: true` must be added to enable them here.
~Edit: ugh, this has a bug apparently, don't land until it's bumped.~ Fixed in 12.0.1.
> Meta: bump ecmarkup to 12.0.1

- spec.html
Consensus for this was gotten as part of #2646.
> Normative: Remove detach check in TypedArray.prototype.sort comparator

- spec.html
> Editorial: Fix "classFieldIntializerName" spelling error in PerformEval

- spec.html
CreateUnmappedArgumentsObject creates an ordinary object, not an arguments exotic object.
(See [10.4.4 Arguments Exotic Objects](https://tc39.es/ecma262/#sec-arguments-exotic-objects) Note 1).
> Editorial: Fix CreateUnmappedArgumentsObject's return-type

- spec.html
As part of #2208 and other good stuff from @rkirsling, we changed it so that TypedArray accesses on TAs with detached buffer don't throw.
In implementing resizable buffers, @marjakh noticed in https://github.com/tc39/proposal-resizablearraybuffer/issues/86 that [`TypedArray.prototype.set`](https://tc39.es/ecma262/#sec-%typedarray%.prototype.set) would need a per-loop iteration detached / "did the buffer resize" check in [SetTypedArrayFromArrayLike](https://tc39.es/ecma262/#sec-settypedarrayfromarraylike). In investigating this, my conclusion is that the array-like case of `TypedArray.prototype.set`, to be maximally consistent with the direction we went, is to use Set and *not* throw on detached or "did the buffer resize".
My best guess as to why SetTypedArrayFromArrayLike partially …
> Normative: Use IntegerIndexedElementSet in %TypedArray%.prototype.set

- .github/workflows/enforce-format.yml
cf. https://github.com/tc39/ecma262/runs/5979841913?check_suite_focus=true
```
Run if ! $(npm bin)/emu-format --check spec.html; then echo "You need to run `npm run format`"; exit 1; fi
Need formatting:
spec.html
You need to run 
> ecma262@1.0.0 format
> emu-format --write spec.html
```
> Refactor the "enforce format" job to output literal backticks rather than command output

- spec.html
> Normative: remove Symbol.species from InitializeTypedArrayFromTypedArray

- spec.html
Closes #1721
In parts having to do with Atomics, we use the phrase "surrounding
agent" interchangeably with "calling agent". This PR makes the phrasing
uniform.
> Editorial: Use "surrounding agent" in favor of "calling agent"

- spec.html
* Use a "return number [if canonical], otherwise return `undefined`" step sequence in correspondence with the description.
* Make "canonical numeric string" a linkable \<dfn> term.
> Editorial: Align the algorithm steps and description of CanonicalNumericIndexString

- spec.html
This PR addresses a problem similar to that of issue #1884.
`_NcapturingParens_` is one of the aliases that are defined in [22.2.2.1 Notation](https://tc39.es/ecma262/#sec-notation) and then referred to 'out of the blue' by various operations.
The general approach to such cases is to make the necessary changes to pass the value explicitly to the operations that reference it.  However, `_NcapturingParens_` is also referenced by two Early Error rules and a grammar production, and there's no way to "pass a value" to such constructs.
Instead, I've replaced those references with invocations of new abstract ops:
- TheNumberOfLeftCapturingParensIn
- TheNumberOfLeftCapturingParensInThePatternContaining
I've also defined a third AO:
- TheNumberOfLeftCapturingParensToTheLeftOf
This isn't necessary …
> Editorial: Eliminate `_NcapturingParens_` from Early Error rules + grammar

- spec.html
See: https://github.com/tc39/proposal-numeric-separator/issues/32
> Editorial: Note that StringNumericLiteral cannot contain NumericLiteralSeparator

- spec.html
Fixes https://github.com/tc39/ecma262/issues/1673.
Capturing group names were introduced in https://github.com/tc39/ecma262/issues/1673, in both `u` and non-`u` regexes, but the alternate grammar for regexes in Annex B (i.e., the actual grammar for regexes) replaces in non-`u` regexes the nonterminal (`Atom`) which derives `GroupSpecifier`, and that PR neglected to update the new nonterminal (`ExtendedAtom`). This PR corrects that oversight.
I've marked this as a normative change rather than editorial because the current spec is, technically, coherent. However, the current spec does not match committee intent or web reality, so in my view we can land this without asking for consensus.
> Normative: allow named capture groups in Annex B non-u regex grammar

- spec.html
This is a follow-up to PR #2547, which tagged many operations as returning a normal completion or an abrupt completion. But in most cases, the only abrupt completion possible is a throw completion. So this PR changes lots of "abrupt completion" to the more precise "throw completion".
The first two commits deal with internal methods and host hooks, which the spec explicitly constrains to return normal+throw completions. The third commit deals with ~200 other operations, which I found via static analysis.
Of the ~50 remaining operations that still say "abrupt completion", I think quite a few should likewise change to "throw completion", but it would take more sophisticated analysis to be sure.
> Editorial: Change many "abrupt completion" to "throw completion"

- spec.html
This PR removes the parameter `callerRealm` from `HostEnsureCanCompileStrings`. `HostEnsureCanCompileStrings` is implemented in html, where the param is being removed (https://github.com/whatwg/html/pull/7653).
> Normative: Remove callerRealm from HostEnsureCanCompileStrings

- package-lock.json
- package.json
Some small tweaks, including a fix for which should un-break https://github.com/tc39/ecma262/pull/2744: https://github.com/tc39/ecmarkup/releases/tag/v12.0.3
> Meta: bump ecmarkup to 12.0.3

- spec.html
GlobalDeclarationInstantiation's `_script_` parameter is a *Script* Parse Node, not a *ScriptBody* Parse Node.
(I thought I had fixed this already, but I was remembering Issue #2354, which identified the problem in passing.)
> Editorial: GlobalDeclarationInstantiation takes a Script

- spec.html
Before this change, NumericToRawBytes is the odd one out (it uses "a BigInt or a Number" while SameValueNonNumeric and SetValueInBuffer and GetModifySetValueInBuffer all use "a Number or a BigInt").
> Editorial: Use consistent phrasing for parameters that are Number or BigInt

- spec.html
While reviewing #2721, I noticed a wording bug in the current spec:
Because the nonterminal _RegExpIdentifierName_ is defined recursively, a _GroupSpecifier_ usually contains/encloses **multiple** _RegExpIdentifierNames_.
So in a phrasing such as:
`a |GroupSpecifier| containing a |RegExpIdentifierName| which has ...`
the spec only intends the 'topmost' _RegExpIdentifierName_, but any of the 'deeper' _RegExpIdentifierNames_ could satisfy the phrase.
E.g., consider `/(?<NotTheOne>foo)\k<TheOne>/`. This *should* be a syntax error, because the _AtomEscape_ `\k<TheOne>` doesn't have a matching _GroupSpecifier_. But the _GroupSpecifier_ `?<NotTheOne>` *does* contain/enclose a _RegExpIdentifierName_ `TheOne` that matches the _GroupName_ of the _AtomEscape_, and so there isn't a syntax error. …
> Editorial: Fix wording bug by tweaking CapturingGroupName

- spec.html
Currently, `JSON.stringify` creates a Record without a named schema, and that gets passed to the `_state_` parameter (of type 'unknown') of the various `SerializeJSONFoo` operations. Instead, declare the `JSON Serialization Record` schema for this purpose.
> Editorial: Declare "JSON Serialization Record"

- spec.html
Example where performing `SetMutableBinding` on `DclRec` would return a throw completion:
```js
function f() { x = 1; }
f(); // 💥
let x;
```
This is covered by 22 tests in test262 which fail when implemented as written.
> Editorial: Fix incorrect SetMutableBinding infallibility assumption

- spec.html
Came up in https://es.discourse.group/t/note-in-liveness-section-appears-to-be-normative/1345,
where the use of "must" can be misconstrued as additional normative
requirements.
> Editorial: Remove use of "must" from liveness note

- spec.html
* Editorial: Specify required localeCompare Number output for canonically equivalent strings
* Editorial: Convert SortCompare output before comparing it against mathematical zero
> Editorial: Properly handle comparison results as Number values

- spec.html
* Remove an unnecessary "for each" step
* Combine out-of-bounds index branches
* Make aliases more clear
* Replace "number of code units in [string]" with "length of"
> Editorial: Simplify GetSubstitution

- spec.html
This adds the `d` flag as a valid flag in IsValidRegularExpressionLiteral, which is currently missing. This was intended to be supported in the RegExp Match Indices proposal, but was overlooked when that proposal advanced to Stage 4.
Fixes #2778
> Normative: Add missing `d` flag character to IsValidRegularExpressionLiteral

- spec.html
This should simplify reading and also help with KAIST-like efforts.
> Editorial: Make the steps of IsLessThan for String values more explicit

- spec.html
That is, eliminate the aliases defined in [22.2.2.1 Notation](https://tc39.es/ecma262/#sec-notation) that are magically accessible to all RegExp algorithms.
Closes #1884 (finally).
To possibly aid review, I've presented this as a logical series of commits, because the various global aliases are eliminated in 5 distinct ways. However, they should probably be squashed into one commit for merging.
There's a couple possibilities for how to handle `_Input_`. Commit 7 shows it being passed around explicitly, but commit 8 has it being passed around as a component of the `State` structure, which is a lot less 'noisy'.
(`State` should probably be made a Record, but that's not the point of this PR. I could make a separate PR if you'd like that to land before this.)
You might wish to rename …
> Editorial: Eliminate RegExp's "global aliases" 

- spec.html
I noticed that when the list is omitted, it would be passing `undefined` to an AO that asserts that it receives a List.
> Editorial: `OrdinaryCreateFromConstructor`: correctly handle an omitted internalSlotsList

- spec.html
When the detached check was removed this seems to have been left behind.
> Editorial: remove unused capture in %TypedArray%.prototype.sort

- spec.html
As observed at https://github.com/tc39/ecma262/pull/2766#discussion_r865008959 , it is very common for an iteration alias (i.e., a value that changes during iteration and effects its conclusion) to be declared immediately before its corresponding iteration. This updates a few deviations to conform more strongly with that convention.
> Editorial: Declare iteration aliases as close to iterations as practical

- spec.html
In [22.2.1.6 Static Semantics: CharacterValue](https://tc39.es/ecma262/#sec-patterns-static-semantics-character-value), it seems that `HexDigits` is typo and `Hex4Digits` is appropriate.
> Editorial: Fix typo in CharacterValue

- spec.html
Extracted from #2820. Not sure why these were `<em>` and not `<dfn>` in the first place.
> Editorial: add missing `<dfn>`s for different kinds of code

- spec.html
Issue #2576 didn't get very far, so I created this PR to spur discussion/decisions.
---
The first 4 commits perform small spot fixes.
The next 2 commits normalize the use of "method" vs "function". I started with the rule that a method is a function that is the value of a property of a prototype object, because it's easy for me to detect automatically, but then added special cases for [Typed]Array.{from,of}. I made each 'direction' (method-to-function vs function-to-method) a separate commit, because I think it's easier to review the changes that way, but they could probably be squashed later.
The remaining 12 commits perform various widespread normalizations on intrinsic function prose. I've left them as distinct commits in case you want me to back out particular changes. It might also …
> Editorial: Consistify prose for intrinsic functions 

- spec.html
The `Evaluation` SDO is different from most SDOs in several ways, which this PR tries to reduce.
Each commit is a logically separate refactoring, but they should probably be squashed before merging.
The "spec bug" label is not to imply that treating `Evaluation` differently was a bug, but rather that this PR fixes some bugs along the way.
----
(1) The definitions of `Evaluation` are distributed over the "ECMAScript Language" sections of the spec rather than being gathered into one place (as established in PR #2271).
This PR does *not* consolidate the definitions of `Evaluation`.
However, the distributed definition has also meant that this SDO doesn't have a "home" section, so the first commit of this PR adds such a section. Now there will be a place to link to for "Evaluation", and a …
> Editorial: Make `Evaluation` more like regular SDOs

- spec.html
This commit clarifies that `HostResolveImportedModule` is required to return the same Module Record when called two times with the same (`null`, _specifier_) arguments only if the two calls are executed with the same current Realm.
Fixes https://github.com/tc39/ecma262/issues/2803.
I don't know if this is normative or editorial, because I don't know what is the current requirement:
- (Editorial) The cache is already implicitly per-Realm, as suggested by @dominic in https://github.com/tc39/ecma262/issues/2803#issuecomment-1164675594
- (Normative) If the referencing script/module is `null` there is currently no caching requirement, as suggested by @codehag in https://github.com/tc39/ecma262/issues/2803#issuecomment-1165251478
- (Normative) If `HostResolveImportedModule` is called with the …
> Editorial: Clarify that the `HostResolveImportedModule` cache is per-Realm

- spec.html
Discussion at https://github.com/tc39/ecma262/pull/2418#discussion_r876052820 uncovered a strange inconsistency: unlike other methods on or related to regular expressions, [RegExp.prototype[@@match]](https://tc39.es/ecma262/multipage/text-processing.html#sec-regexp.prototype-@@match) and [RegExp.prototype[@@replace]](https://tc39.es/ecma262/multipage/text-processing.html#sec-regexp.prototype-@@replace) bypass the "flags" property, instead reading directly (and only) from "global" and "unicode"—and doing so conditionally, checking the latter if and only if the former is coerced to boolean **true**. This is awkward for the introduction of v-mode regular expressions, which need to check a third flag in at least some cases and therefore require taking a position on when to get the property …
> Normative: Always check regular expression flags by "flags"

- spec.html
(This was raised on [the discourse](https://es.discourse.group/t/consider-rewriting-bigint-value-only-convert-to-a-primitive-once/1391).)
Consider
```js
let first = true;
let v = {
[Symbol.toPrimitive]() {
console.log('called');
if (first) {
first = false;
return 'string';
} else {
return 0n;
}
}
};
BigInt(v);
```
Per spec this should print `called` twice and complete normally - step 3 of [the BigInt constructor](https://tc39.es/ecma262/multipage/numbers-and-dates.html#sec-bigint-constructor-number-value) will observe that the first call to `ToPrimitive` returns a value which is not a number and then step 4 will invoke [`ToBigInt`](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-tobigint) on the original, pre-coercion value, which will invoke `Symbol.toPrimitive` again.
In …
> Normative: only coerce once in BigInt constructor

- spec.html
I observed some phrases are written in inconsistent form:
- To extract the element from the list of length 1, other phrases use `the sole element of`.
- To check if the list is empty, other phrases use 'is empty' or 'is not empty'
- To reference some well-known objects, other phrases use `active function object` and `the running execution context`, respectively.
- To append an element to the end of list, other phrases use `append _element_ to _list_.`
- Removed unnecessary prefix 'the String' for denoting a string literal.
> Editorial: Consistify miscellaneous phrases

- spec.html
Generally, the spec capitalizes the names of types (e.g., String, Parse Node, Module Record, Data Block). One notable exception to this pattern is the subtypes of Environment Record:
- declarative Environment Record
- function Environment Record
- module Environment Record
- object Environment Record
- global Environment Record
(These are particularly odd because each combines a lower-case word with two capitalized words.)
This commit capitalizes the first word in each of these type names.
---
Downstream specs:
- Web IDL: one occurrence of "object environment record"
- HTML Standard: no uses
- ECMAScript Intl API: no uses
> Editorial: Capitalize Environment Record subtype names

- spec.html
`|ModuleSpecifier|` is the production used for the source in import declarations, but dynamic imports can use any runtime string.
> Editorial: `HostImportModuleDynamically`'s specifier can be any string

- spec.html
Closes #1339.
Closes #1541.
In ES6, both [`[[Get]]`](https://262.ecma-international.org/6.0/#sec-integer-indexed-exotic-objects-get-p-receiver) and [`[[Set]]`](https://262.ecma-international.org/6.0/#sec-integer-indexed-exotic-objects-set-p-v-receiver) TypedArray methods had the receiver checks, which were removed in #347 due to consistency with [`[[HasProperty]]`](https://262.ecma-international.org/6.0/#sec-integer-indexed-exotic-objects-hasproperty-p). Removing receiver check from [`[[Set]]`](https://262.ecma-international.org/6.0/#sec-integer-indexed-exotic-objects-set-p-v-receiver) turned out to be [web-incompatible (SM bug)](https://bugzilla.mozilla.org/show_bug.cgi?id=1502889), breaking the 🚀 NASA's WorldWind [web app](https://worldwind.earth/explorer/) and …
> Normative: Guard IntegerIndexedElementSet with receiver check

- spec.html
@tabatkins [pointed out](https://matrixlogs.bakkot.com/TC39_General/2022-05-02#L16) that Map and Set iterators are specified with explicit indexing, whereas their `forEach` methods are specified with a "for each element of entries" style loop. The historical reason for that is probably path dependence (explicit indices were required for the iterators prior to the refactoring in https://github.com/tc39/ecma262/pull/2045), but there is now no particular reason they should be different.
I've chosen to make `forEach` match the iterators rather than the other way around because I think it makes it clearer that iteration is required to hit elements added to the list during iteration (either between calls to the iterator's `next` method or by the callback to `forEach`). We could go the other …
> Editorial: Specify Map/Set forEach more explicitly

- spec.html
* Imply semantics for `:::` grammars (cf. https://github.com/tc39/proposal-temporal/issues/2190 ).
* Make the numeric string grammar summary more similar to other grammars.
> Editorial: Improve the numeric string grammar summary

- spec.html
Also includes some typo fixes in nearby text.
> Editorial: Differentiate code point identity (U+…) from value (MV, usually hex)

- spec.html
The term "ECMAScript code" is used interchangeably to refer to "ECMAScript source text" and ECMAScript programs. This bothered me so I tried to separate the cases where it made sense. In addition, there actually is a `dfn` for "ECMAScript code", defining it to be any of 4 kinds of ECMAScript source text, but I don't think the majority of existing usages intended to refer to this term. Here's the remaining cases that I haven't changed as of opening this PR, which should therefore be interpreted roughly as a synonym for "ECMAScript source text". I'm open for suggestions for how to handle these cases (including leaving them as-is).
> spec.html:2883: Return the value of the property whose key is \_propertyKey\_ from this object. If any **ECMAScript code** must be executed to retrieve the …
> Editorial: replace ECMAScript "code" with "source text" as appropriate

- spec.html
It is possible to add private fields to existing objects with the return override trick, although this is not good practice. This PR adds a new carveout allowing hosts such as HTML to reject the addition of private fields on exotic objects they define (by throwing). This is intended particularly for use with the [WindowProxy](https://html.spec.whatwg.org/multipage/window-object.html#the-windowproxy-exotic-object) exotic object, which is super weird. See discussion in https://github.com/whatwg/html/issues/7952 - the upshot is that supporting private fields on WindowProxy is a lot of potentially security-sensitive work in implementations for very little benefit.
It's conceivable that we would want to expose this ability to userland code at some point, or to non-browser hosts, but that can …
> Normative: allow host exotic objects to reject private fields

- spec.html
See https://tc39.es/proposal-hashbang/out.html / https://github.com/tc39/proposal-hashbang
> Normative: add hashbang comments

- spec.html
I introduced this typo in https://github.com/tc39/ecma262/pull/2766. Thanks to @jmdyck for the catch.
> Editorial: fix typo in Set.prototype.forEach

- spec.html
> Editorial: remove misleading sentence about outdated use of "empty"

- spec.html
Split out from #2842. This is a straight refactoring, just reording some `if`s. The only part which isn't totally obvious is that previously there was the following if-else chain:
```
1. If _destructuring_ is *false*, then
1. If _lhsRef_ is an abrupt completion, then
1. Let _status_ be _lhsRef_.
1. Else if _lhsKind_ is ~lexicalBinding~, then
1. Let _status_ be Completion(InitializeReferencedBinding(_lhsRef_, _nextValue_)).
1. Else,
1. Let _status_ be Completion(PutValue(_lhsRef_, _nextValue_)).
```
If you read the original carefully, the only place that could make `_lhsRef_` be an abrupt completion is this earlier bit:
```
1. If _lhsKind_ is either ~assignment~ or ~varBinding~, then
1. If _destructuring_ is *false*, then
1. Let _lhsRef_ be Completion(Evaluation of _lhs_). (It may be …
```
> Editorial: refactor ForIn/OfBodyEvaluation

- spec.html
Fixes #2847 by adding a `radix` parameter to `Number::toString`.
/cc @bathos
> Editorial: clarify string representation of numbers with radix ≠ 10

- spec.html
https://github.com/tc39/ecma262/pull/2744 removed almost every case where GetValue or PutValue was passed a completion record, instead explicitly unwrapping on the previous line or lines. This removes the final three cases and then updates the definitions of those algorithms so that they do not need to handle being passed Completion Records.
> Editorial: GetValue and PutValue do not need to unwrap Completion Records

- spec.html
Previously we were acting as though the value of a missing parse node in an SDO definition was `~[empty]~` but that's not how it works as far as I'm aware. Now I explicitly test for their presence and pass the (more typical) enum `~empty~`.
> Editorial: replace implicit `~[empty]~` in ForBodyEvaluation with explicit `~empty~`

- spec.html
As of #2547 (edit: plus #2744 and #2842), it is always statically knowable whether a given expression at a given point is a Completion Record or not a Completion Record. So the various completion record unwrapping macros don't need to have a "what if it is not a completion record" case.
> Editorial: IfAbrupt macros only take completion records

- package-lock.json
- package.json
Should un-block https://github.com/tc39/ecma262/pull/2863 (except for the IPR), via inclusion of https://github.com/tc39/ecmarkup/pull/478.
> Meta: bump ecmarkup to 14.1.1

- spec.html
The `1. a.` step of [6.1.6.29 BigInt::leftShit(x, y)](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-numeric-types-bigint-leftShift) divides `ℝ(_x_)` by 2<sup>-y</sup>:
> 1. Return the BigInt value that represents ℝ(_x_) / 2<sup>-_y_</sup>, rounding down to the nearest integer, including for negative numbers.
Similarly, the step `2` in the same algorithm multiplies `ℝ(_x_)` by 2<sup>y</sup>:
> 1. Return the BigInt value that represents ℝ(_x_) &times; 2<sup>_y_</sup>.
However, there is no explicit rules for treating exponentiation of a _mathematical value_ base and a _BigInt_ exponent. Therefore, I suggest changing `_y_ ` into `ℝ(_y_)` to compute the exponentiation with mathematical base and exponent.
> Editorial: bugfix for exponentiation of Number and BigInt

- spec.html
In&nbsp;[**Array&nbsp;Exotic&nbsp;Objects**<code>.</code>&#x2060;<code>[[DefineOwnProperty]]</code><code>(</code><code><var>P</var></code><code>,</code><code><var>Desc</var></code><code>)</code>](https://tc39.es/ecma262#sec-array-exotic-objects-defineownproperty-p-desc), only&nbsp;the&nbsp;<code><var>oldLenDesc</var></code> and&nbsp;<code><var>oldLen</var></code> variables are&nbsp;used, and&nbsp;there’s&nbsp;no&nbsp;<code><var>newLenDesc</var></code> or&nbsp;<code><var>newLen</var></code>&nbsp;variable referenced&nbsp;anywhere, so&nbsp;I’m&nbsp;renaming <code><var>oldLenDesc</var></code>&nbsp;and&nbsp;<code><var>oldLen</var></code> to&nbsp;<code><var>lengthDesc</var></code> and&nbsp;<code><var>length</var></code>&nbsp;respectively.
> Editorial: Improve `Array.[[DefineOwnProperty]]` length variable names

- spec.html
noticed as part of #2746 (which it extends; the first commit can be ignored)
Similar to #2737, this should simplify reading and help with KAIST-like efforts.
> Editorial: Make the steps of GetStringIndex more explicit

- spec.html
According to #2746, there are some inconsistent phrases that still use 'the number of code units in' for denoting the length of string value.
> Editorial: Fix remaining phrases using 'the number of code units in' for string length

- spec.html
Fixes #2860. Similar to what we did for `Number.prototype.toString` in #2854.
/cc @bathos
> Editorial: clarify BigInt.prototype.toString for non-decimal radices

- spec.html
These were only added because we were doing dispatch on Number and BigInt which meant they needed matching AOs. We no longer do that.
We could also get rid of `BigInt::equal` by inlining it into the single call site you see here.
> Editorial: get rid of BigInt::sameValue and BigInt::sameValueZero

- spec.html
This is a partial resolution for #2870, as [suggested](https://github.com/tc39/ecma262/issues/2870#issuecomment-1224640184) by @jmdyck.
> Editorial: avoid using Type macro for simple type tests

- spec.html
I think this is simpler, more idiomatic, and reads better.
> Editorial: refactor String.fromCharCode to build a String directly

- spec.html
Alternatively we could make it a note, but I don't think it's needed given the assert.
> Editorial: turn "no action is required" step in Array reverse into note

- spec.html
In the definition of:
- an operation parameter,
- an operation return, or
- a record field,
don't just say "a List", say "a List of [element type]".
(In this PR, it's mostly "a List of ECMAScript language values", plus 3 cases of "a List of byte values".)
> Editorial: Expand on "a List"

- spec.html
... from Boolean to `~unused~`.
When CreateDataPropertyOrThrow returns a normal completion, the `[[Value]]` of that completion is never used (because the only thing it can be is `*true*`, so why bother looking?). So change it to `~unused~`.
Downstream:
- Intl API uses CreateDataPropertyOrThrow lots, but always with "Perform".
- No uses in Web IDL or HTML.
> Editorial: Change CreateDataPropertyOrThrow's normal return

- spec.html
Just for consistency's sake. There's a few other places we declare multiple variables on one line, but those seem motivated by the algorithm's structure; this does not.
> Editorial: split variable declarations into their own lines in JSON.stringify

- spec.html
Since this AO takes a `kind` where 2 of the 3 values cause it to *not* return names, I felt `EnumerableOwnPropertyNames` was a poor name for it.
> Editorial: rename EnumerableOwnPropertyNames to EnumerableOwnProperties

- spec.html
Fixes #2570
* Introduce a definition for ASCII word characters
* Refer to Unicode Basic Latin as "block" rather than "range"
* Refactor URI Handling Functions for clarity
* Refactor `escape` for clarity
* Replace |ControlLetter| with |AsciiLetter|
> Editorial: Consolidate use of ASCII subsets

- spec.html
This makes the phrasing in ReadSharedMemory Event match the phrasing in WriteSharedMemory Event, and in my opinion reads better.
> Editorial: use consistent wording in [[NoTear]] explanation for read/write events

- spec.html
Fixes #2907. @bakkot Maybe a lint rule is in order?
> Editorial: replace any occurrences of "nonempty" with "non-empty"

- spec.html
`"a".substr(0, Infinity)` should return `"a"`, but #2007 incorrectly changed the result to be `""`.
If we change `substr`'s algorithm to be more similar to `String.prototype.substring` and `String.prototype.slice`, we can easily fix this issue:
1. `min(intStart, size)` guarantees that `intStart` is now in `[0, size]`.
2. Clamping `intLength` guarantees it's also in `[0, size]`.
With these two changes, `intEnd = min(intStart + intLength, size)` is now in range `[intStart, size]`, so we no longer have to check for `intStart ≥ intEnd`, but instead can directly perform the `substring` operation.
> Editorial: Revert unintentional normative change for String.prototype.substr

- spec.html
An [Abstract Closure](https://tc39.es/ecma262/#sec-abstract-closure) is not an abstract operation. It is clear since this sentence in the section [Abstract Closure](https://tc39.es/ecma262/#sec-abstract-closure):
> Like [abstract operations](https://tc39.es/ecma262/#sec-algorithm-conventions-abstract-operations), invocations perform the algorithm steps described by the Abstract Closure.
However, [5.2.3.5 Implicit Normal Completion](https://tc39.es/ecma262/#sec-implicit-normal-completion) section only covers abstract operations and builtin functions, but not abstract closures. So, it is necessary to use `NormalCompletion` to return a normal completion wrapping a specific value.
Several abstract operations that create iterators (e.g., …
> Editorial: Fix completion in CreateListIteratorRecord and CreateArrayIterator

- spec.html
If the test at step 13 fails (i.e., `_result_.[[Type]]` isn't `~normal~`), then execution immediately goes to step 14, where `_result_.[[Type]]` *still* isn't `~normal~`, and the test will fail.
I.e. step 14's test can succeed only if step 13's test succeeds, so step 14 might as well be indented under step 13.
(This goes back to ES6.)
> Editorial: Tweak ScriptEvaluation

- spec.html
The current text for MAX_SAFE_INTEGER and MIN_SAFE_INTEGER is somewhat indirect, resulting in repeated confusion and re-explanation of what those values signify and why they should not have magnitude 2<sup>53</sup> (i.e., failing to indicate the relevance of "n + 1" and "n - 1"). It also comes up in other contexts, cf. https://github.com/httpwg/http-extensions/issues/737#issuecomment-452189033 .
This PR attempts to remedy the issue with both prose and simple code examples of collision at 2<sup>53</sup>.
> Editorial: Explain why *_SAFE_INTEGER magnitude is not a power of two

- spec.html
In the current spec, there are ~250~ 240 AO/SDO parameters with a type of "unknown". This PR replaces ~almost~ all of those unknowns with a reasonable type.
<strike>I say "almost all" because it skips:</strike>
- <strike>the 3 `_state_` parameters handled by PR #2741, and</strike>
- <strike>the 5 `_V_` and `_W_` parameters of GetValue, PutValue, and InitializeReferencedBinding, because they're weird, and need some attention before they can get sensible types.</strike>
(PR #2741 and PR #2842 have both been merged, so the above exceptions have already been dealt with.)
The PR is broken into commits according to what replaces "unknown", in case that helps review. Squash before merging.
> Editorial: Eliminate "unknown" as a parameter type

- spec.html
We already have 17 occurrences of "is not finite" and 7 occurrences of "is finite", so I've identified the remaining locations where "is not finite" can be used and changed those. I also added a `<dfn>` for "finite" so it links.
> Editorial: use "is not finite" in more places where appropriate and add dfn for "finite" so they link

- spec.html
There are a couple of algorithms in the spec (`parseInt` and `get RegExp.prototype.flags`) that treat String values as if they're mutable, removing and appending code units.
Modify these algorithms to treat String values as immutable.
(I'm pretty sure these are the only ones, but it's possible I missed something.)
> Editorial: Eliminate mutable String values

- spec.html
This was inspired by [my comment in PR #2843](https://github.com/tc39/ecma262/pull/2843#issuecomment-1204686524), but isn't exactly what I described there.
The first two commits move two AOs out of "Abstract Operations for the RegExp Constructor", where they don't really belong. I move them closer to their invocation(s).
- (1) WordCharacters: I was the one (in #2716) who put WordCharacters in its current location, but I have no idea why. Here, I move it to under [22.2.2.9 Runtime Semantics: CompileToCharSet](https://tc39.es/ecma262/#sec-compiletocharset), but it would also fit after [22.2.2.4.1 IsWordChar](https://tc39.es/ecma262/#sec-runtime-semantics-iswordchar-abstract-operation).
- (2) EscapeRegExpPattern (which isn't even invoked by the RegExp constructor): I move it to under its …
> Editorial: Relocate some RegExp-related operations

- package-lock.json
- package.json
- spec.html
I chose to use "within the inclusive range from A to B" or use chained comparisons where possible. For ranges that have an open end, I name each side as either exclusive or inclusive.
> Editorial: consistency in phrasing of ranges and inclusivity/exclusivity

- spec.html
String.prototype.lastIndexOf must define _searchLen_ before using it.
(fixup for PR #2848)
> Editorial: Define alias before reference

- spec.html
Fixes a few places that seem to incorrectly apply a language operator to a spec alias.
Also corrects a confusing use of "IEEE 754-2019" to refer to the entire IEEE 754 _series_.
> Editorial: Replace mixtures of spec aliases with language operators

- spec.html
This avoids the ill-defined character range.
> Editorial: define `\d` semantics in a similar way to `\s`, avoiding character range

- spec.html
This mirrors what we do in the complementary AO, `RawBytesToNumeric`.
> Editorial: in NumericToRawBytes, consolidate byte ordering decision

- spec.html
[5.1.5 Grammar Notation](https://tc39.es/ecma262/#sec-grammar-notation) is a long section that covers lots of subtopics with no aids to navigation. This PR breaks it up into subsections, which I think makes it more digestible, and provides more precise anchors for links.
(The bulk of the diff is caused by having to indent the existing text of the section. I recommend viewing the diff with "Hide whitespace" checked.)
> Editorial: Subdivide the "Grammar Notation" section

- spec.html
In NewDeclarativeEnvironment, allow parameter `_E_` to be `*null*`,
and in NewGlobalEnvironment, change
`a new declarative Environment Record containing no bindings`
to
`NewDeclarativeEnvironment(*null*)`
History: `NewDeclarativeEnvironment(*null*)` used to have different semantics, which would have been wrong for NewGlobalEnvironment, so the latter used `a new declarative Environment Record containing no bindings` instead. But the merge of PR #1697 changed the semantics of NewDeclarativeEnvironment, and now it makes sense for NewGlobalEnvironment to call it.
The first commit in PR #2287 did something analogous for NewObjectEnvironment and NewGlobalEnvironment's call to it.
(prompted by https://github.com/engine262/engine262/issues/166)
> Editorial: Have NewGlobalEnvironment invoke NewDeclarativeEnvironment

- spec.html
... to separately handle
- NoSubstitutionTemplate,
- TemplateHead,
- TemplateMiddle, and
- TemplateTail.
This separates all the `_raw_/TV/TRV` stuff from the list-concatenation stuff, which I think makes it easier to see what's going on.
~(I don't think GitHub's diff is very helpful for this one.)~
> Editorial: Refactor TemplateStrings SDO

- spec.html
Extracted from #2901. Makes the wording consistent and clearly separates the aliases being declared from the ones being referenced.
> Editorial: refactor remainder AOs

- spec.html
This leaves a few cases of `the String value *"…"*` where it seems important to highlight that the value is a string (and most consistently in sections defining the initial value of a `@@toStringTag` property), but otherwise updates to just `*"…"*`. There is also some minor cleanup of operation descriptions in the neighborhood of those changes, for CanonicalNumericIndexString and Atomics.wait.
> Editorial: Improve consistency of referring to String values

- spec.html
Currently, it is technically possible for the following two operations to
result in different local times and different time zones:
```js
> date = new Date()
> date.toTimeString()
'13:43:47 GMT-0700 (Pacific Daylight Time)'
> new Intl.DateTimeFormat(undefined, {timeStyle: 'full'}).format(date)
'1:43:47 p.m. Pacific Daylight Time'
```
This is because Date gets its notion of the current system time zone from
the operation LocalTZA, while Intl.DateTimeFormat uses the operation
DefaultTimeZone from ECMA-402 to determine the current system time zone.
This is a normative change because there was previously no requirement for
these to be linked. However, they *should* definitely be linked, and no
implementation that includes ECMA-402 that I'm aware of has a discrepancy
between the two. This …
> Normative: Use DefaultTimeZone to get the local time zone for Date

- spec.html
> Editorial: Document use of <ABBREV> grammar covering multiple code points

- spec.html
We found the return type bug in the syntax-directed operation: [13.3.9.2 Runtime Semantics: ChainEvaluation](https://tc39.es/ecma262/#sec-optional-chaining-chain-evaluation) via [ESMeta](https://github.com/es-meta/esmeta) type analyzer.
Currently, the type of `ChainEvaluation` is defined as follows:
```
Runtime Semantics: ChainEvaluation (
_baseValue_: an ECMAScript language value,
_baseReference_: an ECMAScript language value or a Reference Record,
): either a normal completion containing an ECMAScript language value or an abrupt completion
completion
```
However, I think its return type should contain `a normal completion containing a Reference Record`.
For the following cases, it invokes [13.3.6.2 EvaluateCall](https://tc39.es/ecma262/#sec-evaluatecall) and returns its result. So, it …
> Editorial: Fix return type of ChainEvaluation algorithm

- spec.html
HasCallInTailPosition was defined in one place even prior to the more general [SDO consolidation](https://github.com/tc39/ecma262/pull/2271).
But that one place was split up into two subclauses. Prior to SDO consolidation that wasn't remarkable, but afterwards it was, since no other SDO split its parts into subclauses like this. Plus it makes static analysis harder. So remove the subclauses.
I recommend reviewing this PR [with whitespace changes suppressed](https://github.com/tc39/ecma262/pull/2896/files?w=1).
> Editorial: combine the two subclauses for HasCallInTailPosition

- spec.html
We found a bug in parameter types of the abstract algorithm [24.1.1.2 AddEntriesFromIterable](24.1.1.2 AddEntriesFromIterable) via [ESMeta](https://github.com/es-meta/esmeta) type analyzer.
Currently, the type of `AddEntriesFromIterable` AO is defined as follows:
```
AddEntriesFromIterable (
_target_: an Object,
_iterable_: an ECMAScript language value, but not *undefined* or *null*,
_adder_: a function object,
): either a normal completion containing an ECMAScript language value or a throw completion
```
However, I think the parameter `adder` could have any ECMAScript value.
The `AddEntriesFromIterable` is referred in three different algorithms:
- [Step 6 in 20.1.2.7 Object.fromEntries](https://tc39.es/ecma262/#_ref_8810)
- [Step 6 in Step 24.1.1.1 …
> Editorial: move adder callability check out of `AddEntriesFromIterable`

- spec.html
This will help us catch editorial errors (it already caught 1) and IMO reads better by allowing for other groupings (such as by output in `ToBoolean`).
I'd recommend reviewing before/after rendering instead of reading the changeset.
There's probably more opportunities to replace tables, but this is a good start.
> Editorial: replace steps embedded in lookup tables with more typical algorithms

- esmeta-ignore.json
- spec.html
Specifically, replace "Private Name" with "PrivateElement".
ClassElementEvaluation's second definition is relevant: it returns the result of calling MethodDefinitionEvaluation, which can return a PrivateElement, not a Private Name.
> Editorial: Fix ClassElementEvaluation's return type

- spec.html
cf. [AsyncGeneratorCompleteStep](https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-asyncgeneratorcompletestep) and [%ForInIteratorPrototype%.next](https://tc39.es/ecma262/multipage/ecmascript-language-statements-and-declarations.html#sec-%foriniteratorprototype%.next)
> 1. Let _element_ be the first element of _list_.
> 2. Remove the first element from _list_.
> Editorial: Use consistent algorithm steps to consume the head of a List

- spec.html
String contents don't matter any time _fromIndex_ + _searchValue_.length > _string_.length, not just when _fromIndex_ exceeds the length on its own.
> Editorial: Generalize the note about when StringIndexOf is guaranteed to return -1

- spec.html
That is, eliminate NOTE-steps that tell you where a Return-step returns to.
Resolves #2400 by performing the transformation outlined in https://github.com/tc39/ecma262/issues/2400#issuecomment-832335872
This PR goes in roughly the same direction as #2429, but not as far, so maybe it has a better chance of being approved.
> Editorial: Eliminate weird `Return` notes

- spec.html
Ecmarkup currently special-cases the phrase "the result of evaluating" as invoking user code, but as of https://github.com/tc39/ecma262/pull/2744 we barely use that terminology and instead invoke the Evaluation SDO. But we forgot to mark that SDO as invoking user code, despite that being definitionally what it is.
I recall discussing that we'd need to do this, but either I dreamt that or we forgot. Either way, whoops.
> Editorial: Evaluation is user code by definition

- spec.html
The first commit does the conversion, which is possible now that PR #2665 is merged.
The second commit moves the `Await` section to a more appropriate location. Currently, it's in 6.2.4 "The Completion Record Specification Type", and I move it to the end of "27.6.3 AsyncGenerator Abstract Operations". (There isn't one obviously perfect spot for it, but this is my guess at the best.)
> Editorial: Convert `Await` from a shorthand to an abstract operation

- .github/workflows/esmeta-typecheck.yml
- spec.html
In the specification of each of the constructors:
- Function
- GeneratorFunction
- AsyncGeneratorFunction
- AsyncFunction
the parameter list is given as
`( _p1_, _p2_, &hellip; , _pn_, _body_ )`
Note that these specific parameters are not referenced by the preamble or the algorithm. The preamble used to refer to them, before PR #2592; I don't think the algorithm has ever referred to them. Instead, the algorithm currently says:
```
Let _args_ be the _argumentsList_ that was passed
to this function by [[Call]] or [[Construct]].
```
The wording of this step is problematic:
- It refers to an alias that is defined in another algorithm (which is prompting some special-casing in PR #2901).
- It says that `[[Call]]` or `[[Construct]]` is passing something to this function, which is incongruous. …
> Editorial: Tweak the parameter list of Function constructors

- spec.html
This is an alternative to #2818. See that PR for more context - this implements option 3 of the options listed there. Fixes https://github.com/tc39/ecma262/issues/2813.
The main effect of this PR would be that if you had
```js
let done = false;
let inner = {
[Symbol.asyncIterator]: () => ({
next() {
if (done) {
return Promise.resolve({ done: true });
}
done = true;
return Promise.resolve({ done: false, value: Promise.resolve(0) });
},
}),
};
async function* outer() {
yield* inner;
}
(async () => {
for await (let x of outer()) {
console.log(x);
}
})().catch(e => {
console.log('threw', e);
});
```
then you would see printed `Promise.resolve(0)` instead of, as currently, `0`. In other words, it would behave as if you'd written `for await (let x of inner)` instead of `of outer()`.
The other …
> Normative: avoid mostly-redundant `await` in async `yield*`

- spec.html
This PR also removes the HostResolveImportedModule and HostImportModuleDynamically hooks.
A few comments/questions:
1. ContinueDynamicImport is kinda messy, with all the closures and PerformPromiseThen. Is it ok to extend AsyncBlockStart like in https://tc39.es/proposal-array-from-async/#sec-asyncblockstart so that I can use the Await macro?
1. ResolveExport is described as returning *null* or something, but it can also return a throw completion (if it's called on a module that re-exports from a dependency that hasn't been already loaded - **NOTE:** this can only happen if a host calls ResolveExport() even if LoadRequestedModules() doesn't succeed, and they don't have any good reason to do so). This was the behavior even before this PR.
- Is it ok?
- Should we make it return null?
- …
> Layering: Add HostLoadImportedModule hook

- spec.html
In my understanding, the common practice for completion records is to use them as immutable records. For example, [6.2.4.3 UpdateEmpty](https://tc39.es/ecma262/#sec-updateempty) does not directly modify the `[[Value]]` field but creates another completion record having the given value in the `[[Value]]` field.
However, step 7.c.iii.2 in the [15.5.5 Runtime Semantics: Evaluation](https://tc39.es/ecma262/#sec-generator-function-definitions-runtime-semantics-evaluation) for ``<emu-grammar>YieldExpression : `yield` `*` AssignmentExpression</emu-grammar>`` breaks this common practice. I think this is the only step that treats completion records as mutable in the spec.
In addition, as mentioned in https://github.com/es-meta/esmeta/issues/65, we found that only three Test262 tests related to …
> Editorial: Fixed mutable completion records as immutable

- spec.html
Consolidates the exception throwing associated with trying to interact with a revoked proxy.
> Editorial: Clarify proxy operations with a named helper operation

- spec.html
> Normative: Allow implementations to pad timeouts in SuspendAgent

- spec.html
In GeneratorStart, AsyncGeneratorStart, and AsyncBlockStart, there is the following construct:
```
1. Set the code evaluation state of _context_ such that when evaluation
is resumed for that execution context the following steps will be performed:
1. <inner-steps>
```
This is a fairly novel construct, but we can reduce the novelty. Specifically, consider the `<inner-steps>`: they are to be performed later, but can refer to aliases defined in the outer algorithm. These are things that we see in Abstract Closures, so we can pull out those aspects of the construct:
```
1. Let _closure_ be a new Abstract Closure with no parameters
that captures <aliases> and performs the following steps when called:
1. <inner steps>
1. Set the code evaluation state of _context_ such that when evaluation
is …
```
> Editorial: Use Abstract Closure to set the code eval state

- spec.html
The spec is inconsistent on "element[s] in X" vs "element[s] of X".
In pseudocode, I count 37 "in" vs 229 "of".
So in the first commit, I change all the "in" to "of".
----
However, I don't entirely like the result. While:
- "the elements of X"
- "each element of X"
- "an element of X"
- "the first/last element of X"
all sound fine to me, "the number of elements of X" sounds odd.
Compare:
- "the number of hours in a day" vs "the number of hours of a day"
- "the number of pups in a litter" vs "the number of pups of a litter"
Also note that the status quo spec has
- ~28 occurrences of "the number of elements in" vs
- ~11 of "the number of elements of".
So in the second commit, I change "of" to "in" just for "the number of elements of X".
(Alternatively, we could avoid this question by …
> Editorial: Consistify re "elements in/of"

- spec.html
The first two make the declared type narrower, and the rest make it wider (by adding `~empty~` or `*undefined*`).
The changes can be confirmed by looking at the places where the fields are set.
> Editorial: Correct the 'Value Type' of a few Record fields

- spec.html
Some Record values don't have a named schema. The spec has a standard way to refer to these in parameter-types and return-types, e.g.:
`a Record with fields [[CharSet]] (a CharSet) and [[Invert]] (a Boolean)`
However, for a *List* of such values, the spec isn't so consistent. This PR changes 2 "List of Records" types to use the "with fields" phrasing.
---
Also, for [[TemplateMap]], I made the field types more precise.
> Editorial: Rephrase 2 "List of Records" types

- spec.html
Modify NewPromiseCapability() to wait until the very end to create the PromiseCapability Record, so that its fields have non-transient values.
As suggested in https://github.com/tc39/ecma262/pull/2963#discussion_r1033986008
> Editorial: Create PromiseCapability Record with non-transient field values

- spec.html
cf. https://tc39.es/ecmarkup/#emu-grammar
> Editorial: Use the preferred indication for example grammars

- package-lock.json
- package.json
- spec.html
The breaking change in version 16 is the removal of the automatic handing of the phrase "the result of evaluating" as user code. Our use of that phrase was almost entirely removed in https://github.com/tc39/ecma262/pull/2744, so only two sites still require manual marking.
This should also unblock https://github.com/tc39/ecma262/pull/2972 via inclusion of https://github.com/tc39/ecmarkup/pull/514.
> Meta: bump ecmarkup to 16.0.1

- esmeta-ignore.json
- spec.html
At the latest editors call, I was invited to expand on https://github.com/tc39/ecma262/pull/2877#issuecomment-1340382495, giving specific cases instead of just counts. That's what this PR does.
Most of the commit messages have a relevant excerpt from that comment and some discussion.
> Editorial: Examine+reduce the diversity of forms in PR #2877

- esmeta-ignore.json
- spec.html
Extracted from #2821. Fixes #2794.
* use `=`, <code>&ne;</code>, `<`, <code>&le;</code>, `>`, and <code>&ge;</code> for mathematical value and bigint comparisons (except in asserts); prefer `=` over <code>&ne;</code>
* use `is`, `is not`, `<`, <code>&le;</code>, `>`, and <code>&ge;</code> for number comparisons
* use `SameValue(..., ...) is *true*` for equality comparison of symbols (except well-known) / objects / unknown ECMAScript language values
* use `is` and `is not` for equality comparison of all other values, including booleans, strings, well-known symbols, null, undefined, enums, etc; avoid "is different from" or "is the same as"
* prefer "if a is either b or c" over "if a is b or a is c"; use "any of" in place of "either" when more than 2 options
* prefer "if a is c and b is c" …
> various editorial changes for comparisons

- spec.html
Even though aliases are "reference-like" per [Algorithm Conventions](https://tc39.es/ecma262/multipage/notational-conventions.html#sec-algorithm-conventions), it is not always clear in context that steps like "append \<value> to _listAlias_" and "remove \<value> from _listAlias_" affect the Record whose field is referenced by _listAlias_—and to be honest, the presence of many such aliases doesn't even contribute very much in my opinion. But this PR is still split into meaningful commits in case the editors disagree with a subset of its changes.
Another alternative option would be to keep the aliases but make their behavior more explicit, as is done like "Let _S_ be **a reference to** the list of waiters in _WL_." in [RemoveWaiters](https://tc39.es/ecma262/multipage/structured-data.html#sec …
> Editorial: For clarity, manipulate _record_.[[Field]] rather than its alias

- spec.html
Found this while investigating a different issue here: https://github.com/tc39/ecmarkup/issues/518#issuecomment-1430542065
> Editorial: add emu-not-ref for "date-time values"

- spec.html
This PR fixes #2434.
In the core grammar, named backreferences have been syntax errors if no `u` flag. For example, `/(?<foo>A)\k<foo>/` is a syntax error unless using Annex B.
This PR fixes that by moving two passes parsing to Annex B.
> https://arai-a.github.io/ecma262-compare/?pr=2436&collapsed=1
> Normative: allow named backreferences without `u` flag in core grammar

- .github/workflows/ipr.yml
This aligns it with the other privileged jobs.
> Meta: Limit IPR check job to the tc39 repository

- esmeta-ignore.json
- spec.html
Factor out ArrayFindViaPredicate from:
- Array.prototype.find
- Array.prototype.findIndex
- Array.prototype.findLast
- Array.prototype.findLastIndex
and factor out TypedArrayFindViaPredicate from:
- %TypedArray%.prototype.find
- %TypedArray%.prototype.findIndex
- %TypedArray%.prototype.findLast
- %TypedArray%.prototype.findLastIndex
----
ArrayFindViaPredicate and TypedArrayFindViaPredicate are mostly the same, so it's tempting to go one step further and factor out FindViaPredicate (say). We could then either:
- retain ArrayFVP and TypedArrayFVP as a couple steps + a call to FVP, or
- push those non-common steps back to the caller functions.
But I didn't do any of that because I wasn't sure.
> Editorial: Factor out FindViaPredicate

- spec.html
Resolves issue #3010.
----
Usually, I rename the inner alias, but in one case, I rename the outer...
- In `AsyncFromSyncIteratorContinuation` and `Await`: change the AC's `_value_` to `_val_`.
- In `Promise.prototype.finally`: change both ACs' `_promise_` to `_prom_`.
- In `GeneratorStart` and `AsyncGeneratorStart`: change the AC's `_genContext_` and `_generator_` by prepending 'ac'.
- In `AsyncBlockStart`: change the AC's `_asyncContext_` likewise.
- In `Proxy.revocable`: change the *outer* `_p_` to `_proxy_`.
----
Possible wording for editorial convention:
> Every Abstract Closure (AC) is defined within an 'outer' algorithm. Inside the AC, the only outer aliases that are visible are the ones explicitly captured in the AC's header. Any other outer aliases cannot be referenced within the …
> Editorial: Ensure Abstract Closures don't re-use outer aliases

- spec.html
Stage 4 spec for https://github.com/tc39/proposal-change-array-by-copy
> Normative: Adds change-array-by-copy

- spec.html
> Editorial: mark a note step as a note

- spec.html
#3024 
change:
The unary `-` operator converts its operand to Number type and then negates it.
to:
The unary `-` operator converts its operand to a numeric value and then negates it.
> Editorial: fix the Unary - Operator's description

- spec.html
This PR represents the Stage 3 specification text for [Symbols as WeakMap keys](https://github.com/tc39/proposal-symbols-as-weakmap-keys).
The proposed spec has been written as a PR against the full spec due to the high number of small tweaks to descriptions and notes in sections such as liveness.
A separate minimal proposal specification with only the core changes is available at http://tc39.es/proposal-symbols-as-weakmap-keys
Closes #1194
> Normative: Permit Symbols as WeakMap keys

- spec.html
There was a lot of gratuitous divergence between Encode, Decode, escape, and unescape, and also between those operations and other string operations.
Non-comprehensive improvements:
* Make better use of ParseText to get Parse Nodes or errors rather than testing syntax first.
* Align on `code {unit,point} whose numeric value is…` phrasing rather than `code {unit,point} whose value is…`.
* Increase the majority of `Let _len_ be the length of…` over alternate aliases for `_len_`.
* Increase the majority of `Repeat, while _k_ &lt; _len_` iteration over alternatives like `while _k_ ≠ _len_` or embedded `If _k_ = _len_, return…`.
* Make better use of string-concatenation accepting both strings and code units.
> Editorial: Increase consistency and clarity of string operations

- spec.html
I find GetIterator's optional parameters confusing because the hint is ignored when the method is passed. There's also a recursive call that serves no real purpose.
This PR gets rid of the optional parameters and does some refactoring.
> Editorial: Clarify GetIterator

- spec.html
`GetV` just does a `ToObject`, but we already know `iterator` is an Object due to the check in the previous step.
> replace an unnecessary GetV with a Get

- package-lock.json
- package.json
The notable change here is that you can now click on `[[FieldNames]]` to highlight other uses of that name within the same algorithm, like you could already do for variable names. Thanks to @gibson042 for [the PR](https://github.com/tc39/ecmarkdown/pull/96).
This is mainly expected to be useful for specs like 402 and Temporal, which make heavier use of objects with many internal slots than 262 does. But we might as well have it here as well.
~~(Edit: sigh, I see I need to do a patch release first...)~~ Done.
> Meta: bump ecmarkup to 16.1.1

- spec.html
Fixes #3036. Closes #1277.
There's other places where such a note could be warranted (e.g. in `push`) but I'm not adding new notes in this PR.
> Editorial: Fix notes about explicit setting of "length" in certain Array methods

- spec.html
`RegExp(…)` is not equivalent to `new RegExp(…)`, because when the argument is an existing `RegExp` object, the former passes through the same object and the latter creates a new one (with e.g. `lastIndex` reset).
Fixes #3028.
> Editorial: Remove incorrect equivalence claim for RegExp constructor

- spec.html
We have a few cases of algorithms with steps like
```
1. …
1. If <condition>, <simple consequent>.
1. Else,
1. <alternative step 1>.
1. …
1. …
```
This makes it unnecessarily difficult to track expected behavior, especially when skimming, and I think the spec should have a convention (ultimately codified as a lint rule) to avoid mixing collapsed an non-collapsed steps at the same level of an If–Else construct.
The first commit of this PR replaces violations of that convention, and ~~later commits (removable upon request)~~ PRs #3044, #3045, and #3046 apply simplifications in the neighborhood of its changes.
> Editorial: Avoid preceding a multi-step Else with a collapsed single-step If

- spec.html
This PR addresses two inconsistencies:
* Some expressions of the form "_x_<sup>_y_</sup> - _z_" are missing spaces around the operator.
* Some uses of 𝔽/ℤ/ℝ wrap the argument in `<emu-eqn>` when it includes exponentiation, while others do not. Uses inside of `<emu-alg>` never include the wrapping, while uses outside of it are evenly split (but never wrap any argument _without_ exponentiation, even if it uses other operations such as division with `/`):
```sh
$ grep -v '^ *1[.]' spec.html | grep -o '[𝔽ℤℝ][(][^()]*\([(][^()]*[)][^()]*\)*[)]' | grep '<sup>' | sort | uniq -c
1 𝔽(2<sup>32</sup> - 1)
1 𝔽(-(2<sup>53</sup> - 1))
2 𝔽(2<sup>53</sup> - 1)
1 ℤ(-2<sup>63</sup>)
1 ℤ(2<sup>63</sup> - 1)
1 ℤ(2<sup>64</sup> - 1)
1 𝔽(<emu-eqn>2<sup>15</sup> - 1</emu-eqn>)
1 …
```
> Editorial: Consistently represent expressions that include exponents

- spec.html
Changed the reference [String.prototype.normalize](https://tc39.es/ecma262/#sec-string.prototype.normalize) is using as per https://github.com/tc39/ecma262/issues/912
Please let me know if any further changes are needed, thanks!
> Editorial: String.prototype.normalize references the Unicode Standard instead of Annex 15

- spec.html
See https://github.com/tc39/proposal-is-usv-string.
> Normative: integrate well-formed Unicode strings proposal

- spec.html
Added an additional step to check if `size` is bigger than `2**53` as per https://github.com/tc39/ecma262/issues/1032
I could create a `test262` PR once the edit is approved.
Please let me know if any further changes are needed, thanks!
> Normative: Disallow ArrayBuffers bigger than 2**53

- .github/workflows/esmeta-typecheck.yml
- esmeta-ignore.json
I updated the version of [ESMeta](https://github.com/es-meta/esmeta) to [`v0.3.0`](https://github.com/es-meta/esmeta/releases/tag/v0.3.0).
Now, ESMeta supports that not only nonterminals but also any symbols can be optional (https://github.com/es-meta/esmeta/issues/144) by (https://github.com/es-meta/esmeta/commit/503b2fae9ceb0bbc58162a85d89cad831f29e97c).
And we fixed several minor issues. Thus, we can remove one unnecessary ignore case in the `esmeta-ignore.json`:
```diff
"GetThisValue",
-  "HostEnqueuePromiseJob",
"INTRINSICS.DefaultTimeZone",
```
> Meta: upgrade ESMeta to v0.3.0

- .github/workflows/esmeta-typecheck.yml
I updated the version of [ESMeta](https://github.com/es-meta/esmeta) to [`v0.3.1`](https://github.com/es-meta/esmeta/releases/tag/v0.3.1).
We fixed the bug in the grammar parser related to https://github.com/es-meta/esmeta/issues/145 and https://github.com/tc39/ecma262/pull/2418#discussion_r1173563802.
> Meta: Upgrade ESMeta to v0.3.1

- spec.html
Extends #3043 to simplify CreateArrayIterator by combining GeneratorYield steps and adding an alias to avoid repeating `𝔽(_index_)`.
> Editorial: Simplify CreateArrayIterator

- spec.html
https://github.com/tc39/ecma262/pull/3077 moved the definition of "Object type" out of header text, but kept the capitalization of "Type" in the non-header text, which is inconsistent with other sections.
> Editorial: fix capitalization of "Object type"

- esmeta-ignore.json
- spec.html
This PR simplifies and clarifies spec text related to time zone identifiers, but is not intended to change any observable behavior nor implementer requirements.
Goals of this PR include to make it easier to later integrate Temporal into ECMA-262, to simplify both Temporal and ECMA-402 spec text by centralizing common logic in ECMA-262, and to make it less disruptive to make future normative changes to time zone identifier behavior.
If this PR is merged into ECMA-262, editorial PRs will follow for Temporal (draft: https://github.com/tc39/proposal-temporal/pull/2573) and ECMA-402 (draft TBD) to leverage the updated spec text and AOs to simplify those specs.
Changes:
* Adds editorial spec text explaining how time zone identifiers work in ECMAScript, and pointing readers to 402 for …
> Editorial: simplify and clarify time zone identifier spec text

- spec.html
This preserves the existing "safe-integer" id, but fixes autolinking issues necessitating things like https://github.com/tc39/proposal-temporal/pull/2502 .
> Editorial: Replace biblio term "safe" with the more specific "safe integer"

- spec.html
It seems that while "Proxy object" and 'Proxy exotic object" refer to the same thing. Considering algorithm steps in [isArray](https://tc39.es/ecma262/#sec-isarray) and [getFunctionRealm](https://tc39.es/ecma262/#sec-getfunctionrealm), it seems more appropriate to use "Proxy exotic object" instead of "Proxy object" for [Proxy.revocable](https://tc39.es/ecma262/#sec-proxy.revocable)
It also gives a nice highlight and link to proxy exotic object definition.
> Editorial: Clarify Proxy.revocable

- spec.html
> Normative: Add Atomics.waitAsync

- spec.html
* `ToIntegerOrInfinity(*undefined*)` already returns 0, so no special case is necessary.
* ToLength is superfluous vs. just checking directly against the valid range.
> Editorial: Simplify ToIndex

- spec.html
I noticed that ToUint8Clamp inappropriately uses [ℝ](https://tc39.es/ecma262/multipage/notational-conventions.html#%E2%84%9D) with an input that might be infinite. This PR fixes that by replacing it with [the extended mathematical value of](https://tc39.es/ecma262/multipage/notational-conventions.html#extended-mathematical-value-of), and also performs some related cleanup of text and refactoring of algorithm steps.
> Editorial: Cleanup ToUint8Clamp

- spec.html
Extends #3043 to simplify `Date(…)` and `Date.UTC(…)` by combining common steps for handling years between 0 and 99 into a new MakeFullYear operation.
> Editorial: Simplify Date(…) and Date.UTC(…)

- spec.html
Fixes #3089.
From [5.2.5](https://tc39.es/ecma262/#sec-mathematical-operations):
> Numeric operators such as +, ×, =, and ≥ refer to those operations as determined by the type of the operands. [&hellip;] When applied to Numbers, the operators refer to the relevant operations within [IEEE 754-2019](https://tc39.es/ecma262/#sec-bibliography).
> Editorial: use standard arithmetic operators in MakeTime

- .github/workflows/esmeta-typecheck.yml
I updated the version of [ESMeta](https://github.com/es-meta/esmeta) to [v0.3.2](https://github.com/es-meta/esmeta/releases/tag/v0.3.2).
We fixed the bug in the grammar parser related to https://github.com/tc39/ecma262/pull/3098 (https://github.com/es-meta/esmeta/issues/147 and https://github.com/rbuckton/grammarkdown/issues/91).
> Meta: Upgrade ESMeta to v0.3.2

- esmeta-ignore.json
- spec.html
Changed argument types and removed `ToString` and `ToLength` calls from `StringPad` as per https://github.com/tc39/ecma262/issues/2634
For `maxLength`, I went with `a non-negative integer` instead of `a Number`.
I'm not sure if the new steps for `String.prototype.padStart` and `String.prototype.padEnd` are needed or not.
Please let me know if any further changes are needed, thanks!
> Editorial: take ToString and ToLength out of StringPad and make it infallible

- spec.html
Originally the [SystemTimeZoneIdentifier](https://tc39.es/ecma262/#sec-systemtimezoneidentifier) AO contained an assert that applied to named time zones but not offset time zones. Based on editors' feedback in #3035, this assertion was removed and replaced with different text, making the remaining If statement unnecessary. But I didn't notice this until after #3035 was merged.
This commit removes the now-unnecessary `If` statement.
> Editorial: Remove unnecessary `If` in SystemTimeZoneIdentifier

- spec.html
Fixes #2540, which see for all the details.
It's possible that the EvalDeclarationInstantiation insertion point should be one step later (after the "no abnormal terminations" Note), but I'm playing it safe (advancing it the minimum that ensures `_declaredVarNames_` is set).
> Editorial: Fix 2 old bugs re Block-Level Function Declarations

- spec.html
Followup to #2960.
"**BigInt value for**" is a term, but "**BigInt value that represents**" is not (and most uses of the latter can be replaced with "ℤ" anyway). Even the ℝ-coercions are technically unnecessary because of [Mathematical Operations](https://tc39.es/ecma262/multipage/notational-conventions.html#sec-mathematical-operations) ("_When applied to BigInts, [operators such as +, ×, =, and ≥] refer to the usual mathematical operations applied to the mathematical value of the BigInt_"), but I've kept them here to avoid making the BigInt operations trivial (e.g., [BigInt::unaryMinus](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-numeric-types-bigint-unaryMinus) would be `<emu-alg>1. Return -_x_.</emu-alg>`).
> Editorial: Use linkable terms for coercion to BigInt

- spec.html
This means that types match the constructors. This both reads more cleanly, and also supports https://github.com/ljharb/proposal-dataview-get-set-uint8c.
> Editorial: rename `~Uint8C~` type to `~Uint8Clamped~`

- spec.html
`HasCallInTailPosition` is currently implicitly defined on `ImportCall` via the chain rule: `HasCallInTailPosition` of `import( xxx )` is `HasCallInTailPosition` of `xxx`. This is wrong, because `xxx` is not in tail position.
This PR explicitly defines it to be false.
For what is worth, JSC matches this PR (we can't talk about "web reality" in this case, it's just a spec bug):
> Normative: Make `HasCallInTailPosition` for `ImportCall` always return false

- package-lock.json
- package.json
- spec.html
Should unblock https://github.com/tc39/ecma262/pull/3102 via inclusion of https://github.com/tc39/ecmarkup/pull/538.
Includes a commit cherry-picked from https://github.com/tc39/ecma262/pull/3102 (which should be included as a separate commit, marked editorial) so that it can pass CI.
> Meta: bump ecmarkup to 17.0.2

- spec.html
> Editorial: Quick fixes re PR #2418

- spec.html
In a tagged TemplateLiteral, NotEscapeSequence is allowed.
The TV of `TemplateCharacter :: \ NotEscapeSequence` is `*undefined*`.
This will then propagate up to TemplateString and TemplateStrings (when `_raw_` is `*false*`).
This PR fixes the return-type of TemplateString[s] accordingly.
> Editorial: Fix return-type of TemplateString[s]

- spec.html
In the section [Example Cyclic Module Record Graphs](https://tc39.es/ecma262/#sec-example-cyclic-module-record-graphs), the word "desiderable" is used.
>Loading closely interacts with the [host](https://tc39.es/ecma262/#host), and it may be **desiderable** for some of them to allow users to retry failed loads (for example, if the failure is caused by temporarily bad network conditions).
Apparently this is actually [an obsolete word](https://en.wiktionary.org/wiki/desiderable), but I've never heard it used in English. I think it's probably an artifact of using the term desideratum.
There's no other use of this word in the spec. There's 1 instance of "desirable", 2 of "undesirable", and 2 of "desired". This patch updates "desiderable" to "desirable" for consistency with the rest of the …
> Editorial: Correct desiderable to desirable

- spec.html
`ExportEntry.[[LocalName]]` calls itself the name used in the _importing_ module. I think this is meant to say exporting.
https://tc39.es/ecma262/multipage/ecmascript-language-scripts-and-modules.html#table-exportentry-records
>The name that is used to locally access the exported value from within the **importing** module. null if the exported value is not locally accessible from within the module.
Some export declarations relay imports (which would make this the importing module), but not all. It's always the exporting module for every export.
I think this probably snuck in by analogy with the `ImportEntry.[[LocalName]]` description.
https://tc39.es/ecma262/multipage/ecmascript-language-scripts-and-modules.html#table-importentry-record-fields
>The name that is used to locally access the …
> Editorial: Correct ExportEntry.[[LocalName]] description

- spec.html
After https://github.com/tc39/ecma262/pull/3029, there's no mention that `RegExp` is constructible any more. This PR aligns the text with the other similar methods.
Note that ideally it should put "when called as a function rather than as a constructor" at the end of the sentence, but that makes the structure too awkward, so I have to do it this way.
> Editorial: add mention that RegExp is constructible

- spec.html
Currently, 15 Date-related operations are defined via `<emu-eqn>` elements:
- Day
- TimeWithinDay
- DaysInYear
- DayFromYear
- TimeFromYear
- YearFromTime
- InLeapYear
- MonthFromTime
- DayWithinYear
- DateFromTime
- WeekDay
- HourFromTime
- MinFromTime
- SecFromTime
- msFromTime
This PR converts each into a 'proper' abstract operation (with a structured header and an `<emu-alg>`).
For the one-line equations, conversion to an `<emu-alg>` was straightforward: basically just insert a `Return`. But for the multi-line definitions (`DaysInYear`, `InLeapYear`, `MonthFromTime`, `DateFromTime`), the changes were more involved, so should probably get more review attention.
I reordered the definitions a little: they have a fairly strong define-before-use vibe, so I made that stronger. Specifically, …
> Editorial: Convert Date-related equations into proper AOs

- spec.html
I observed in passing that the overwhelming majority of `If _alias_ is *value*, … return …` steps that return either `_alias_` or `*value*` after determining that the two are equivalent opt for the latter (i.e., `return *value*`). It seems like a reasonable convention to be cognizant of even if not caught by linting, and this PR cleans up an outlier.
<details>
```sh
$ gawk '
BEGIN {
d = 0;
}
{
while (d > 0 &&
(index($0, state[d, "indent"]) != 1 || $1 != "1." || index($0, state[d, "indent"] "1.") == 1)) {
i = state[d, "start"];
j = state[d, "end"];
if (i <= j) print "--";
while (i <= j) printf "%d: %s\n", i, buf[i++];
d--;
}
}
match($0, /([[:space:]]*)1[.] If (_[^_]*_) is ([*][^*]*[*]),/, m) {
d++;
state[d, "start"] = NR;
state[d, "end"] = 0;
state[d, "indent"] = m[1];
state[d, "alias"] = …
```
> Editorial: Prefer returning static values after alias comparison

- spec.html
The [`GetExportedNames`](https://tc39.es/ecma262/multipage/ecmascript-language-scripts-and-modules.html#sec-getexportednames) method of Source Text Module Record claims it returns a List of either Strings or `null`. I find no way for it to ever include `null` in the result. Module Record apparently can be subclassed, and I'm unsure how to check all possible subclasses. I'm giving the argument here and hopefully someone familiar with modules can evaluate.
Called this Editorial because it changes no behavior, it just corrects the description of the actual behavior. But maybe it needs to be Normative because it does change a signature.
---
There's only a single use of `GetExportedNames` in the spec, which assumes a String-only result. …
> Editorial: Correct GetExportedNames return type

- scripts/check-form.js
- spec.html
This was a case I hadn't considered - #3097, specifically, where the commits in the PR aren't actually linked to the user's github.
> Meta: fail IPR check on commits with unknown authors

- spec.html
Resolves #3118.
Eliminates:
- `this time value` term
- `thisTimeValue` operation
- `this Date object` term
and introduces `ThisDateObject` operation.
This PR is structured as a series of small refactorings (with explanatory commit messages), in case that helps review. I intend to squash it somewhat before merging.
This should probably land before #3063, to avoid churn on `thisTimeValue`.
> Editorial: Eliminate some Date cruft

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- .github/workflows/enforce-format.yml
- .github/workflows/ipr.yml
- .github/workflows/preview-build.yml
- .github/workflows/preview.yml
- .github/workflows/publish-biblio.yml
This ensures the actions aren't running node 12, which will be removed soon.
> Meta: update github actions

- spec.html
Specifically:
- thisBooleanValue
- thisSymbolValue
- thisNumberValue
- thisBigIntValue
- ~thisTimeValue~
- thisStringValue
Since ES6, each of these operations has been defined in the corresponding "Properties of the Foo Prototype Object" section, rather than in a section dedicated to the operation, with a structured header, as is now the norm. 
Past efforts in this direction have encountered the problem of placement. E.g., in the status quo, `thisBooleanValue` is defined within [20.3.3 Properties of the Boolean Prototype Object](https://tc39.es/ecma262/#sec-properties-of-the-boolean-prototype-object), so if you were to simply create a subsection for `thisBooleanValue` right there, context would suggest that `thisBooleanValue` is a *property* of the Boolean Prototype Object.
This PR solves …
> Editorial: Define each `thisFooValue` AO in its own section

- spec.html
There are some algorithms where same variable is defined twice:
- [15.10.2 Static Semantics: HasCallInTailPosition](https://tc39.es/ecma262/#sec-static-semantics-hascallintailposition)
- [15.5.5 Runtime Semantics: Evaluation](https://tc39.es/ecma262/#sec-generator-function-definitions-runtime-semantics-evaluation)
Both algorithms define a (target) variable at the beginning, thus the declarations afterward are redeclaration which should be fixed. 
Please note that this is a continuation of PR #2365.
<details>
<summary>HasCallInTailPosition, CaseBlock</summary>
```html
1. Let _has_ be *false*.
2. If the first |CaseClauses| is present, let _has_ be HasCallInTailPosition of the first |CaseClauses| with argument _call_.
3. If _has_ is *true*, return *true*.
4. Let _has_ be …
```
> Editorial: Correct usage of 'Let'/'Set' in algorithms

- spec.html
... so that the [[Construct]] for ~exotic~ built-ins can be defined properly, instead of "the same as [[Call]] except that step 10 is different".
<strike>The second commit is a bonus, changing "a built-in function" to "an exotic built-in function" where appropriate. This is mostly of benefit in 10.3 Built-in Function Objects, where (in the status quo) the reader could be misled into thinking that these internal methods are for *all* built-in functions.</strike>
> Editorial: Factor out BuiltinCallOrConstruct

- spec.html
This makes the parameter more easily searchable while clarifying its meaning.
Issue: #2411
> Editorial: Clarify RegExp grammar parameter N → NamedCaptureGroups

- spec.html
This PR contains two suggested changes to the type signatures of two abstract operations, for different reasons elaborated in the each commit messages.
49fffca0dc0c0f45b45a03f6605fd72630e1c1eb is mainly for style consistency, as it's the only place where just "ECMAScript function" is used in type signatures. I also spotted other places in the spec where "ECMAScript function" is used instead of more prevalent "ECMAScript function object", if those need to be changed, I will change them also.
7d22df7d14340694e120aaa777f86b1336995f0d is for field access `_F_.[[PrivateEnvironment]]` in step 10 of PrepareForOrdinaryCall. The internal slot is guaranteed to exist for an ECMAScript function object but not for other built-in function ojects. Narrowing down the type parameter into ECMAScript …
> Editorial: use "ECMAScript function object" for parameter types

- spec.html
> Editorial: Rename "to link" to "to load" in the Source Text Module Records section

- spec.html
In PR #3063, I inadvertently un-defined 5 ids:
- thisbooleanvalue
- thissymbolvalue
- thisnumbervalue
- thisbigintvalue
- thisstringvalue
This PR reinstates them as oldids.
> Editorial: Reinstate 5 ids

- spec.html
This PR narrows "a function object" to "an ECMAScript function object" where appropriate.
(This is an expansion of https://github.com/tc39/ecma262/pull/3138#issuecomment-1662353988.)
I've split it into 2 commits to make it a bit easier to follow the propagation of narrowing, but they can probably be squashed for merging.
---
commit 1: Creating an ECMAScript function object
OrdinaryFunctionCreate returns an ECMAScript function object (EFO).
(1)
So, every operation that returns the result of OrdinaryFunctionCreate (i.e., every operation that creates a function for a FunctionBody or similar) also returns an EFO:
- InstantiateOrdinaryFunctionObject
- InstantiateOrdinaryFunctionExpression
- InstantiateArrowFunctionExpression
- DefineMethod
- InstantiateGeneratorFunctionObject
- …
> Editorial: "a function object" -> "an ECMAScript function object"

- spec.html
Among three call sites of IsCompatiblePropertyDescriptor, one in [[GetOwnProperty]] internal method of a Proxy exotic object(step 14 with respect to [es2023](https://tc39.es/ecma262/2023/#sec-proxy-object-internal-methods-and-internal-slots-getownproperty-p)) it is possible that argument `targetDesc` is *undefined*. For example, in the below javascript code,
```javascript
const monster1 = {
eyeCount: 4,
};
const handler1 = {
getOwnPropertyDescriptor(target, prop) {
return { enumerable: true, configurable: true, value: "I'm a descriptor!" }
},
};
const proxy1 = new Proxy(monster1, handler1);
proxy1.hasOwnProperty("noseCount"); // true
```
`targetDesc` is *undefined* as `monster1` does not have `noseCount` property.
> Editorial: widen parameter type of IsCompatiblePropertyDescriptor

- package-lock.json
- package.json
- spec.html
Adds [a new lint rule for redeclarations](https://github.com/tc39/ecmarkup/pull/541). ~~There are 7 such redeclarations right now, which will need to be fixed before landing; I'll add a commit fixing the remaining ones after https://github.com/tc39/ecma262/pull/3131 lands (which fixes most of them).~~
Also fixes the last two remaining redeclaration issues. Feel free to suggest better names for these aliases.
> Meta: bump ecmarkup to 17.1.1

- spec.html
The only call site of `GetModifySetValueInBuffer` does not pass a value for the `isLittleEndian` parameter.
> Editorial: remove unused isLittleEndian parameter of GetModifySetValueInBuffer

- spec.html
This PR adds missing `~empty~` guard in LabelledEvaluation for LabelledStatement.
Currently, [LabelledEvaluation for LabelledStatement](https://tc39.es/ecma262/#sec-runtime-semantics-labelledevaluation) is defined as follows:
```
1. Let label be the StringValue of LabelIdentifier.
2. Let newLabelSet be the list-concatenation of labelSet and « label ».
3. Let stmtResult be Completion(LabelledEvaluation of LabelledItem with argument newLabelSet).
4. If stmtResult.[[Type]] is break and SameValue(stmtResult.[[Target]], label) is true, then
a. Set stmtResult to NormalCompletion(stmtResult.[[Value]]).
5. Return ? stmtResult.
```
According to the definition, `SameValue`, used in step 4, requires two arguments which are both `ECMAScript langauge value`. In step 3, `stmtResult.[[Target]]` can be …
> Editorial: use proper comparison operation in LabelledEvaluation of LabelledStatement

- package-lock.json
- package.json
This introduces a new, hopefully more legible font.
Also drops some old unused scripts from `package.json`, since they'd be broken by this update and it's not worth fixing them given that they're unused.
> Meta: bump ecmarkup to v18.0.0

- spec.html
$nn patterns fall back to $n when there aren't at least nn captures
Fixes gh-1426
test262 PR: https://github.com/tc39/test262/pull/3931
> Normative: Update GetSubstitution to match reality

- spec.html
It was weird that there was what appeared to be a `<dfn>` for "built-in constructor" in a note of the "built-in object" section when both "built-in function" and "built-in method" had their own sections.
Alternatively, for anything with its own actual `<dfn>`, I would prefer we don't have a T&D section. But we can follow up with that later.
> Editorial: move built-in constructor into its own Terms & Definitions section

- spec.html
Don't use an `<emu-xref>` element when ecmarkup will auto-link the text.
> Markup: Eliminate unnecessary <emu-xref> elements

- spec.html
I think this is the last bit of "making RegExps consistent with rest of ecma262" (from the 'Upcoming Editorial Work' slide).
Note: CaptureRange and Match Record have the same structure, though slightly different uses. I wonder if we should either merge them or rename them (in a way that acknowledges their similarity and their difference).
> Editorial: Model CaptureRange and MatchState as Records

- spec.html
Fixes #3199.
Marking this as editorial because the current spec text always fails and is obviously a bug.
> Normative bug fix: Fix RevalidateAtomicAccess to check against byte length

- spec.html
I'm sure there are more of these, these are the ones I noticed today.
> Editorial: remove some unnecessary calls to SameValue

- spec.html
Implementing the good suggestion from https://github.com/tc39/ecma262/pull/3200#pullrequestreview-1686330852
> Editorial: Rename indexedPosition to byteIndexInBuffer

- spec.html
Among the 16 call sites of IsAnonymousFunctionDefinition, one of them in NamedEvaluation of ParenthesizedExpression : `(` Expression `)` passes |Expression| Parse Node
https://github.com/tc39/ecma262/blob/0802e7da54fc870af4e6c37b048428611c449f61/spec.html#L9060
which was not covered in the previous type annotation. This commit fixes this issue.
I checked and confirmed that downstream dependies are not effected.
> Editorial: widen parameter type of IsAnonymousFunctionDefinition

- spec.html
This is the only `<img>` element without an alt text in the entire specification, so add an alt text.
> Markup: add alt text to Ecma logo

- spec.html
This fixes https://github.com/tc39/ecma262/issues/3108
`Number::lessThan` incorrectly asserts that both numbers must be non-zero before being compared for inequality.
Due to this assertion, expressions such as `0 < 1` or `-5 < 0` would fail.
I've removed the mention of `non-zero` from the assertion.
I hope this edit helps! 😄
> Editorial: fix invalid assertion in Number::lessThan

- spec.html
This is more precise specification with EvaluatePropertyAccessWithExpressionKey' usage and also in line with parameter specification of EvaluatePropertyAccessWithIdentifierKey.
> Editorial: Make parameter of EvaluatePropertyAccessWithExpressionKey more precise

- spec.html
The first commit is an exact copy of https://github.com/tc39/ecma262/pull/3127.
The second commit adds more assertions with respect to Abstract Operations in module section, this was done primarily to make clear non-null values are passed into `ResolveExport` and `GetImportedModule`
> Editorial: Narrow return type of GetExportedNames and more assertions

- package-lock.json
- package.json
Unblocks https://github.com/tc39/ecma262/pull/3163 by inclusion of https://github.com/tc39/ecmarkup/pull/558.
Unblocks https://github.com/tc39/ecma262/pull/3175 by inclusion of https://github.com/tc39/ecmarkup/pull/559. #3175 will need to be updated to add the `skip global checks` attribute to `DetachArrayBuffer` so that ecmarkup knows not to try to apply whole-program analysis to it.
> Meta: bump ecmarkup to 18.1.0

- spec.html
See https://tc39.es/proposal-array-grouping/
> Normative: add `Object.groupBy` and `Map.groupBy`

- spec.html
> Editorial: Add missing period to `AsyncFunction.prototype.constructor` section

- spec.html
This includes an alternative fix to #3243 as discussed in editor call. Closes #3243.
> Editorial: avoid using % notation with an alias

- spec.html
Closes #3248.
The current algorithm has a bug that can result in OOB reads in the source TA, because _count_ is not correctly recomputed when the source TA is resized during evaluation of the species constructor.
(It is currently bounded by _len_, which is recomputed, but this is incorrect because the bounds of the copy loop is not on the length, but instead on how many bytes need to be copied.)
> Normative: Recompute count in TA.p.slice

- spec.html
The phrase "is an object" links to [The Object Type](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-object-type), but if someone is clicking that link they probably want to know the answer to the question "are functions objects in this sense".  The answer is yes, but to discern that from the current section you need to go down to between two tables in the [Object Internal Methods and Internal Slots](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-object-internal-methods-and-internal-slots) subsection and find the "Table 5 summarizes additional essential internal methods that are supported by objects that may be called as functions. A function object is an object that supports the [[Call]] internal method" bit.
This PR adds a …
> Editorial: document that functions are objects

- spec.html
Broadly, this PR follows the following conventions for TA methods that
take start and end parameters,
- The aliases for parameters are start and end
- The relative values for the parameters, after coercion, are called
relativeStart and relativeEnd
- The absolute index values are called startIndex and endIndex
Also explicitly parenthesize multiplication in element size
computations.
> Editorial: Improve readability of TypedArray methods

- spec.html
Alternative to #3183, as discussed in editor call. Fixes #3180. Closes #3183.
> Editorial: fix formatting of note step in DayFromYear

- spec.html
> Editorial: use _Pk_ for unity of content and form

- spec.html
"IteratorStepValue" isn't a _great_ name, but I'm worried that sticking with IteratorStep will lead to a bunch of confusing documentation/comments, so I didn't want to reuse it.
In the cases which deal with completion records explicitly you might have to think for a second to convince yourself the change doesn't actually affect behavior.
The only 2 remaining uses of IteratorStep are in the elisions in `[a, /* hole */, b] = iterable`. Ordinarily I'd inline it into those and delete the AO, but I want to update 402 and proposals to use the new AO before doing that.
There are still 8 uses of IteratorValue: 7 in `yield*`, 1 in the AsyncFromSyncIterator wrapper. `yield*` could probably use a cleanup too, but not in this PR.
> Editorial: Introduce AO combining IteratorStep and IteratorValue

- spec.html
This fixes a bug where we can reach the declaration of `value` not-exactly-once. That is in editorial issue. Fixed using the pattern we already use in many other places, often with the alias `v`.
Done on top of #3268 as to not conflict. Marking as draft until that is merged.
> Editorial: avoid multiple declarations of an alias

- spec.html
Fix https://github.com/tc39/ecma262/issues/2897.
I have no idea if this meets the conventions, but I hope the idea is at least correct. Below is the output of `Math.atan2` in Node:
> Editorial: fix algorithm of Math.atan2

- package-lock.json
- package.json
- spec.html
Waiting on the release of https://github.com/tc39/ecmarkup/pull/571. Draft until then.
> Editorial: pull in ecmarkup reduced-width document styles

- spec.html
This is based on Mike Samuel's work in #1498, but ultimately goes in a different direction. Due to #2670, this change can be made simpler than it previously was.
This change provides the source text to be evaluated, and the grammar symbol that should be used to parse it, to the host hook HostEnsureCanCompileStrings.
One example of where this is needed is for allowing a Content Security Policy to provide hashes for code executed via `eval()` or `new Function()`:
https://github.com/w3c/webappsec-csp/issues/623
This is useful on its own, but has come up again in the topic of ShadowRealm-HTML integration. In a ShadowRealm you can either execute code asynchronously, with ShadowRealm.p.importValue, or synchronously, with ShadowRealm.p.evaluate. Because the latter uses `eval()` inside the …
> Normative: Provide source text to HostEnsureCanCompileStrings

- spec.html
This PR updates the spec to match web reality (tested in Safari, Firefox, and Chrome -- XS does not implement HTML comments).
Annex B allows HTML closing comments (`--> foo`) after a line terminator, potentially preceded by other comments or spaces ([`SingleLineHTMLCloseComment`](https://tc39.es/ecma262/#prod-annexB-SingleLineHTMLCloseComment)). However, browsers also support them at the beginning of scripts. Some test cases:
- ```js
eval("--> foo\nconsole.log(123)");
```
- ```html
<script>--> foo
console.log(123);
</script>
```
- ```html
<script src="./script.js"></script>
```
```js
--> foo
console.log(123);
```
- ```js
eval("/* comment */ --> foo\nconsole.log(123)");
```
- (this case is already supported by the current spec)
```js
eval("/* com\nment */ --> foo\nconsole.log(123)");
``` …
> Normative: Allow Annex B scripts to start with `-->`

- spec.html
Fixes #3253.
Calling this editorial because it's not currently coherent with text in the surrounding section. It's debatably normative though.
The constraints are sometimes worded in a slightly confusing way. The intended constraints on GetOwnProperty are:
- No constraints on how `configurable: true` properties can change
- `configurable: false` + `writable: true` properties can change value and can become non-writable, but no other changes are allowed
- `configurable: false` + (`writable: false` or accessor) properties cannot change in any way
- properties cannot be created on non-extensible objects
These are clearly the intended constraints, especially if you read the NOTE:
> As a consequence of the third invariant, if a property is described as a [data …
> Editorial: fix an invariant for [[GetOwnProperty]]

- spec.html
This changes a `?` to a `!` in [EvaluateClassStaticBlockBody](https://tc39.es/ecma262/multipage/ecmascript-language-functions-and-classes.html#sec-runtime-semantics-evaluateclassstaticblockbody).
[FunctionDeclarationInstantiation](https://tc39.es/ecma262/multipage/ordinary-and-exotic-objects-behaviours.html#sec-functiondeclarationinstantiation) only throws if there is a parameter expression (computed member in destructuring, or default value) which throws. In this case the "function object" being evaluated is a synthetic value created by [ClassStaticBlockDefinitionEvaluation](https://tc39.es/ecma262/multipage/ecmascript-language-functions-and-classes.html#sec-runtime-semantics-classstaticblockdefinitionevaluation) which is used to explain how static blocks work (threaded through from …
> Editorial: EvaluateClassStaticBlockBody cannot throw during function instantiation

- spec.html
When an SDO definition is associated with a production that has `X?` on the RHS, the algorithm sometimes says:
`if |X| is [not] present`
and sometimes says:
`if |X?| is [not] present`
In the status quo, there are 78 occurrences of the former, vs only 7 of the latter, so change the latter to the former. (Most of them are in `ClassDefinitionEvaluation`.)
(Also, eliminate '?' from `the PrivateBoundIdentifiers of |ClassBody?|`.)
> Editorial: Remove `?` from `|X?| is [not] present`

- spec.html
See https://tc39.es/proposal-arraybuffer-transfer/
> Normative: add ArrayBuffer.prototype.{detached,transfer,transferToFixedLength}

- spec.html
`DefinePropertyOrThrow` invocation in [10.2.8 DefineMethodProperty](https://tc39.es/ecma262/#sec-definemethodproperty) can throw an abrupt completion. Consider following JavaScript code:
```js
class A {
static * ['prototype'] () {}
}
```
- `prototype` property of `A` is defined in step 16 of [15.7.14 Runtime Semantics: ClassDefinitionEvaluation](https://tc39.es/ecma262/#sec-runtime-semantics-classdefinitionevaluation) with property descriptor `{[[Configurable]]: false, ... }`
- It tries to define static generator method `prototype` of `A` in [10.2.8 DefineMethodProperty](https://tc39.es/ecma262/#sec-definemethodproperty) with property descriptor `{[[Configurable]]: true, ...}`.
- Since `ValidateAndApplyPropertyDescriptor` return `false`, it throws a`TypeError` exception.
> Editorial: Fix wrong assertion in 'DefineMethodProperty'

- spec.html
In [IsLessThan](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-islessthan), first both values are coerced to primitives, and then those are later possibly coerced to numerics. The second part can throw (if given a Symbol), but cannot invoke user code, as you can tell from the note immediately before these steps.
> Markup: coercing primitives to numerics is not user code in IsLessThan

- spec.html
Of the normative changes:
```
git log --oneline --grep=Normative $(git merge-base main es2023)..main
```
```
44bb0e0d Normative: add ArrayBuffer.prototype.{detached,transfer,transferToFixedLength} (#3175)
197f1245 Normative: Allow Annex B scripts to start with `-->` (#3244)
b07ca066 Normative: Provide source text to HostEnsureCanCompileStrings (#3222)
22de3740 Normative: Recompute count in TA.p.slice (#3255)
11cbf729 Normative: add `Promise.withResolvers` (#3179)
3a9c9dcb Normative: add `Object.groupBy` and `Map.groupBy` (#3176)
5eaee2f3 Normative: Update GetSubstitution to match reality (#3157)
a9ae96ed Normative: Add resizable ArrayBuffer and growable SharedArrayBuffer (#3116)
53454a9a Normative: Make HasCallInTailPosition for ImportCall always return false (#3106)
26b23696 Normative: …
```
> Editorial: Describe changes in ES2024

- spec.html
This should be landed after #2814.
This AO was only used in one place, and it's just a specialized form of one of the two branches in DefineMethodProperty (it was already only ever setting a function, on a configurable property on a normal object, with a hardcoded enumerable false), so this seemed like a good change.
> Editorial: replace the only instance of CreateMethodProperty with DefineMethodProperty

- spec.html
> Markup: fix SAB toStringTag section ID

- LICENSE.md
old link is dead.  also eliminated the scare quotes
> Meta: fix ecma text copyright link

- spec.html
Found while implementing these, details in commit messages.
> Editorial: Fix a couple of inconsistencies

- img/figure-2.svg
- spec.html
This supersedes https://github.com/tc39/ecma262/pull/3234
This is effectively same as https://github.com/tc39/ecma262/pull/3234, but in order to avoid the readability issue, added dedicate well-known intrinsics for Generator prototype and Async generator prototype, that's used in the same way as %SetIteratorPrototype%.
* All occurrences of "Generator Prototype" and "Generator.prototype" are replaced with %GeneratorPrototype%
* All occurrences of "AsyncGenerator Prototype" and "AsyncGenerator.prototype" are replaced with %AsyncGeneratorPrototype%
* Related ids are updated, with moving the old ids into `oldids` attribute
* Also tweaked the description of Generator and AsyncGenerator to avoid the confusion from "instance of"+"generator function"
> Editorial: Add %GeneratorPrototype% and %AsyncGeneratorPrototype% well-known intrinsics (#3230)

- spec.html
Unicode v15.1.0 makes both U+200C and U+200D `ID_Continue` characters, meaning we no longer need to explicitly special-case them for them to match `IdentifierPart`.
Fixes #3073
> Editorial: Remove special-casing of U+200C and U+200D

- spec.html
... in line with PR #2877 and PR #3202.
The first commit changes:
`_X_ and _Y_ are [not] the same {Realm,Module} Record`
to just:
`_X_ is [not] _Y_`
The second commit changes:
`SameValue(_X_, _Y_) is {*true*,*false*}`
to
`_X_ is [not] _Y_`
when the two values are both Strings, or else one is a String and the other is a String or `*null*`.
> Editorial: More changes for comparisons

- spec.html
> Editorial: Use "well-known symbol" term consistently (#3231)

- spec.html
Normally, an early error rule consists of:
- an `<emu-grammar>` (with 1 or more productions), and
- a `<ul>` (with 1 or more "it is a Syntax Error" or "must cover" statements).
However, in a few cases, there is also a `<p>` that says when the rule is applied.
One such case is in [13.2.5.1](https://tc39.es/ecma262/#sec-object-initializer-static-semantics-early-errors), which PR #3227 will eliminate. This PR eliminates the remaining cases. These occur in [13.15.1](https://tc39.es/ecma262/#sec-assignment-operators-static-semantics-early-errors), [13.15.5.1](https://tc39.es/ecma262/#sec-destructuring-assignment-static-semantics-early-errors), and [14.7.5.1](https://tc39.es/ecma262/#sec-for-in-and-for-of-statements-static-semantics-early-errors), and are all of the form:
```
<emu-grammar>
(1 …
```
> Editorial: Eliminate 6 `<p>` elements that say when to apply early error rules

- spec.html
The official name has been binary64 since IEEE 754-2008. We already use that name in a few places. This uses that name in 2 additional places where I felt such rigour was important.
> Editorial: refer to binary64 values by their official name in more places

- spec.html
https://github.com/tc39/ecma262/pull/3222 (cc @ptomato) accidentally changed the `new Function` implementation to stringify the body _before_ the parameters, rather than after. This change was introduced in [this force-push to that PR](https://github.com/tc39/ecma262/compare/639273d8c16879dbe6f8d3a6770dcc7fc2b7f393..af086c85de3fa2a8a68f6232d5ce1443fb729c96), as part of the response to https://github.com/tc39/ecma262/pull/3222#discussion_r1445101746, but it was unnecessary (and unrelated) for Kevin's request.
Being accidental, this change was never discussed in plenary ([slides](https://docs.google.com/presentation/d/1MRItYS_b1hwKstlqlfoD8mgbecS2OkTSiPFVWHs3Y_8), [notes 1](https://github.com/tc39/notes/blob/main/meetings/2023-11/november-27.md#provide-source-text-to-hostensurecancompilestri …
> Normative: Restore params/body ToString order in `new Function`

- spec.html
As the textual description of the example suggests, _D_ is visited before _C_ and thus its `[[DFSIndex]]` is lower.
You can test the indexes for various graphs at https://nicolo-ribaudo.github.io/es-module-evaluation/#s=IEEKQiBDCiBEIEUK&c=QSAtPiBCCkEgLT4gQwpCIC0%2BIEQKQyAtPiBECkQgLT4gQQpDIC0%2BIEUK&a=RSBEIEMgQiBB&f=
> Editorial: Fix `[[DFSIndex]]` in cyclic module record async evaluation example

- spec.html
This is already established via the parameter type annotation.
> Editorial: Remove redundant type assertion from AsyncBlockStart

- spec.html
This is single-use within ECMA-262, but can be leveraged more heavily in ECMA-402.
> Editorial: Introduce StringLastIndexOf

- spec.html
`ParseText(StringToCodePoints(_str_), |Nonterminal|)`, often introducing a new alias just for the output of StringToCodePoints, is a common pattern necessitated by ParseText expecting its first argument to be a sequence of code points in operations that have a String. I think it makes sense to simplify those call sites by allowing ParseText to directly accept the String and perform conversion itself.
> Editorial: Generalize ParseText to support String input

- spec.html
I've broken it out into ~6~ 5 commits in case that helps review.
----
commit 1:
Rename the existing SDO "IsStrict" to "ScriptIsStrict", because it's specific to Scripts, and I want the general name for the general operation.
----
commit 2:
The algorithms in the spec have 7 occurrences of:
```
X is contained in strict mode code
```
and 22 occurrences of:
```
X is strict mode code
```
This commit changes all of the former to the latter.
It isn't obvious whether or not this is a trivial change.
At first, I thought it was non-trivial, with the following reasoning: Clearly, you can have islands of strict mode code (SMC) within a sea of non-SMC. So, for such an island, it seems like it *is* SMC, but it's not *contained in* SMC, it's contained in non-SMC. (And so, this commit's change might …
> Editorial: Introduce IsStrict() abstract operation

- spec.html
As noted in https://github.com/tc39/ecma262/issues/1794#issuecomment-558868977 the language about an `implementation-defined "message"` property in the _NativeError_ section is an outdated holdover from ES3, since the definition was changed to be the empty string in ES5. The outdated language was subsequently duplicated to the Error section in #2040.
Since the message prototype property is defined to be the empty string for all Error types, I thought it would be least confusing to remove it from the "differing only in ..." list entirely.
I am also inclined to update `only in the name used as the constructor name instead of _NativeError_` to `only in the constructor name` in the Error Objects copy, since that clause isn't specific to _NativeError_.  I can roll that into this PR or open a …
> Editorial: Remove "message" property from list of Error differences

- spec.html
Fixes #3298.
Ecma402 PR: https://github.com/tc39/ecma402/pull/875
No uses in Temporal that I saw, and offhand I don't think it would be used in any other proposals.
> Editorial: make String{,Last}IndexOf return not-found

- spec.html
There are a few places where Lists of Strings are sorted with the awkward phrasing "ordered as if an Array of the same values had been sorted using %Array.prototype.sort% using *undefined* as _comparefn_." Encapsulate this sorting into a new AO, SortStringListByCodeUnit. I find this clearer about the intention (the current language leaves it implicit that the sorting is by code unit), and more concise.
This phrasing is used in several places in ECMA-402 as well, so this change will bring additional benefit there.
> Editorial: Introduce definition for sorting according to lexicographic code unit order

- spec.html
Per @michaelficarra's suggestion [here](https://github.com/tc39/ecma262/pull/3307#discussion_r1575464392), let's just replace the AO `IsPropertyKey` with the phrasing "is a property key", given that "property key" is a well-defined term.
> Editorial: Do away with IsPropertyKey AO.

- spec.html
E.g., change:
> 1. Return the BoundNames of |Foo|.
to:
> 1. Return BoundNames of |Foo|.
----
This PR is divided into 4 commits, depending on:
- whether the occurrence is in pseudocode or prose, and
- whether it's at the start or middle of a sentence ("The" vs "the").
since those are factors that might conceivably affect how you feel about the removal.
For the origin of this PR, see the discussion at https://github.com/tc39/ecma262/pull/3210#discussion_r1491684924 and following (re `the second "the"`).
----
Personally, I've got mixed feelings about this PR: I like the consistification, but I think the status quo is slightly easier to read. One possibility would be to include "The" in the name of some SDOs, e.g.
> 1. Return TheBoundNames of |Foo|.
Another possibility would be use a more …
> Editorial: Insert "the" before SDO-names

- spec.html
The iterator protocol has a bunch of helper AOs. But almost everything just uses `IteratorStepValue` (introduced in https://github.com/tc39/ecma262/pull/3268) and `IteratorClose`; the exceptions are
- `IteratorStep` still gets used when you need to iterate but don't care about the value - specifically, it gets used for `[foo, , bar] = baz` [destructurings with elisions](https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#sec-runtime-semantics-iteratordestructuringassignmentevaluation), and in some of the iterator helper proposals (e.g. [`.drop`](https://tc39.es/proposal-iterator-helpers/#sec-iteratorprototype.drop)), which will need updating.
- `IteratorNext` gets used in [`%AsyncFromSyncIteratorPrototype%.next`](https://tc39.es/ecma262/multipage/control-abstraction-obje …
> More tweaks for the iterator handling AOs

- spec.html
Fixes https://github.com/tc39/ecma262/issues/3326.
As mentioned in that issue, the editors suspect this was a refactoring issue, since it does not appear to ever actually have been possible for this to be `*undefined*`, and in any case is not assigned later. The only caller of ParseScript known to us is [in HTML](https://html.spec.whatwg.org/multipage/webappapis.html#creating-scripts), which passes the realm of an environment settings object, which (I believe) cannot be `*undefined*`, so this restriction on types matches what the consumer actually passed.
> Layering: the [[Realm]] of a Script Record cannot be *undefined*

- spec.html
In [9.6 InitializeHostDefinedRealm](https://tc39.es/ecma262/#sec-initializehostdefinedrealm), there are two `If`-steps that allow the host to customize the global object and global `*this*` binding. If the host just wants the default (of either), that's handled by passing `*undefined*` to (the relevant parameter of) `SetRealmGlobalObject`, which takes care of setting the realm's `[[GlobalObject]]` and `[[GlobalEnv]]` appropriately.
This division of labor always struck me as a bit odd. E.g., why set `_global_` to `*undefined*` and then have prose to explain the significance of doing so? Why not just set `_global_` appropriately right there? That was the impetus for this PR. (My guess was that `SetRealmGlobalObject` was used by the HTML spec, but it isn't, and as far as I can tell it never …
> Editorial: InitializeHostDefinedRealm-related refactorings

- spec.html
This PR reworks the relations that define the memory model to read closer to existing memory model literature.
- Relations (e.g. happens-before) are no longer kept in slots in candidate executions, and instead look like "_a_ happens-before _b_ in _execution_". Currently relations are defined as basically Lists of pairs, and keeping them in internal slots like [[HappensBefore]] gives the misconception that these relations are algorithmically maintained. In reality the Relations are "manifested" as needed over the sets of events. **What's kept in slots are the things that are in fact algorithmically maintained**, like [[EventsList]].
- Rename relation names to start with a verb so the inline "_a_ _R_ _b_" form reads naturally.
- Remove `aoid`s from the relations, since they aren't AOs.
- …
> Editorial: Rework memory model relations

- spec.html
This doesn't remove all occurrences, but the other occurrences are either in prose/asserts or we talked about them and they are justified because they form a nice pattern of spec steps. Typically, we avoid using this structure.
Additionally, this particular test is done in 6 places, 4 of which are already using our preferred phrasing.
> Editorial: remove some "are both" usages

- spec.html
> Normative: Allow [[ReferencedName]] in Reference Records to be a not-yet-resolved property key

- spec.html
Per https://github.com/tc39/ecma262/pull/3306#discussion_r1605815512.
> Editorial: introduce CanonicalizeKeyedCollectionKey

- spec.html
See [proposal](https://github.com/tc39/proposal-set-methods).
> Normative: add set methods

- spec.html
Ref #3337
Renames the _keyCoercion_ enumeration value corresponding with use of CanonicalizeKeyedCollectionKey from `~zero~` to `~collection~`, better describing its intent rather than its raw mechanics.
> Editorial: Better align GroupBy keyCoercion with CanonicalizeKeyedCollectionKey

- spec.html
> Markup: Add theads to all tables

- spec.html
We've had a `<dfn>` for "integral Number" since PR #2007, and the status quo uses it about 80 times. So it's odd that we still have the AO `IsIntegralNumber` (which dates back to ES6 where it had the name `IsInteger`).
This PR replaces the few uses of `IsIntegralNumber` with `is an integral Number`.
It also inserts the word "finite" into the definition of "integral Number", as noted by bakkot.
(Compare to PR #3316 replacing `IsPropertyKey` with `is a property key`.)
> Editorial: Replace `IsIntegralNumber` AO with `is an integral Number`

- spec.html
Fixes https://github.com/tc39/ecma262/issues/2412 by trapping the exception and using it to reject the promise returned by the call to `AsyncGenerator.prototype.return`.
You can make a promise which throws when you try to `await` or `Promise.resolve` it:
```js
let brokenPromise = Promise.resolve(42);
Object.defineProperty(brokenPromise, 'constructor', {
get: function () {
throw new Error('broken promise');
}
});
```
(see [PromiseResolve](https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-promise-resolve) step 1.a.)
If you `await` such a value, or pass it to `Promise.resolve`, it will synchronously throw an exception.
Generators have a `.next()` method which asks for the next value. Async generators have the same thing, except it returns a promise. Because the generator …
> Normative: handle broken promises in AsyncGenerator.prototype.return

- scripts/insert_snapshot_warning.js
- scripts/snapshot_warning.html
To avoid being too annoying it checks the referrer and collapses the warning when navigating within the same snapshot.
> Markup: also insert snapshot warning in multipage

- img/figure-2.svg
- package-lock.json
- package.json
- spec.html
- this avoids a conceptual conflict with decorators, when they land
Open to bikesheds; other alternatives I considered:
- explicitly using intrinsics, ie, `%SymbolSpecies%`, and hardcoding that table, while removing the "well-known symbols table". This felt like it would lose some clarity around intrinsics vs well-known-symbols.
- Using `%Symbol%species%` - this would require upstream support in ecmarkup, so i opted not to do it for now.
- something else?
> Editorial: Convert @@ notation to intrinsics notation for well-known Symbols

- scripts/check-form.js
local git‘s short SHA was shorter than github‘s short SHA, breaking the API call
> Meta: check IPR form script: use a long SHA

- spec.html
This aligns well with our editorial convention of avoiding "the value of".
> Editorial: remove some unnecessary "the result of" phrasing

- spec.html
> Editorial: create and assign [[PrivateElements]] slot in MakeBasicObject

- spec.html
> Markup: unlink Invoke in the Jobs section

- spec.html
Following ISO-8601, #2781 introduced U+2212 (Unicode minus) as an alias for the regular ASCII minus sign for use in time zone offsets.
There's two new data that lead me to believe that this was a mistake, and that we should revert this change.
The first is that the newly-released RFC 9557 (the string format standard that Temporal uses) disallows non-ASCII characters. Its predecessor RFC 3339 also disallows non-ASCII characters. So strings that follow the current (since 2022) ECMAScript spec could be rejected by RFC 9557 clients.
The second new data is feedback from implementers of a Rust version of Temporal that this single obscure character in the grammar will incur a performance cost because they must now use Rust strings instead of plain U8 ASCII data. See …
> Normative: Revert U+2212 (Unicode minus sign) as a valid character in timezone offsets

- spec.html
This provides improved readability while maintaining the same information.
I will also be making these changes to the ever-so-slightly different 2024 branch, but i will likely not open a pr on that branch as that work’s mostly for me.
> Editorial: Pivots the tables within clause 16.2.1.5.4

- spec.html
This PR completes a small bugfix from 9 years ago.
Fixes #2663.
----
History:
2015-07-17:
@bakkot identifies a problem in Annex B's
"Changes to FunctionDeclarationInstantiation":
https://esdiscuss.org/topic/block-level-function-declarations-web-legacy-compatibility-bug
To remedy this, @allenwb submits bug 4427:
https://tc39.es/archives/bugzilla/4427/
in which he recommends changing
> For each FunctionDeclaration _f_ **in _varDeclarations_** that is directly contained in the |StatementList| of a |Block|, |CaseClause|, or |DefaultClause|,
to
> For each FunctionDeclaration _f_ that is directly contained in the |StatementList| of a |Block|, |CaseClause|, or |DefaultClause| **Contained within _code_**,
(emphasis mine).
2015-10-29:
@anba submits PR #141, claiming to fix bug 4427.
It deletes "in …
> Editorial: Fix old bug in Annex B's changes to FunctionDeclarationInstantiation

- .github/workflows/spellcheck.yml
- .gitignore
- scripts/spellcheck.mjs
- spec.html
Integrates `aspell` to check the spelling in `spec.html`. Currently just a `package.json` script, but if we want this enforced during CI, we should be able to do that, too. Updates a bunch of spellings for a variety of reasons. Commits should be reviewed individually.
> Meta: integrate aspell for spelling checks

- spec.html
These were missed before landing https://github.com/tc39/ecma262/pull/3335.
> Editorial: rename IDs that were embedded in emu-grammar elements back

- spec.html
This matches the behaviour that web engines today already display with the WebAssembly `f64.sqrt` instruction.
/cc @sunfishcode
> Normative: fully define Math.sqrt

- spec.html
Closes #3356.
Modules that depend on modules with top-level await but do not themselves have a top-level await may currently hang. When a module with TLA finishes evaluating, it triggers evaluation of ancestors modules that depend on it.
Currently, ancestors that do not have TLA themselves are evaluated and have their [[Status]] set to ~evaluated~ but incorrectly leaves their [[AsyncEvaluation]] field unchanged as true. This means subsequent importers of those ancestors consider them as in the middle of async evaluation and will wait on them in InnerModuleEvaluation. But since they are already evaluated, those waits cause a hang.
This PR sets [[AsyncEvaluation]] to false for those ancestors when their [[Status]] transition to ~evaluated~.
Note that the ancestors that error out during …
> Normative: Fix hangs with top-level await

- spec.html
In the [GeneratorStart](https://tc39.es/ecma262/#sec-generatorstart) AO, the first step is the following assertion:
```
GeneratorStart (
_generator_: a Generator,
_generatorBody_: a |FunctionBody| Parse Node or an Abstract Closure with no parameters,
): ~unused~
...
1. Assert: The value of _generator_.[[GeneratorState]] is *undefined*.
```
However, in the [EvaluateGeneratorBody](https://tc39.es/ecma262/#sec-runtime-semantics-evaluategeneratorbody) SDO for [GeneratorBody](https://tc39.es/ecma262/#prod-GeneratorBody), there is no initialization of the `[[GeneratorState]]` internal slot for the variable `_G_` before passing it into the [GeneratorStart](https://tc39.es/ecma262/#sec-generatorstart) AO:
```
Runtime Semantics: EvaluateGeneratorBody (
_functionObject_: an ECMAScript function …
```
> Editorial: Initialize [[GeneratorState]] and [[AsyncGeneratorState]]

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- .github/workflows/enforce-format.yml
- .github/workflows/ipr.yml
- .github/workflows/preview-build.yml
- .github/workflows/preview.yml
- .github/workflows/publish-biblio.yml
- .github/workflows/spellcheck.yml
This is just a waste of time in automation; it's crazy that it's the default behavior for `npm ci`.
~~edit: apparently the bit I changed is just the name of the step, not the actual command being run, oops~~ (fixed, thanks jordan)
> Meta: do not npm audit in CI

- spec.html
This PR replaces the broken URL link  `http://ampl.com/REFS/abstracts.html#rounding` to the latest `https://ampl.com/_archive/first-website/REFS/rounding.pdf` in Note 3 of in Note 3 of https://tc39.es/ecma262/#sec-numeric-types-number-tostring
Fixes #3389
> Markup: Update broken link in `Number::toString`

- spec.html
> Editorial: Clamp size before using with "substring of"

- spec.html
I noticed a bug in ECMAScript specification language types. As far as I know, the word `Reference` used to be the name of the specification type in the past. According to the specification, the word `Record` has now been added to these types. I added this word, and the link to the [Reference Record](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-ecmascript-specification-types) also became available.
> Editorial: replace non-existent type 'Reference' with type 'Reference Record' and its link

- spec.html
The argument _C_ of the abstract operation [PromiseResolve](https://tc39.es/ecma262/#sec-promise-resolve) has type of Constructor in current spec. However, as following example, it allows an object as _C_ and throws an error 42 in 1.a. I think the type of _C_ should be an Object, not a constructor.
```js
var C = {}
var x = new Promise(function () {});
Object.defineProperty(x, 'constructor', { get: () => { throw 42; }});
Promise.resolve.call(C, x);
```
> Editorial: Using Object instead of constructor in PromiseResolve

- spec.html
I carefully assume that the return type of [`ExpectedArgumentCount`](https://tc39.es/ecma262/multipage/ecmascript-language-functions-and-classes.html#sec-static-semantics-expectedargumentcount) can be narrowed into `non-negative integer`, which is `integer` in current specification. 
The reason why I suggest this PR is that the return type of the ExpectedArgumentCount is integer makes type mismatching in [`OrdinaryFunctionCreate`](https://tc39.es/ecma262/multipage/ordinary-and-exotic-objects-behaviours.html#sec-ordinaryfunctioncreate) and [`SetFunctionLength`](https://tc39.es/ecma262/multipage/ordinary-and-exotic-objects-behaviours.html#sec-setfunctionlength).
> Editorial: Narrow `integer` into `non-negative integer` in return type of ExpectedArgumentCount

- spec.html
According to the current specification, type of the `newTarget` in [`CreateDynamicFunction`](https://tc39.es/ecma262/multipage/fundamental-objects.html#sec-createdynamicfunction) needs to be a `constructor`. However, there is the case that `newTarget` is **undefined** as follows:
```javascript
Function();
```
When this code executes, [`Function`](https://tc39.es/ecma262/multipage/fundamental-objects.html#sec-function-p1-p2-pn-body) calls `CreateDynamicFunction` in third step as follows:
```html
<emu-alg>
1. Let _C_ be the active function object.
1. If _bodyArg_ is not present, set _bodyArg_ to the empty String.
1. Return ? CreateDynamicFunction(_C_, NewTarget, ~normal~, _parameterArgs_, _bodyArg_).
</emu-alg>
```
In this situation, **undefined** is assigned to `NewTarget` . Therefore, …
> Editorial: Widen parameter type of CreateDynamicFunction

- spec.html
Per editor call discussion.
Related: #3339.
> Editorial: add `SameType` AO

- spec.html
Per editor call discussion.
Related: #3339.
> Editorial: `CreateListFromArrayLike`: change element type list to a 2-state enum

- spec.html
- Capital 'B' on "Boolean"
- When an operation has an optional parameter X, the op doesn't do anything with X until either:
- it has established that a value was passed to X, or
- it has established that a value wasn't passed to X, and has set X to some value.
> Editorial: Quick fixes for CreateListFromArrayLike

- spec.html
> Editorial: remove Type() macro

- package-lock.json
- package.json
- spec.html
There were 13 of these, so it seemed enough to justify an AO like we have for `NormalCompletion` (31) and `ThrowCompletion` (15).
> Editorial: add a ReturnCompletion AO, mirroring NormalCompletion/ThrowCompletion

- esmeta-ignore.json
- spec.html
> Editorial: OrdinaryCreateFromConstructor has wrong parameter type

- spec.html
Closes https://github.com/tc39/ecma262/issues/3421
> Editorial: String.prototype.matchAll iterators won't return null

- .github/workflows/esmeta-typecheck.yml
- esmeta-ignore.json
We updated the version of [ESMeta](https://github.com/es-meta/esmeta) to [v0.4.3](https://github.com/es-meta/esmeta/releases/tag/v0.4.3) to resolve the issue https://github.com/es-meta/esmeta/issues/258 by this commit https://github.com/es-meta/esmeta/commit/de9ef686ed48fc429d9f2b425284625921066a4e.
With this support, the ESMeta type checker can support the `Constructor` type as a subtype of the `FunctionObject` type, and we can remove the `OrdinaryCreateFromConstructor` in the `esmeta-ignore.json` file.
However, because of the precise constructor type, we need to add the `TypedArrayCreateFromConstructor` algorithm in the `esmeta-ignore.json` file. It happens the current ESMeta type checker does not support type refinement for algorithm invocation. For example, we need to refine the type …
> Meta: Upgrade ESMeta to v0.4.3

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- .github/workflows/enforce-format.yml
- .github/workflows/esmeta-typecheck.yml
- .github/workflows/ipr.yml
- .github/workflows/preview-build.yml
- .github/workflows/preview.yml
- .github/workflows/publish-biblio.yml
- .github/workflows/require-allow-edits.yml
- .github/workflows/spellcheck.yml
- spec.html
See https://github.com/tc39/proposal-promise-try/issues/15
> Normative: add `Promise.try` (#3327)

- spec.html
The return type of [CreateBuiltinFunction](https://tc39.es/ecma262/#sec-createbuiltinfunction) is a function object. However, as indicated by its name, the return type should more specifically be identified as a built-in function object.
This distinction clarifies an operation in [ClassDefinitionEvaluation](https://tc39.es/ecma262/#sec-runtime-semantics-classdefinitionevaluation), where [MakeConstructor](https://tc39.es/ecma262/#sec-makeconstructor) requires either an ECMAScript function object or a built-in function object.
> 14.b. Let F be [CreateBuiltinFunction](https://github.com/tc39/ecma262/compare/main...kimjg1119:create-builtin-object?expand=1#sec-createbuiltinfunction)(defaultConstructor, 0, className, « [[ConstructorKind]], [[SourceText]] », the current Realm Record, …
> Editorial: Narrow return type of CreateBuiltinFunction

- spec.html
https://github.com/tc39/proposal-iterator-helpers
> Normative: add Iterator Helpers

- scripts/check-form.js
- spec.html
If an implementation can produce distinguishable NaN values, then writing NaN values to a frozen (non-configurable and non-writable) property can be detectable.
This is a regression from #2468.
> Editorial: Don't allow writing NaN to frozen properties

- spec.html
`[[HomeObject]]` is always set to an ordinary object (or `undefined`). Assert this in `MakeMethod` and `GetSuperBase`. `GetSuperBase` and `MakeSuperPropertyReference` are now both also infallible.
> Editorial: [[HomeObject]] is always an ordinary object

- spec.html
In #3383, we chose to use ~suspended-start~ instead of undefined for initializing a GeneratorState, but the changes do not include [CreatorIteratorFromClosure](https://tc39.es/ecma262/#sec-createiteratorfromclosure).
> Editorial: use suspended-start instead of `undefined` in GeneratorState initialization

- esmeta-ignore.json
- spec.html
In current ECMA262 specification, the abstract operation [`ToLength`](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-tolength) returns a integer or throw completion.   
However, I think that type of the return value of [`ToLength`](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-tolength) can be narrowed to a *non-negative* integer or throw completion.
> Editorial: Using non-negative integral Number instead of integral Number in ToLength

- spec.html
`%GeneratorFunction.prototype.prototype%` is just `%GeneratorPrototype%`
> Editorial: eliminate extra verbosity with %GeneratorPrototype% references

- spec.html
This allows you to have a regex like
```js
/(?<year>[0-9]{4})-[0-9]{2}|[0-9]{2}-(?<year>[0-9]{4})/
```
where a capturing group name is re-used across alternatives. It continues to be illegal to re-use a name within the same alternative.
~~As currently specified, it also enforces that named backreferences correspond to capturing groups in the same alternative, which would make the following (currently legal) program illegal:~~
```js
/(?<a>x)|\k<a>/
```
~~There is no reason to write this because the `\k` can never refer to anything, meaning it will always match the empty string. For this reason I think it should have been illegal in the first place. But if we want to preserve that behavior, it's easy enough to specify.~~
EDIT: updated so that the above remains legal, per plenary.
(I have a …
> Normative: allow duplicate named capture groups

- spec.html
There is no use of Abstract Closures as async function bodies in ecma262 itself. This PR is a prereq to allow the JSPI specification to pass in an AC.
> Editorial: Allow ACs in Async{Function,Block}Start

- spec.html
Closes https://github.com/tc39/ecma262/issues/3392
When I opened that issue I was wrongly assuming that array literals longer than 2**32-1 would throw an error when evaluated. This is only true if the array contains holes in one of those too big indexes, which are not valid JSON syntax. What happens in the non-hole case is that the integer-indexed property gets defined without updating the array length, so it does not throw an error.
@michaelficarra and I went through the possible cases and we are confident this indeed never throws, so having ! instead of Completion(...) can help when reading the spec. If there were cases where it can throw, the current usage of Completion(...) is probably wrong anyway because you would want to re-throw the error (`?`), instead of using it as …
> Editorial: Assert that Evaluation in JSON.parse does not throw

- spec.html
> Normative: Return false in [[PreventExtensions]] for variable length TypedArrays

- esmeta-ignore.json
- spec.html
In [RelationalExpression](https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#sec-relational-operators-runtime-semantics-evaluation), evaluation of RelationalExpression : PrivateIdentifier in ShiftExpression makes an alarm in ESMeta since it is not trivial to know that running execution context's PrivateEnvironment never becomes null. 
It can be resolved in the same way with step 2 of [MakePrivateReference](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-makeprivatereference); add an assertion to annotate it. 
ESMeta alarm: 
```
[ParamTypeMismatch] Call[9993] argument assignment to first parameter _privateEnv_ when Call[9993] function call from RelationalExpression[7,0].Evaluation (step 6, 7:33-92) to ResolvePrivateIdentifier
- expected: …
```
> Editorial: Add an assertion for PrivateEnvironment cannot be null

- spec.html
The [[GlobalObject]] of the Realm record is an Object or undefined. However, it seems that in GetGlobalObject, the slot cannot be undefined. To make this clear(and resolve some ESMeta alarms), I suggest adding an assertion.
> Editorial: GlobalObject cannot be undefined in the GetGlobalObject 

- esmeta-ignore.json
- spec.html
In [Construct](https://tc39.es/ecma262/multipage/ordinary-and-exotic-objects-behaviours.html#sec-built-in-function-objects-construct-argumentslist-newtarget) method for built-in function object, it seems that the result must be an object. However, current ESMeta is unable to check this since [BuiltinCallOrConstruct](https://tc39.es/ecma262/multipage/ordinary-and-exotic-objects-behaviours.html#sec-builtincallorconstruct) handles Call and Construct together.
It will be helpful to add an assertion to resolve a false alarm. 
ESMeta alarm: 
```
[ReturnTypeMismatch] Block[6404] return statement in Record[BuiltinFunctionObject].Construct (step 1, 2:12-96)
- expected: Normal[Record[Object]] | Throw
- actual  : Normal[ESValue] | Throw
```
> Editorial: Add an Assertion for Built-in Function Object

- esmeta-ignore.json
- spec.html
This is completely the same PR as #3483, but an async version.
> Editorial: use suspended-start instead of undefined in AsyncGeneratorState 

- esmeta-ignore.json
- spec.html
In [GetFunctionRealm](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-getfunctionrealm), step 3.c. call `GetFunctionRealm` recursively with `proxyTarget` which assumes that `proxyTarget` is a function object. 
If my investigation is correct, proxy exotic objects are generated in [ProxyCreate](https://tc39.es/ecma262/multipage/ordinary-and-exotic-objects-behaviours.html#sec-proxycreate) and it is callable only if the `target` is callable. Thus if a function object has a target, then it is also a function object thus it isn't a spec bug. However I think add an assertion here will be helpful.
> Editorial: ProxyTarget is always a function object in GetFunctionRealm

- spec.html
As pointed out [here](https://github.com/tc39/ecma262/pull/3395#discussion_r1807857989).
This pattern of closing an iterator _not_ because of an error or other abrupt completion hasn't come up much yet, but compare e.g. step 5.c.ii.1.a of [Set.prototype.isDisjointFrom](https://tc39.es/ecma262/multipage/keyed-collections.html#sec-set.prototype.isdisjointfrom).
> Editorial: fix IteratorClose call in %IteratorHelperPrototype%.return

- spec.html
Fixes #3473.
Readers should still think of these algorithms as using SameValueZero, so we went with saying "the semantics of SameValueZero" to make it technically correct while still referencing SameValueZero.
> Editorial: clarify that Map/Set do not literally use SameValueZero

- spec.html
The `[[PromiseResult]]` of a Promise is only initialized when the Promise actually settles. Generally we prefer to initialize everything explicitly. See #3482 (which also covers `[[GeneratorContext]]`).
There's various places which use this field without asserting that it's not `~empty~`, which might confuse esmeta, but those places _do_ assert that the state is not `~pending~`, so an additional assert seemed like overkill. I could add those asserts anyway if we want though.
> Editorial: more explicit handling of [[PromiseResult]]

- spec.html
This adds the specification text for the Stage 3 [RegExp Modifiers](https://github.com/tc39/proposal-regexp-modifiers) proposal.
Test262 tests can be found at https://github.com/tc39/test262/pull/3960.
> Normative: Add RegExp Modifiers

- esmeta-ignore.json
- spec.html
In runtime semantics [SuperCall: super Arguments](https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#sec-super-keyword), there is an assertion which narrows a `newTarget`'s type to Object. However, we know that this is always a constructor in this step, and fixing it to a constructor will resolve a mismatch between calling [Construct](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-construct) at step 6.
> Editorial: Narrowing an assertion in SuperCall: super Arguments

- esmeta-ignore.json
- spec.html
In step 6.a.iv.3 of [ResolveExport](https://tc39.es/ecma262/multipage/ecmascript-language-scripts-and-modules.html#sec-resolveexport), the case where `e.[[ImportName]]` is `ALL`, indicating that the module does not provide a direct binding, is addressed. I’m uncertain but curious whether we should also handle [other cases](https://tc39.es/ecma262/multipage/ecmascript-language-scripts-and-modules.html#table-exportentry-records) such as ALL-BUT-DEFAULT and null in this context.
c.f. This is problematic because the recursive call in step 6.a.iv.4 requires exportName to be a string. Therefore, the remaining cases should be explicitly handled in some way.
> Editorial: Add [[ImportName]] assertion for non-direct binding cases in ResolveExports

- esmeta-ignore.json
- spec.html
In step 9.e of [MakeMatchIndicesIndexPairArray](https://tc39.es/ecma262/multipage/text-processing.html#sec-makematchindicesindexpairarray):
> e. If i > 0 and groupNames[i - 1] is not undefined, then …
`groupNames[i - 1]` is refined to a non-undefined value. However, the current implementation of ESMeta does not support field-level refinement. To remove unsatisfactory alarms, it would helpful to first assign the value to a temporary variable before we support the feature.
c.f. Alternatively, this could be achieved by adding an identical assertion below step 9.e.ii. I'm not sure this is a better way though.
> Editorial: Allocate-and-use in MakeMatchIndicesIndexPairArray for refinement

- esmeta-ignore.json
- spec.html
* When zero bounds a Number range, always use <code>&lt; -0<sub>𝔽</sub></code> or <code>&gt; +0<sub>𝔽</sub></code> (_there was one exception_).
* Consolidate static bounds checking in [IsValidIntegerIndex](https://tc39.es/ecma262/multipage/ordinary-and-exotic-objects-behaviours.html#sec-isvalidintegerindex) and [StringGetOwnProperty](https://tc39.es/ecma262/multipage/ordinary-and-exotic-objects-behaviours.html#sec-stringgetownproperty) (_index Numbers with negative sign bit are in the same "not applicable" category as non-integers_).
* Clean up [StringGetOwnProperty](https://tc39.es/ecma262/multipage/ordinary-and-exotic-objects-behaviours.html#sec-stringgetownproperty) to remove a redundant check and swap comparison operands for a more conventional ordering.
> Editorial: Update range comparisons involving a zero

- esmeta-ignore.json
- spec.html
According to [runtime semantics of `_YieldExpression_ : yield * _AssignmentExpression_` evaluation](https://tc39.es/ecma262/#_ref_7471), `_generatorKind_` is NON-GENERATOR, SYNC, or ASYNC. However, the type of second parameter of [`GetIterator`](https://tc39.es/ecma262/#sec-getiterator) is SYNC or ASYNC in current specification. This is type-mismatch. I think [`GetGeneratorKind`](https://tc39.es/ecma262/#sec-getgeneratorkind) cannot return NON-GENERATOR in this case, so this PR includes adding assertion that `generatorKind` is not NON-GENERATOR.
> Editorial: Add assertion that generatorKind is not non-generator

- spec.html
- always refer to "the GlobalSymbolRegistry List" instead of sometimes just saying "GlobalSymbolRegistry"
- when creating a GlobalSymbolRegistry Record, do so explicitly
- dfn "GlobalSymbolRegistry List"
> Editorial: consistency around how we refer to GlobalSymbolRegistry stuff

- .github/workflows/preview-build.yml
- .github/workflows/preview.yml
See https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> Meta: update upload-artifact action prior to deprecation

- spec.html
AOs are generally nicer for readers (and tooling).
I've left these where they were and just changed their type, but since each section is preceded by a sentence like
> The behaviour of the additional concrete specification methods for Function Environment Records is defined by the following algorithms:
we should probably also either reword that sentence or move these somewhere else.
Commits can be reviewed individually but should land as a single commit.
> Editorial: make single-implementation concrete methods into abstract operations

- spec.html
It looks like PR #3459 missed these changes to capitalization and use of `<em>`.
----
Things I noticed but didn't change:
- "Iterator instance objects": Not sure about that "I".
- "an [Oo]bject that conforms to the IteratorResult interface": Change to "an IteratorResult object" (of which there are already many occurrences)?
The latter reminds me that the spec should perhaps have a sentence saying that an object that conforms to interface Foo can be called "a Foo object".
> Editorial: Consistify capitalization re iterator wording

- spec.html
ToString(𝔽(_k_)) was sometimes stored in let Pk and sometimes not. While this does not affect behavior, for consistency in the specification, I have standardized it to be stored in a variable.
Fixes #3530
> Editorial: Store ToString(𝔽(k)) in a variable for consistency

- esmeta-ignore.json
- spec.html
This proposal (https://tc39.es/proposal-import-attributes/, https://github.com/tc39/proposal-import-attributes) reached stage 3 during the March 2023 meeting, conditional on [stage 3 reviews](https://github.com/tc39/proposal-import-attributes/issues/137). I'm opening this PR before "real" stage 3 to help editors reviewing the full spec changes.
The proposal has already been integrated in HTML: https://html.spec.whatwg.org/#hostloadimportedmodule
**PREVIEW**: https://ci.tc39.es/preview/tc39/ecma262/pull/3057
**DIFF**: https://arai-a.github.io/ecma262-compare/?pr=3057 (note: the diff doesn't mark _deprecated_ sections)
> Normative: Add Import Attributes

- spec.html
This pull request builds on top of https://github.com/tc39/ecma262/pull/3057.
I mostly ported the spec text as-is, taking care of integrating editorial changes from the PRs open in the repo, but I have a few comments / questions for the editors.
> Normative: Add JSON modules

- spec.html
This updates [Async-from-Sync Iterator Objects](https://tc39.es/ecma262/#sec-async-from-sync-iterator-objects) so that the async wrapper closes its sync iterator when the sync iterator yields a rejected promise as value. This also updates the async wrapper to close the sync iterator when `throw` is called on the wrapper but is missing on the sync iterator, and updates the rejection value in that case to a TypeError to reflect the contract violation. This aligns the async wrapper behavior to the `yield*` semantics.
[Slides](https://docs.google.com/presentation/d/1W9EJoWOvi6jU1A2bwyixzOceoP_ASAeaOYER3Zy9P00/edit) presented at TC39 plenary in January 2020.
A rejected promise as value is transformed by the async wrapper into a rejection, which is considered by consumers of async iterators as …
> Normative: Close sync iterator when async wrapper yields rejection

- spec.html
I noticed this due to a recent test262 test from @shvaikalesh: https://github.com/tc39/test262/pull/3914
The explainer has been pulled into a proposal repo: https://github.com/tc39-transfer/proposal-redeclarable-global-eval-vars
This PR still serves as the spec draft.
> Normative: Remove [[VarNames]] from the global

- spec.html
See https://github.com/tc39/proposal-regex-escaping/issues/58
> Normative: add `RegExp.escape`

- spec.html
The general rule when working with iterators / iterables is that once you get an iterator it is your responsibility to close it when you're done with it, unless it errors out or completes. We're consistent about this when we get the iterator from an iterable, and in some of the places where we get the iterator directly (e.g. in [`Set.prototype.isDisjointFrom`](https://tc39.es/ecma262/multipage/keyed-collections.html#sec-set.prototype.isdisjointfrom) step 5.c.ii.1.a), but as [pointed out](https://github.com/tc39/proposal-iterator-sequencing/issues/16#issuecomment-2448601515) by @zloirock, iterator helpers don't close their receiver when one of their argument is invalid. Since iterator helpers are conceptually "take ownership" of their receiver (either by consuming it fully, or by closing …
> Normative: iterator helpers close receiver on argument validation failure

- spec.html
This adds the spec text from [proposal-float16array](https://github.com/tc39/proposal-float16array). I intend to ask for stage 4 at the upcoming meeting.
> Normative: add Float16Array and Math.f16round

- spec.html
[Object Internal Methods and Internal Slots](https://tc39.es/ecma262/multipage/ecmascript-data-types-and-values.html#sec-object-internal-methods-and-internal-slots) defines the initial value of an internal slot to be **undefined**, but without a reference to that in [MakeBasicObject](https://tc39.es/ecma262/multipage/abstract-operations.html#sec-makebasicobject), it can be difficult to track branding/externally-oriented slots such as [Error](https://tc39.es/ecma262/multipage/fundamental-objects.html#sec-error-message) [[ErrorData]], [AllocateArrayBuffer](https://tc39.es/ecma262/multipage/structured-data.html#sec-allocatearraybuffer) [[ArrayBufferDetachKey]], and [ECMA-402](https://tc39.es/ecma402/) [[Initialized$TypeName]] slots.
This PR adds a note to make that behavior more obvious.
> Editorial: Document initial internal slot values at their point of creation

- spec.html
> Editorial: Change remaining `_c_` to `_cp_` in EncodeForRegExpEscape

- spec.html
The execution order of modules that were waiting on a given async module was based on the order in which their [[AsyncEvaluation]] field was set to *true*.
This PR replaces the [[AsyncEvaluation]] boolean with an actual number that keeps track of ordering in each agent. It also adds a note on when it's safe to reset this order to 0, since:
- implementations might want to prevent this number from overflowing, and V8 currently has a bug that resets the number to 0 too early
- figuring out when it's safe to reset the number might not be trivial, given the complexity of the module algorithms.
You can verify the numbers in the updated tables for the example using https://nicolo-ribaudo.github.io/es-module-evaluation/.
Fixes https://github.com/tc39/ecma262/issues/3289
> Editorial: Explicitly track async evaluation order of pending modules

- spec.html
* unify phrasing in RawBytesToNumeric and NumericToRawBytes
* prefer "NaN" over "the NaN Number value"
* rename `v` alias in DataView.prototype methods to `view`
> Editorial: unify NaN phrasing, editorial followups to #3532

- spec.html
Ref https://github.com/tc39/ecma262/issues/3538 / https://github.com/tc39/ecma262/pull/3391#discussion_r1813687569. I'm also going to use this AO in ECMA-426.
> Editorial: Extract JSON parsing into its own AO

- spec.html
All the other signatures omit these spaces, which I think also looks better.
> Markup: consistent spacing for method signatures in tables

- spec.html
Ref https://github.com/tc39/ecma262/issues/3538 / https://github.com/tc39/ecma262/pull/3391#discussion_r1954783861. This is especially useful for Source Text Module Record, since it "inherits" some abstract methods from two different "super classes".
Review with whitespace changes disabled: https://github.com/tc39/ecma262/pull/3541/files?w=1
> Editorial: Put module concrete methods in their own emu-clauses

- spec.html
The overlapping background gradient is fun in Chrome, but it ends up a blurry mess against vector table borders in the PDF. Also the CSS spec apparently doesn’t actually define behavior for non-static positioning within table cells? So implementations vary. Prince’s isn’t great. (idk, i read this somewhere, i didn’t dig in to the spec because it doesn’t really matter)
Anyway here’s a base64-encoded SVG. It’s only on Table 48, as that’s how I found it.
IMO you should put this in ecmarkup, it could be useful for other publications. But you do you boo.
> Markup: Print styles for slashed corner cell

- package-lock.json
- package.json
Adds dark mode, thanks @arai-a!
~We need to update the SVGs to render correctly in dark mode before landing (which I think we can do with some CSS in the SVGs).~ Actually they're already fine.
~Also should land some other ecmarkup PRs first I guess.~ Done.
> Meta: bump ecmarkup to v21.2.0

- spec.html
`Is{Accessor,Data,Generic}Descriptor` are never called with `undefined`.
---
[StructuredSerializeInternal](https://html.spec.whatwg.org/#structuredserializeinternal) seems to be the only caller where `undefined` is ever used as an input.
> Editorial: Remove unnecessary `undefined` type from property descriptor tests

- spec.html
As discussed in editor call. Fixes #3555 using the first suggested approach. Closes #3556.
> Editorial: address circular definition of Iterator.prototype

- spec.html
This amends some editorial inconsistencies introduced by PR #3559.
(You should probably use "Hide whitespace" if you're looking at the first commit, or at all commits together.)
> Editorial: Quick fixes re recent merge

- .github/workflows/esmeta-typecheck.yml
We updated the version of [ESMeta](https://github.com/es-meta/esmeta) to [v0.6.0](https://github.com/es-meta/esmeta/releases/tag/v0.6.0).
We fixed minor bugs in the `Math` type domain (https://github.com/es-meta/esmeta/pull/272) and the stringified form for return type mismatches (https://github.com/es-meta/esmeta/pull/273).
In addition, we support the following two new features:
- [ECMA Visualizer](https://chromewebstore.google.com/detail/ecma-visualizer/nlfpedidieegejndiikebcgclhggaocd), a specification visualizer with example programs or conformance tests as a Chrome extension
- [ECMAScript Double Debugger](https://es-meta.github.io/playground/), an ECMAScript interpreter with states of both ECMAScript programs and the specification
If you're interested in how to use it, take a look at …
> Meta: Upgrade ESMeta to v0.6.0

- spec.html
> Editorial: Explain the nature of TypedArray property handling

- spec.html
When we "unwrap" the promise returned by `_module_.Evaluate()`, we need to mark is as handled so that the host knows that the rejection is not unhandled. Note that this is not currently observable withing ECMA-262: it's only observable if a host provides a custom Module Record "subclass" other than Cyclic Module Record whose `Evaluate()` can return a rejected promise.
I extracted this "synchronously evaluate and unwrap the promise" into its own AO, which is currently also used in https://tc39.es/proposal-defer-import-eval/.
Fixes https://github.com/tc39/ecma262/issues/3533.
> Normative: Mark sync module evaluation promise as handled

- spec.html
This PR removes the optional _waitable_ parameter in the ValidateAtomicAccessOnIntegerTypedArray AO. Only Atomics.notify passes true explicitly as an argument, and this inlines the steps in that caller.
See #3475.
> Editorial: Remove optional waitable parameter

- CONTRIBUTING.md
The document as it stands is more equivocal than it should be about using this repo for feature requests. This makes it more explicit.
> Meta: clarify CONTRIBUTING.md

- package-lock.json
- package.json
Fixes https://github.com/tc39/ecma262/issues/3479 via inclusion of https://github.com/tc39/ecmarkup/pull/626 (hopefully).
> Meta: bump ecmarkup to v21.3.0

- spec.html
This is the same as #3597 but for AsyncBlockStart.
> Editorial: mark asyncBody() as a completion record in AsyncBlockStart

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
This came from a discussion during Web Engines Hackfest that we sometimes forget about WASM integration with our proposals and we should add the WebAssembly spec to our list of downstream dependencies.
> Meta: Add WebAssembly to our list of downstream dependencies

- spec.html
https://github.com/tc39/proposal-is-error/issues/7
> Normative: add `Error.isError`

- spec.html
This commit updates the list of TypedArray internal slots in `#sec-typedarray-exotic-objects` and `#sec-properties-of-typedarray-instances` to match the list of slots added by `TypedArrayCreate`.
> Editorial: List all TypedArray internal slots

- spec.html
All other callsites are annotated properly, we just missed this one. Tooling doesn't handle concrete methods very well currently which is why it's not caught automatically.
> Editorial: mark a callsite of GetBindingValue as not throwing

- esmeta-ignore.json
- spec.html
This is because the only way to get a return completion in expression position is with a `yield`, and `yield` is [statically forbidden](https://tc39.es/ecma262/multipage/ecmascript-language-functions-and-classes.html#sec-generator-function-definitions-static-semantics-early-errors) in generator formal parameters.
I suspect esmeta will complain about this, because [FunctionDeclarationInstantiation](https://tc39.es/ecma262/multipage/ordinary-and-exotic-objects-behaviours.html#sec-functiondeclarationinstantiation) calls [IteratorBindingInitialization](https://tc39.es/ecma262/multipage/syntax-directed-operations.html#sec-runtime-semantics-iteratorbindinginitialization) to do the initialization, and that AO is also used for `let [foo] = bar` declarations, which _can_ contain `yield` …
> Editorial: FunctionDeclarationInstantiation cannot return ReturnCompletion

- .github/workflows/esmeta-typecheck.yml
We updated the version of [ESMeta](https://github.com/es-meta/esmeta) to [v0.6.1](https://github.com/es-meta/esmeta/releases/tag/v0.6.1).
In this update, we added support for the shorthand `IfAbruptCloseAsyncIterator`, which is introduced in the **Array.fromAsync** proposal ([proposal-array-from-async](https://github.com/tc39/proposal-array-from-async), [ecma262/pull/3581](https://github.com/tc39/ecma262/pull/3581)). The proposal is currently at Stage 3 and may be approved for Stage 4 at the upcoming TC39 plenary. This shorthand is expected to be used in other proposals such as [proposal-async-iterator-helpers](https://github.com/tc39/proposal-async-iterator-helpers), as per [esmeta/284#comment](https://github.com/es-meta/esmeta/issues/284#issue-3091434500).
While not yet part of the …
> Meta: Upgrade ESMeta to v0.6.1

- spec.html
Split from #3629 as requested at https://github.com/tc39/ecma262/pull/3629#issuecomment-3010643518 , starting with AO reordering because internal movement is a big cause of avoidable merge conflicts.
> Editorial: Reorder some TypedArray AOs to support top-down readability and future refactoring

- spec.html
Replaces #2193.
This PR specifies the web reality that the following are not early errors in sloppy mode on browser-hosted engines:
```js
f() = 1;
f() *= 1;
f()++;
for (f() in [1]) {}
for (f() of [1]) {}
```
It aligns with the new Annex B editorial convention (#2952) and amounts to:
- augmenting AssignmentTargetType with a new value `~web-compat~`
- throwing a ReferenceError immediately after performing the function call in each case
> Normative: Add "Runtime Errors for Function Call Assignment Targets" to Annex B

- spec.html
Turns out there were 23. As discussed in editor call. Layered on top of https://github.com/tc39/ecma262/pull/3599.
> Editorial: wrap AC return values in completion records where needed

- spec.html
This matches how all other `constructor` properties are defined and implementations also implement the property as writable.
> Normative: WeakRef.prototype.constructor should be writable

- spec.html
This is the only place where `[[Call]]` is referred to as an "internal slot". Change it to "internal method" for consistency.
> Editorial: Refer to [[Call]] as an internal method

- spec.html
Include "object" to match dfn of other built-in prototype objects.
> Editorial: Include "object" in dfn for WeakRef and FinalizationRegistry prototype object

- spec.html
There are 17 occurrences of `is either *undefined* or *null*` and only 1 occurrence of `is either *null* or *undefined*`.
> Editorial: consistently order undefined before null in comparisons

- .github/workflows/esmeta-typecheck.yml
I directly updated [v0.6.4](https://github.com/es-meta/esmeta/releases/tag/v0.6.4) instead of [v0.6.3](https://github.com/es-meta/esmeta/releases/tag/v0.6.3).
It resolves the [CI failure](https://github.com/tc39/ecma262/actions/runs/16358715380/job/46222498674) that appears in https://github.com/tc39/ecma262/pull/3653 by fixing bugs related to handling the `function object` and `constructor` types by revising the intersection and normalization of record types (https://github.com/es-meta/esmeta/pull/300).
It supports more detailed reporting with the number of occurrences of each unique phrase (https://github.com/es-meta/esmeta/issues/287).
It adds type modeling for each separate case of `TypedArray` (e.g. `Uint8Array`) to resolve the type check error in …
> Meta: Upgrade ESMeta to v0.6.4

- spec.html
Partially fixes #3648.
The following occurrences
- `If cond, s1. Otherwise s2`
- `If cond, s1. Otherwise, s2`
- `If cond, s1; otherwise, s2`
have been replaced with `If cond, s1; otherwise s2`.
> Editorial: unify various forms of if-otherwise in single-line conditionals

- spec.html
As previously discussed with @michaelficarra, I replaced the occurrences of `ref's property value` with the conventional `ref.property`.
A more detailed report is available [here](https://github.com/tontonialberto/ecma262-spec-inconsistencies?tab=readme-ov-file#object-field-references).
> Editorial: allow Symbols and Private Names to have internals slots and use slot notation as appropriate

- spec.html
Pending [stage 4](https://github.com/tc39/proposal-math-sum/issues/19).
> Normative: add Math.sumPrecise

- package-lock.json
- package.json
Introduced in https://github.com/tc39/ecma262/pull/3296 but rendered unused in https://github.com/tc39/ecma262/pull/3352.
These pull in 246 transitive dependencies totaling almost 120 MB, which is probably a big part of why CI is so slow lately.
> Meta: remove unused pagedjs dependencies

- spec.html
Removes the pluralization of "functions" in "Anonymous functions objects"
> Editorial: remove unnecessary pluralization

- spec.html
Test case: `class Foo { static { this.toString() } }`
This will require the `[[SourceText]]` of `Foo` to be set.
> Normative: Set [[SourceText]] on classes before static blocks evaluate

- spec.html
This PR
- Cleans up and improves comments on ECMA-262-specific print styles
- Restores the (mandatory? i thought?) version line to metadata
- Transforms 5 identical cells into one cell with rowspan 5 in table "Module fields after the initial Evaluate() call"
- we made this change last year as well, I must have failed to push those changes back to main
- Clarifies in the colophon that ecmarkup is used for Ecma specifications, not _just_ ECMAScript specifications
> Markup: rendering edits for 2025 edition & beyond

- spec.html
A personal favourite of mine: the order of checking/comparing `iterationKind` and `iteratorKind` is different between two otherwise nearly identical blocks handling abrupt completions (exceptions) in the loop header binding, and handling non-loop-continuing results of the body evaluation.
The difference makes the two blocks really hard to compare, even though they're 100% the same except for the `UpdateEmpty` call.
> Editorial: Unify style of abrupt completion and non-LoopContinues result handling in ForIn/OfBodyEvaluation

- spec.html
Convention is to use `≥` for mathematical value comparisons.
> Editorial: replace "is at least" with ≥ in parseInt

- spec.html
...regardless of copy direction
Fixes #3618
This aligns the spec with implementation reality.
> Normative: When TA.copyWithin argument handling shrinks TA, use whatever elements still fit

- spec.html
This matches the structure used for other built-in objects.
The first commit moves the clause and the second commit reformats the spec.
> Editorial: Make "Properties of the Iterator Prototype Object" a subclause of "Iterator Objects"

- package-lock.json
- package.json
Fixes tc39/ecmarkup#653  tc39/ecmarkup#652
> Meta: bump ecmarkup to v21.4.0
