tc39/ecma262

README.md
Proposal at https://github.com/DavidBruant/Map-Set.prototype.toJSON
=> Proposing Set/Map.prototype.toJSON

README.md
Presented to the committee in March 2015 to become Stage 1. Ready to advance at next presentation.
=> Adding export-from

README.md
Stage 1, per 2015.07.29 TC39 meeting.
=> Add String#trimLeft/String#trimRight

README.md
See: https://github.com/rwaldron/tc39-notes/blob/master/es7/2015-07/july-30.md#613-advance-restspread-properties-to-stage-2
cc @sebmarkbage
=> Advance Rest/Spread Properties to stage 2

stage0.md
=> Add link to shared memory + atomics spec

stage0.md
Moving from old gist to new tracking repo
=> Update class property proposal link on stage0 doc

README.md, stage0.md
=> move class property declarations proposal to stage 1

README.md
=> change Object.observe champion to Adam Klein

README.md
=> advance trailing commas to stage 2

FAQ.md
Various FAQ's pop up on esdiscuss and elsewhere from time to time, so I figured this would be a good defacto place to log and point anyone who has FAQs.
=> Add an FAQ.md doc

spec.html
Per https://github.com/tc39/ecma262/pull/266#issuecomment-166147862.
=> Editorial: Fix unintentional normative changes from #266 / 5512445d776b0

README.md, stage0.md
=> Meta: bump `Object.getOwnPropertyDescriptors` to stage 3

spec.html
=> Editorial: Use assert rather than "must be true"

spec.html
=> fixes #185: link methods referenced in well-known symbols table

spec.html
=> swapping %TypedArray%.prototype.includes and %TypedArray%.prototype.indexOf

spec.html
This is just a cosmetic change but helps a lot reading the spec steps.
=> Editorial: Optimize _if_ order in TypedArray#set

spec.html
This also makes it consistent with the phrasing used in #559.
=> Editorial: Simplify `QuoteJSONString`

spec.html
See https://github.com/tc39/ecma262/issues/601
=> ResolveExport: return null instead of throwing

spec.html
@bterlson Another case of the maintenance difficulty we discussed in gh-617.
=> Editorial: Update algorithm step references

spec.html
Miscellaneous editorial tweaks to recent commits.
=> Misc editorial

spec.html
Thanks @jswalden for noticing this.
I assume this was a bad merge in #692.
=> Editorial: Remove duplicate GeneratorPrototype mention

spec.html
=> Add ValidateTypedArray in each iteration of ArrayIterator

spec.html
I ended up putting the memory model as its own top-level clause as the last clause.
The informative guideline sections of the proposal are still unintegrated. I'm unsure where to put them or if they should be put in.
=> SAB integration even sections

spec.html
Changes to consistify the "With parameter(s)" paragraphs of production-based operations.
=> Editorial re "With parameter(s)" paragraphs

spec.html
This reverts commit 5d5fdaba029ff87ffda08d1332c177bf46c9fa32.
Fixes #776
=> Revert "Editorial: Re-factor ExportSpecifier (#637)"

spec.html
=> Allow duplicate function declarations in switch-statements

spec.html
Found these while working on the BigInt spec. WDYT?
=> Two editorial fixes

spec.html
As pointed out by John Regehr on Twitter.
=> Change 'behaviour is undefined' to 'is implementation-defined'.

spec.html
@AndrewScheidecker found a bug in the wait algorithm, this should fix it.
=> Issue 861: Only remove a waiter from the waiter list if the wait timed out

spec.html
value producing item → value-producing item
=> Editorial: Add missing hyphen

spec.html
These are either used by [Web IDL](https://heycam.github.io/webidl/), or in a portion of the W3C TAG [Promises Guide](https://www.w3.org/2001/tag/doc/promises-guide) [slated to be moved into Web IDL](https://github.com/w3ctag/promises-guide/issues/27).
/cc @domenic
=> Editorial: Add a few well-known intrinsic objects

spec.html
=> Editorial: Create OrdinarySetWithOwnDescriptor

spec.html
Except for c70a81a42a8c7f6af8d2dfe1aacd976130b0208a, the other commits should be acceptable as non-normative changes.
=> Misc editorial fixes

spec.html
=> Editorial: Add missing 'The following steps are performed:' before several Date algorithms.

CONTRIBUTING.md
URL was updated to use HTTPS protocol
=> Update HTTP -> HTTPS

spec.html
- data property
- accessor property
- integer index
- array index
- Integer-Indexed exotic object
=> Editorial: Linkify some terms

CONTRIBUTING.md
See https://github.com/tc39/Reflector/issues/104 for context.
=> Meta: Link to the new contributor form

CONTRIBUTING.md
(based on https://github.com/tc39/ecma262/pull/1044#issuecomment-364972833)
=> Editorial: Add para re resolving conflicts with master.

spec.html
=> Editorial: Move AsyncFunctionCreate into 9.2 ECMAScript Function

spec.html
Closes https://github.com/tc39/ecma262/issues/1169
=> Editorial: specify Date.parse cannot return an abrupt completion

spec.html
Fixes #1189. @syg please review for correctness.
=> describe clause 27 (memory model) in section 4.4 (organisation)

spec.html
Bringing more editorial changes from master into ES2018.
=> ES2018: more editorial changes

spec.html
See https://github.com/tc39/ecma262/issues/1155.
=> Remove bogus assertion in GetModuleNamespace.

spec.html
Contains non-normative improvements from [proposal-uniform-interchange-date-parsing](https://github.com/gibson042/ecma262-proposal-uniform-interchange-date-parsing).
=> Editorial: Update date-time format language

spec.html
=> Editorial: "length" should be used consistently

spec.html
=> Editorial: ensure spaces around binary operators

spec.html
=> Editorial: Add "async generator" to [[FunctionKind]] description

spec.html
=> Editorial: fix a misused completion

spec.html
=> Editorial: Add missing <i> to IteratorResult interface

table-unicode-script-values.html
https://unicode.org/versions/Unicode12.0.0/
Ref. #1467.
=> Normative: Update Unicode property lists per Unicode v12

spec.html
=> Fix typo (DFSAncestoreIndex -> DFSAncestorIndex)

spec.html
=> Meta: use discourse link in community box

CONTRIBUTING.md
Definition copied from the "normative change" label
(cf. https://github.com/tc39/ecma262/labels?q=normative )
=> Meta: Improve the explanation of normative changes

spec.html
=> Editorial: align formatting of metadata block

spec.html
Addressing https://github.com/tc39/ecma262/pull/1592#discussion_r296410088
=> Editorial: "_@@toStringTag_" -> "@@toStringTag" in %RegExpStringIteratorPrototype%

spec.html
=> Editorial: Replace usages of "add" and "subtract" with "set"

README.md
Adding missing Stage 1 proposals list to the `README.md`.
=> Meta: Add Stage 1 proposals list

spec.html
@ljharb had asked for critical section to be defined. How does this sound?
=> Editorial: Define critical section

spec.html
(Forgot to apply these last night. I'm pretty sure that's all for now.)
=> Editorial: more quick fixes

spec.html
Two fixes re recent merge of PR #1124.
=> Editorial: quick fixes

spec.html
=> Editorial: fix intrinsic notation from previous PRs

spec.html
=> Editorial: Remove the |Keyword| nonterminal

spec.html
=> Markup: fix a malformed <emu-xref> tag

spec.html
I've missed this one in #1615.
Please see https://github.com/tc39/ecma262/pull/1615#discussion_r301840600 for motivation.
=> Editorial: Remove extra note from InternalizeJSONProperty

spec.html
As discussed in https://github.com/tc39/ecma262/pull/1914#discussion_r398316023.
=> use spec-internal enum in GetOwnPropertyKeys AO

spec.html
=> Editorial: Treat not present flatMap parameter as undefined

spec.html
=> Editorial: Fix TemplateStrings early error for SubstitutionTemplate

spec.html
5 commits for #1932 and 1 for #1931.
=> Editorial: quick fixes for recent merges

spec.html
Just a little reorder to improve the clarity here.
=> Editorial: reorder step in GetTemplateObject

spec.html
See https://github.com/WICG/construct-stylesheets/issues/90 as well.
=> Editorial: s/constructable/constructible

spec.html
=> Editorial: Clarify notes on async functions in CreateDynamicFunction

.travis.yml, package-lock.json, package.json, scripts/netlify.sh, scripts/publish-preview.js
Co-authored-by: Ryan Block <rblock@gmail.com>
Co-authored-by: Jordan Harband <ljharb@gmail.com>
This adds a deploy preview from Begin.
Once I've confirmed that the PR works as designed, I'll promote it from being a draft PR; until then, no need to review it.
=> [meta] add Begin deploy preview

package-lock.json, package.json
#1995 broke the rendering of SDOs, whoops.
=> meta: bump ecmarkup

spec.html
=> fixes #2002: more precise definition of NumberBitwiseOp and ByteListBitwiseOp

table-binary-unicode-properties.html
Tests: https://github.com/tc39/test262/pull/2526
Ref. #1897 & #1896.
=> Normative: Update RegExp property aliases per Unicode v13

README.md
Noticed the discourse is missing from the community section of the readme
=> Meta: add discourse to readme

spec.html
Unified both wording and formatting.
=> Editorial: Unify text about refining grammars

spec.html
=> Editorial: A couple fixes from OrdinaryFunctionCreate and undefined arguments

package-lock.json, package.json, spec.html
This fixes #2066. There wasn't already a `<body>`, so I added one.
=> fixes #2066: add a language tag to the document body

spec.html
=> Editorial: fix minor errors in step syntax

scripts/snapshot_warning.html
=> Meta: Update link in snapshot warning

spec.html
=> Editorial: handle NaN and infinities in Math.round

spec.html
=> Editorial: move CreateRegExpStringIterator

spec.html
Resolves https://github.com/tc39/ecma262/issues/1852.
=> Editorial: Remove Formal[Rest]Parameter from IteratorBindingInitialization

spec.html
=> Editorial : ref extended/modified steps/entries

spec.html
Fixes https://github.com/tc39/ecma262/issues/2243, thanks @lukq.
=> Editorial: fix type in preamble of EvaluateCall

spec.html
I believe there is an 'of' missing in that sentence.
=> Editorial: add missing word

spec.html
Fixes https://github.com/tc39/ecma262/issues/1874. This came up in [IRC](https://freenode.logbot.info/tc39/20210107#c6445825-c6445844) recently as well.
=> Editorial: make EPSILON unambiguously positive

spec.html
=> Editorial: add missing assertion to ApplyStringOrNumericBinaryOperator

spec.html
As discussed on the editor call, the feeling is that there isn't enough added value here for this paragraph in a technical specification.
=> Editorial: Remove paragraph listing similarities to other languages

spec.html
See https://piccalil.li/quick-tip/add-scroll-margin-to-all-elements-which-can-be-targeted
=> Meta: add `scroll-margin-top` CSS to make for a nicer anchor experience

package-lock.json, package.json, spec.html
Fixes https://github.com/tc39/ecma262/issues/1270. See also https://github.com/tc39/ecma262/issues/1434, https://github.com/tc39/ecma262/issues/1700, https://github.com/tc39/ecmarkup/issues/151.
Implementation in ecmarkup is [here](https://github.com/tc39/ecmarkup/pull/301).
I've only done this for the main build, not the yearly ones, since we're in the process of tweaking those (https://github.com/tc39/ecma262/pull/2337).
=> Meta: multipage builds

spec.html
... just to eliminate some repetition.
=> Editorial: Factor out abstract operation RegExpHasFlag

spec.html
This includes changes from https://tc39.es/proposal-private-methods/.
=> (ignore) Normative: Add private methods and getter/setters.

spec.html
=> Editorial: fix handling of infinities in Math.hypot

package-lock.json, package.json
Fixes #2461 by inclusion of https://github.com/tc39/ecmarkup/pull/338.
=> Meta: bump ecmarkup to 8.0.1

spec.html
More changes in the same vein as PR #2483.
=> More suggested changes

spec.html
Proposal is currently at stage 3 and this spec text has already been reviewed by @ljharb @leobalter and @Felienne
https://github.com/tc39/proposal-accessible-object-hasownproperty
=> Normative: Add `Object.hasOwn`

spec.html
=> Editorial: fix slight ambiguity in ToPrimitive note about Dates

README.md, spec.html
#2520 missed a couple references to the old IRC rooms, including one in the document itself.
=> Meta: drop remaining references to IRC

spec.html
A bigger refactoring of the Date AOs is still in order, but this will help comprehensibility in the meantime.
=> Editorial: Document parameter type for Date Abstract Operations

spec.html
For proposal [error cause](https://github.com/tc39/proposal-error-cause).
=> Normative: add error cause

spec.html
Re: https://github.com/tc39/proposal-array-grouping/pull/20
=> Editorial: `find`/`findIndex`: update note about delete before visit

spec.html
More normalisation in phrasing.
=> Editorial: replace most occurrences of "has the value" with "is"

spec.html
- 2x Delete "TODO" comments.
- 4x Add underscores around "Desc".
- 4x Change comma to semicolon before "else".
=> Editorial: Quick fixes re PR #2468

spec.html
=> Editorial: Use consistent wording for SDO application with argument(s) 

.github/workflows/publish-biblio.yml
=> Meta: fix biblio publish job

.github/workflows/publish-biblio.yml
so that [this](https://github.com/tc39/ecma262/blob/e212096f6242648d0eb2ffcb1ea100163a4422c5/scripts/publish-biblio.sh#L12) works
=> Meta: fix biblio publish job, take 2

spec.html
=> Editorial: fix type confusion in msFromTime

spec.html
=> Editorial: fix ambiguity in Annex B definition of typeof semantics

spec.html
As discussed in https://github.com/tc39/ecma262/pull/2305#discussion_r819164968.
=> Editorial: eliminate unnecessary phrasing that explains how return works

package-lock.json, package.json, spec.html
=> Editorial: use < -0 instead of < +0

spec.html
=> Editorial: `splice`: consolidate redundant count variables

spec.html
=> Editorial: note about arguments immutability in strict code

spec.html
=> Editorial: clarify that built-in functions may lack [[Construct]]

spec.html
As suggested at https://github.com/tc39/ecma262/pull/2739/files#r852477711
=> Editorial: Use consistent phrasing for string length

spec.html
Ref 58057150a5fe6dd2e08f7c83d0ba28e8165a9490
=> Editorial: Add missing preposition

spec.html
=> Editorial: Fix descriptor kind check in ValidateAndApplyPropertyDescriptor

spec.html
This adds the spec text from https://github.com/tc39/proposal-array-find-from-last, currently at Stage 3.
=> Normative: Add array-find-from-last

LICENSE.md
=> Meta: Specification text uses alternate policy

spec.html
As suggested at https://github.com/tc39/ecma262/pull/2839#discussion_r940640879 .
=> Editorial: Use StringPad rather than "padded" prose

spec.html
Details in the commit messages.
=> Editorial: Correct notes in Create{Method,NonEnumerableData}Property 

spec.html
=> Editorial: properly define and `<dfn>` spec enums

spec.html
- Add a "Syntax" header.
- Add new nonterminals to Annex A.
=> Editorial: Fixups for hashbang PR

scripts/check-form.js
This uses the commits list API instead of the compare API, and actually covers every author. It also adds exceptions, and some legacy TODOs we need to address over time
=> Meta: properly fix IPR script (#2872)

spec.html
This conversion to a List wasn't helping anything. It's still not perfect, but I think it's much better.
=> Editorial: remove some unnecessary complexity due to the SourceText AO

spec.html
A V8 engineer was confused about this today, figured it doesn't hurt to add a note.
=> Editorial: Add note that roundtripping ToIntegerOrInfinity never produces -0

spec.html
Just some minor things I noticed in this code sample.
=> Editorial: tweak a code sample

spec.html
=> Editorial: Add 'AsciiLetter' to Annex A

spec.html
cf. https://github.com/tc39/proposal-string-cooked/pull/11#discussion_r879488509 and https://github.com/tc39/proposal-string-cooked/pull/11#discussion_r880732986
May be reviewed holistically or by commit.
=> Editorial: Refactor String.raw in anticipation of generalization

spec.html
I also updated the Notation section's ID since it was *way* under-specific.
=> Editorial: dfn the Pattern data structures

package-lock.json, package.json, spec.html
Based on https://github.com/tc39/ecma262/pull/3043.
There's a few more cases the lint rule catches; I've pushed up a new commit handling those.
=> If-else consistency

spec.html
=> Editorial: fix the type of Iterator Record [[NextMethod]]

scripts/insert_snapshot_warning.js
=> [meta] fix newline in snapshot warning

spec.html
Fixes https://github.com/tc39/ecma262/issues/2395
=> Editorial: ToUint8Clamp guard against infinity doubles

spec.html
Plus a small addition for "Properties of String Instances".
=> Editorial: Add "Properties of BigInt Instances" section

spec.html
More or less stolen from PromiseCapability Records.
=> Editorial: dfn PromiseReaction Records

spec.html
As per https://github.com/tc39/Admin-and-Business/issues/350.
=> Editorial: update links to Ecma specs and update ECMA-402 descriptor

spec.html
(apply editorial convention to recently-merged PR #3337)
=> Editorial: Change some `X is Y` to `SameValue(X, Y) is *true*`

spec.html
(This is against the iterators-helpers-integration branch.)
=> Editorial suggestions for PR #3395

spec.html
=> Editorial: Fix typo

spec.html
https://github.com/tc39/ecma262/pull/3342#issuecomment-2192894464 only did one of the several table cells which needed this.
=> Markup: more slashed corner cells

spec.html
=> Normative: Revert ArrayIterator and RegExpStringIterator to manual iterators

spec.html
=> Editorial: Fix some ?! misuses

spec.html
I guess this predates the spell checker?
=> Editorial: fix spelling of "requirements"

spec.html
=> Editorial: add note to SetFunctionName clarifying optionality

spec.html
=> Editorial: make RequireObjectCoercible return `~unused~`
