stage0.md
- It's tiny
- It's already available inlined in SM
- It's already a runtime call in V8
- Applications & frameworks should be able to use these as well
=> Add proposal to expose IsCallable/IsConstructor to JS code

README.md
Rebase from original PR: https://github.com/tc39/ecma262/pull/14
As per https://github.com/tc39/tc39-notes/blob/master/es6/2014-09/sept-25.md#58-object-rest-destructuring-and-spread-properties
Putting the rocket ship on it since it's ready for Stage 2 at the next meeting.
=> Bump Rest/Spread Properties to Stage 1

README.md
From the TC39 meeting on 2015.07.28.
=> Update to reflect advancement of `Array#includes` && `**`

spec.html
This avoids repeating a bunch of steps that actually *must* remain the same for backwards compatibility reasons. As new primitive types are added, this reduces the places these changes need to be added from 3 to 1.
Per brief discussion with @bterlson, it may be too soon to PR this, but I figured I'd write it up anyways. Please feel free to let it sit as long as necessary.
=> Consolidate SameValueZero and Strict Equality Comparison steps to delegate to SameValue

spec.html
Fixes https://github.com/tc39/ecma262/issues/128#issuecomment-151277006.
=> Normative: Define 21.2.2.2 behavior when `index >= str.length`

stage0.md
Reference: https://esdiscuss.org/topic/efficient-64-bit-arithmetic#content-7
https://gist.github.com/BrendanEich/4294d5c212a6d2254703
Looks like it was never added here
=> add 64-bit integer operations entry to stage 0 proposals table

spec.html
Fixes #264.
- A few legacy methods that have deviating lengths are documented explicitly.
- Any unneeded explicit lengths are removed.
- Needed legacy explicit lengths are added.
- Spacing inside optional argument brackets is made consistent
- Fixed a bug with a `DataView` note having the wrong argument name
- replaced two instances of a spreaded argument using an ellipsis with three dots
The DataView prototype get/set methods have inconsistent lengths across all browsers, so rather than select one of them as legacy, I decided to let them fall into the default category, which hopefully implementations will align with.
=> Normative: change default function length value to not include optional arguments

spec.html
The majority of uses of emu-eqn in this spec were bogus: around property descriptors, abstract operation calls, or in one case just part of a sentence.
=> Editorial: remove bogus uses of emu-eqn

spec.html
Fixes #383. then-ing a promise should always mark it as handled, not
just when the promise is already rejected.
=> Layering: fix unhandled rejection tracking in PerformPromiseThen

spec.html
The GetExportedNames method returns an abrupt completion when the host
cannot resolve the requested module. This possibility must be accounted
for when the method invokes itself.
=> Normative: account for possible abrupt completion

.travis.yml
Add `sudo: false` to the `.travis.yml` file in order to use Travis CI's container-based infrastructure, thus, making the builds start and run faster.
--
It seems this repository was recognize by Travis CI before 2015-01-01, so builds where sent to the standard infrastructure:
* https://docs.travis-ci.com/user/migrating-from-legacy/
* https://docs.travis-ci.com/user/workers/container-based-infrastructure/
=> Meta: Use Travis CI's container-based infrastructure

spec.html
This patch makes a change to ES2015 RegExp semantics to prevent
certain property accesses and method calls from throwing. Although
the feature testing patterns here are dispreferred, they were found
necessary to ensure web compatibility of ES2015-based RegExp
semantics with respect to old versions of certain libraries.
This closes #262.
This patch attempts to encode the consensus of the March 2016 TC39 meeting.
=> RegExp.prototype not an instance web compatibility workaround

spec.html
Immediately prior to invoking ResolveExport, the [[Get]] method ensures
that the property key exists in the [[Exports]] list. In
ModuleNamespaceCreate, the [[Exports]] slot is set to the list of all
bindings that may be resolved unambiguously from the requested module.
This means that this invocation of ResolveExport cannot return an abrupt
completion.
Document this fact in the text of the algorithm.
=> [editorial] Assert normal completion value

spec.html
A module Namespace exotic object's [[Exports]] internal slot is defined
through the following sequence of steps:
1. GetModuleNamespace invokes GetExportedNames
2. GetExportedNames returns a List of strings describing the
LocalExportEntries in source code order, followed by the
IndirectExportEntries in source code order, followed by the same for
each of the module's "star" exports.
3. GetModuleNamespace resolves all `exportedNames`, filters out all
ambiguous names, and passes the result to ModuleNamespaceCreate
4. ModuleNamespaceCreate sets the object's [[Exports]] internal slot to
the provided list
There is no normative text that modifies the order of list elements
following its creation in GetExportedNames. This conflicts with the
~~informative~~ text in table 29, "Internal Slots of …
=> [editorial] Specify order of module namespace keys

spec.html
This closes #489. RegExpBuiltinExec reads other flags from
[[OriginalFlags]], based on the fact that it is operating on a RegExp
instance. In ES2015, however, it accessed 'global' and 'sticky' via
property accesses. This patch changes RegExpBuiltinExec to access
those flags via [[OriginalFlags]] as well.
=> Read global and sticky from [[OriginalFlags]] in RegExpBuiltinExec

spec.html
https://tc39.github.io/ecma262/#sec-functiondeclarations-in-ifstatement-statement-clauses
To begin with I was just going to fix typos, then I thought the language could be simplified, and noticed some terminology issues.
Is there anything meaningful about the "subsequent" here (emphasis mine)?:
> *subsequent* processing of that code
I figured it's redundant and trimmed it.
Typos:
* "is match"
* "takes places"
Terminology:
* "rule" => "production"
* "not strict mode code" => "non-strict code"
=> Edit B.3.4: fix typos & terminology, simplify language

spec.html
I'd like to suggest only referring to `Object.assign()` as a function since it never uses ~~context~~ the `this` value.
If this is too nitty please let me know for future reference.
=> Only reference Object.assign as function, not method

spec.html
3e33231618980b070f1c70828758b1065f2590ee (#269) accidentally limited the maximum size to 2<sup>32</sup> for TypedArray allocations from iterables (cf. CreateArrayFromList call in IterableToArrayLike).
=> Allow iterables with more than 2^32 elements in TypedArray.from

spec.html
In cases where Annex B re-defines semantics in the preceding sections,
the relevant sections are generally annotated with a reference to the
relevant extension. This aids discovery by readers and also maintenance
by authors--as section numbers and step numbers change, references in
Annex B prose may need to be updated accordingly.
Explicitly reference the relevant Annex B extension from within the
algorithm steps for EvalDeclarationInstantiation.
=> [editorial] Document algorithm modification

spec.html
The TypedArray constructor includes a "fast path" for a TypedArray input (as
opposed to treating it as an iterable), which has a fast path for the case of
the same-type input and output. Previously, this called CloneArrayBuffer.
CloneArrayBuffer takes an argument for the start offset, but not for the end,
so it copied the underlying ArrayBuffer until the end. The extra wasted copy
remains observable, e.g. in cases like
new Uint8Array(new Uint8Array(10000).subarray(0, 1)).buffer.byteLength // => 1 or 10000 ?
This patch refactors CloneArrayBuffer into CloneUnderlyingArrayBuffer which
clones only the viewed part of the ArrayBuffer, taking the end into account.
This does not make an observable change for the other caller
(%TypedArray%.prototype.set), where it would have already been valid to …
=> In the TypedArray(typedArray) constructor, copy only the needed portion

spec.html
This function already isn't really that straight forward, because of the handling of C. I feel like getting the !IsArray case out of the way earlier makes it easier to understand. This is also how we implemented this in Firefox.
=> Simplify ArraySpeciesCreate

spec.html
Instead of only looking at Function components, and falling back to the running execution context, simply go for the topmost execution context with a ScriptOrModule component.
The "no such context exists" case can in fact be reached, if GetActiveScriptOrModule() is called with a stack that only contains the "realm execution context" (i.e. if this is called without being initiated by ScriptEvaluation or ModuleEvaluation).
=> Layering: take care of edge cases for GetActiveScriptOrModule()

spec.html
The [step 9 from 22.2.3.24](https://tc39.github.io/ecma262/#sec-%typedarray%.prototype.slice) creates a new TypedArray instance that will be validated on [22.2.4.6 step 2](https://tc39.github.io/ecma262/#typedarray-create), including a validation for a length that is >= the given `count`, which is never gonna be higher than the original instance's length.
It seems it is impossible to have an abrupt completion from the ~~_Get_ and~~ _Set_ operations on steps ~~14.b.ii and~~ 14.b.iii. This patch reflects it.
=> TypedArrays slice set operation does not throw

spec.html
Previously, the character case of alphabetic hexidecimal digits rendered
by the `escape` function was unspecified. Specify the case to be "upper
case" in order to reduce ambiguity and match the behavior implemented by
the following web browsers:
Browser           | Version (operating system)
------------------|------------------------------------------------------------
Microsoft Edge    | v13 (Windows 10), v12 (Windows 10)
Internet Explorer | v11 (Windows 10), v6 (Windows XP)
Firefox           | v46 (Windows 10), v32 (Windows 10), v3 (Windows XP)
Chrome            | v50 (Windows 10), v37 (Windows 10), Android v5, Android N
Opera             | v36 (Windows 10), v23 (Windows 10), v10.6 (Windows XP)
Yandex            | v14.12 (Windows 10)
Safari            | v9 (OSX El Capitan), v5.1 …
=> [normative] Specify char case of `escape` output

spec.html
At this step of the algorithm, `y` cannot take the value NaN because the
previous branch would have been taken, terminating algorithm execution.
This makes the explicit condition superfluous.
=> [editorial] Remove tautological condition

README.md, stage0.md, withdrawn-proposals.md
This removes the list of proposals from the main `ecma262` repo, and moves them to a separate repo hosted [here](https://github.com/tc39/proposals).
Some advantages of this include that the specification's commit log no longer need be cluttered with "Meta" commits updating proposal information, and that all TC39 members will now have full push access to edit the proposals list without any concern about too many people having full access to the official spec.
=> Meta: Remove proposals list and point to new repo

spec.html
(https://github.com/tc39/proposal-string-pad-start-end/issues/23)
=> Per May 2016 TC39 consensus, `String#{padStart,padEnd}` is now stage 4!

spec.html
Most of them (i.e. the ones adding a black 1px border) didn’t have any visual effect in the first place, and the others made the table headers look inconsistent. With this change, table headers get the same background color rather than using fifty shades of gray.
=> Editorial: Remove inline style attributes

spec.html
- Add underscores to parameter names in clause header.
- Add `<p>..</p>` to `<emu-note>`s.
=> Editorial: tweak String.prototype.pad{End,Start}

spec.html
Previously this wasn’t being done consistently.
In the context of code points, e.g. `0x10FFFF` is more readable than `1114111`.
=> Editorial: Use hexadecimal notation for code points and bytes

spec.html
The current spec creates fictional “equivalent functions” called “Identity” and “Thrower”, and passes these around with `PromiseReaction` records.
Instead, this change adds a string “Type” field to `PromiseReaction` records, and sets the “Handler” field to `undefined` when none is provided, so that the behavior can be determined solely inside `PromiseReactionJob`.
This change should be non-observable, hopefully adds a bit more clarity, and helps [future Promise proposals](https://github.com/ljharb/proposal-promise-finally) have smaller diffs against the spec.
=> Editorial: spec refactor of PromiseReaction records/PromiseReactionJob

spec.html
(https://github.com/tc39/proposal-object-getownpropertydescriptors/issues/9)
=> Per May 2016 TC39 consensus, `Object.getOwnPropertyDescriptors` is now stage 4!

spec.html
Ref #265
On these changes, the offset arguments have a consistent check to throw for values < 0, and length will pass through the ToLength.
=> Normalize TypedArray, ArrayBuffer and DataView constructors 

spec.html
A previously overlooked aspect of intersection semantics for
#sec-block-level-function-declarations-web-legacy-compatibility-semantics
is the ability to have multiple function declarations with the same name
in the same block. This patch relaxes that constraint in sloppy mode.
Because it relaxes a static semantics rule, and replaces rather than
simply adds behavior, it is in the main spec text rather than Annex B.
The patch also puts the non-normative text in Annex B in an emu-note.
Fixes #320.
=> Normative: Allow duplicate FunctionDeclarations in a block

spec.html
Previously, proxy OwnPropertyKeys returning duplicate keys would cause an error when the target object was non-extensible. The error does not seem deliberate but rather a result of not considering the possibility of duplicate keys. This PR handles that possibility and removes the error.
I think this is just a bug fix but if anyone thinks this needs consensus let me know. Also note that this is a breaking change for spidermonkey and chakra. V8 already implements these semantics. cc @efaust.
=> Normative: Remove proxy OwnPropertyKeys error with duplicate keys

spec.html
Specifically, change:
```
the [[Foo]] internal slot of _O_  (132 occurrences)
```
and
```
_O_'s [[Foo]] internal slot (265 occurrences)
```
to
```
_O_.[[Foo]]
```
(Resolves issue #574)
=> Editorial: use dot notation for accessing internal slots

spec.html
Replace `</emu-grammar> .` with `</emu-grammar>.`.
=> Editorial: Remove extraneous spaces

spec.html
HasComputedPropertyKey was introduced in revision 20 of 2015 [1], but in
that draft, it was not referenced from any other algorithm (nor mentioned
in the accompanying change log [2]). The latest revision of ECMA
maintains the abstract operation in this state.
Remove HasComputedPropertyKey due to its being superfluous to the
specification.
[1] http://wiki.ecmascript.org/lib/exe/fetch.php?id=harmony%3Aspecification_drafts&cache=cache&media=harmony:working_draft_ecma-262_edition_6_10-28-13-rev20markup.pdf
[2] http://wiki.ecmascript.org/doku.php?id=harmony:specification_drafts&s=es6#october_28_2013_draft_rev_20
=> [editorial] Remove unused "HasComputedPropertyKey"

spec.html
(Make things more explicit, and establish a clearer parallel between rhs-guard syntax and rhs-nonterminal use syntax.)
Resolves Issue #374.
=> Editorial: Tweak the syntax of grammatical parameters.

spec.html
Rather than “Separator, Space” and other variations, consistently use the canonical Unicode category name `Space_Separator` along with its alias `Zs`.
=> Editorial: Use the canonical category name `Space_Separator`

spec.html
This phrase was last used in ES5 for String#toString and String#valueOf
and it seems this paragraph can be safely removed now.
=> Editorial: Remove reference for 'this String value'

spec.html
Because an anonymous FunctionDeclaration can only occur as part of an
`export default` declaration, an `export` declaration can only occur in
in module code, and module code is always strict mode code, the function
code of an anonymous FunctionDeclaration is always strict mode code.
Remove the condition that allows for non-strict anonymous function
declarations, and update the accompanying informative note to explain
this detail.
=> Editorial: Remove impossible condition

spec.html
Currently clicking on `Block` anywhere in the main document, e.g. [here](https://tc39.github.io/ecma262/#sec-block), links to [the preface](https://tc39.github.io/ecma262/#prod-Block). This is particularly annoying since the runtime semantics given in that section are not in fact the semantics for `Block`.
This PR corrects this.
=> Editorial: (markup) add namespace to algorithm-conventions

spec.html
I first thought on prefixing that step with a Note, but that information does not add much as there's no ambiguous or complex thing to explain there. It actually took me a few seconds to see it is not doing anything, just informing the changes will be applied in a further step.
=> Editorial: Remove unnecessary step from ValidateAndApplyPropertyDescriptor

spec.html
The word optionally might be taken as implementation defined to use
the respective arguments it refers to. Removing it makes it clear
the following steps will be taken when Date.UTC is called with 3 or
more arguments.
cc @jugglinmike
=> Editorial: Remove ambiguous statement from Date.UTC

spec.html
As of June 21st, Unicode 9.0.0 is the latest version.
**Update July 27:** This PR has been updated to refer to the latest available Unicode version rather than v9.0.0 specifically, as per the July 27 meeting.
=> Normative: Require the latest available Unicode version instead of a fixed version number

spec.html
Per discussion on https://github.com/tc39/ecma262/pull/582#issuecomment-223368443
This needs TC39 consensus.
=> Normative: `Object.getOwnPropertyDescriptors` should not create keys for undefined descriptors

spec.html
Fixes #260.
Per [discussion](https://github.com/rwaldron/tc39-notes/blob/aad8937063ab32eb33ec2a5b40325b1d9f171180/es6/2014-04/apr-10.md#revisiting-initializer-in-for-in), this adds a section in Annex B with a production for `for ( var BindingIdentifier Initializer in Expression) Statement` with its original semantics, in light of the [usage statistics collected by V8](https://github.com/tc39/ecma262/issues/260#issuecomment-220823926) and the fact that implementers have had to allow this production.
--
Edit (July 27, 2016): This comment was slightly wrong; it was only added to non-strict code.
=> Normative: Allow initializers in ForInStatement heads

spec.html
This one is quite opinionated, but I find proposed option easier to read (took me a moment to notice how [`29708-9`](https://github.com/tc39/ecma262/compare/master...shvaikalesh:master#diff-3540caefa502006d8a33cb1385720803L29709) and [`29713-14`](https://github.com/tc39/ecma262/compare/master...shvaikalesh:master#diff-3540caefa502006d8a33cb1385720803L29714) are different) and maintain (please, note the missing `?` before `Get` on [`29708`](https://github.com/tc39/ecma262/compare/master...shvaikalesh:master#diff-3540caefa502006d8a33cb1385720803L29708)).
=> Editorial: Refactor Array.prototype.join

spec.html
Previously, when performing ArgumentListEvaluation for tagged templates,
the result of evaluating each substitution expression was not passed to
GetValue. This meant that unresolvable references would not interrupt
ArgumentListEvaluation, and that Reference values would eventually be
assigned to function parameter bindings in
FunctionDeclarationInstantiation.
Update ArgumentListEvaluation (and the related SubstitutionEvaluation)
to avoid this situation and increase parity with the abstract
operation's behavior when applied to the Arguments production.
=> Normative: Resolve template argument references

spec.html
The `S` argument is only used to make decisions about sets occuring
after initialization, so the mention of "before initialization"
here was spurious.
=> Editorial: Simplify description of CreateImmutableBinding

spec.html
Follow-up to #638.
Drop `separator` parameter reassignment and extra `ToString` call for default `separator` value.
=> Editorial: Tweak Array.prototype.join

spec.html
Follow-up to #638.
Move special handling of first index into the loop body, removing some
duplication. Drop extra reassignments of `R` and concatenations with empty strings.
=> Editorial: Refactor Array.prototype.toLocaleString

spec.html
When comparing to `null/undefined`, ensure that `undefined` goes before
`null` in all cases.
This improves consistency and search experience.
=> Editorial: Consistent `undefined or null` order

spec.html
Fixes dangling reference to `ScriptBody`. Resolves #587.
=> Editorial: Fix reference in ScriptEvaluation

spec.html
Rename variable in `Array.prototype.pop` to be consistent with naming in other algorithms.
=> Editorial: Rename variable (indx --> index)

spec.html
1. Add missing semicolon.
1. Improve variable naming consistency (`protoName` --> `protoKey`, because `key`).
1. Early `continue` for `symbol`s (less indentation, more obvious what keys are skipped).
1. Use `const` instead of `let`.
=> Editorial: Tweak EnumerateObjectProperties informative definition

spec.html
=> Editorial: Fix a wrong cross-reference in Annex C

spec.html
It refers to "BoundNames of `argumentsList`", but `argumentsList` is now an actual value, not a grammar production.  I suspect the name used to be correct, then someone renamed `argumentsList` to `formals`, and things got skew.  Now `parameterNames` exists as the "BoundNames of `formals`", so it's the best thing to use.
I also went and added big WARNING comments next to all the monkey-patched spec algorithms, so maybe renames of stuff will remember to update Annex B as well.  There were already NOTE: steps that theoretically should have been enough reminder to the spec-modifier, but I guess they weren't.  It seems to me like a comment at the start of the algorithms is most likely to be read by someone skimming the algorithms to see where to do variable renames, so it's worth adding even …
=> Annex B.3.3.1's monkeypatching of FunctionDeclarationInstantiation is out of date

.travis.yml, package.json
Note that the Travis configuration has been updated accordingly.
Ref. https://github.com/bterlson/ecmarkup/pull/101.
=> Meta: Update ecmarkup version dependency

spec.html
Instead of referring to a version snapshot, link to the latest version of UTR15.
Ref. #620.
=> Normative: Point to the latest version of UTR15

spec.html
It is strange, but web browsers do this correctly, so may be I am misinterpreting the spec text.
=> (10).toPrecision(1) to give "1e+1", not "1.e+1"

spec.html
Closes #618.
Other options discussed at various points include "DistinctFormalParameters", "RestrictedFormalParameters" and "ModernFormalParameters" but this suggestion from @allenwb seems best. I'll leave this open for a bit in case there is some disagreement about this renaming.
=> Editorial: %s/StrictFormalParameters/UniqueFormalParameters/g

spec.html
Previously, `super` was allowed inside eval if eval was called inside
any function and disallowed inside arrow functions. This semantics
likely predates the eviction of super from functions during ES6 and was
simply not updated. This PR updates the relevant semantics to align more
closely with both user expectations and implementation reality.
With this PR, SuperProperty is only allowed inside eval if the current
this environment is a function environment record with a home object.
This means SuperCall is allowed in eval (and nestings thereof) in arrow
functions in methods per implementation reality. Other usages of
SuperProperty inside eval is an early error.
Additionally, SuperCall is only allowed inside eval if the current this
environment is a function environment record with a home …
=> Normative: Clarify rules around super inside eval

spec.html
Implementations have not had this extension for many years so continuing
to poison pill it is needless. This removes all mention of arguments
object's "caller" property with the exception of a note that gives a bit
of history (mostly so people can still ctrl+f "caller").
Closes #670.
=> Normative: Remove arguments.caller poison pill

spec.html
This was probably a copy/paste bug. This should refer to the production it is defined in.
cc @bterlson
=> AssignmentElement -> AssignmentRestElement

spec.html
- typo: ``"caller"` → `"caller"`
- bug: remove a leftover reference to a special [[HasProperty]]
implementation that is gone with #689
=> Editiorial: Small corrections following #689

spec.html
The [function trailing commas proposal](https://tc39.github.io/proposal-trailing-function-commas/)
is now Stage 4, so this PR updates the spec text to reflect it.
Please review carefully as I'm fairly noobish at merging ecmaspeak.
=> Trailing commas in function param and call lists

spec.html
This fixes two pluralization agreement issues introduced by #689.
=> Editorial: Minor grammar correction regarding arguments.callee

spec.html
Since a _FunctionExpression_ is a _PrimaryExpression_, I believe returning `false` in `IsFunctionDefinition` for every production of _UnaryExpression_ is incorrect. It's also not consistent with the rules for every other expression.
Otherwise I think `IsFunctionDefinition` would return `false` when evaluating initializers (e.g. `function foo(bar=function(){}) {}`), after "unrolling" all production rules.
Or am I misinterpreting the rules?
=> Apply chain rule to IsFunctionDefinition UnaryExpression: UpdateExpression

spec.html
Previously, NewTarget was disallowed in nested eval contexts and in eval inside arrow functions. This change allows NewTarget inside eval anywhere it would be allowed outside of eval.
This PR is on top of #685 as it uses a similar pattern.
=> Normative: Clarify rules around NewTarget in eval

spec.html
Table 5 and Table 30's row orderings are inconsistent with the subsection ordering of sections 9.1 and 9.5 respectively.
Precisely, `[[DefineOwnProperty]]` is lower in the table than in the section ordering.
This inconsistency bugged me a bit. :)
=> Editorial: Rearrange tables to be consistent with section ordering

spec.html
I had trouble understanding the steps required when a ReturnIfAbrupt is nested in a call to another operation such as `ToBoolean(? Call(...))`
I could not find appropriate guidance in the spec about how to apply the "means the same thing as" macro patterns, when the macro is applied mid-line as in this case.
The attached patch gives what I think is the intended meaning (after some initial discussion on IRC).
=> Add definition of unfolding of AbstractOperation(ReturnIfAbrupt(arg))

spec.html
- Explicitly state that they are just like ordinary objects, and have
the same internal slots, except for one weird trick. (closes #705)
- Factor out the body of the [[SetPrototypeOf]] method of immutable
prototype exotic objects into an abstract operation to make it
easier to do integration with embedders.
(see https://github.com/whatwg/html/issues/2035)
=> Clean up definition of Immutable Prototype Exotic Objects

spec.html
The `+Infinity` check is superfluous as the `min` function takes care
of that as well.
=> tolength: remove superfluous +Infinity check

spec.html
In prior editions, the ExportSpecifier production was defined using only
IdentifierName. However, when the ExportSpecifier is part of an "local"
ExportDeclaration, the IdentifierName was interpreted as an
IdentifierReference through an Early Error rule. The rule was
undesirable for a number of reasons:
- it duplicated the definition of IdentifierReference
- it relied on an abstract operation, ReferencedBindings, which was
otherwise unused
- it was not technically necessary (a separate Early Error rule for
ModuleBody requires that all ExportedBindings are declared within the
module itself, and it is not possible to create a such a binding)
These details made interpreting ExportSpecifier difficult and tended to
obscure the motivation for the use of IdentifierName.
Re-factor ExportSpecifier …
=> Editorial: Re-factor ExportSpecifier

spec.html
This makes its [[SetPrototypeOf]] method consistent with
other objects whose prototypes are immutable.
TC39 came to consensus on this change at the November 2016 meeting.
=> Allow resetting a Module Namespace object's prototype to null

spec.html
Per consensus at the November 2016 meeting, Module Namespace exotic
objects no longer have an @@iterator method.
Also changes the [[Configurable]] property of the @@toStringTag
property to false, as per consensus in the same meeting (and
because it's impossible to reconfigure due to the exotic
methods of such objects).
This closes #693 and #710.
=> Remove @@iterator from Module Namespace objects

README.md
I tend to find myself hitting this readme first when looking for proposal status updates, I think it's because "ecma262" is a clean, specific filter term vs "proposals".
It's currently a minor nuisance to have to click through to the "active proposals" page first, then scroll to the bottom and click "Finished Proposals" in order to navigate to the stage 4 proposals.
=> Add link to "Finished" proposals

spec.html
Fixes #699: currently the below `new` does not invoke `A`; with this change it does.
```js
function A() { this.x = 1; }
A.prototype = null;
new class extends A {}
```
As mentioned there, this is a normative change, but it causes the spec to match current behavior on (at least) Chrome and Firefox and so probably isn't breaking.
At the moment it does nothing to resolve the scoping issue mentioned [here](https://github.com/tc39/ecma262/issues/699#issuecomment-254676629).
=> Normative: Invoke superclass constructor even if its .prototype is null

spec.html
This PR creates a minimal amount of infrastructure around executing "agents".  Informally, agents are bundles of the existing execution machinery and a few additional bits.
The shared memory spec needs to talk about the relation between multiple executing agents at the semantic level.  For example, some executing agents can enter a synchronous wait state by calling Atomics.wait, and other executing agents can wake waiting agents by calling Atomics.wake.  It thus becomes necessary to treat agents as semantics objects.  In addition, the shared memory spec will need to attach properties to agents, making it even more convenient for them to be semantic objects.
Finally, a notion of forward progress is introduced here.  That notion is required for the shared memory work but it is also implicit …
=> Add language to define Agents

spec.html
With these changes , non-global non-sticky regexps with nonwritable
lastIndex property should just work:
- In RegExpBuiltinExec, remove any access to the lastIndex property for
non-global, non-sticky regexp.
- In RegExp.prototype.@@search, avoid to to set the lastIndex property
when not necessary.
=> Disregard lastIndex for non-global non-sticky regexps

spec.html
These calls are preceded by checks for `null` and `undefined`,
so they're guaranteed to succeed. But not all such calls were
annotated with `!`.
=> Editorial: annotate ToObject calls with `!`

spec.html
The spec first defines them as "well-known" so this just corrects a few places where they were referred to as "well known", which could cause some problems for anyone trying to search the spec for all references to well-known symbols.
=> Correct all references to "well known" Symbols

spec.html
Fixes a clause id and add Atomics[@@toStringTag], which was missing.
=> SAB integration editorial and normative fixes

spec.html
This is a very minor nitpick that came up recently: https://github.com/tc39/proposal-regexp-named-groups/commit/55b638988573b0e08e99e84a18d7799f06cfd7db#commitcomment-20385510
Note that my editor removed some trailing whitespace on unrelated lines as per the configuration in `.editorconfig`.
=> Editorial: Hyphenate “left-capturing”

spec.html
This was the consensus reached at the January TC39 meeting.
Future work will be done to re-enable the use of a null
extends clause, but the changes this PR reverts have some
undesirable side-effects.
Manual revert of the following commits, which stemmed from #543:
98c67f2c2696652005ab7fb7284fe8b4661a5dbf
a35f0f3b8ac53bbfa019bd35989c4027ce4976e4
f3881fe4b2363707cc68ba9972b041e1c7233922
=> Revert to ES2015 semantics for `class extends null`

spec.html
Per previous discussion, use prose instead of an algorithm since the initialization is of a spec mechanism and has no meaningful, observable ordering.
=> Normative: spell out initialization of agent clusters' candidate execution

spec.html
This slot was added by me to the async function proposal, assuming the Function.prototype.toString rewrite would land first. I'm removing these unused internal slot assignments from the main spec text and will be adding them back in #697 once this is merged. In the process, I've renumbered the lists for easier diffing since they were misnumbered to begin with.
=> remove mentions of unused [[SourceText]] internal slot; renumber lists

spec.html
Specifically, change 19 occurrences of
```
the [[Foo]] internal method of _O_
```
and 2 of
```
_O_'s [[Foo]] internal method
```
to
```
_O_.[[Foo]]
```
and 2 occurrences of
```
calling the [[Get]] internal method of _obj_ with argument _j_
```
to
```
calling _obj_.[[Get]](_j_)
```
(Split off from #591.)
=> Editorial: use dot notation for internal methods

spec.html
The meaning of `export * from <module-specifier>` is to signal that additionally to the local exports, any additional export present in that `<module-specifier>` should also be exported. Which means that the following graph should be valid:
```js
// main.js: entry point
export * from "A";
// A.js
export * from "B";
// B.js
export * from "A";
```
Developers can start with some boilerplates, and then fill the blanks on each module in that graph, and this progression is sounded. E.g.: Add `export const a = 1;` to `B.js`, and the graph should remain valid, but now with one exported name for Main, A, and B.
In the spec, there are two mechanisms to deal with circularity:
* `ResolveExport( exportName, resolveSet, exportStarSet )`
* `GetExportedNames( exportStarSet )`
`GetExportedNames` works …
=> fixes #708: removing ResolveExport's exportStarSet in favor of allowing circular valid dependencies

spec.html
=> Read `lastIndex` property before processing flags in RegExpBuiltinExec

spec.html
This is an integration error. The Access Atomicity section was an informative section in the SAB spec draft.
=> Editorial: remove stale reference to the Access Atomicity section.

spec.html
See discussion in https://github.com/tc39/ecmascript_sharedmem/issues/131.
The formalish language in the informative note for the IsLockFree fields of the Agent Record comes from a concurrency textbook.  It seems the sentence adds heat but no light, so let's remove it, leaving just the informal (but intuitive) language in place.
=> Remove odd language for IsLockFree

spec.html
=> Normative: use ToIndex instead of ToInteger in ValidateAtomicAccess

spec.html
This was previously disallowed because users could add a custom return() method for enumeration iterators, cf. https://bugs.ecmascript.org/show_bug.cgi?id=3031.
Split from #775.
=> Allow tail-calls in for-in loops

spec.html
SortCompare is an internal abstract operation, so it cannot be used as the comparator function argument for `Array.prototype.sort`.
=> Use the default sort function when calling Array.prototype.sort to sort the exported names of a module

spec.html
SetImmutablePrototype is meant for use by a variety of objects beyond the ECMA-262 spec. Some of those objects do not have a [[Prototype]], or have a [[Prototype]] but use custom [[GetPrototypeOf]] logic to act is they don't sometimes. (Respectively: HTML's WindowProxy and Location objects.) As such, SetImmutablePrototype should look up the prototype using [[GetPrototypeOf]] instead of trying to look at the possibly-nonexistant [[Prototype]] slot directly.
Some background:
* https://github.com/w3c/web-platform-tests/pull/5015#issuecomment-284802893
* https://github.com/whatwg/html/pull/2400
/cc @annevk @littledan.
This should have no normative impact on ECMA262 since Object's [[GetPrototypeOf]\]() just returns [[Prototype]]. It makes https://github.com/whatwg/html/pull/2400 work correctly …
=> Layering: change SetImmutablePrototype to use [[GetPrototypeOf]]

spec.html
This clarifies that `await` can sometimes be given the semantics of an identifier rather than unconditionally being parsed as a keyword.
Edit: I just noticed https://github.com/tc39/ecma262/pull/818, which also addresses this.
=> Editorial: clarify parsing semantics for `await` tokens

spec.html
_srcByteLength_ is the same value as _byteLength_, so we can use the latter instead of getting [[ByteLength]] from the input typed array.
=> Use already computed byteLength instead of getting [[ByteLength]] slot

spec.html
ToIndex always returns a Number >= 0, so remove the check in
ValidateAtomicAccess for the > 0 case.
=> Editorial: Remove range check for unreachable case

spec.html
A module namespace exotic object has an own Symbol.toStringTag property, which
is non-configurable.  This patch changes [[Delete]] to return false rather than
true for this property, thus making its behavior consistent with other own
properties of the object.
See also: #747
=> Make [[Delete]] on module namespace return false for @@toStringTag.

spec.html
Previously, TypedArray.prototype.fill failed to coerce its value
argument multiple in the beginning of the definition, instead coercing
it when writing into the TypedArray each time. This patch tweaks
the definition to perform the coercion once.
Fixes #855
=> Normative: Ensure that TypedArray.prototype.fill does one coercion

spec.html
In RegExp.prototype[Symbol.replace] as applied to RegExps, if a
substitution string is used with a numerical group reference which
is out of bounds, the behavior was previously implementation-defined.
This patch changes the behavior to not do a replacement.
Testing with eshost showed that V8, SpiderMonkey, JSC and ChakraCore
all agree on these semantics.
=> Normative: Specify String.prototype.replace edge case

spec.html
Previously, in one of the TypedArray constructor paths, an ArrayBuffer
was checked for being detached, and then a ToIndex calculation is done.
Because ToIndex may detach the ArrayBuffer itself, this patch moves
the detached check to afterwards, so that it can include that possible
time when the ArrayBuffer may be detached.
Closes #842
=> Normative: Swap side effect and check in TypedArray constructor

spec.html
Number.prototype.toFixed, toExponential and toPrecision previously
permitted a second argument, with implementation-defined behavior.
This language dates back to the original specification in ES3.
However, in testing with eshost and looking at the sources of V8,
SpiderMonkey, JSC and ChakraCore, I cannot find a usage of this
second argument.
This patch removes the implementation-defined behavior clause to
simplify spec reading and reduce a potential point of variability
and confusion among new implementations.
=> Normative: Remove implementation-defined behavior for Number methods

spec.html
Changed the typology of the note about Async Expression (" [...] when the Await parameter in present. " to " [...] when the Await parameter is present. ")
=> Fix typology in the spec at async expressions

spec.html
FunctionDeclarationInstantion may return an abrupt completion, and the
following lines handle that abrupt competion, so there should be no !.
=> Editorial: Remove stray ! from async function spec

spec.html
This makes it easier to disallow invalid `\k` escapes for https://tc39.github.io/proposal-regexp-named-groups/#annex-b-grammar and also disallows `/\/` 😰 .
cc @littledan
=> Only allow standalone reserve solidus in Annex B regular expression when immediately followed by `c`

spec.html
Renames variable to drop "is" prefix, because its value is not of boolean type. New name is taken from step *2a* of [`String.prototype.match`](https://tc39.github.io/ecma262/#sec-string.prototype.match).
EDIT: also, new name improves search results for `isregexp`.
=> Editorial: isRegExp => matcher

spec.html
Originally proposed (among many other commits) as part of #821, but there was some [discussion](https://github.com/tc39/ecma262/pull/821#discussion_r107032095) as to its validity.
To me, the before and after versions say the same thing. Whether they say what they're *supposed* to say is another question (above my pay grade).
=> Editorial: simplify 2 'Repeat' steps

spec.html
Originally proposed (among many other commits) in #821, but @bterlson [asked](https://github.com/tc39/ecma262/pull/821#discussion_r107040459) for it to come back as a separate PR.
=> Editorial: separate clauses for Reference abstract ops

spec.html
The definition says single-equal, but the uses say double-equal.
Change the uses to match the definition.
=> Editorial: positive lookahead-restriction: use single-equal

spec.html
"declarations collective define only one variable" -> "declarations collectively define only one variable"
=> collective -> collectively

spec.html
Implementations seem to agree on semantics here for the most
part, modulo timezone strings, which are left implementation-defined.
Addresses part of #845
=> Normative: Specify Date string conversion functions

spec.html
`await` was removed as FutureReservedWord from [11.6.2.2](https://tc39.github.io/ecma262/#sec-future-reserved-words) in aec498db94dedbf31a930c6b09c2ae939d21890f but wasn't removed from [A.1](https://tc39.github.io/ecma262/#sec-lexical-grammar)
See #818 and #846 for context
Fixes #922
=> Editorial: remove `await` from FutureReservedWords in A.1.

spec.html
Previously, @jswalden found that ASI would depend on whether the
[Yield] and [Await] flags were set. This minor change prohibits
yield and await as BindingIdentifiers based on static semantics
rules, rather than grammar parameters, in order to make ASI
invariant between the two flags.
Inspired by https://github.com/tc39/test262/pull/956
=> Normative: Prohibit ASI between 'let' and 'yield'/'await'

spec.html
This requires implementations throw a `TypeError` when the compare function is neither undefined nor a function, which is currently vaguely implied but not explicitly required.
This reflects web reality in that every engine except v8 already throws in this case. (Safari does not, but Safari TP and webkit latest do)
eshost output of `[1, 2].sort(true)`:
```
┌─────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────┐
│ chakra              │                                                                                             │
│ chakra-es6          │ TypeError: Array.prototype.sort: argument is not a JavaScript object                        │
│ chakra-experimental │ …
```
=> Normative: `Array.prototype.sort`: comparefn must be fn or undefined

spec.html
Previously, the specification for Number.prototype.toFixed, Number
gave a fixed range for the fractionDigits parameter, but allowed
implementations to permit a larger range. Historically, only
SpiderMonkey accepted a larger range, and other implementations
threw a RangeError outside the range.
This patch specifies the SpiderMonkey behavior. The range checks
always permitted more decimal digits to be printed than what is
provided by the accuracy, so the limits are arbitrary. Waldemar
Horwat has mentioned that SpiderMonkey's higher limits have
been useful for him in explaining floating point numbers to
others.
An alternative would be to retain the previous limits and remove
the implementation-dependent aspects. Either way, locking down
this detail should help developers get consistent …
=> Normative: Define particular precision for toFixed and friends

spec.html
This patch specifies a previously unspecified piece of RegExp
syntax and semantics: If a character class has a control escape
(\c) which is not followed by an extended control character
[a-ZA-Z0-9_], then four engines will accept it as syntactically
valid. V8, JSC and SpiderMonkey will treat it as the character
class [\\c]; ChakraCore's behavior differs and depends on what
follows.
This patch codifies the majority behavior within the Annex B
RegExp extensions. This change is consistent with malformed \c
behavior when it takes place outside of a character class: It
behaves like \\c, rather than an identity escape.
Closes #863
Thanks @schuay for raising this issue and @anba for already specifying all the other surrounding cases I came across.
=> Normative: Specify RegExp malformed character class behavior

spec.html
JSC and V8 have been shipping the version of the specification
included in this patch, so it is likely to be web-compatible.
Throwing on receivers which are not Date instances is simpler
and more consistent with other methods in ECMAScript.
Closes #849
=> Normative: Date.prototype.toString throws on non-Date receiver

spec.html
Dear Ecma-262 team,
I have noticed the following simple omission in the specification. The first axiom of the strict total order does not work when a = b. I have applied the necessary change. Please, let me know what other steps are necessary for this change to be applied. As this is a trivial change, I do not think it is necessary to pass any copyrights, but I am very happy to do so.
Yours faithfully,
Mateusz Grotek
For and on behalf of IdeaPiece Ltd.
=> Correct an axiom of strict total order

spec.html
The spec currently refers to an "extrapolated Gregorian system",
but the term "proleptic Gregorian calendar" is more precise and is
the terminology used elsewhere in other standards and languages.
(e.g. ISO 8601:2004 3.2.1 "The use of this calendar for dates
preceding the introduction of the Gregorian calendar (also called
the proleptic Gregorian calendar) should only be by agreement of
the partners in information exchange.")
=> Editorial: Refer to proleptic Gregorian calendar.

spec.html
I just noticed that @anba added the "do" language for the "For each" lines in the memory model relations back in February.
I'd like to revert the "do", because the "algorithm" is describing conditions that must be satisfied on relations, not steps to be performed. It reads really odd to me that these conditions have a "do".
I'm open to other editorial suggestions to further clarify that these are really descriptions of relations, not algorithms.
=> Editorial: Remove "do" language from memory model relations

spec.html
Previously, String.prototype.toUpperCase and
String.prototype.toLowerCase were specified with wording indicating
that Unicode case conversion was to be used, but code points should
be looked up one by one. The Unicode Default Case Conversion algorithm
is context-dependent, and a note alludes to this, but the normative
text seems to prohibit using the context. However, JSC, V8 and
ChakraCore do seem to pay attention to this context, at least when
it comes to final sigma.
This patch clarifies the spec text to make an explicit reference
to the Default Case Conversion algorithm.
These semantics are already tested by @anba's test262 test https://github.com/tc39/test262/blob/master/test/built-ins/String/prototype/toLowerCase/special_casing_conditional.js
=> Normative: Clarify that case conversion is context-sensitve

spec.html
There were 4 occurrences of "was provided" and 14 occurrences of "was supplied", so I went with the latter.
Unfortunately, there's still 23 occurrences of "is provided" and 13 occurrences of "is supplied". 😕 Not sure what to do there.
=> consistently use "is present" over "was supplied", "was provided", and other alternatives

spec.html
Proxy [[OwnPropertyKeys]] now throws if the trap returns an array with duplicate entries and reverts a few of the changes made to handle duplicate property keys in a few places. See also discussion in #461. I believe this is needs-consensus, though I haven't heard arguments against this.
/cc @anba
=> Normative: Throw TypeError if proxy [[OwnPropertyKeys]] returns duplicate entries

spec.html
Closes #668. Still not convinced we want this in 262 but here it is so we can discuss!
=> Implement undefined-like exotic objects

spec.html
In the AsyncFunctionDeclaration production, FormalParameters were parameterized
with [?Await] instead of [+Await]. According to the note below, the intention
was [+Await].
This also makes AsyncFunctionDeclaration consistent with AsyncFunctionExpression
in this regard.
=> Normative: Fix [?Await] in async function FormalParameters (#978)

spec.html
A link to *function object* is needed by WebIDL (in particular by https://github.com/heycam/webidl/pull/405).
Additionally, it would be useful to link to *constructor* from various parts of the spec, notably from the introductory paragraphs to [interface objects](https://heycam.github.io/webidl/#interface-object): 
> If the interface is declared with a [Constructor] extended attribute, then the interface object can be called as a _constructor_ […]
This PR adds both.
=> Meta: Add DFNs for function object and constructor

spec.html
"shadowed by a global lexically binding" --> "shadowed by a global lexical binding"
=> Editorial: fix typo in HasRestrictedGlobalProperty description

spec.html
Reduce variations with respect to Strings and code units.
Introduce the term "reparsing".
=> Misc Editorial

spec.html
This allows us to remove the code path in CloneArrayBuffer when the _cloneConstructor_ argument is absent and simplifies the TypedArray constructor algorithm a bit. 
I didn't remove the extra `IsDetachedBuffer(_srcData_)` step for the same element case to avoid introducing a semantic change, but I think we should either remove this extra check or apply it for both cases.
=> Call SpeciesConstructor in TypedArray constructor to reduce indirections

spec.html
This sentence has been around for some time and is no longer accurate.
PerformEval can create an execution context with initially different
LexicalEnvironment and VariableEnvironment components.
Closes #980.
=> Editorial: Remove out-of-date sentence about execution contexts

spec.html
When reading through [`Symbol.prototype`](https://tc39.github.io/ecma262/#sec-properties-of-the-symbol-prototype-object) methods, it takes a bit of concentration to see common steps. This PR relieves that and aligns `thisSymbolValue` with [`thisStringValue`](https://tc39.github.io/ecma262/#sec-thisstringvalue), [`thisNumberValue`](https://tc39.github.io/ecma262/#sec-thisnumbervalue), and [`thisBooleanValue`](https://tc39.github.io/ecma262/#sec-thisbooleanvalue).
=> Editorial: Extract thisSymbolValue abstract op

spec.html
Benefits: brevity, expressiveness, and consistency with other *constructor* checks.
With this change I was able to see all `IsConstructor` calls in references and make a [JS implementation](https://github.com/shvaikalesh/is-constructor/blob/master/index.js).
=> Editorial: Use IsConstructor instead of checking [[Constructor]]

spec.html
Clarifying that conversion to a number from comparefn should occur before the detachment check. This ambiguity led to this security problem: https://bugs.chromium.org/p/project-zero/issues/detail?id=983
=> Adding explicit number conversion to %TypedArray%.prototype.sort

spec.html
=> Add %JSONParse% for Fetch et al

spec.html
unicode.org is now available over HTTPS. Let’s make use of it.
=> Editorial: Use HTTPS for unicode.org URLs

spec.html
dc370115a779e34ec2998f46de6c87581152c215:
`reservedSet` contains only ASCII characters, so we don't need to check for `reservedSet` when decoding an escaped character. Passing a decoded ASCII character throws a URIError because of the checks in 4.d.vii.2 and 4.d.vii.8. Also see the note below Decode:
> RFC 3629 prohibits the decoding of invalid UTF-8 octet sequences. For example, the invalid sequence C0 80 must not decode into the code unit 0x0000. Implementations of the Decode algorithm are required to throw a URIError when encountering such invalid sequences.
c2b368efe45bbc51cc7ba4a81210299e8443beb3:
Replaces the non-defined term `array` with `List` and simplifies a loop to use list iteration.
=> Decode doesn't need to check the reserved-set for non-ASCII characters

spec.html
This is a continuation of #988.
=> Fix next method

spec.html
=> Early errors for RegExp literals

spec.html
Please check that I made the correct fix in the first commit.
=> Misc Editorial re recent commits

CONTRIBUTING.md
This patch documents how to contribute to TC39 in a bit more detail,
explaining in terms of how things work today. It does not overlap
with the process document, but instead describes how things work
surrounding that, and provides practical suggestions for getting
involved. Phrasing is changed to include not just non-members but
also Ecma members, who may need this documentation as well. This
document also does not describe how to make a proposal repository,
which will be left to be documented elsewhere (possibly eventually
cross-referenced from here).
I'm not sure if CONTRIBUTING.md is the right place for this content. If you think it's inappropriate, do you have another idea of where it should go? The process document? A personal blog post?
I made this PR since I just went to JSKongress …
=> Meta: Expand CONTRIBUTING.md

spec.html
Note: the other instance of _month_ before _day_ (in #sec-datestring) is correct w.r.t. web reality (4/4).
See the test case below for the web reality (4/4 engines) output for all 4 `Date.prototype.to*String()` method outputs:
print(new Date('2008-10-13T05:16:33Z').toUTCString());
print(new Date('2008-10-13T05:16:33Z').toString());
print(new Date('2008-10-13T05:16:33Z').toDateString());
print(new Date('2008-10-13T05:16:33Z').toTimeString());
Mon, 13 Oct 2008 05:16:33 GMT
Sun Oct 12 2008 22:16:33 GMT-0700 (Pacific Daylight Time)
Sun Oct 12 2008
22:16:33 GMT-0700 (Pacific Daylight Time)
See discussion at https://github.com/Microsoft/ChakraCore/pull/4067#issuecomment-345651062
=> Normative: Web Reality (4/4 engines): _day_ before _month_ in Date.prototype.toUTCString

spec.html
Thus I think this statement is contradictory with the previous bullet. @allenwb, @jmdyck noticed [old bug 1075](https://bugs.ecmascript.org/show_bug.cgi?id=1075) seems relevant, but presumably this is not needed anymore.
=> Normative: built-in functions are not allowed to have caller/arguments properties

spec.html
Proposal repo: https://github.com/tc39/proposal-regexp-dotall-flag
=> [Normative] Add RegExp `dotAll` mode (`s` flag)

spec.html
@littledan asked me to prepare the PR for his proposal adding named capture groups to ECMAScript regular expressions.
Proposal repo: https://github.com/tc39/proposal-regexp-named-groups
@littledan, I’ve added you as the commit author.
=> [Normative] Add RegExp named capture groups

spec.html
Add `Promise.prototype.finally` to ECMAScript.
Closes https://github.com/tc39/proposal-promise-finally/issues/18.
=> Normative: Add Promise.prototype.finally

spec.html
@littledan asked me to prepare the PR for the proposal adding lookbehind assertions to ECMAScript regular expressions.
Proposal repo: https://github.com/tc39/proposal-regexp-lookbehind by Gorkem Yakin, Nozomu Katō, and @littledan.
@littledan, I’ve added you as the commit author — I hope I’m not misrepresenting you :)
=> [Normative] Add RegExp lookbehind assertions

spec.html
Fixes #1078
cc @anba
Technically this might be a normative bugfix?
(I also fixed the whitespace on the CatchFinally emu-clause)
=> Normative: add explicit "length" property info for ThenFinally/CatchFinally

spec.html
Read painfully literally, the conditions of synchronizes-with are mutually incompatible, or at least ungrammatical.
https://tc39.github.io/ecma262/#sec-synchronizes-with
The phrasing of these conditions seems to come, at least partially, from an earlier draft, where synchronizes-with was computed in a more algorithmic way.
https://tc39.github.io/ecmascript_sharedmem/shmem.html#MemoryModel.SynchronizesWith
The switch to the non-algorithmic definition with the phrasing "if all the following are true"  in the preamble means that the conditions must be rephrased.
=> Editorial: fix grammar of synchronizes-with conditions

spec.html
Proposal repo: https://github.com/tc39/proposal-object-rest-spread/
=> [Normative] Add Object Rest Spread

spec.html
To address #1030
This is my first pull request to the spec, please let me know if I'm doing it wrong.
=> Normative: provide default prototype and realm values for CreateBuiltinFunction

spec.html
This supersedes @zbraniecki's #1063. The individual commits are just to show the delta from that.
One potential question for the editor is the ordering of sections within 25 (Control Abstraction Objects). I went with
- Iteration
- GeneratorFunction Objects
- **AsyncGeneratorFunction Objects**
- Generator Objects
- **AsyncGenerator Objects**
- Promise Objects
- AsyncFunction Objects
but I can also see an argument for keeping the two new sections together, perhaps even after the AsyncFunction Objects section.
(Closes #1063)
=> Normative: add async iteration

package.json
https://tc39.github.io/ecma262/2018/ is missing styles and search is not working due to missing resources.
@bterlson we have encountered this very same issue during the 402 release. this fix seems to do the trick for me.
=> release-fix: 2018 is missing the js and css files from the build

package.json, spec.html
=> Editorial: rename EnumerableOwnProperties to EnumerableOwnPropertyNames

spec.html
Using the record notation for creating a thrown TypeError completion is super awkward; this new abstract operation makes it read much more clearly for me.
Thoughts?
=> Editorial: create a ThrowCompletion abstract operation to reduce boilerplate

spec.html
This PR fixes an oversight.
[12.2.8.1 Static Semantics: Early Errors](https://www.ecma-international.org/ecma-262/8.0/#sec-primary-expression-regular-expression-literals-static-semantics-early-errors) disallows `s` flag currently. But it should allow `s` flag since #1028.
=> Normative: FlagText allows s

spec.html
This patch gives ArrayBuffers an "owner" internal slot. This slot is
used to throw a TypeError on inappropriate DetachArrayBuffer calls.
WebAssembly needs it to be an error to detach an ArrayBuffer (e.g.,
through postMessage) for ArrayBuffers which come from
WebAssembly.Memory objects. It should only be the Memory grow
operation which ever detaches this ArrayBuffer.
Corresponding WebAssembly patch: https://github.com/WebAssembly/spec/pull/712
Closes #1024
=> Layering: Check for the correct owner in DetachArrayBuffer

spec.html
Fixes #1140.
This appears to have been a copy-paste artifact from adding async generators.
Most of the existing ones have "async-generator", very few have "asyncgenerator", so I went with the (nicer) hyphenated variant.
=> Editorial: fix section IDs for some async generator sections.

spec.html
This PR adds the syntax of RegExp Lookbehind Assertions into B.1.4 Regular Expressions Patterns section.
Since #1029 didn't look to update the Annex-B section but I think it's needed (https://github.com/tc39/ecma262/pull/1029#issuecomment-364003143).
I apologize if it's intentional.
=> Normative: add RegExp lookbehind to annex-B

spec.html
That is, an object with a [[Construct]] internal method must have a [[Call]] internal method.
Previously, this was assumed but not explicitly stated.
See https://stackoverflow.com/questions/50109554/
=> Editorial: clarify that [[Construct]] implies [[Call]]

spec.html
[Note that, currently, the first 8 commits listed for this PR actually belong to PR #1122. If/when that's merged, I think they'll disappear from here.]
For many intrinsics (the constructors, the prototype objects, and a few others), there are blocks of text that specify (what I'm calling here) their 'characteristics'. (Elsewhere I'd say 'properties', but in ES that word is already taken.) This PR converts each of those blocks from paragraphs to a bulleted list.
Mainly, I think the result is more readable (both by humans and software). Implementers and testers can (more easily) treat it as a checklist of items to implement and test.
The commit could be merged as is. However, there are variations/extensions that you might like to consider/discuss/request.
(1)
Grammatically speaking, each …
=> Editorial: use <ul> to list characteristics of intrinsics

spec.html
`ToString` on a guaranteed Number just calls into `NumberToString`, so let's remove a conceptual stack frame from this recursion.
=> Editorial: reduce indirection in NumberToString

spec.html
Resolves #1201.
Follows from:
[§17](https://tc39.github.io/ecma262/#sec-ecmascript-standard-built-in-objects):
> Unless specified otherwise, the [[Extensible]] internal slot of a built-in object initially has the value **true**.
[§9.1](https://tc39.github.io/ecma262/#sec-ordinary-object-internal-methods-and-internal-slots):
> Once the value of an object's [[Extensible]] internal slot has been set to **false** it may not be subsequently changed to **true**.
=> Editorial: Don't explicitly set [[Extensible]] to true

spec.html
All the other getter/setter methods default `littleEndian` to `false`
when it is not present.
This doesn't affect the overall algorithm.
=> Editorial: Default littleEndian to false in DataView.p.getInt32

spec.html
As all the other consecutive tokens are explicitly separated into own literals, it seems beneficial to separate `let [` as well for clarity (that it doesn't special-case exact literal sequence, but like all others, matches consecutive tokens).
=> Editorial: separate `let [` into two tokens

spec.html
As requested by @ljharb: https://github.com/tc39/proposal-well-formed-stringify/issues/6#issuecomment-394888970
* Introduce UnicodeEscape for QuoteJSONString.
* Use similar language for all fixed-length (hexa)decimal conversions.
* Specify all JSON single-character escapes via table.
=> Editorial: Refactor QuoteJSONString (and propagate improvements)

spec.html
Reverts #1212 and addresses #1201 properly.
[§17](https://tc39.github.io/ecma262/#sec-ecmascript-standard-built-in-objects) gives `[[Extensible]]` a default value of `true` for built-ins. This has no impact on §9 but rather implies that we should remove the superfluous initializations in §18-25.
=>  Editorial: Built-ins needn't initialize [[Extensible]] to true

.gitignore
Add package-lock.json to the gitignore file because we do not commit it
anyway.
=> Meta: add package-lock.json to gitignore

spec.html
Since these comments don't actually get converted into anchors, they serve no purpose. Let's get rid of them.
=> Editorial: remove useless es6num comments

spec.html
Fix a typo in Section 6.4.2, which concerns the Reference Specification
Type in the definition for a "Super Reference".
represents => represent
Fixes: https://github.com/tc39/ecma262/issues/1229
=> Editorial: fix typo in Section 6.4.2

spec.html
Remove the unused variable (named `succeeded`) in Steps 16.c.iii-iv. in
Section 9.4.2.4, which describes the abstract operation ArraySetLength.
Fixes: https://github.com/tc39/ecma262/issues/1230
=> Editorial: remove unused variables in ArraySetLength

spec.html
Extract common steps from the following clauses:
25.1.4.2.1 %AsyncFromSyncIteratorPrototype%.next
25.1.4.2.2 %AsyncFromSyncIteratorPrototype%.return
25.1.4.2.3 %AsyncFromSyncIteratorPrototype%.throw
into new primitive AsyncFromSyncIteratorContinuation.
=> Editorial: Simplify %AsyncFromSyncIteratorPrototype% methods

spec.html
Issue tracked here:  https://github.com/tc39/ecma262/issues/1130
This PR attempts to specify that the runtime semantics for **DestructuringAssignmentEvaluation (12.14.5.2)** should perform `RequireObjectCoercible(value)` as the first step, since assignment to `null` throws a TypeError as specified in [this test assertion](https://github.com/tc39/test262/blob/master/test/language/expressions/assignment/dstr-obj-rest-val-null.js).
Thank you.
=> Normative: specify RequireObjectCoercible as first step in destructuring assignment semantics

spec.html
This implements https://github.com/tc39/proposal-json-superset , currently at stage 3.
=> Extend ECMA-262 syntax into a superset of JSON

spec.html
Fixes https://github.com/tc39/ecma262/issues/1175 by moving the `getThisBinding()` before evaluating the computed property expression.
=> Evaluate this binding first in SuperProperty

spec.html
This consolidates some of the logic in the Map and WeakMap constructors, and also creates a convenient operation for https://github.com/tc39/proposal-object-from-entries/issues/11.
=> Editorial: create addIterableFromEntries abstract operation

spec.html
Fixes https://bugs.ecmascript.org/show_bug.cgi?id=4375
Closes #1267.
=> Restore early SyntaxError for strict mode assignment to eval/arguments

spec.html
Implementations are not currently consistently limiting *time values* to the spec defined ranges of both *time value* and *extended years*.
This change is editorial cleanup that more clearly states the allowed *time value* range and the supported range of *extended years* that fit within the allowed *time value* range.
Implementations will need to be updated to conform with the spec (SM currently adheres) and pass the accompanying test in tc39/test262#1501.
**Concrete examples of what will be fixed are detailed in #1145.**
Time Values and Time Range:
- Language about `Number` range in hundreds-of-thousands of years plus/minus UTC epoch is not immediately relevant; move it to an `emu-note`
- New `emu-note` text fixes inconsistency in spec where this section was not properly accounting for …
=> Normative: Cleanup Time Values and Time Range

spec.html
Adds %JSONStringify% intrinsic object per https://mail.mozilla.org/pipermail/es-discuss/2018-March/050325.html
See also #1105 
See also: https://github.com/whatwg/infra/pull/207, https://github.com/w3c/webauthn/issues/712
[note: my affiliation is [PayPal, an ECMA Ordinary Member](https://www.ecma-international.org/memento/ordinary.htm)]
=> Editorial: Add %JSONStringify% intrinsic object

spec.html
=> Renames Atomics.wake => Atomics.notify

spec.html
Date.prototype.toString is not generic.
Fixes #1268
I've essentially copy-pasted the corresponding note in Number.prototype.toString.
=> Date.prototype.toString is not generic

spec.html
- `enum` was changed to `enumerable` because `enum` is a terrible thing to name a variable. (also changed `conf` to keep consistent)
- `Type` parameter changed to `type` because shadowing abstract op names is not fun
=> Editorial: fix a few variable names

spec.html
Fixes #694.
I followed @domenic's steps in the linked issue here; I'm not sure if other changes are needed.
Specifically, which `PerformPromiseThen` calls should now be able to omit a capability?
=> Editorial: refactor PerformPromiseThen to allow no capability

spec.html
No other abstract operation calls use that phrase. In fact even the immediate next line doesn't.
=> Editorial: Remove some extraneous "result of performing"

spec.html
It seems like all other cases of `"Let X be the result of evaluation SomeGrammar."` that actually use the value are followed by a call to `GetValue`, but this one is missing. I was talking through the spec with someone on StackOverflow and they noted that it was missing, and thing I realized #934 had been filed, so a PR seemed like the best next step to get the conversation going.
Fixes #934.
=> Normative: Use GetValue to evaluate class heritage.

spec.html
See issue #1119 for background on the current behaviour.
This proposal strengthens the synchronization between a waking thread and its wakees as though they were each a coinciding atomic write/read (respectively) to the same memory location, in line with some previous comments by @lars-t-hansen on the informal language of an earlier draft of the memory model proposal.
Since each waker/wakee pair is determined purely operationally, there is no need to struggle to reassociate the events from scratch in the axiomatic semantics (a la the ReadsBytesFrom relation for Shared Data Block events). Instead, each agent tracks which waking events it is responsible for in a new [[AgentSynchronizesWith]] field of its Events Record, which is then unified with the global synchronizes-with relation.
I …
=> Normative: Strengthen Atomics.wait/notify synchronization to the level of other Atomics operations

spec.html
As currently spec'd, it is an undefined behavior when an *Expression* that evaluates to a Reference is present in a *TemplateLiteral*, as the Reference value would be directly passed into ToString which expects an ECMAScript language value.
Fixes #935.
----
Quite similar to #1286.
=> Normative: Add missing GetValue() to TemplateLiteral evaluation

spec.html, table-binary-unicode-properties.html, table-unicode-script-values.html
https://unicode.org/versions/Unicode11.0.0/
=> Update Unicode property lists per Unicode v11

spec.html
All engines except Chakra agree on the following behavior:
$ eshost -e 'x = new String(); x[2**32-2] = 1; x[2**32-1] = 1; x[2**53-1] = 1; x[2**53] = 1; Reflect.ownKeys(x)'
4294967294,4294967295,9007199254740991,9007199254740992,length
4294967294,length,4294967295,9007199254740991,9007199254740992
4294967294,length,4294967295,9007199254740991,9007199254740992
4294967294,length,4294967295,9007199254740991,9007199254740992
4294967294,length,4294967295,9007199254740991,9007199254740992
That is, they use array indices instead of integer indices in `[[OwnPropertyKeys]]()` for String exotic objects.
This patch makes the spec match the reality of the majority of implementations.
=> Normative: Fix [[OwnPropertyKeys]]() for String exotic objects

spec.html
All major JavaScript engines agree on the following behavior:
$ eshost -e 'Reflect.ownKeys({ a: 1, [Number.MAX_SAFE_INTEGER]: 1, 42: 1, [2**32-1]: 1, [2**32-2]: 1 })'
42,4294967294,a,9007199254740991,4294967295
42,4294967294,a,9007199254740991,4294967295
42,4294967294,a,9007199254740991,4294967295
42,4294967294,a,9007199254740991,4294967295
42,4294967294,a,9007199254740991,4294967295
That is, the order is:
- array indices, in ascending numeric index order
- strings that are not array indices, in ascending chronological creation order
- symbols, in ascending chronological creation order
This patch makes the spec for `OrdinaryOwnPropertyKeys` match Web reality.
=> Normative: Use array indices instead of integer indices in OrdinaryOwnPropertyKeys

spec.html
According to [grammarkdown reference](https://github.com/rbuckton/grammarkdown#assertions), prose assertions referencing a non-terminal should fence the non-terminal reference with `|` chars.
=> Editorial: Fence non-terminal token for NotCodePoint/CodePoint.

spec.html
- Previously did not account for any obvious mention of non-string return value.
Fixes #1344.
=> Update abstract line of JSON.stringify section

package.json
A bug in grammarkdown (which is fixed in master and not yet released)
causes a newline after an html entity to get consumed, making
alternatives run together and look like a seqence of symbols.
This commit works around the bug by adding a trailing space after html
entities in grammar productions.
See https://github.com/rbuckton/grammarkdown/pull/29 for the proper fix
which has yet to be released.
=> Editorial: Fix formatting of grammar productions ending in html entities

spec.html
Prior to this commit there has always been an implicit "Return." step, after the previous step in Await "sucks up" all the remaining steps in the caller. This is visible in places such as AsyncFunctionStart, which asserts that Await returns "a normal completion with a value of **undefined**," due to the fact that a "return" without value implicitly returns **undefined**.
Left implicit, the implicit "return" behavior is at best counterintuitive and at worst misleading (on top of something as abstruse as execution context suspension), for implementors such as myself. In this commit, I took the step of making the return explicit. Alternatively, I could keep the "return" implicit, but add a textual note explaining that Await in fact returns an **undefined** value, independent of any returns …
=> Editorial: Add explicit Return to Await

spec.html
…because they never return an abrupt completion from that particular code path.
This came up this morning while chatting with @bmeurer and @gsathya. 
https://tc39.github.io/ecma262/#sec-object-initializer-runtime-semantics-propertydefinitionevaluation
=> Editorial: add ‘!’ to CreateDataPropertyOrThrow calls in PropertyDefinitionEvaluation

spec.html
All major JavaScript engines now have a stable `Array.prototype.sort` implementation. Let’s update the spec accordingly.
References:
- https://v8.dev/blog/array-sort
- https://github.com/Microsoft/ChakraCore/commit/c565b12f0aada9fc188cea5eb5243699d27c56e6
- https://github.com/Moddable-OpenSource/moddable/commit/d3ee129350f6ae0043319b06c56b9828e8e256a6
- https://mathiasbynens.be/demo/sort-stability
- [September 2018 TC39 meeting presentation](https://docs.google.com/presentation/d/1mHvxDciqsAchhjepMZlU5fn1DBvglCXSjDWUEtsPGvI/edit)
- [November 2018 TC39 meeting presentation](https://docs.google.com/presentation/d/1Io53b2Bi3_N0_wguWoA9OKuPRpHch34EVbS1H8zISes/edit)
=> [Normative] Make Array.prototype.sort stable

spec.html
SetFunctionName is currently called after ClassDefinitionEvaluation, which means the class name is not available in static class field initializers (https://github.com/tc39/proposal-class-fields/issues/85) and may cause issues for a `@frozen` decorator (https://github.com/tc39/proposal-decorators/issues/168). 
This PR moves the initialization of the "name" property into ClassDefinitionEvaluation, which should avoid both aforementioned issues. I've split this PR into three parts for easier reviewing:
- The first commit 7bb51dd87436dcf655e8cbf1ff2285d3688b28e7 adds calls to a new runtime semantic `NamedEvaluation` to evaluate anonymous function definitions (as identified by `IsAnonymousFunctionDefinition`). 
- 3d752d728202f4c8511df4d9720972e85ddd976f adds the actual definitions for …
=> Add "name" property for classes as part of ClassDefinitionEvaluation

spec.html
=> Normative: Treat IterationStatements uniformly in Annex B.3.5.

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
As a way to alert downstream dependencies as suggested in https://github.com/tc39/ecma262/pull/1101#issuecomment-462481738.
=> Meta: pull request template

spec.html
This integrates the stage 3 [symbol description proposal](https://github.com/tc39/proposal-Symbol-description) in preparation for stage 4.
As of this writing, there are [three compatible browser implementations](https://test262.report/browse/built-ins/Symbol/prototype/description).
=> add Symbol.prototype.description getter

spec.html
This PR adds `Object.fromEntries` to the spec.
It is currently stage 3; and still needs merged test262 tests, and consensus, to reach stage 4 and be merged here.
Closes https://github.com/tc39/proposal-object-from-entries/issues/21.
=> Normative: add `Object.fromEntries`

spec.html
This is a pull request for the **stage 3** proposal https://github.com/tc39/proposal-string-left-right-trim. The proposal is/was championed by @sebmarkbage. 
test262 tests: yes, https://github.com/tc39/test262/commit/5931e313fc1ed6d3eafb1a0be8c30f32cf8d41ac and others
ES5 standardized `String.prototype.trim`. All major engines have also implemented corresponding `trimLeft` and `trimRight` functions - without any standard specification.
For consistency with `padStart`/`padEnd` we propose `trimStart` and `trimEnd` and `trimLeft`/`trimRight` as aliases required for web compatibility.
I wasn't quite sure where to put TrimString, but this follows String.prototype.replace with GetSubstitution by putting it inline.
=> Normative: Add String.prototype.{trimStart/trimEnd} (+ trimLeft/trimRight)

spec.html
=> Normative: LeftHandSideExpression -> UnaryExpression in Static Semantics: Early Errors

spec.html
This implements https://github.com/tc39/proposal-well-formed-stringify , currently at stage 3. [Tests](https://github.com/tc39/test262/pull/1787) have already been merged.
Fixes #944
=> Normative: Prevent JSON.stringify from returning ill-formed Unicode strings

spec.html
Implements the currently stage 3 proposal at https://github.com/tc39/Function-prototype-toString-revision. This PR is part of the new stage 4 entrance criteria.
Fixes #664.
=> Normative: make Function.prototype.toString forward-compatible and fully defined

spec.html
Currently, only Source Text Module Records (STMR) can participate in cycles. From my conversations with those who put that limitation in the spec, this restriction was only added because there wasn't an immediate need for cyclic dependencies with non-STMR modules. 
This PR makes it possible for other languages to add module record types that can participate in cycles with Source Text Module Records. To do this, it moves the logic for managing cycles to a new module type, Cyclic Module Record (CMR). STMR are a subclass of the CMR, and other specs such as WebAssembly can also subclass this module record type.
To help with review, I've broken this into smaller commits, but can squash them before merge if that is preferred.
Note: This is an update to #1199. In this version, I removed the …
=> Layering: Enable cyclic dependencies with non-STMR module types

spec.html
JavaScript programmers may expect that the following
two programs are largely similar in terms of how they perform with
respect to the ECMAScript job queue (if inside of an async function):
promise.then(f);                f(await promise);
However, if `promise` is a built-in promise, then these two code fragments
will differ in the number of iterations through the job queue are taken: because
`await` always wraps a Promise with another Promise, there are three job
queue items enqueued and dequeued before calling `f` in the `await` example,
whereas there is just a single item for the `then` usage.
In discussions with JavaScript programmers, the number of job queue items
in the current semantics turns out to be surprising. For example, the difference
has become more visible in conjunction …
=> Normative: Reduce the number of ticks in async/await

spec.html
This PR implements [the stage 3 proposal](https://tc39.github.io/proposal-flatMap/) adding `Array.prototype.flatMap` and `Array.prototype.flat`.
=> add Array.prototype.flatMap and Array.prototype.flat

spec.html
The current indentation mistakenly means that the two constraints are **true** if the *first* event is valid, instead of if *all* events are valid.
=> Fix indentation of the "Valid Chosen Reads" and "Coherent Reads"

spec.html
`environment` will be `undefined` if the formal parameters contain duplicates
=> Editorial: fix assertion in IteratorBindingInitialization

spec.html
As agreed in the referenced issue, made sure `AsyncFromSyncIteratorContinuation` keeps its contract to return rejected promise on abrupt completion.
Fixes #1461.
=> Editorial: Handle abrupt completion in AsyncFromSyncIteratorContinuation

spec.html
* Use ISO 8601 vocabulary
* Move interpretation of absent date time elements into Date.parse
=> Editorial: Update date-time format language

spec.html
To me, this seems like a nice way to DRY up a common operation - asserting that a value is an Object with a given internal slot.
What are your thoughts on this? Is this too much indirection, or does this reduction in spec lines make it easier to read?
It was a pretty quick change, mostly a single regex operation, so I'm happy to close it if we don't think this is an improvement.
=> Editorial: add RequireInternalSlot abstract operation

spec.html
Allows GetExportedNames() to be called without `exportStarSet`, and
for ResolveExport() to be called without `resolveSet`.
=> Editorial: Refactor GetExportedNames() and ResolveExport() calls

spec.html
The name of the standard is properly "IEEE Standard for Floating-Point Arithmetic", not "IEEE Standard for Binary Floating-Point Arithmetic".
Appropriately refer to the binary64 format as "double-precision 64-bit binary format", rather than just "double-precision 64-bit format".
Replace the legacy "round to nearest, ties to even" rounding mode to the modern "roundTiesToEven" rounding direction mode.
=> Editorial: Clarify IEEE 754-2008 terminology

spec.html
- Do not redundantly set initial value, as "Unless specified otherwise, the initial value of an internal slot is the value **undefined**."
- Do explicitly state what the internal slots are when creating a new exotic object.
=> Editorial: Clarify internal slots during object creation

spec.html
Previously, the ECMAScript specification permitted non-callable
non-standard exotic objects to have implementation-defined typeof,
within certain limits. Although some ECMAScript implementations
may have taken advantage of this possibility historically, it's not
clear that anyone needs it anymore. Instead, other mechanisms can
be used by embedders to indicate aspects of objects.
Closes #1440
=> Normative: Remove implementation-defined typeof behavior

spec.html
(https://github.com/tc39/proposal-string-matchall/issues/21)
=> Normative: add `String.prototype.matchAll`/`Symbol.matchAll`

spec.html
There are currently 50 occurrences of `<code class="javascript">` and 2 occurrences of
`<code language="javascript">`. This changes the minority to match the majority.
=> Editorial: Consistently represent JavaScript code

spec.html
[[Status]] is a field of Cyclic Module Records; Abstract Module Records
don't keep track of it.
This patch avoids checking the [[Status]] of modules that don't have one,
instead first checking whether the module is cyclic. All of the use
cases seemed to be when modules were in dependency chains and not leaves.
Given the proposed Synthetic Module Records
https://github.com/tc39/proposal-javascript-standard-library/pull/44
and their possible usage in JSON modules, CSS modules, and WebIDL
modules, it makes sense to avoid these code paths for those cases.
Fixes #1455
=> Editorial: Don't read the [[Status]] of non-cyclic modules

spec.html
Per https://github.com/tc39/ecma262/pull/1407#issuecomment-479619396
=> Editorial: Introduce StringPad operation backing padStart and padEnd

spec.html
=> Normative: Require at least four digits in string representations of negative years

spec.html
Fixes #632.
This is _arguably_ normative, in that it changes the interpretation of a strict reading of the spec (which, I argue in the above issue, implies that `function f(a, a) { 'use strict'; }` would be legal, contrary to the intent of the author of the relevant text, implementations, and common sense).
In practice I think we're regarding this as either fixing a spec bug or merely a clarification, depending on whether you buy my above reading. So I've marked it as editorial.
Note that I've also changed the rule for names to be based on the strictness of `BindingIdentifier` rather than the strictness of the entire `FunctionDeclaration` (or similar) production. I don't think that actually changes anything, since the full production can't be strict unless all of its parts are. I'm mainly …
=> Editorial: clarify when early errors for functions apply

spec.html
This is explicitly permitted, and I think clearer. Mostly because I just misread the right-hand side of `lookahead ∉ { let [ }` as a two-element set.
=> Editorial: replace `lookahead ∉ { ele }` with `lookahead ≠ ele`

spec.html
NewPromiseCapability will immediately check if the argument (C) is an Object using IsConstructor and it will throw a TypeError if it's not.
This patch will just simplify the text with a fewer steps but this won't cause any new observable changes.
```
NewPromiseCapability ( _C_ )
1. If IsConstructor(_C_) is *false*, throw a *TypeError* exception.
IsConstructor ( _argument_ )
1. If Type(_argument_) is not Object, return *false*.
```
=> Editorial: Remove unnecessary steps before NewPromiseCapability

spec.html
The Abstract Equality Comparison operation may return abrupt completions, but the Strict Equality Comparison operation should always return Boolean values. Indicate that.
=> Editorial: Fix Completion handling for != and !==

spec.html
(PR submitted following co-ordination with @syg)
In the November TC39 meeting, [consensus was reached](http://tc39.github.io/tc39-notes/2018-11_nov-28.html#memory-model-bug-drf-sc-bug) to strengthen the axiomatic model to provide Sequential Consistency of Data-Race-Free Programs (SC-DRF). This property was [always intended to be provided by the model](https://www.ecma-international.org/ecma-262/9.0/index.html#sec-data-race-freedom) (but see https://github.com/tc39/ecma262/issues/1354 for a counter-example).
A PR to amend the model was drafted (https://github.com/tc39/ecma262/pull/1362), but I asked for a [delay in landing it](https://github.com/tc39/ecma262/pull/1362#issuecomment-443306833) after @stedolan noticed that the JS model (independent of our fix) appeared to be too strong to …
=> Normative: fix axiomatic model to be SC-DRF, and allow ARMv8 compilation

spec.html
=> Editorial: Don't equate TypedArray types with C types.

spec.html
... which was the subject of issue #1484.
This is basically @allenwb's suggested wording from
https://github.com/tc39/ecma262/issues/1484#issuecomment-473686361
The example string-to-be-eval'ed isn't one for which the distinctness of parse trees actually *matters*. Are there any simple cases for which it does?
=> Editorial: Clarify note re parsing the same string multiple times

spec.html
As discussed in #1266 and #1532, this replaces usages of increase/increment and decrease/decrement with the more general "set X to X + N" and "set X to X - N".
=> Editorial: remove usages of increase/increment and decrease/decrement

spec.html
Change "ECMAScript code execution context" to just "execution context" in the [[Call]] algorithm for a built-in function that *isn't* an ECMAScript function.
(An ECMAScript code execution context is a kind of execution context that's specifically for executing ECMAScript code, which is not the case here.)
=> Editorial: Fix incorrect use of "ECMAScript code execution context"

spec.html
Throughout the spec, there are 7 usages of "`X` occurrences of the code unit `Y`".
`X` is always non-negative in all usages except this one in `JSON.stringify`.
=> Editorial: Tweak handling of negative `space` values in JSON.stringify

spec.html
These lines didn't appear in #697.
@ljharb [says](https://github.com/tc39/ecma262/issues/1458#issuecomment-495930883) that was likely an oversight:
=> Editorial: set [[SourceText]] for async arrow functions

spec.html
=> Editorial: Make asserts in Else clauses explicit

spec.html
The terminology between WebAssembly and ES modules differs when it comes to instantiation, which causes some confusion for the integration of the two systems. Ideally, we wouldn't use the same term to mean two different things between the specs.
After talking about it with multiple people, it seems like calling it "the linking phase" might be a better name for this phase anyway. Developers are often confused about what actually happens during instantiation and why it's separated from evaluation. I believe "linking" more clearly communicates the justification for this being its own phase.
Note: This depends on #1311. The relevant commit for this PR is the last one. Once #1311  is merged, I can rebase this to remove those commits.
=>  Layering: Rename Module.Instantiate to Module.Link 

spec.html
Fixes #1495
which identifies the ordering of host callouts and input
type checks as a spec bug.
This uses option 1 from
https://github.com/tc39/ecma262/issues/1495#issuecomment-478626560
to ensure that type checks happen before host callouts.
This can't be tested in test262 but if this lands, I will follow up
with tests via web-platform-tests/wpt.
=> Normative: `eval(nonString)` should not have observable side effects

spec.html
=> Added 'yield' example for line terminator grammar restrictions.

spec.html
It took me a few times over the specification to understand that the
headings and introductory text with descriptions like
"when a direct eval call occurs outside of any function"
were non-normative. Here's a confusing case:
new class { constructor() { function f() { eval("super()") } f(); } }
This example will throw a SyntaxError because the enclosing
ThisEnvironment when eval runs is not a derived constructor. However,
in the ordinary English sense of "outside", I'd say that the eval
call is not outside of a constructor.
This patch removes the use of the term "outside" when describing the
distribution of this error case. It puts the error text inline in
PerformEval, where it's easier to see the relationship with where
the error condition comes from.
=> Editorial: Remove "Outside" wording for eval errors

spec.html
This PR includes minor changes to rebase, which are out for
review in https://github.com/tc39/proposal-dynamic-import/pull/72
Proposal author: Domenic Denicola
=> Normative: Add dynamic import()

spec.html
Fixes https://github.com/tc39/ecma262/issues/1505
=> Lookup constructor.resolve only once in PerformPromise{All, Race}

spec.html
@devsnek pointed out that [14.6.13](https://tc39.es/ecma262/#sec-runtime-semantics-classdefinitionevaluation) step 10 has extremely odd spacing:
```js
constructor(... args){ super (...args);}
```
Like Gus, I'd rather not battle over style here, but I think anyone can agree that that line needs fixing.
The first commit here fixes parentheses and braces to align with the style shown in [13.7.5.15](https://tc39.es/ecma262/#sec-enumerate-object-properties)'s note. (_Strictly speaking, this is more than necessary; even just **removing** spaces would be an improvement._)
The second commit normalizes a couple of `...,` cases to our more typical `&hellip; ,`.
=> Editorial: Normalize code spacing.

spec.html
- Move an ecmarkdown-adjacent HTML comment outside of its containing element to restore style generation on master (_search for <code>\`</code> or `_` and you'll see what I mean_).
- Fix two other typos found while bisecting (`&rt;` → `&gt;`, <code>\`"\`"</code> → <code>\`""\`</code> ).
=> Markup: Fix breakage after #1482.

spec.html
Formerly, for every different form of function definition, we would ask whether:
>   the function code for the function definition is strict mode code
and then pass the result to *FunctionCreate, and from there to FunctionAllocate.
Instead, we can equivalently ask whether:
>    the source text of the function definition's body is strict mode code.
The thing is, *this* question can be asked for all function definitions in one place: FunctionInitialize.
So do that, and drop the _strict_ parameter from FunctionAllocate. (In #1562, I said we could eliminate one of the parameters: this is it.)
---
Downstream effect:
HTML  has one call to FunctionCreate, whose signature is changed by this PR. The value that it passes to the Strict parameter is the same as what would be determined by …
=> Editorial: Centralize strictness-determination for function definitions

spec.html
Fixes #1172
b4708ca0389d58b1e5dd7ea43c83baac3e0b2a0c
- Instead of adding a new intrinsic, this PR simply performs a `Get` to retrieve the "next" method. 
e4516b0b325c6180eb8e64acf7673b06c6e3100c
- Remove non-observable behaviour from Async-from-Sync iterator objects.
=> Normative: Make Async-from-Sync iterator object inaccessible to ECMAScript code

spec.html
Commit message:
> In the March 2018 meeting of TC39, the committee elected to extend the
> definition of "function code" to include the BindingIdentifier of the
> productions where a BindingIdentifier is present. This decision was motivated
> by a desire to match implementation reality.
>
> This alteration does not require a change to Test262 because like the
> majority of modern implementations, Test262 already enforces the new
> behavior [1].
>
> [1] tc39/test262#1404
I don't know the best way to specify this, though I have a feeling that what I'm proposing here isn't it. The phrase "any BindingIdentifier present in the grammar production" is somewhat vague, but including a specific list of productions would be pretty verbose, especially considering the existing list of productions in …
=> Normative: Extend definition of "function code"

spec.html
Resolves #691.
(_This does not handle all concerns discussed in that thread, but it does serve as a solution for the OP.  
See https://github.com/tc39/ecma262/issues/691#issuecomment-471251881 onward for my own reasoning; in hindsight, I should've made a separate issue._)
=> Normative: Let all early errors be SyntaxErrors.

spec.html
This patch changes math in the ECMAScript specification to be based on
a concrete division into mathematical values and Numbers. All
numeric values and operations are explicitly either one or the other
with this patch. Previously, math took place in mathematical values,
based on a system of implicit conversions between these values and
Numbers.
This patch makes a big change in the idea of how most math operations
are evaluated internally, from mathematical values to Numbers, but the
goal is to make no observable change in semantics. The notation here
is intended to be relatively unintrusive and terse but unambiguous and
readable; I'd appreciate any feedback and suggestions. The hope is that
this notation will extend cleanly to BigInt as well as specifications for
embedders such as the Web …
=> Editorial: Explicitly note mathematical values

spec.html
Saw an opportunity for some reusability. This should be observably identical.
=> Editorial: use `TrimString` in `parseFloat` and `parseInt`

spec.html
=> Editorial: use "be the *this* value" over "be *this* value"

spec.html
(Unnoticed bug in ceb31ab from PR #1602.)
=> Editorial: '_trimmedString_' -> '_S_' in parseInt

spec.html
Fixes #1624 
`%RegExpStringIteratorPrototype%` which previously was undocumented
in well known Intrinsic Objects table is now added to the table.
If anything in this PR seems out of place or requires a change please let me know and I'll make the necessary changes ASAP (^_^)
=> Editorial: Added %RegExpStringIteratorPrototype% to well know Intrinsic objects table

spec.html
In #1560, we discovered that deferring NamedEvaluation to the evaluation algorithm for ClassExpressions would cause an undesirable change in behaviour. So this PR is the alternative: keep NamedEvaluation of ClassExpression special and set its `[[SourceText]]` slot.
This should be the last missing `[[SourceText]]` slot  :crossed_fingers:.
=> Normative: set [[SourceText]] in NamedEvaluation of ClassExpression

spec.html
* Normalised the wording of applying a syntax-directed operation
* Normalised the wording of passing arguments to a syntax-directed operation
* Used `?` shorthand for syntax-directed operations where applicable
I was a bit conflicted between the terse "Operation of |NonTerminal|" and the verbose "the result of applying Operation {for,of,to} |NonTerminal|". I'm happy either way.
I left "the result of evaluating" alone, both for wording normalisation and for usage of `?`. Even though it's just another syntax-directed operation, it is invoked using a special form. If the editors decide that we should include evaluation in this normalisation, I'll make the change.
=> Editorial: normalize wording used to apply syntax-directed operations

spec.html
- Make dashes consistent; certain instances in the title of standards are not changed
- Bold the Number value +0
=> Editorial: Some small formatting tweaks

spec.html
... and define the term "array-like object".
(As suggested at the end of [this comment](https://github.com/tc39/ecma262/pull/1612#discussion_r300876270).)
=> Editorial: Define + use LengthOfArrayLike operation

spec.html
Add some assertions to clarify the intended usage of this abstract operation.
I wanted to assert that `target` is an Array exotic object, but I think because of `ArraySpeciesCreate` I can't.
=> Editorial: `FlattenIntoArray`: add assertions

spec.html
This follows the years-old editorial direction of prefixing all calls to abstract operations where the result is not an inspected Completion Record (typically, looking for an abrupt completion), with `?` or `!`.
=> Editorial: Use `!` on calls to `ToBoolean`

spec.html
Looks like I forgot to capitalize one of the 'i's.
=> Editorial: fix capitalization of "RegExp String Iterator"

package.json
By @ljharb's [suggestion](https://github.com/tc39/proposal-nullish-coalescing/pull/41#issuecomment-511162676).
We could ditch `build-master` entirely, but I left it to start with, just in case we prefer the explicitness.
=> Meta: Refactor package.json scripts to use prebuild.

spec.html
Fixed a possible typo in `spec.html`
* `architectrue` -> `architecture`
In case this change isn't required please let me know and I'll close the PR (^_^)
=> Editorial: Fixed typo in Shared Memory Guidelines note

spec.html
Thanks to @devsnek for discovering.
=> Editorial: `parseFloat`/`parseInt`: fix unintentional normative change from #1629

spec.html
Per editors' group discussion, separating this out from #1314.
The intention here is to prevent unbounded future growth of the intrinsics table, while also making intrinsic references slightly more readable/intuitive by making them more closely mirror the JS you'd use to access them (in an unmodified realm).
This ideally would be coupled with a change in ecmarkup to auto-link intrinsic syntax to the value in question, for even easier consumption.
Closes #1377. Closes #1105.
=> Editorial: define and use improved intrinsics notation

spec.html
This better matches HostResolveImportedModule, which only requires idempotency when it completes normally (which is analogous to the success case here).
Closes https://github.com/tc39/proposal-dynamic-import/issues/80, at least on the ECMAScript side.
---
To be presented at TC39 today; I thought it'd be easier to have a concrete needs-consensus PR rather than trying to page through https://github.com/tc39/proposal-dynamic-import/issues/80.
=> Normative: change idempotency for HostImportModuleDynamically

.npmrc, package.json, scripts/insert_snapshot_warning.js, scripts/netlify.sh, scripts/snapshot_warning.css, scripts/snapshot_warning.html
this commit adds a warning (stolen from whatpr.org) to "snapshot" builds that exist for non-reference reasons, such as pr previews.
if we add some sort of github action to auto deploy netlify or something on a new pr and then post a comment with the url, this will provide a nice preview. someone with permissions on this repo will have to set that part up.
rendered: https://5ce61b1a493e120007e63323--brave-elion-abb3d4.netlify.com/
=> meta: add snapshot builds for pr previews

spec.html
.. re PR #1571
... and PR #1376.
=> Editorial: misc fixes

spec.html
The `LocalTZA` implementation-defined algorithm must accept the full
range of `Number` and not define its input to be a *time value* because
the algorithm is specified to take an already offset local time that can
be outside of the time value range.
This cleans up the specification text to clearly distinguish UTC time
values versus local time `Number` inputs and uses the same subscript
notation for both UTC and local time to make the text more clear.
Fixes #1070
=> Editorial: LocalTZA input specification

spec.html
Codify the existing fairness requirements that came up during https://github.com/tc39/proposal-atomics-wait-async/issues/12.
This is editorial because the bounded fairness is already implied by the forward progress guarantee.
=> Editorial: Spell out fairness requirements of EnterCriticalSection

spec.html
This PR is include changes to integrate [tc39/proposal-bigint](https://github.com/tc39/proposal-bigint) into ECMA262 text. It contains changes on:
1. Grammar to support BigInt literals.
2. Abstract Operations to consider this new primitive.
3. Semantics of arithmetic expressions to support BigInts.
4. The specification of BigInt objects, including the constructor and BigInt.prototype.
5. Including `BigInt64Array` and `BigUint64Array` as new types of `TypedArray`.
6. Changes on `DataView` operations to support new types.
Proposal author: Daniel Ehrenberg and Brendan Eich
=> Normative: Add new BigInt primitive

spec.html
This is a pull request for the **Stage 3** proposal https://github.com/tc39/proposal-promise-allSettled. The proposal is championed by @mathiasbynens.
**test262 tests:** yes https://github.com/tc39/test262/pull/2131 and https://github.com/tc39/test262/pull/2124
A common use case for this combinator is wanting to take an action after multiple requests have completed, regardless of their success or failure. Other Promise combinators can short-circuit, discarding the results of input values that lose the race to reach a certain state. Promise.allSettled is unique in always waiting for all of its input values.
=> Normative: Add Promise.allSettled()

spec.html
PR #1515 changed this step to `ToInteger` wrongly. We need to change it back to `ToNumber`.
=> Editorial: Changing 'SetViewValue' to use 'ToNumber' instead of 'ToInteger'

spec.html
There is no context on the stack that contains the current module while modules are setting up their environments, unlike scripts which push their context right before GlobalDeclarationInstantiation. This results in function declarations in modules having null [[ScriptOrModule]] slots. This breaks import.meta and dynamic import inside modules.
=> Editorial: Fix null [[ScriptOrModule]] of function declarations in modules

spec.html
NotifyWaiter is always called immediately after W is removed from the waiter list.
=> Normative: Fix bogus assert in NotifyWaiter

spec.html
Previously, array literals (including spreads) had their indices and
lengths calculated with a ToUint32 operation. As Georg Neis noted
in #1095, such a calculation isn't quite right, as 2**32-1 is not
an array index. These semantics are unlikely to be observable in many
current JavaScript implementations due to resource limitations, but
the strange behavior may appear in future, resource-rich
implementations.
This patch specifies Georg Neis's suggestion for semantics: to write to
the length just in the case of elisions (regardless of where they are in
the Array literal), and don't bother to write to the length for writes for
ordinary elements (as Array indices will already lead to length updates).
As a bonus, the semantics for Array literals are singificantly simplified, involving
just …
=> Normative: Remove ToUint32 from array literal evaluation

spec.html
@conrad-watt @lars-t-hansen 
Fixes #1680.
=> Strengthen Atomics critical section to imply synchronizes-with

spec.html
- Adds intrinsic `%GlobalThisValue%`
- Sets it in `SetRealmGlobalObject`
- Adds global name `globalThis`
Per https://github.com/tc39/proposal-global/issues/12
=> Normative: add `globalThis`

spec.html
This PR adds export * as ns from "mod" updates from tc39/proposal-export-ns-from to the spec as part of the July 27, 2017 notes. This PR replaces and expands this PR: https://github.com/tc39/ecma262/pull/1005
To see an updated diff of the new spec changes, you can look here: https://spectranaut.github.io/proposal-export-ns-from
Tests partially complete.
Closes #1005.
=> Normative: Add `export * as ns from "mod”` to Export production and Module Semantic

spec.html
Per October 2 2019 TC39 meeting consensus.
- [V8](https://bugs.chromium.org/p/v8/issues/detail?id=9800)
=> Normative: make String.prototype.matchAll throw for non-global regular expressions

spec.html
This commit contains two kinds of changes:
1. usage of CreateDataProperty, with an assert that it returns `true`,
converted to "Perform ! CreateDataPropertyOrThrow"
2. usage of CreateDataProperty, but with what I believe to be a
*missing* assertion that it returns true, converted to the same
=> Editorial: use `! CreateDataPropertyOrThrow` instead of `CreateDataProperty` and an assert

spec.html
=> Resolve #1007 - say what the draft reprsents

spec.html
This commit clarifies the definition of `%ThrowTypeError%` and `%FunctionPrototype%`'s restricted properties. It does not make any changes (observable or otherwise) to the structure and/or semantics of these objects.
Fixes #1719.
=> Editorial: fix and improve definition of %ThrowTypeError%

spec.html
Follow-up to #1239.
On IRC, two ideas were raised as to a consistent, enforceable approach to quoting properties:
- @ljharb suggested always using quotes unless that property can also be considered an identifier (hence "`"prototype"` property" but "`Function` property of the global object" ).
- @jmdyck suggested using quotes just when referring to it _as_ a property (hence "`"Function"` property" but "`Function` constructor", "`"toString"` property" but "`toString` method").
Either approach is acceptable to me, but I am starting with the latter, as the diff is more conservative.
I've also included a few related commits which fix neighboring typos, add missing backticks (e.g. to Array.prototype in plaintext), and turn "value `foo`" into "value **foo**" where trivial. The last of these …
=> Editorial: Quote properties across the board.

spec.html
This change makes `%JSONStringify%` in [Well-Known Intrinsic Objects](https://tc39.es/ecma262/#table-7) table a link to [JSON.stringify](https://tc39.es/ecma262/#sec-json.stringify).
Follow-up of #1272.
=> Editorial: Improve %JSONStringify% intrinsic definition

spec.html
Formerly, the heading and preamble of [7.4.9.1 ListIterator next ( )](https://tc39.es/ecma262/#sec-listiterator-next) suggested that there was a built-in object named "ListIterator" with a method named "next", none of which is true.
This PR changes the heading and preamble to be more like those of other arbitrarily-many-per-realm anonymous built-in functions.
(This is the one exception I mentioned [here](https://github.com/tc39/ecma262/pull/1635#discussion_r305586256).)
=> Editorial: Rephrase "ListIterator next"

spec.html
=> [meta] use an HTML comment to avoid auto-dfn-linking

spec.html
Simple improvement noticed while working on #1727.
=> Editorial: Reference DecimalDigit rather than duplicating its RHS

CONTRIBUTING.md
To give context on this, I couldn't remember the URL for the discourse (I admittedly do not frequent it). Googling for "esdiscourse" and variants didn't help me find it. I went to https://tc39.es/ and didn't see a reference there. I went to the CONTRIBUTING doc, thinking surely it must be there, and couldn't find a link either. I gave up and copied a link out of my emails.
@codehag @gesa @jorydotcom surely we must be able to make this better.
=> replace es-discuss link in CONTRIBUTING with discourse link

spec.html
First commit:
Currently, VarScopedDeclarations is defined for
IterationStatement :
`for` `await` `(` `var` ForBinding `of` AssignmentExpression `)` Statement
in two different places with conflicting definitions. Remove the incorrect definition.
Second commit:
Coalesce children of `for`-`in`, `for`-`of`, and `for`-`await`-`of` statements with identical definitions for VarDeclaredNames and VarScopedDeclarations for better readability: instead of having six different algorithm blocks for each of VarDeclaredNames and VarScopedDeclarations now there are only two for each.
=> Editorial: Correct and make readable for-in/of/await-of static semantics 

spec.html
Follow-up to #1302, prerequisite for the <code>\`"foo"\`</code> → <code>\*"foo"\*</code> update.
This patch aims to change all non-observable magic strings into `~foo~`-style spec-internal values.
=> Editorial: Use tildes for spec-internal values wherever possible.

spec.html
Re-evaluating all cases of <code>\`"foo"\`</code> throughout the spec (so as to switch to <code>\*"foo"\*</code> in one fell swoop) reveals that our notation for code ~units~ points isn't entirely consistent.
I'm starting with the maximal patch here for discussion's sake, but I'm happy to drop any (or all) of these changes; my only goal is to avoid blindly upgrading to asterisks without adequate consideration.
(CC: @jmdyck)
=> Editorial: Use consistent notation for code points.

spec.html
Currently we have 7 cases of '`this` object' and 19 cases of '**this** object' in the spec.
This appears to be short for '**this** value (which is an object)', so let's unify them accordingly.
=> Editorial: Stylize "this object" consistently.

spec.html
In AsyncFunctionStart, the context created by PrepareForOrdinaryCall is copied, and the copied context is used as the context for future evaluation with the async function. The context created by PrepareForOrdinaryCall is never used, and doesn't seem to (observably) exist in most implementations:
<sub>Only engine262 shows the original context from PrepareForOrdinaryCall (the one with no location on it)</sub>
After some light experimentation, I found that removing the context doesn't result in any test262 failures, so I am assuming for now that this is a safe change to make.
=> Editorial: remove context copy from AsyncFunctionStart

spec.html
Partially addresses #1742, changing the singular use of "_x_'s Y component" to the closest common form, "_x_'s Y".
=> reword only use of "_x_'s Y component"

spec.html
We were using both `cxt` and `ctx` as a shortening of "context" in variable names. To avoid this inconsistency, I just replaced them with `context`.
=> rename cxt/ctx variables to context

spec.html
Two things:
1. Define `IsStrict` for `Script`, since that's how it's applied.
1. Refer to the directive prologue of a `ScriptBody`/`FunctionBody` since that's how it's defined.
=> find Directive Prologue in appropriate node in IsStrict/ContainsUsestrict

spec.html
This reverts commit e9faaa18253f2d6dc063f4cb3c4cf481e8f4f849.
I now think my analysis in #1685 of removing the copy was incorrect. After discussion with @devsnek on IRC, the issue comes down to this step:
4. Resume the suspended evaluation of _asyncContext_. Let _result_ be the value returned by the resumed computation.
That seems to assume that _asyncContext_ can be "executed" and its _result_ observed without overwriting the current "execution" of AsyncFunctionStart. If _asyncContext_ isn't a copied context but instead **is** the current context, I think that step is ill-formed, it'd be like a jump or tail call: there's no way to get the _result_ as required by that step.
All in all it seems clearer to me to revert.
=> Revert "Editorial: remove context copy from AsyncFunctionStart (#1685)"

spec.html
At first, I noticed that there was a missing `ContainsUseStrict` definition for `AsyncConciseBody`, which was used in an early error, so I added the missing definition. ~But then I noticed that there was no way for the early error condition to be `true`, so I removed the early error and the `ContainsUseStrict` definitions became dead, so I removed those, too.~
=> add missing ContainsUseStrict definition for AsyncConciseBody

spec.html
#1725 included a new section on Value Notation; this PR enacts it by updating <code>\`"foo"\`</code> → <code>\*"foo"\*</code> throughout the spec. This means that all ECMAScript language values shall now be stylized as such.
=> Editorial: Stylize strings as values.

spec.html
Changes arising from discussion in issue #1544.
(The second commit changes the signature of FunctionAllocate, but that operation isn't used by WebIDL or HTML.)
Closes #1544.
=> Editorial: simplifications around [[FunctionKind]] and _functionKind_

spec.html
Adds the explicit `SerializeJSONProperty` carve-out for `BigInt`
and change to `GetV` that were part of the proposal spec text.
Fixes #1755
=> Normative: Restore BigInt.prototype.toJSON

spec.html
=> Normative: Make BigInt a global

spec.html
PR #1753 inserted the BigInt* clauses after Boolean,
but they should be *before* Boolean.
=> Editorial: quick fix re insertion of global BigInt

spec.html
This refactor was prompted by the confusing **-0** check in Integer-Indexed exotic objects' [[DefineOwnProperty]] trap. Usually the index validity checking is done in IntegerIndexedElementGet and IntegerIndexedElementSet, but that trap does some extra checks because it might not fall through to IntegerIndexedElementSet due to a non-data property descriptor.
=> Editorial: Refactor index checking for Integer-Indexed exotic objects

spec.html
[BigInt](https://github.com/tc39/ecma262/pull/1515) is missing in the list of primitive values
=> Editorial: Add BigInt to the list of primitive values

spec.html
Object coercion is only relevant to `GetSubstitution` call in [`RegExp.prototype[@@replace]`](https://tc39.es/ecma262/#sec-regexp.prototype-@@replace) (step **14.l.i**), so let's move it there. There are no observable steps between current and proposed locations of `ToObject` call.
=> Editorial: Move ToObject out of GetSubstitution

spec.html
Ref tc39/test262#2102
Ref tc39/test262#2109
This normative change matches the current behavior of V8, SpiderMonkey, and JSC (e.g. `Function("-->")`. This is not only for the convenience of reflecting the observed behaviors, ~~but this will allow some guard for potential false positives like `Function("#!hashbang")`~~.
=> Normative: CreateDynamicFunction early concatenates bodyText

spec.html
... in the [[Call]] and [[Construct]] internal methods for built-in function objects.
Resolves #1395.
=> Editorial: Delete unwanted use of "implementation-defined"

spec.html
FunctionAllocate and FunctionInitialize are always invoked in tandem. Moreover, the division between them seems somewhat arbitrary. So, merge the two operations into one, called OrdinaryFunctionCreate.
(Yeah, it's got 7 parameters, but I'm pretty sure we can eliminate one of them in a future refactoring.)
The second commit is the main one; the others are prep and cleanup.
(Web IDL and HTML do not reference FunctionAllocate or FunctionInitialize.)
=> Editorial: Merge FunctionAllocate and FunctionInitialize

spec.html
Fixes #1343 according to the approach [discussed therein](https://github.com/tc39/ecma262/issues/1343#issuecomment-458646159); see that issue for full context, but briefly, the current spec text says to do a parse according to "the goal symbol Pattern", which is meaningless in the current spec because Pattern has flags, which must be provided. Determining these flags is a little involved.
As it says there, this is heavily duplicated with [the runtime semantics for RegExpInitialize](https://tc39.github.io/ecma262/#sec-regexpinitialize). If the editors think this is worth noting, or avoiding, I can try to come up with something.
I'd particularly appreciate reviews from @jmdyck and @waldemarhorwat.
=> Editorial: correctly determine flags for static RegExp parsing

spec.html
A couple quick fixes for one of today's merges.
=> Editorial: quick fixes

spec.html
Using missing parameters directly eliminates extra steps, resulting in more descriptive variable names and increased visibility for functions where "X is (not) present" is absolutely required. ES6+ era algorithms already do treat missing parameters as `undefined` and use them directly.
=> Editorial: Treat not present parameters as `undefined`

spec.html
This one's my fault: during review of PR #1464, I suggested a change to (what is now) the "Parse" line, without noticing that it stranded the "Otherwise" line.
=> Editorial: Fix dangling "Otherwise" step

spec.html
```diff
[[IteratedList]]
- [[ListIteratorNextIndex]]
+ [[ListNextIndex]]
```
```diff
[[IteratedString]]
- [[StringIteratorNextIndex]]
+ [[StringNextIndex]]
```
```diff
- [[IteratedObject]]
+ [[IteratedArrayLike]]
- [[ArrayIteratorNextIndex]]
+ [[ArrayLikeNextIndex]]
- [[ArrayIterationKind]]
+ [[ArrayLikeIterationKind]]
```
```diff
- [[Map]]
+ [[IteratedMap]]
[[MapNextIndex]]
[[MapIterationKind]]
```
**(no changes)**
```diff
[[IteratedSet]]
[[SetNextIndex]]
[[SetIterationKind]]
```
**(no changes)**
```diff
[[IteratingRegExp]]
[[IteratedString]]
[[Global]]
[[Unicode]]
[[Done]]
```
=>  Editorial: Name internal slots of iterators consistently

spec.html
I noticed in passing that this case was missing.
=> Normative: IsSimpleParameterList is false for standalone rest parameters

spec.html
It closes #1754. This change is missing from original BigInt additions (#1515), but it was specified in the BigInt [spec text](https://tc39.es/proposal-bigint/#sec-number-constructor-number-value).
CC @littledan @devsnek @ljharb
=> Normative: Properly handle Number(BigInt)

spec.html
Similar to https://github.com/tc39/ecma262/pull/1769 — BigInt was absent from the list of types that the base value component of a Reference could be.
Note that it is already included and handled as a possible base value in the [HasPrimitiveBase abstract op](https://tc39.es/ecma262/#sec-hasprimitivebase).
I was unsure if there was any particular logic to the ordering of types, so I just slotted it in the ‘most alphabetic’ seeming part of the list. Alternatively, the sentence could be reworded to avoid listing them all if it’s felt that this is becoming an update hazard, e.g.
> The base value component is either an Environment Record or a language type other than Null.
Or, if it’s desired to draw additional attention to undefined’s distinct significance here:
> The base value component is …
=> Editorial: Add BigInt to the list of reference base value types and the language types intro text

spec.html
This change iterates over the existing keys of an array when truncating it instead of every possible key between `newLen` and `oldLen`, clarifying the observable behaviour of the loop.
https://deploy-preview-1702--ecma262-snapshots.netlify.com/#sec-arraysetlength
The behaviour of this change has been verified in engine262.
=> Editorial: simplify ArraySetLength truncation

spec.html
Resolves #1643.
As expressed there, boolean seems best if `nonsimple` is the best enum value we can come up with. I've also taken the opportunity to simplify the name to `IsSimpleAssignmentTarget` since I'm not sure that "valid" really serves to clarify anything (but feel free to disagree).
=> Editorial: Simplify AssignmentTargetType values.

spec.html
=> Editorial: Extract IsNonNegativeInteger abstract op

table-unicode-script-values.html
Accidental `<td>` where `<li>` was expected in the row for Elymaic / Elym in the Unicode script values table is bustin out weird:
=> Editorial: Fix Elymiac row markup in scripts table

spec.html
Fixes #1180.
This PR replaces those `obj.[[Get]](j)`s by the abstract operation `Get(obj, j)` since those lacked the 2nd argument `Receiver`.
=> Editorial: replace obj.[[Get]](j) with Get(obj, j)

spec.html
Unsure on how we want to put @littledan as original author.
=> Editorial: Add Interesting Cases of Automatic Semicolon Insertion

spec.html
Fixes #1133. The other uses of "idempotent" (to mean "if applied to any of its own outputs, it behaves as the identity function") were left intact.
=> fixes #1133: replace some uses of "idempotent" with alternative wording

spec.html
This change adds the relevant updates for the stage 3 [Optional Chaining](https://github.com/tc39/proposal-optional-chaining/) proposal. The intended changes can be viewed at https://tc39.es/proposal-optional-chaining/.
The Test262 PR is available at https://github.com/tc39/test262/pull/2212
=> Normative: Add Optional Chaining

spec.html
This change adds the relevant updates for the stage 3 [Nullish Coalescing](https://github.com/tc39/proposal-nullish-coalescing) proposal. The intended changes can be viewed at https://tc39.es/proposal-nullish-coalescing/.
The Test262 PR is available at https://github.com/tc39/test262/pull/2402
=> Normative: Add Nullish Coalescing

spec.html
Related to [proposal-for-in-order](https://github.com/tc39/proposal-for-in-order). Added as a separate PR because this change wasn't technically in scope during the process for that proposal. Thanks to @domenic for [bringing this to my attention](https://github.com/tc39/proposal-for-in-order/issues/19#issue-509659089).
`EnumerableOwnPropertyNames` is used by `Object.keys`, `Object.values`, `Object.entries`, `JSON.parse`, and `JSON.stringify`.
Removing this line has the effect of requiring those to be ordered the same way as `Reflect.ownKeys`, which is fully specified, rather than `for-in`, which is only partially specified.
I have not been able to find cases where implementations order any of the APIs which use `EnumerableOwnPropertyNames` differently than they would `Reflect.ownKeys`, …
=> Normative: make EnumerableOwnPropertyNames ordered

spec.html
This environment was originally added to the spec as the fix for a [bug](https://bugs.ecmascript.org/show_bug.cgi?id=3383) reported by @anba 
during the development of ES6. It first appeared in rev33, after a [brief discussion](https://mail.mozilla.org/pipermail/es-discuss/2014-December/040541.html)
on es-discuss.
Yet as explained in my [presentation](https://docs.google.com/presentation/d/11xRhQlcNGBdmKC43lEx7fUP0wl-QtFLg55FwgAvLE2k/edit?usp=sharing) at the November 2017 meeting,
it has not been uniformly implemented in engines, and its correct implementation in engines
that have attempted it has been a major source of bugs.
This PR implements "Option 4" of the linked slides, which coincides with the implementation
in JavaScriptCore, and thus is believed to be web-compatible.
=> Normative: Eliminate extra environment for eval in parameter initializers

spec.html
These are already covered by the chain productions rule.
=> Editorial: Remove redundant definitions of ComputedPropertyContains.

spec.html
Simple bugfix. When lookbehind assertions were introduced (PR #1029), a _direction_ parameter was added in the evaluate semantics of some productions of the RegExp grammar. Additional productions found in Annex B were overlooked.
Fixes #1674.
=> Editorial: Add missing _direction_ parameter in extended regexp pattern evaluate semantics in annex b

spec.html
This PR implements the [for-in-order](https://github.com/tc39/proposal-for-in-order) proposal, currently at stage 3.
I intend to request stage 4 at the December 2019 meeting.
[Here](https://github.com/tc39/test262/pull/2432) is the PR adding tests to test262.
=> Normative: specify for-in enumeration order in more cases

spec.html
Fallout from #1046. When creating a new environment so that
sloppy direct eval-introduced vars are in a different environment, the
LexicalEnvironment of the execution context was not updated.
Thanks to @devsnek for the catch.
=> Bugfix: Fix the LexicalEnvironment of the execution context during function parameter eval

spec.html
Those checks are needed in order to maintain the [Invariants of the essential internal methods](https://tc39.github.io/ecma262/#sec-invariants-of-the-essential-internal-methods). Their omission is a bug in the spec. This is a minimal patch for resolving them.
It remains glitches in some weird edge cases (commented below), but they need a little more refactoring.
/cc @erights, @tvcutsem
Fixes #652
=> Normative: Add three missing checks in proxy internal methods

spec.html
There is minor inconsistency with casing: 63 occurrences of "empty **S**tring", 15 of "empty **s**tring". Should we uppercase all the "string"s in this PR to avoid any possible doubt on primitive vs object wrapper?
=> Editorial: Tweak casing of "empty String" and "Number value"

package.json
Links to abstract operations `thisBooleanValue` and `thisTimeValue` are absolute and point to https://tc39.github.io/ecma262.
- ecmarkup contains an [es6biblio.json](https://github.com/bterlson/ecmarkup/blob/master/es6biblio.json) file which enables other specs / proposals to reference ECMA-262.
- This file has not been updated in over three years.
- Unlike [consciously-linked](https://bterlson.github.io/ecmarkup/#emu-biblio) bibliographies, es6biblio.json is [loaded unconditionally](https://github.com/bterlson/ecmarkup/blob/master/src/Spec.ts#L190).
And so, ecmarkup thinks living ECMA-262 is just some spec that happens to reference ES2017.
1. Ensure es6biblio.json is an empty object before building 262 (this PR).
2. Update es6biblio.json over in ecmarkup, since everybody else needs it …
=> Meta: Stop letting ecmarkup load 262's own outdated bibliography file.

spec.html
=> Normative: Add missing `ReturnIfAbrupt` to “Evaluation of `in` expression”

spec.html
See https://github.com/bterlson/ecmarkup/issues/126#issuecomment-570834393.
A certain `emu-grammar` element is currently marked `type="example"` in spite of clearly being no such thing. This has no visible effect at the moment but it will soon.
=> Editorial: Remove erroneous emu-grammar attribute.

spec.html
`CreateArrayIterator` is only ever called with one of three values; but there is no assertion that this is the case except inside the `next` method.
=> Editorial: `CreateArrayIterator`: add missing `kind` assertion

spec.html
Noticed by @bathos in https://github.com/tc39/ecma262/issues/1834#issuecomment-571075603.
I'm shocked by how many of these there are, but it makes sense because there's nothing to enforce their correctness. We really could use a safer approach here, but in the mean time, this should fix what's no longer accurate.
=> Editorial: Fix outdated Step # references.

spec.html
Introduce a new production _ExpressionBody_ for both plain and async arrow functions, and allow correctly handling return value logic for both. Currently, _AsyncFunctionStart_ does not correctly handle the return value of async arrow functions correctly.
=> Editorial: Fix return value logic for async arrow functions

spec.html
This PR cleans up a couple of notes which are inlined into algorithms:
- Move notes that share a line with a normal algorithm step to their own line. (x3)
- Un-inline a final note which refers to the algorithm as a whole. (x1)
- Fix grammar. (x2)
=> Editorial: Clean up some inline notes.

spec.html
Resolves #1825.
(_Well, sort of. This should eventually be done in ecmarkup itself, but ecmarkup is tricky to get changes into at the moment, and it's nice to have a concrete 262 snapshot to critique._)
This PR implements the "green notes without colored NOTE indicator" approach of https://github.com/tc39/ecma262/issues/1825#issuecomment-570971879.
Specifically:
- Borrow green border and background colors from Bikeshed
(_easier than inventing something new, at least as a starting point_)
- Remove grey text color
- Add 10px padding to the three non-border sides
- Make `<code>` background transparent and `<td>` background white
(_existing issues that only become visible when sitting on top of a non-white background_)
=> Editorial: Give emu-notes some color.

spec.html
The main commits are the 1 and 3, which define UTF16Encode and UTF16Decode respectively. Everything else is related editorial changes.
(Yes, there's already an op called UTF16Decode, but commit 2 renames it to something more appropriate.
So this changes the signature/behavior of UTF16Decode, but Web IDL and HTML don't reference it.)
=> Editorial: Introduce abstract ops UTF16Encode + UTF16DecodeString

CONTRIBUTING.md
This change updates the wording of the first part of the “To make a pull request” guidance in the CONTRIBUTING.md file to read:
> To make a pull request (PR), fork the ecma262 repository, apply changes to the `spec.html` file, and upload it ...
Without this change, the text lacks the word “repository" after “ecma262” and the word “file” after “spec.html”.
=> Meta: Update "To make a pull request" wording

spec.html
The spec uses `behaviour` 125 times and `behavior` 4 times, so let's unify upon the former.
(_I looked for any other US/UK spelling inconsistencies I could find, but didn't identify any._)
Also fix a misspelling on one of these lines (`soley` → `solely`).
=> Editorial: Unify spelling of 'behaviour'.

spec.html
Closes #1453. Closes #1437.
* Defines ordinary objects as having the ordinary internal methods, and exotic objects as not having the ordinary internal methods.
* Introduces AllocateBasicObject, which now is the only source of object creation, centralizing the undefined phrase "a newly created object" or "newly created X exotic object" into one location.
* Introduces explicit definitions for every type of exotic object in terms of how they override the internal methods. This makes phrases like "x is an Array exotic object" well-defined.
* Renames ObjectCreate to OrdinaryObjectCreate, and clarifies how it should be used.
* Fixes immutable prototype exotic objects to not inaccurately state that they always have default internal methods besides [[SetPrototypeOf]]; this is not the case for web …
=> Editorial: clarify ordinary and exotic object definitions and creation

spec.html
=> Editorial: Update IEEE 754 standard version

spec.html
Fixes #1637.
This only has an observable impact on `Atomics.store`.
=> Normative: ToInteger normalizes `-0` to `+0`

spec.html
The spec was inconsistent on whether _F_.[[SourceText]] was a String or a source text (sequence of Unicode code points). This commit picks the latter.
Resolves #1458.
Web IDL and HTML specs do not refer to this slot.
=> Editorial: fix inconsistency re type of [[SourceText]]

spec.html
fixes https://github.com/tc39/ecma262/issues/1351
=> Normative: Make super() throw after evaluating args

spec.html
=> Editorial: add missing argument to two CreateImmutableBinding calls

spec.html
Per https://github.com/tc39/ecma262/pull/1827#issuecomment-586545198
=> Normative: `ToInteger`: fix spec bug from #1827 that allows (-1,0) to produce `-0`

spec.html
[Static Semantics: SV](https://tc39.es/ecma262/#sec-static-semantics-sv) gives definitions for the `SV`s of the various parts of string literals.
This PR changes the four callers of this abstract operation which are phrased as `SV(|Foo|)` to be phrased as `the SV of |Foo|` instead, to match all other callers.
(Also two of these calls are not valid, but that can be fixed separately. See #1861.)
=> Editorial: make callers of SV consistent

spec.html
The phrase "the Number value for X" is only defined on mathematical values,
but `_prim_` is a BigInt value here.
So we have to take the mathematical value of `_prim_`
before applying "the Number value for ..."
(Quick fix for PR #1766.)
=> Editorial: quick fixes for recent merges

spec.html
Fixes #1795. cc @scole66, @claudepache, @mathiasbynens.
Marked as editorial because the previous spec text was nonsensical as written.
The first commit is all that is strictly necessary to resolve the issue. The second is just an improvement in clarity (to my eyes).
=> Editorial: remove AssertionTester from RexExp semantics

spec.html
(I think there are still some coverage holes in Evaluation, but that's a bit tricky.)
(Plus there's the bug in VarScopedDeclarations addressed by PR #1284.)
=> Normative: plug some holes in the coverage of syntax-directed operations

spec.html
This change updates the wording of the first sentence in the "About this Specification" section to read:
> This document at https://tc39.es/ecma262/ is the most accurate and up-to-date ECMAScript specification.
Without this change, it just reads “the most accurate up-to-date”, without the word “and”.
=> Editorial: Update About this Specification wording

spec.html
Just a small wordsmithing follow-up to #1062:
We have two sentences in a row saying effectively the same thing in different words, namely, the definition of "interesting". In fact, the previous paragraph already sets up the same concept (surprising reparses) for a different purpose (_new_ productions instead of existing ones) so in addition to eliminating a sentence here, we can also make a cleaner transition into the new paragraph.
=> Editorial: Improve readability in 11.10.

spec.html
Refactor and correct Early Error rules for LeftHandSideExpression productions potentially covering an AssignmentPattern:
* Add two missing early error rules  “All Early Error rules for |AssignmentPattern| ... are applied to the |AssignmentPattern| covered by ...”
* Removes an early error rule “... derives a phrase that would produce a Syntax Error ...”, because it is implied by the previous rule.
=> Normative: Add two missing Early Error rules for productions covering an AssignmentPattern

spec.html
=> Editorial: supply args to IteratorBindingInitialization

spec.html
Fixes #1878
(copied from [JSON.parse source text access
proposal](https://tc39.es/proposal-json-parse-with-source/#sec-internalizejsonproperty))
No effects on downstream dependencies:
* [Web IDL](https://heycam.github.io/webidl/)
* [HTML Standard](https://html.spec.whatwg.org/)
=> Editorial: Update InternalizeJSONProperty to accept reviver explicitly

spec.html
We don't have a well-defined notion of closures purely for use within the spec. This PR introduces the notion of an abstract closure and replaces the ad-hoc "internal procedures" and "internal closures" used by RegExps with them.
Also intended for use in #1597 for speccing Jobs.
=> Editorial: Introduce abstract closure and use them in RegExps

spec.html
Replace the EnqueueJob abstract operation with a HostEnqueuePromiseJob operation, responsible for asking the host to schedule the PromiseJob, and run it in a way that preserves the run-to-completion nature of JavaScript. As it is a host hook and not an algorithm, the invariants are specified declaratively, rather than imperatively as previously.
This PR implements the conclusion of the discussion in the June 2019 TC39 discussion on Promise scheduling and host layering.
Replaces #735 
cc @erights
=> Layering: Allow hosts to cleanly specify Promise Job semantics

spec.html
Thanks to @devsnek for the catch from #1597
=> [editorial] Fix typo in NewPromiseReactionJob

spec.html
Hello, there are two uses of the word 'operator' that refer to those not defined to be operators. This PR proposes to replace them with other appropriate words.
- “`new` or `super` operators”
- While `new` is actually an operator ([12.3.5 The new Operator](https://tc39.es/ecma262/#sec-new-operator)), `super` is not ([12.3.7 The super Keyword](https://tc39.es/ecma262/#sec-super-keyword)). Following @ljharb's suggestion, this PR rephrases it to “`new` operator or a `super` call`”.
- “optional chaining operator”
- The production that starts from `?.` token is simply called optional chains ([12.3.9 Optional Chains](https://tc39.es/ecma262/#sec-optional-chains)). Since the paragraph in question discusses syntactic analysis, I chose the word 'syntax'.
=> Editorial: fix misleading uses of 'operator'

package-lock.json, package.json, spec.html
Fixes https://github.com/tc39/ecma262/issues/1079, fixes https://github.com/tc39/ecma262/issues/1875. https://github.com/tc39/ecma262/issues/1730 was already fixed with a hack ([here](https://github.com/tc39/ecma262/pull/1731) then [here](https://github.com/tc39/ecma262/commit/435306ad232fbc211a528b250fe57d0b78a41667)) but this fixes it properly. Uses the [brand-new](https://github.com/bterlson/ecmarkup/pull/176) `emu-not-ref` [tag](https://bterlson.github.io/ecmarkup/#emu-not-ref).
=> Editorial: suppress some spurious links to definitions

spec.html
Hello, Step 4.a of [GetExportedNames](https://tc39.es/ecma262/#sec-getexportednames) refers to an '`import *` circularity', but it should be corrected to `export *` circularity'.
The GetExportedNames concrete method recurses for each entry in [[StarExportEntries]] of this Module Record. The role of _exportStarSet_ in GetExportedNames is to prevent an infinite loop due to the recursion.
Contents of [[StarExportEntries]] of Source Text Module Records correspond to _starExportEntries_ in [ParseModule](https://tc39.es/ecma262/#sec-parsemodule), which is a list of [ExportEntry Records](https://tc39.es/ecma262/#exportentry-record) whose [[ImportName]] is "*" and [[ExportName]] is null.
According to [Static Semantics of ExportEntries](https://tc39.es/ecma262/#sec-exports-static-semantics-exporten …
=> Editorial: correct 'import * circularity' to 'export * circularity'

spec.html
`SerializeJSONProperty `, `SerializeJSONObject`, and `SerializeJSONArray` refer to variables which they have not been passed using notation like ``SerializeJSONProperty has access to _ReplacerFunction_ from the invocation of the `stringify` method``.
I find this sketchy (see #1884).
This PR makes all the necessary values be passed explicitly, wrapped up in a Record.
=> Editorial: pass necessary arguments to SerializeJSON*

spec.html
This PR cherry-picks commits 4 - 7 of PR #1651. Their purpose is to reduce inconsistencies between the main body and Annex A (Grammar Summary), making it easier to keep them in synch going forward.
=> Editorial: Annex A tweaks

spec.html
=> Editorial: Spec variables shouldn't use TDZ in their names.

spec.html
An implementation of HostImportModuleDynamically, could, in theory, call
Evaluate() in the same tick as the call to HostImportModuleDynamically.
If that call to HostImportModuleDynamically was the direct result of
another call to Evaluate(), this may eagerly evaluate a module that
is already queued to be run at a later time.
cc @guybedford
=> Normative: Prevent DFS invariants from being broken

spec.html
Adding subscripts here makes sense, because the semantics specifically talk
about the presence of a parameter.
Also, the productions below, where the semantics also talk about the presence
of a parameter, already have the subscripts. So it's inconsistent to not have
them here.
=> Editorial: Add subscripts to BindingIdentifier static semantics.

spec.html
The abstract algorithm [`ForIn/OfHeadEvaluation`](https://tc39.es/ecma262/#sec-runtime-semantics-forinofheadevaluation) has an assertion is the step 7-a for checking whether the variable _iterationKind_ points to `iterate`. However, I think that _iterationKind_ might be `async-iterate` when the algorithm is invoked by `for await (...) ...` syntax. In [`Runtime Semantics: LabelledEvaluation`](https://tc39.es/ecma262/#sec-for-in-and-for-of-statements-runtime-semantics-labelledevaluation), `ForIn/OfHeadEvaluation` is called with `enumerate`, `iterate`, and `async-iterate` for the parameter _iterationKind_. In the `ForIn/OfHeadEvaluation` algorithm, the `enumerate` case is already consumed in step 6. Thus, I think that both `iterate` and `async-iterate` are possible values of _iterationKind_ …
=> Editorial: added ~async-iterate~ in assertion of ForIn/OfHeadEvaluation

spec.html
`LocalTZA` is currently listed as having 0 references, and not auto-linked.
=> fix auto-linking of LocalTZA abstract op

spec.html
This change aligns wording of [`OrdinaryOwnPropertyKeys`](https://tc39.es/ecma262/#sec-ordinaryownpropertykeys) with String's [`[[OwnPropertyKeys]]`](https://tc39.es/ecma262/#sec-string-exotic-objects-ownpropertykeys) and [`[[OwnPropertyKeys]]`](https://tc39.es/ecma262/#sec-integer-indexed-exotic-objects-ownpropertykeys) method of typed arrays, preferring more explicit `Type(X) is Y` notation.
=> Editorial: Align wording of [[OwnPropertyKeys]] methods

spec.html
This is the spec text for the stage 3 proposal `import.meta`.
Tests are available in both test262 (https://github.com/tc39/test262/pull/1888) and wpt (https://github.com/web-platform-tests/wpt/pull/7888). Implementation status is *very* good (JavaScriptCore, QuickJS, SpiderMonkey, V8, Moddable XS, engine262, Babel, Rollup, probably more), and it is shipping in many browsers (87% on https://caniuse.com/#search=import.meta).
=> Normative: add import.meta

spec.html
Fixes #1861. See that issue for context. Marked as normative despite fixing a spec bug because there are two sensible behaviors possible here, either of which is compatible with the current (incomplete) specification.
This PR takes the approach of making `/(?<\ud835\udc9c>.)/u` legal (in addition to making `/(?<\u{1d49c}>.)/u` legal, which is more obviously the intent of the current incomplete spec text).
=> Normative: Fully specify legal escape sequences in RegExp capture group names

spec.html
This is a followup to https://github.com/tc39/ecma262/pull/1869. Per consensus, `/(?<𝒜>.)/` should be legal. But the rules for parsing non-`u` patterns are such that the source text is parsed by treating each half of a surrogate pair as an individual code point. So the rules for `RegExpIdentifierStart` and `RegExpIdentifierPart` need to be tweaked to allow surrogate pairs for that case.
=> Normative: allow non-BMP characters in capture group names

spec.html
The rules for parsing non-`u` patterns are such that the source text is parsed by treating each half of a surrogate pair as an individual code point. But [IsValidRegularExpressionLiteral](https://tc39.es/ecma262/#sec-isvalidregularexpressionliteral) was applying the parsing rules for non-`u` patterns to the actual code points in the source text, rather than first splitting non-BMP code points into two surrogate code units and then interpreting those as code points.
=> Editorial: use correct source text for IsValidRegularExpressionLiteral

spec.html
This change replaces prose in normative steps with [`IsDataDescriptor`](https://tc39.es/ecma262/#sec-isdatadescriptor) abstract op, explicitly marks a `NOTE:` and result of `OrdinaryDefineOwnProperty` call.
=> Editorial: Tweak Array exotic object internal methods

spec.html
This unifies the wording used to introduce abstract operations. The intent is that the new wording should provide all and only the information in the current wording (except in a couple cases where the existing wording is obviously wrong). This is a step towards #545 (structured headers could be used to generate this text) and #1796 (which wants a consistent place to describe the return type of abstract operations).
We're wildly inconsistent about what information we bother to include in these descriptions. This is more obvious after this PR because the wording is now consistent, but since it doesn't actually make the information included any less consistent, I would prefer we not try to address that here.
~This PR also removes abstract operation preambles entirely when they contain no …
=> Editorial: use consistent wording for abstract operation preambles

spec.html
Fixes #1049
692cdb2e0dd96986c536889e0baf2589b2837516
- `[[SourceText]]` was not assigned for class expressions with an inferred name and async arrow functions. Fixed here because the next commits will change the same algorithms.
91d3ac1a6840afd6b8a664ae7adfb44695a97e16
- Changes the `NamedEvaluation` operations to no longer forward to `Evaluation` and splits `Evaluation` for `ClassExpression`. This in preparation for the next commit where `NamedEvaluation` will directly pass the function name to `FunctionCreate`.
99bf20554ff3e11f949b7893f7e6d36c797fc08e
- Add `name` property even if the function doesn't have an explicit or inferred name (#1049).
- Set the function `name` property as part of `FunctionInitialize`. This matches the behaviour of JSC, Graal and V8, which all three create …
=> Normative: Set "name" property for anonymous functions

spec.html
All cases of `<built-in> {object, type, value, instance, prototype}` throughout the spec have the built-in name consistently unstylized. `<built-in> constructor`, however, varies: usually the name is unstylized, but sometimes it's written with backticks.
I originally thought to do away with _all_ of these backticks, but I ended up feeling like perhaps the backticks are meant to distinguish "the concrete <code>\`&lt;built-in&gt;\`</code> constructor function" from "the conceptual `<built-in>` constructor", in which case some of them could be legitimate.
For instance:
- <code>The AsyncGeneratorFunction constructor ... is a standard built-in function object that inherits from the \`Function\` constructor</code> certainly feels broken, but...
- <code>A Number object is created by using the …
=> Editorial: Improve consistency of backtick use for built-ins.

spec.html
Fixes https://github.com/tc39/ecma262/issues/1942. See that issue for context.
Marked as a spec bug because the algorithm violates assertions as written (and also didn't really make sense; the `_envRec_.HasBinding(_fn_)` check could never actually return `*false*`).
cc @littledan @anba @syg
=> Editorial: use correct check in B.3.3.6

spec.html
indirect eval should not allow `new.target`, `super`, etc., and `GetThisEnvironment` is not defined in terms of non-ecmascript execution contexts.
=> Editorial: Fix indirect eval environment check

spec.html
The syntax-directed operations `ConstructorMethod` and `NonConstructorMethodDefinitions` have some duplicated code. Factor out this code and define a new SDO `ClassElementKind`.
=> Editorial: Define+use `ClassElementKind`

spec.html
... to the 'standard' form introduced in PR #1914.
=> Editorial: Convert more abstract operation preambles

spec.html
In the following Evaluation runtime semantics of update expressions, the variable `oldvalue` is suddenly appeared. I believed that it is a typo of `oldValue`.
- [Postfix Increment Operator](https://tc39.es/ecma262/#sec-postfix-increment-operator-runtime-semantics-evaluation)
- [Postfix Decrement Operator](https://tc39.es/ecma262/#sec-postfix-decrement-operator-runtime-semantics-evaluation)
- [Prefix Increment Operator](https://tc39.es/ecma262/#sec-prefix-increment-operator-runtime-semantics-evaluation)
- [Prefix Decrement Operator](https://tc39.es/ecma262/#sec-prefix-decrement-operator-runtime-semantics-evaluation)
Thus, I revised each use of `oldvalue` to use `oldValue` in the four semantics.
=> Editorial: Fixed typos in variable name `oldvalue`

spec.html
Noticed during review of #1860.
The wording of 25.7.1 seems to differ needlessly from 25.2.1 and 25.3.1.
=> Editorial: Align wording of The *Function Constructor sections

spec.html
In the previous version ES2019, [The Unsigned Right Shift Operator(`>>>`)](https://www.ecma-international.org/ecma-262/#sec-unsigned-right-shift-operator-runtime-semantics-evaluation) utilize [`ToUint32`](https://www.ecma-international.org/ecma-262/#sec-touint32) for both left and right expressions. However, the current version apply [`ToUint32`](https://tc39.es/ecma262/#sec-touint32) for only the right number value but use [`ToInt32`](https://tc39.es/ecma262/#sec-toint32) for the left number value in [`Number::unsignedRightShift`](https://tc39.es/ecma262/#sec-numeric-types-number-unsignedRightShift). I think it breaks the backward compatibility thus I revised the semantics of [`Number::unsignedRightShift`](https://tc39.es/ecma262/#sec-numeric-types-number-unsignedRightShift) to use …
=> Normative: Fixed bug in Number::unsignedRightShift

spec.html
In the previous version ES2019, The [Evaluation](https://www.ecma-international.org/ecma-262/#sec-binary-bitwise-operators-runtime-semantics-evaluation) of binary bitwise operators utilize [`ToInt32`](https://www.ecma-international.org/ecma-262/#sec-toint32) for both left and right expressions. However, the current version apply [`ToInt32`](https://tc39.es/ecma262/#sec-toint32) for only the left number value but use [`ToUint32`](https://tc39.es/ecma262/#sec-touint32) for the right number value in [`NumberBitwiseOp`](https://tc39.es/ecma262/#sec-numberbitwiseop). I think it breaks the backward compatibility thus I revised the semantics of [`NumberBitwiseOp`](https://tc39.es/ecma262/#sec-numberbitwiseop) to use [`ToInt32`](https://tc39.es/ecma262/#sec-toint32) for both left and right number …
=> Normative: Fixed bug in NumberBitwiseOp

spec.html
@bakkot You may want to consider linting for these in https://github.com/bterlson/ecmarkup/issues/173.
=> Editorial: delete some SDO cases that are covered by the chain production rule

spec.html
In step 10 and step 11 of [`Abstract Equality Comparison`](https://tc39.es/ecma262/#sec-abstract-equality-comparison) operation, return value of [`ToPrimitive`](https://tc39.es/ecma262/#sec-toprimitive) operation is directly used. However, [`ToPrimitive`](https://tc39.es/ecma262/#sec-toprimitive) operation may return abrupt completion record and adding prefix '?' on calling [`ToPrimitive`](https://tc39.es/ecma262/#sec-toprimitive) operation seems to be proper way of handle this problem.
=> Editorial: add prefix '?' on calling ToPrimitive in Abstract Equality Comparison

spec.html
Currently, [ProxyCreate][0] is sensitive to whether its arguments are revoked proxies. If either is, it throws a TypeError. This PR alters the algorithm to remove that sensitivity. Its consequence is that a Proxy could be created successfully where _target_ or _handlers_ are revoked Proxy exotic objects. (It was already possible for such Proxies to exist — just not for them to be _created_ while already in that state.)
The motivation for this change is discussed in issue #1798. Quoting @erights:
> It is a mistake because it makes the revocable-ness state of a proxy observable. When we first introduced revocable proxies, we intended observational equivalence to a handler that only throws. We were not trying to introduce behavior that could not otherwise be expressed. We were trying to …
=> Normative: Remove steps 2 and 4 from ProxyCreate

spec.html
[Forbidden Extensions](https://tc39.es/ecma262/#sec-forbidden-extensions) has a list of methods which are specified in ECMA-402 instead, but a few are missing; this PR rectifies that.
=> Normative: Generically forbid 402 method extensions in Forbidden Extensions

spec.html
Proposed change couples definitions and checks of `limit` and `size`, making 1:1 implementations with the spec a little bit nicer.
<details>
<summary>
Relevant part of current <code>RegExp.prototype[@@split]</code> implementation in JSC ... <br>(please note "Defered from" comments)
</summary>
```js
// 11. Let A be ArrayCreate(0).
// 12. Let lengthA be 0.
var result = [];
// 13. If limit is undefined, let lim be 2^32-1; else var lim be ? ToUint32(limit).
limit = (limit === @undefined) ? 0xffffffff : limit >>> 0;
// 16. If lim = 0, return A.
if (!limit)
return result;
// 14. [Defered from above] Let size be the number of elements in S.
var size = str.length;
// 17. If size = 0, then
if (!size) {
// a. Let z be ? RegExpExec(splitter, S).
var z = @regExpExec(splitter, str);
// b. If z is not …
```
=> Editorial: Reorder a few steps in String.prototype.split

spec.html
The spec "variables" are not variables, but aliases as defined in [5.2 Algorithm Conventions](https://tc39.github.io/ecma262/#sec-algorithm-conventions).
=> Editorial: Correct variable terminology

spec.html
=> Editorial: Fix casing of @@hasInstance well-known symbol

spec.html
[ForIn/OfBodyEvaluation](https://tc39.es/ecma262/#sec-runtime-semantics-forin-div-ofbodyevaluation-lhs-stmt-iterator-lhskind-labelset) expects an iterator Record of the sort returned by [GetIterator](https://tc39.es/ecma262/#sec-getiterator) (with [[Iterator]] and [[NextMethod]] slots) from [ForIn/OfHeadEvaluation](https://tc39.es/ecma262/#sec-runtime-semantics-forinofheadevaluation), but the `for...in` ("enumerate") branch was instead returning an Iterator _object_ (with a `next` method) from [EnumerateObjectProperties](https://tc39.es/ecma262/#sec-enumerate-object-properties). This corrects the mistake by passing that object to GetIterator.
=> Editorial: Return an iterator *record* for for...in heads

spec.html
Fixes #1398 
If the "return" property of an iterator is not callable, a TypeError will be thrown from `IteratorClose`, regardless of the completion provided as an argument.
If a "throw" completion is provided to `IteratorClose`, then it will rethrow that error even if the return property is not callable.
```js
let iter = {
[Symbol.iterator]() { return this; },
next() { return { value: 1, done: false }; },
return: 0, // Not a function
};
try {
for (let i of iter)
throw 1; // Throw and trigger IteratorClose
} catch (e) {
// Does this print "1" or "TypeError: 0 is not a function"?
print(e);
}
```
```
eshost -e '(() => { try { for (let i of { [Symbol.iterator]() { return this }, next() { return { value: 1, done: false }; }, return: 0 }) throw 1; } catch (e) { print(e) } })()'
1
1
TypeError: …
```
=> Normative: Suppress GetMethod errors in IteratorClose

spec.html
Every call to OrdinaryFunctionCreate is closely followed by a step that sets the `[[SourceText]]` of the resulting function object. Replace all but one of the latter steps by passing another argument
to `OrdinaryFunctionCreate`.
---
Re "all but one": the exception is in `CreateDynamicFunction`, where there isn't a Parse Node that represents the whole function, so we just pass `~empty~` to `OrdinaryFunctionCreate` and set the function's `[[SourceText]]` explicitly later. If you'd like this case to be handled inside `OrdinaryFunctionCreate` as well, I can think of a few ways:
- Say that the new parameter is either a Parse Node (handled as in this PR) **or** it's a sequence of Unicode code points (which gets assigned directly to `_F_.[[SourceText]]`). In `CreateDynamicFunction`, we'd move up …
=> Editorial: Set [[SourceText]] inside OrdinaryFunctionCreate

spec.html
... and numeric binary expressions in general.
Resolves #1561.
The first commit does what I suggested [here](https://github.com/tc39/ecma262/issues/1561#issuecomment-497365930), except:
- I called it `ApplyNumericBinaryOperator` because `ApplyBinaryOperator` was over-claiming. (Even "NumericBinaryOperator" is a bit much, since one could reasonably expect that to include relational operators.)
- I didn't factor out the `ApplyPlusOperator`/`Plus` operation, as it didn't seem that useful to me. (The BigInt refactoring probably made a difference.)
The second commit does what @michaelficarra requested [here](https://github.com/tc39/ecma262/issues/1561#issuecomment-616748116).
The third commit is just a suggestion. *I* like it, but it might be an acquired taste. If you do like it, …
=> Editorial: refactoring the evaluation semantics of compound assignment

spec.html
I revised a small part in [`StringGetOwnProperty`](https://tc39.es/ecma262/#sec-stringgetownproperty) to use `is -0` instead of `= -0` to correctly represent the semantics. The expression `index = -0` denotes that `index` is `-0` or `+0` because the `=` operator is floating point equality operator. Thus, instead, I think that it should be revised to `index is -0`.
=> Editorial: Using `is -0` instead of `= -0` in StringGetOwnProperty

spec.html
There are currently 21 places in the spec where we say something like `Repeat, while x,` (with a trailing comma) and 65 where we say something like `Repeat, while x` (without it). I would like us to be consistent.
I've chosen to have trailing commas in all cases, rather than none. This is a larger change, but I think more consistent with the rest of the specification given that when we repeat without condition we say `Repeat,` with the trailing comma. (We also say `Else,` rather than `Else`.)
But if there is a compelling reason to omit these I am happy to go the other direction and delete the 19 existing trailing commas instead.
I intend to introduce tooling to enforce this as soon as I can.
=> Editorial: end all 'Repeat' steps with commas

spec.html
Refactor semantic functions as used by atomic RMW operations to be
a subclass of abstract closures that are pure.
The remaining use of "semantic function" for reads-bytes-from is
changed to say "mathematical function". It is used in the axiomatic
event semantics and do not have algorithm steps.
Fixes #1895.
=> Editorial: Use abstract closures instead of semantic functions

spec.html
While we have a note stating "template object cannot result in an abrupt completion", it would be nice to assert that `[[DefineOwnProperty]]` calls are successful.
=> Editorial: Use DefinePropertyOrThrow and ! prefix in GetTemplateObject

spec.html
(This is a follow-up to #1953, which was a follow-up to #1914.)
This PR ensures that every numeric method (Number::foo and BigInt::foo) has a preamble that is in the standard form.
- The first 4 commits deal with the 6 Number methods that have non-standard preambles (exponentiate, multiply, divide, remainder, add, subtract):
- Commits 1-3 move out some wording that I don't think belongs in the preambles.
- Commit 4 converts what's left to standard form.
- Commit 5 goes to every numeric method that doesn't have a preamble, and adds a standard one.
=> Editorial: Complete standard preambles for numeric methods

spec.html
https://github.com/tc39/ecma262/pull/1932 introduced `UnicodeLeadSurrogate` to refer to a Unicode code point in the range of lead surrogates (0xD800 to 0xDBFF). The spec already has `LeadSurrogate` meaning four hex digits which represent a number that range. This PR renames the latter production to `HexLeadSurrogate` to be more explicitly distinguished from the former.
=> Editorial: rename LeadSurrgate, TrailSurrogate, and NonSurrogate

package-lock.json, package.json, spec.html
This enforces some simple linting rules for the specification added in https://github.com/tc39/ecmarkup/pull/199. Specifically, during `npm run build-master`, it checks:
- grammarkdown's built-in validity checks for the grammar
- the productions used in the definition of each early error and SDO are defined in the main grammar (at least when it is able to identify the early errors and SDOs)
- those productions do not include `[no LineTerminator here]` restrictions or `[+flag]` gating
- line endings in algorithm steps are consistent with the current style; [see here](https://github.com/tc39/ecmarkup/blob/7930f0baaea557db600023d33427e8eefdfffa97/src/lint/rules/algorithm-line-endings.ts#L5-L19) for precisely what that means
If any lint rule fails, the build fails. Hopefully we'll find out, …
=> Meta: bump ecmarkup, enforce linting

spec.html
Ensure `op` is a String in all cases, and ensure all three operations assert on the contents of `op`.
Previously, `NumberBitwiseOp` and `ByteListBitwiseOp ` did not assert on `op`, and they were passing an operator as if it was a first-class value. Instead, I made all three use the approach of `BigIntBitwiseOp`.
An alternative to strings would be to use `~^~` etc; happy to switch them all to that form if that's preferred.
=> Editorial: make `NumberBitwiseOp`, `BigIntBitwiseOp`, `ByteListBitwiseOp` consistent

spec.html, table-binary-unicode-properties.html, table-nonbinary-unicode-properties.html, table-unicode-general-category-values.html, table-unicode-script-values.html
Compare [current](https://tc39.es/ecma262/#table-binary-unicode-properties) with [updated](https://ci.tc39.es/preview/tc39/ecma262/pull/1992/#table-binary-unicode-properties).
I also removed a few duplicate entries from Table 58: `Cham`, `Lisu`, `Modi`, `Newa`, and `Thai`.
FYI @mathiasbynens this would require a rebase of #1896 and #1939. I'm happy to do it for you if we merge this first.
=> Editorial: use real table rows instead of ULs in Unicode tables

spec.html
This change makes handling of non-finite `this` values more concise (by using [`Number::toString`](https://tc39.es/ecma262/#sec-numeric-types-number-tostring)) and moves it earlier in steps, as well as argument range checks. This makes observable steps grouped and order of observable steps easier to read (especially if a runtime uses something like `std::isfinite` as JSC does).
=> Editorial: Early return & throw in Number.prototype.to* methods

table-unicode-script-values.html
https://unicode.org/versions/Unicode13.0.0/
Tests: https://github.com/tc39/test262/pull/2526
Ref. https://github.com/tc39/ecma262/issues/1897.
=> Normative: Update Unicode property lists per Unicode v13

spec.html
=> fixes #2003: consistent wording of "two's complement"

spec.html
Fixes an extra word in the opening paragraph of the Abstract Operations section.
=> Editorial: Remove extra "to" in Abstract Operations

README.md
I realized that the historical view of the spec might not be accessible for most people, so this PR adds a link to the readme. Related to #1999
=> add searchfox link to readme

spec.html
... from common code in IsValidRegularExpressionLiteral and RegExpInitialize.
---
This is the refactoring I referred to over [here](https://github.com/tc39/ecma262/pull/1464#discussion_r264020343).
---
I've split the PR into a series of smaller refactorings so that it's easier to follow. I expect these will be squashed together at merge, so I didn't bother prefixing their commit messages with "Editorial:". (Except for the final commit, whose commit message can serve as the message for the squash.)
IVREL = IsValidRegularExpressionLiteral, REI = RegExpInitialize
---
Note that if the parse fails, ParsePattern returns an abrupt completion. This is somewhat odd when it's being called by IsValidRegularExpressionLiteral, because the latter is static semantics. (Its only invocation is from an …
=>  Editorial: Extract operation 'ParsePattern'

spec.html
=> Editorial: Fix description of [[ThisMode]] internal slot of Function Object

spec.html
=> Editorial: fix inconsistent phrase "the empty String value"

spec.html
... specifically, steps of the form:
```
If _symbol_ is an |Identifier| and StringValue of _symbol_
is the same value as the StringValue of |IdentifierName|,
return *true*.
```
Resolves #831.
As @allenwb points out, the intended use case for such steps does not occur in the spec.
And as I point out, these steps are semantically problematic.
If the intended use case ever *does* occur, I suspect we'll find a different way to handle it.
=> Editorial: Remove unused steps from definitions of Contains

spec.html
This change makes promise.{all,allSettled,race} behave more like a canonical JS implementation.  In particular, the resolve property is now checked to be callable before beginning iteration on the first argument.
Closes #1902.
=> Normative: Promise.{all,allSettled,race} should check resolve is a function before opening their iterable

spec.html
Fixes <https://github.com/tc39/ecma262/issues/385>
---
[Preview](https://ci.tc39.es/preview/tc39/ecma262/pull/1996) ([#sec-well-known-symbols](https://ci.tc39.es/preview/tc39/ecma262/pull/1996#sec-well-known-symbols))
=> Editorial: Add <dfn> to well‑known symbols

spec.html
This also makes the definition of [`BigInt.prototype`](https://tc39.es/ecma262/#sec-bigint.prototype) consistent with other `prototype` properties.
---
[Preview](https://ci.tc39.es/preview/tc39/ecma262/pull/2024) ([#sec-bigint.prototype](https://ci.tc39.es/preview/tc39/ecma262/pull/2024#sec-bigint.prototype))
=> Editorial: Add <dfn> for %BigInt.prototype%

spec.html
This makes auto‑linking work.
---
[Preview](https://ci.tc39.es/preview/tc39/ecma262/pull/2025) ([#sec-well-known-intrinsic-objects](https://ci.tc39.es/preview/tc39/ecma262/pull/2025#sec-well-known-intrinsic-objects))
=> Editorial: Add <dfn>s for TypedArray subclass constructors

package-lock.json, package.json, spec.html
Two commits: one to bump ecmarkdown, one to make it pass linting by changing some stray non-`1.` step numbers to `1.`.
=> Meta: bump ecmarkup

package-lock.json, package.json, spec.html
This fixes a persistent problem where step numbers would get stale and we'd forget to update them. Now, by given the steps (somewhat arbitrarily chosen) labels, we can refer and link to them explicitly. See https://github.com/tc39/ecmarkup/pull/217 for a description of the syntax.
~Marked as draft until a version of ecmarkup with support for the new syntax is published.~ Edit: done, this should be good to go. Deploy preview looks good to me.
Corresponding ecmarkdown PR at https://github.com/tc39/ecmarkdown/pull/74. Corresponding ecmarkup PR at https://github.com/tc39/ecmarkup/pull/217.
=> Editorial: use step labels rather than numbers to refer to steps

spec.html
Previously a mixture of "complete property descriptor" and "fully populated property descriptor" was used. Change to use the defined "fully populated property descriptor" term.
Also capitalise "Property Descriptor" so that definition detection (hopefully) kicks in elsewhere, to be consistent with the rest of the spec.
=> Editorial: Consistency for the term "fully populated Property Descriptor"

spec.html
Proposal: https://github.com/tc39/proposal-string-replaceall
Tests: https://github.com/tc39/test262/pull/2423
Note that the changes to `String.prototype.matchAll` that were part of this proposal have already been merged here: https://github.com/tc39/ecma262/pull/1716.
=> Normative: Add String.prototype.replaceAll

spec.html
This is admittedly a very minor change.
```js
const o = {
next(...args) { console.log('args', args); return { done: true }; },
[Symbol.iterator]() { return this }
};
for (const item of o) {}
```
logs `'args', []`
```js
(async () => {
const o = {
next(...args) { console.log('args', args); return { done: true }; },
[Symbol.iterator]() { return this }
};
for await (const item of o) {}
})();
```
logs `'args', [undefined]`. The intention of this change is to make async iteration match sync iteration from the perspective of a userland iterator `next` method.
This was an intentional decision made by the feature champion in https://github.com/tc39/proposal-async-iteration/issues/113, but I don't recall it being discussed in committee. I find this inconsistency mildly troubling, and would like to …
=> Normative: make async iterators next/return/throw not pass `undefined` when value is absent

spec.html
This makes auto‑linking work.
---
[Preview](https://ci.tc39.es/preview/tc39/ecma262/pull/2026) ([#sec-well-known-intrinsic-objects](https://ci.tc39.es/preview/tc39/ecma262/pull/2026#sec-well-known-intrinsic-objects))
=> Editorial: Add <dfn>s for native error constructors

spec.html
PR #2009 recently introduced StringIndexOf, locating its definition in a subclause of [10 ECMAScript Language: Source Code](https://tc39.es/ecma262/#sec-ecmascript-language-source-code). This placement doesn't make much sense, as StringIndexOf isn't particularly related to source code.
There are various plausible places where it could go:
- as a subclause of [6.1.4 The String Type](https://tc39.es/ecma262/#sec-ecmascript-language-types-string-type).
- somewhere within [7 Abstract Operations](https://tc39.es/ecma262/#sec-abstract-operations) (though none of the existing subclauses is appropriate).
- as a subclause of one of the builtins that invokes it:
- [String.p.includes](https://tc39.es/ecma262/#sec-string.prototype.includes)
- …
=> Editorial: Relocate the definition of StringIndexOf

spec.html
I didn't bother to add an assertion after every callsite of `NewPromiseCapability`.
=> Editorial: add PromiseCapability Record assertions

spec.html
For property access section (with expression and identifier), add oldids - 
sec-evaluate-property-access-with-expression-key
sec-evaluate-property-access-with-identifier-key
Closes #2070
=> Editorial: add oldids for property access section

spec.html
=> Editorial: Add missing part of note in Array `find`/`findIndex`/`forEach`

spec.html
In declarative environment records, CreateMutableBinding and CreateImmutableBinding creates uninitialized bindings. Unlike declarative environment records, in object environment records, such internal methods does not create uninitialized bindings. They just creates a new property for the binding object with `undefined` value and there is no mention about uninitialized bindings. However, in InitializeBinding of object environment records, it requires uninitialized bindings. I think that it is better to remove the following highlighted assertion.
=> Editorial: Remove assertion in InitializeBinding of Object Environment Record

spec.html
Currently, `%AsyncGenerator%` auto‑links to <https://tc39.es/ecma262/#sec-asyncgeneratorfunction-prototype> instead of <https://tc39.es/ecma262/#sec-properties-of-asyncgeneratorfunction-prototype>.
I also sorted the `<ul>` to match other definitions and made the “see Figure” text an `<emu‑xref>`.
---
[Preview](https://ci.tc39.es/preview/tc39/ecma262/pull/2059) ([#sec-well-known-intrinsic-objects](https://ci.tc39.es/preview/tc39/ecma262/pull/2059#sec-well-known-intrinsic-objects), [#sec-properties-of-asyncgeneratorfunction-prototype](https://ci.tc39.es/preview/tc39/ecma262/pull/2059#sec-properties-of-asyncgeneratorfunction-prototype))
=> Editorial: Fix %Generator% and %AsyncGenerator% <dfn>s

spec.html
=> Editorially distinguish host and implementation

spec.html
I didn't add `oldids` for the terms that were just introduced in #1951, only for the ones that's been around for longer.
=> Editorial: Don't use "sec-" prefix for dfn ids

spec.html
Fixes #1970.
Essentially, this PR makes Reflect no longer be the "odd one out" - ie, the only namespace-like builtin object that lacks a `Symbol.toStringTag`.
See also: https://github.com/tc39/ecma402/pull/430
=> Normative: add `Reflect[Symbol.toStringTag]`

spec.html
Specification text for https://github.com/tc39/proposal-promise-any
This also includes changes to _IterableToList_ runtime semantics
=> Normative: Add Promise.any & AggregateError

spec.html
https://github.com/tc39/proposal-logical-assignment
This includes a few new changes:
- `NamedEvaluation` is used, given today's tentative consensus
- `LogicalAssignmentOperator` has been removed, and instead each `@@=` operator is defined individually
- - -
<details>
<summary>Outdated discussion</summary>
I need help getting it to compile correctly, though. When I run `build`, I get:
```
Could not find a production matching RHS in syntax-directed operation (undefined-nonterminal)
```
This is likely from defining the grammar as `LeftHandSideExpression ShortCircuitAssignmentOperator AssignmentExpression`, but defining individual algorithms as ```AssignmentExpression : LeftHandSideExpression `||=` AssignmentExpression```. We could define each grammar individually, or do a bit of …
=> Normative: Add Logical Assignment Operators

spec.html
This was missed in <https://github.com/tc39/ecma262/pull/2040>.
=> Editorial: Fix <emu‑xref> to AggregateError Objects

spec.html
See https://github.com/tc39/ecma262/issues/1435.
We could do the whole host hook song and dance, but that seems like overkill.
This PR takes the approach of making the `SharedArrayBuffer` property of the global object optional for hosts which do not provide concurrent access to SAB objects. There's no other way of getting a `SharedArrayBuffer` object (in this spec, certainly), so I think that's sufficient.
cc @erights @annevk @syg
Closes #1435.
=> Normative: make SharedArrayBuffer optional

spec.html
Resolves #2039.
Specifically:
- (Untagged) templates already have early errors for <code>\`\8\`</code> and <code>\`\9\`</code> so no action is needed there.
- All engines agree that `'\8'` and `'\9'` are just `'8'` and `'9'` in sloppy mode, so specify that in B.1.2.
- JSC has never(?) supported `'\8'` and `'\9'` in strict mode, so there should be no web compatibility risk.
Tests: https://github.com/tc39/test262/pull/2654
=> Normative: Specify \8 and \9 in sloppy non-template strings.

spec.html
Verify binding existence in the object's SetMutableBinding on Strict Mode.
Closes #2093
Ref #467
Ref tc39/test262#427
=> Normative: Verify if Binding is preserved for obj's SetMutableBinding

spec.html
Specification text for https://github.com/tc39/proposal-weakrefs
This version of the specification is _without_ cleanupSome (see https://github.com/codehag/proposal-cleanup-some), in anticipation of the discussion of the upcoming meeting. Adding this back in would be trivial if we decide against it. 
Note: we're adding inline normative optional spec text.
=> Normative: Add Weakrefs and FinalizationRegistry

spec.html
Unintentionally omitted from #2089.
Also added the `<dfn>`s for easier linking.
=> Editorial: add missing WeakRef/Finalization well-known intrinsics to table

spec.html
Fixes #1941
cc @michaelficarra
=> Normative: fix Function toString on builtins

spec.html
`RequireInternalSlot` has the same behaviour as what’s currently specified, so this can be simplified.
---
[Preview](https://ci.tc39.es/preview/tc39/ecma262/pull/2111) ([#sec-regexp.prototype.compile](https://ci.tc39.es/preview/tc39/ecma262/pull/2111#sec-regexp.prototype.compile))
=> Editorial: Use `RequireInternalSlot` in `RegExp.prototype.compile`

spec.html
The referenced nonterminals don't exist. This was changed in #2030, presumably by accident (cc @jridgewell), and this PR puts it back (while keeping the tweaked wording @michaelficarra preferred).
Thanks to @devsnek for spotting it.
=> Editorial: reference correct nonterminals in IteratorDestructuringAssignmentEvaluation

spec.html
Closes #1930
This PR intentionally leaves the actual steps to ensure there's a usable execution context implementation/host-defined.
My philosophy here is to be as loose as we can be without tripping assertions.
Some nuances:
- The choice of Realm is loosely constrained, just that it's non-null. The particular Realm only matters when a Job schedules a non-user function to run. If the Job runs a user function, calling that function will push a new execution context with that function's Realm.
- The active script or module could be null. The requirement is that Jobs that evaluate user code should propagate the active script at the queueing time to the time when the Job is run. I don't know any real world examples where we must propagate forward a null active script, but I don't see any …
=> Layering: Refine execution context requirements for Jobs

spec.html
In InnerModuleEvaluation, the argument _module_ is defined as `(a Source Text Module Record)`, but this could be a non-source text module record as well it looks like...
=> Editorial: Module Record in InnerModuleEvaluation need not be a Source Text Module Record

spec.html
Previously it was referencing an undeclared _TemplateLiteral_.
=> Editorial: Fix SubstitutionTemplate ArgumentListEvaluation

spec.html
If `S` is an empty string, `SplitMatch(S, 0, R)` can succeed only if `R` is an empty string too.
Since it isn't immediately visible from [`SplitMatch`](https://tc39.es/ecma262/#sec-splitmatch) definition, and its index result is unused, this PR simplifies the check.
Both [V8](https://github.com/v8/v8/blob/ddc9a9bae3386524f741954addf6855a1dd20b91/src/builtins/builtins-string-gen.cc#L1771) and [JSC](https://github.com/WebKit/webkit/blob/e647f5978f0d7a5fd91cc87bdc811ceef4cbbae7/Source/JavaScriptCore/runtime/StringPrototype.cpp#L1288) check separator for emptiness instead of performing extra [`SplitMatch`](https://tc39.es/ecma262/#sec-splitmatch).
=> Editorial: Simplify String.prototype.split with empty separator

spec.html
This oversight was discovered and reported to me by James Clark (jjc@jclark.com).
=> Editorial: (Exponentiation) Add NaN to exponent values whose behavior deviates from IEEE 754-2008

spec.html
Fixes https://github.com/tc39/ecma262/issues/1863 following @domenic's [suggestion](https://github.com/tc39/ecma262/issues/1863#issuecomment-597291191) there. I've also renamed `UTF16DecodeSurrogatePair` to `UTF16SurrogatePairToCodePoint` and `UTF16DecodeString` to `UTF16CodeUnitsToCodePoints`. I'm open to other names; these seemed the clearest.
After just renaming, some of the wording became a little strange: "the UTF16CodePointToCodeUnits of a Unicode code point" reads more awkwardly to me than "the UTF16Encoding of a Unicode code point" did. So I rephrased those usages.
cc @jmdyck
EDIT: names [changed](https://github.com/tc39/ecma262/pull/2014#issuecomment-633823196).
=> Editorial: Rename Unicode encoding/decoding operations

spec.html
This is to align with [wasm allowing atomics to work on non-shared memory](https://github.com/WebAssembly/threads/issues/144).
Most methods work in the obvious deterministic way on ArrayBuffers, with the exceptions of:
- `Atomics.wait` still throws on `ArrayBuffer`s.
- `Atomics.notify` always returns 0 on `ArrayBuffer`s.
=> Normative: Allow Atomics methods on ArrayBuffers

spec.html
In HTML, JS functions that are called asynchronously as part of jobs
(like Promise microtasks) are generally associated with a piece of state
called an incumbent settings object. The incumbent is stored at the time
when the callback is first passed to the API that is responsible for
scheduling the job (e.g. Promise.then), and restored when the callback
is called.
For symmetry, all WebIDL callbacks do this:
https://heycam.github.io/webidl/#idl-callback-interface
This PR adds the necessary host hook machinery to let HTML store and
restore the incumbent settings object. The default behavior is nop.
cc @domenic @annevk @codehag
=> Normative: Add machinery to track the incumbent settings object in HTML for Job callbacks

spec.html
Fixes suboptimal linking. Compare the latest draft to the preview build of this PR.
* Draft: string-concatenation links (e.g., from https://tc39.es/ecma262/#sec-utf16encode) point at #sec-ecmascript-language-types-string-type (6.1.4 The String Type).
* This PR: string-concatenation links (e.g., from https://ci.tc39.es/preview/tc39/ecma262/sha/e80669a328d044fed714e6975844ce1bdc4b2e9f/#sec-utf16encode) point at #string-concatenation (the specific definition of "string-concatenation").
=> Editorial: Add specific id for string-concatenation

spec.html
Also up for consideration is defining and using "the <dfn>string-slice</dfn> of <var>S</var>...", similar to [string-concatenation](https://tc39.es/ecma262/#sec-ecmascript-language-types-string-type).
=> Editorial: Use consistent language for extracting substrings

spec.html
With this PR:
* _L_ is initialized with default value and reassigned later, eliminating two `Else` clauses;
* "be the larger of ... and" prose is replaced with well-defined [`max`](https://tc39.es/ecma262/#eqn-max) operation, also improving readbility.
=> Editorial: Tweak "length" handling in Function.prototype.bind

spec.html
This PR is meant to be used as an example in the next editor call to decide whether we want rest parameters to be automatically reified in the associated algorithm steps as a spec List. We'll probably have to add a sentence to the Notational Conventions section to explicitly describe this.
=> Editorial: rest parameters are reified as spec Lists

spec.html
- also, add `<dfn>`s as needed so everything links nicely
This PR was extracted from #2065, and should land before it.
=> Editorial: consistently connect Prototype objects to the appropriate `.prototype` property

spec.html
#2139 clarified rest parameters, making these notes unnecessary.
=> Editorial: Remove notes on well-formed rest arguments

package-lock.json, package.json, spec.html
Every place that an algorithm talks about iterating a List it now says `1. For each element _name_ of _list_, do`, rather than saying "in" or "that is a member of" or "from" or whatever. Sometimes an actual type is used in place of "element".
I also added a sentence to the description of the List type that explicitly says Lists are iterated in order, and removed the few places in the spec text which explicitly specified that the order of iteration was the order of the List. (Most places just assume it.)
~Marked as a draft until I get feedback on this and, if we are in favor of these changes, add a lint rule to ecmarkup to enforce this style where possible.~ Edit: ready to go. The first commit bumps ecmarkup, which fails linting, and the second commit changes the list iteration style and …
=> Editorial: consistency around List iteration

package.json
Fixes #2083. The relevant difference is that `npm run watch` no longer passes `--strict` (which is necessary because `--strict` cannot be combined with `--lint-spec`).
=> Meta: fix watch script

spec.html
All uses of these have been removed from HTML and 402:
- https://github.com/heycam/webidl/pull/898
- https://github.com/whatwg/html/pull/5655
- https://github.com/whatwg/infra/pull/316
- https://github.com/tc39/ecma402/pull/474
Closes #2023. Closes #2124.
=> Editorial: remove legacy intrinsics

spec.html
This was previously done for [`#table‑4`][table-4] in <https://github.com/tc39/ecma262/pull/1614> and for [`#table‑49`][table-49] in <https://github.com/tc39/ecma262/pull/1734>.
I did this because of <https://github.com/tc39/proposal-realms/pull/263#discussion_r444387192>.
[table-4]: https://tc39.es/ecma262/#table-default-attribute-values
[table-49]: https://tc39.es/ecma262/#table-the-typedarray-constructors
=> Editorial: Use semantic table IDs

spec.html
=> Editorial: add missing `!` on calls to `OrdinaryObjectCreate`

spec.html
The term "Proxy exotic object" appears 24 times, including once as a definition (with a `<dfn>`), whereas "proxy exotic object" appears twice. This PR changes those two cases to be capitalized, matching the other usages.
=> Editorial: consistent capitalization for "Proxy exotic object"

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/require-allow-edits.yml
This adds a github action to require "allow edits" to be checked.
I've created the PR while unchecking the box, so i can get a screenshot of it failing, and then i'll check it and rerun it, and then update the OP with the comparison.
---
---
Note that the job has to be manually rerun (by rebasing or pushing to the PR, one of us clicking "rerun job" on the action, or by closing/reopening the PR); when I figure out how to make it automatically rerun when the box is checked, I'll update it to do so. imo this is Fine, though, because the benefit is automatically signaling to the PR author that they need to check the box.
=> Meta: add "Require Allow Edits" action

package-lock.json, package.json, spec.html
Replaces https://github.com/tc39/ecma262/pull/2043, using the strategy described in https://github.com/tc39/ecma262/pull/2043#issuecomment-658477872. I've opened this as its own PR so that reviewers can more easily see the differences.
This doesn't have precisely the same semantics as the original: in particular, this PR does not allow `_` in the sequences of decimal digits which occur in regular expressions such as `/(a)(a)(a)(a)(a)(a)(a)(a)(a)(a)\10/` or `/a{0,10}/`, and similarly does not _forbid_ `/{1,1_0}/` (which is currently legal under Annex B). I am almost certain the changes to regex literals were an oversight. cc @rwaldron to confirm.
I've also added the new `NumericLiteralSeparator` production to Annex A.
Otherwise this should have identical semantics, just with less …
=> Normative: add NumericLiteralSeparator

spec.html
Replaces https://github.com/tc39/ecma262/pull/835. This includes two of the three commits in that PR; the third, https://github.com/tc39/ecma262/pull/835/commits/8e56f87a235130a319a8adcc4b99bd4acc336aef, I am not inclined to take.
I'm neutral on the second commit, but included it for completeness.
(I opened a separate PR rather than just updating #835 because I wanted to drop https://github.com/tc39/ecma262/pull/835/commits/8e56f87a235130a319a8adcc4b99bd4acc336aef but didn't want to force-push it away.)
cc @anba @syg @lars-t-hansen
=> Editorial: deduplicate some work in atomics

spec.html
[`ObjectDefineProperties`](https://tc39.es/ecma262/#sec-objectdefineproperties) has two call sites: [`Object.create`](https://tc39.es/ecma262/#sec-object.create) and [`Object.defineProperties`](https://tc39.es/ecma262/#sec-object.defineproperties).
This change moves Object type check before the latter since [`Object.create`](https://tc39.es/ecma262/#sec-object.create) always passes a newly created object as the first argument.
=> Editorial: Move Object type check out of ObjectDefineProperties

spec.html
"_X_ is empty" prose is somewhat ambiguous: a reader may assume it refers to `~empty~` or absent parameters.
=> Editorial: Reword StringIndexOf note and remove unused vars at its call sites

spec.html
Starting a few methods to get feedback.
Fixes #2119
=> Editorial: define Math functions using algorithm steps

spec.html
Aligns it with [`Date.prototype.toJSON`](https://tc39.es/ecma262/#sec-date.prototype.tojson) and removes incorrect "allowed values" note.
=> Editorial: Add note on ignored argument of Symbol.prototype[@@toPrimitive]

spec.html
Followup to https://github.com/tc39/ecma262/pull/2122.
The first commit, https://github.com/tc39/ecma262/pull/2172/commits/75c3c480aec360a013e98890fb94bc204f1b7451, makes it explicit that coercion happens exactly once for each argument to Math.hypot. See https://github.com/tc39/ecma262/pull/2122#discussion_r487365913.
The second commit, https://github.com/tc39/ecma262/pull/2172/commits/fb2811b5b18e9d5cb9517554278acf015ec4ae81, ensures that `Math.hypot(-Infinity)` returns `Infinity`, not `-Infinity`.
The third commit, https://github.com/tc39/ecma262/pull/2172/commits/464d064159606b75f736d0e79b4269186762fd09, ensures that all possible side effects in `Math.hypot`, `Math.max`, and `Math.min` happen before the method returns.
=> Editorial: a couple of fixes for Math

spec.html
(Things I missed in my review of PR #2122.)
----
Brief history of 'max' ('min' is similar):
ES1, ES2:
- 15.8.2.11  max(x, y)
- Returns the larger of the two arguments.
ES3, ES5:
- 15.8.2.11  max( [ value1 [, value2 [, ...] ] ] )
- Given zero or more arguments, ...
- If no arguments are given, the result is -inf.
- The `length` property of the `max` method is 2.
Draft 23 of ES6 deleted the full-bracketing in the heading, unclear why...
ES6:
- 20.2.2.24 Math.max ( value1, value2 , ...values )
- Given zero or more arguments, ...
- If no arguments are given, the result is -inf.
- The `length` property of the `max` method is 2.
PR #266 removed the line about the `length` property...
ES7+:
- 20.2.2.24 Math.max ( value1, value2 , ...values )
- Given zero or more arguments, ...
- If no arguments …
=> Editorial: quick fixes re Math functions

package.json, spec.html
Fixes https://github.com/tc39/ecma262/issues/1257.
~Edit: actually apparently this does not fix the issue, somehow? At least in CI. I'd guess it's a biblio issue. I'll look into it.~ Edit x2: fixed; see below.
This is the fault of https://github.com/tc39/ecmarkup/pull/167 + https://github.com/tc39/ecma262/blob/d3fa570c8561ba54653640889790e0cb36f87bde/package.json#L22.
~I'll fix this properly in ecmarkup so we don't need the hacky npm script.~ We already have a fix, it just wasn't in use: https://github.com/tc39/ecmarkup/pull/169. Pushed.
=> Editorial: rename Suspend to SuspendAgent

spec.html
Noticed in the context of #2164.
The note about `delete`'s behavior in strict mode is easy to misread as if it were exhaustive, so let's just make it exhaustive.
=> Editorial: Clarify note about `delete` in strict mode.

spec.html
The original grammar of `IfStatement` is ambiguous thus the specification describes the following additional note:
- Each `else` for which the choice of associated `if` is ambiguous shall be associated with the nearest possible `if` that would otherwise have no corresponding `else`.
Thus, I introduced a new parameter `Else` for `Statement` and `IfStatement` to remove unambiguity in the grammar of `IfStatement`. Only if `Else` is false, the second alternative of `IfStatement` could be selected, which is an `if` statement without `else` block.
- `if s_1 else s_2`
Thus, in the above statement, if `s_1` is an `IfStatement` then `s_1` always has `else` block. I believe that it could remove the unambiguity in the grammar of `IfStatement`.
=> Editorial: Unambiguous grammar for IfStatement

spec.html
This was incorrectly added by @ljharb in <https://github.com/tc39/ecma262/pull/1376>.
---
[Preview](https://ci.tc39.es/preview/tc39/ecma262/pull/2036) ([#sec-well-known-intrinsic-objects](https://ci.tc39.es/preview/tc39/ecma262/pull/2036#sec-well-known-intrinsic-objects))
=> Editorial: Intrinsic %ArrayIterator% doesn’t exist

spec.html
A significant minority of abstract operations have a "Runtime Semantics" prefix that doesn't seem very useful (since the operations can only be used by reference from elsewhere, RS or otherwise). This PR updates them to match the rest of the spec.
=> Editorial: Remove "Runtime Semantics" prefix from abstract operations

spec.html
While reviewing https://github.com/tc39/ecma262/pull/2007, @michaelficarra and I noticed that [`MakeTime`](https://tc39.es/ecma262/#sec-maketime) is underspecified: it has a step which reads
> Let t be h * msPerHour + m * msPerMinute + s * msPerSecond + milli, performing the arithmetic according to IEEE 754-2019 rules (that is, as if using the ECMAScript operators * and +)
but does not specify in which order to perform the additions. The choice of order is observable when using IEEE double-precision floats: for example,
- `((80063993375 * 3600000 + 29 * 60000) + 1 * 1000) + -288230376151711744` is `29312`, but 
- `80063993375 * 3600000 + (29 * 60000 + (1 * 1000 + -288230376151711744))` is `29248`.
(The actual value is `29256`.) So [`Date.UTC`](https://tc39.es/ecma262/#sec-date.utc)`(1970, …
=> Normative: explicitly specify order of operations in MakeTime

spec.html
* Describe what the highlighted text does in B.1.4.1, as we do elsewhere.
* Reference the modified sections in B.3.3.4 and B.3.3.5.
* Included both list items in both B.3.3.4 and B.3.3.5 as to not imply they are meant to be discarded.
* Pedantry about surrounding ~whitespace~/punctuation in `<ins>` tags.
=> Editorial: clarify B.1.4.1, B.3.3.4, and B.3.3.5; other minor markup

spec.html
This eliminates the weird unspecified "hint X" form and replaces some internal-only usage of strings with spec `~enums~`.
=> Editorial: replace some more internal usage of strings with spec enums

spec.html
As suggested by @bakkot as a follow-on to #2142. *edit*: Added the rephrasing that @gibson042 suggested in that thread as well.
Note that this only addresses the remaining phrasing inconsistencies, and *does not* attempt to address the inconsistency with when we use double angle brackets to denote List literals.
=> Editorial: normalise phrasing used to create Lists

spec.html
As reported on #1964, the fact that we are using Number as default representation of numeric literals and operations creates uncounted bugs throughout the spec. This PR is proposing to rollback the default value to mathematical value. Since the major intention of PR #1135 was to avoid implicit conversions between numeric versions, we are keeping this change but it necessary to properly cast those numeric types when they are manipulated, since mixing different numeric types is not allowed.
The goals we want to achieve here are:
1. Resolve bugs on current version of spec like #1960 or #1229.
1. Mathematical values should never be leaked and are internal concept of ECMA262 specification. If this happens, it should be considered as editorial error.
1. Avoid the maximum of explicit conversions …
=> Editorial: Make numeric values and operations default to mathematical values

package-lock.json, package.json
This introduces a few new linting rules, mainly aimed at enforcing the conventions introduced in #2007.
=> Meta: bump ecmarkup to 4.2.0

spec.html
- `Date(...)` [before](https://tc39.es/ecma262/#sec-date-year-month-date-hours-minutes-seconds-ms) [after](https://ci.tc39.es/preview/tc39/ecma262/sha/c085a92dcaec12b98c5f8446afd47679928d45ec/#sec-date)
- `Array(...)`  [before](https://tc39.es/ecma262/#sec-array-constructor-array) [after](https://ci.tc39.es/preview/tc39/ecma262/sha/c085a92dcaec12b98c5f8446afd47679928d45ec/#sec-array)
- `%TypedArray%.prototype.set(...)` [before](https://tc39.es/ecma262/#sec-%typedarray%.prototype.set-overloaded-offset) [after](https://ci.tc39.es/preview/tc39/ecma262/sha/c085a92dcaec12b98c5f8446afd47679928d45ec/#sec-%typedarray%.prototype.set)
- `_TypedArray_` [before](https://tc39.es/ecma262/#sec-typedarray) [after](https://ci.tc39.es/preview/tc39/ecma262/sha/c085a92dcaec12b98c5f8446afd47679928d45ec/#sec-ty …
=> Editorial: Rewrite overloaded functions so each has a single definition

spec.html
Resolves #678.
Specifically, web reality is such that IsDetachedBuffer checks should not cause the following to throw:
- `ArrayBuffer.prototype.byteLength`
- [[HasProperty]] for typed arrays
- IntegerIndexedElementGet (i.e. [[GetOwnProperty]] and [[Get]] for typed arrays)
- IntegerIndexedElementSet (i.e. [[DefineOwnProperty]] and [[Set]] for typed arrays)
To ensure that we don't violate EIM invariants for typed arrays, we must also:
- Make integer-indexed elements [[Configurable]]
- Override [[Delete]] such that `false` is returned upon attempted deletion of an integer-indexed element
(CC @syg, @rwaldron)
=> Normative: Align detached buffer semantics with web reality

spec.html
Resolves #333.
This PR:
* [makes](https://github.com/tc39/ecma262/commit/f3d2ad9180fb2eb5ea00eeb8df314b5c2e99f7c7) Reference type a Record, [moving](https://github.com/tc39/ecma262/commit/5497a598561bbb3a886e99fe59d959da7b2a685d) field description to a Reference Fields table;
* makes `[[Base]]` of an unresolvable reference _absent_ instead of `undefined` (nice improvement suggested by @claudepache);
* [replaces](https://github.com/tc39/ecma262/commit/ac0d4cf47fd919dda9b0f2db09cee7292c058014) (currently inconsistent) prose like "base value component of V" with field access, removing a few now unnecessary helpers ([`GetBase`](https://github.com/tc39/ecma262/commit/2699f7d7a8baa8095cc19167e1a8524e7beca26b), [`GetReferencedName`](https://github.com/tc39/ecma262/commit/46deceff02cab03d93e0be9c9 …
=> Editorial: Make Reference type a Record value

package-lock.json, package.json, spec.html
There are 1578 `1. If _foo_, do _bar_.` steps in ecma262 master, and only 16 `1. If _foo_, then do _bar_.`. This changes the latter 16 to match the rest of the spec, and bumps ecmarkup so its linter will enforce this style.
This PR has two commits: one bumping ecmarkup, and one changing the style. They should be landed in the opposite order, so that the change to the style precedes the commit which enforces it.
=> Editorial: consistency for single-line "if" algorithm steps

spec.html
`GetReferencedName` was removed by #2085, but while that PR was open #2030 landed and introduced three new references to it, which we missed. This PR fixes those three references.
Also, #2085 removed the id for "super-reference"; this restores that as an `oldid` on the definition of "Super Reference Record".
Thanks to @jmdyck for pointing these out.
=> Editorial: replace a few stray GetReferencedName invocations / re-define "super-reference"

spec.html
A built-in function that is implemented as an exotic object has no need for a `[[ScriptOrModule]]` internal slot. It always has the value `*null*`, and the only place it's used is in [the [[Call]] and [[Construct]] methods for exotic built-ins](https://tc39.es/ecma262/#sec-built-in-function-objects-call-thisargument-argumentslist), so we can just inline `*null*` there.
The remaining 3 appearances of `[[ScriptOrModule]]` pertain only to ordinary functions.
(Setting `[[ScriptOrModule]]` for exotic built-ins made more sense when the slot was introduced, because of the way `GetActiveScriptOrModule()` was written, but PR #556 changed it to basically the current situation.)
=> Editorial: Drop [[ScriptOrModule]] slot for exotic built-ins

spec.html
In `PropertyDefinition : PropertyName : AssignmentExpression` rule of ["12.2.6.8 Runtime Semantics: PropertyDefinitionEvaluation"](https://tc39.es/ecma262/#sec-object-initializer-runtime-semantics-propertydefinitionevaluation), abrupt completion can be created by NamedEvaluation of AssignmentExpression at step 3.a. Therefore, it seems that adding `ReturnIfAbrupt` call at step 3 would be appropriate.
=> Editorial: Add missing ReturnIfAbrupt to PropertyDefinitionEvaluation

package-lock.json, package.json
This is a fix for the bug mentioned in [this comment](https://github.com/tc39/ecma262/issues/570#issuecomment-729349410) (but not for the issue in which that comment appears).
=> Meta: bump ecmarkup to 4.2.2

spec.html
(See issue #828.)
The first 4 commits are independent refactorings that would be useful even if the main point of the PR is rejected. They're here because they reduce the number of cases that the final commit has to deal with.
=> Editorial: Have SV, TV, TRV, and CodePointToUTF16CodeUnits return a String rather than a sequence of code units

package-lock.json, package.json
This makes it so that when you copy/paste or search on the page for grammar productions there will be space characters in the text as there are on screen.
=> Meta: bump ecmarkup to 4.2.3

spec.html
envRec.[[HomeObject]] was always equal to envRec.[[FunctionObject]].[[HomeObject]], so the field was redundant.
Fixes #1358.
=> Editorial: Remove [[HomeObject]] from function Environments

spec.html
(This is the PR foreshadowed [here](https://github.com/tc39/ecma262/pull/1866#discussion_r423416235). Attn @michaelficarra)
<s>It's only a draft pull request so far, because:
(a) Some of the prose is first draft.
(b) I haven't used ParseText in IsValidRegularExpressionLiteral and RegExpInitialize yet, because that would just raise merge conflicts when #1866 is merged. Simpler to just wait.</s>
=> Editorial: Extract operation ParseText

spec.html
There is a general pattern in which Contains abstract operations do not descend into function bodies, called out with notes like "Static semantic rules that depend upon substructure generally do not look into function definitions." ([example](https://tc39.es/ecma262/#sec-function-definitions-static-semantics-contains)). But the note is missing for [`async function` productions](https://tc39.es/ecma262/#sec-async-function-definitions-static-semantics-Contains) and is strangely worded (with "normally") for concise functions (both [sync](https://tc39.es/ecma262/#sec-arrow-function-definitions-static-semantics-contains) and [async](https://tc39.es/ecma262/#sec-async-arrow-function-definitions-static-semantics-Contains)).
This PR fixes those issues.
=> Editorial: Use consistent "...generally do not look into function definitions" language

spec.html
In [B.1.4 Regular Expressions Patterns](https://tc39.es/ecma262/#sec-regular-expressions-patterns), the order of a production's alternatives is significant: "each alternative is considered only if previous production alternatives do not match".
So in the partial production
```Term :: Atom | Atom Quantifier```
the `Atom Quantifier` alternative will be considered only if the `Atom` alternative doesn't match.
But at any point where `Atom Quantifier` would match (e.g., in `/x*/u`), `Atom` would necessarily also match, thus preventing `Atom Quantifier` from ever being considered. (In such a case, the `Atom` match would result in a syntax error.)
This is clearly not the intended behavior.
(a) There's no point having an alternative that can never be used.
(b) It contradicts the guarantee that …
=> Editorial: Swap 2 alternatives of Term in Annex B

spec.html
Specifically, change:
```
AtomEscape[U, N] :: CharacterEscape[~U, ?N]
```
to:
```
AtomEscape[U, N] :: CharacterEscape[?U, ?N]
```
This fixes a bug that PR #403 introduced way back in 2016.
Resolves issue #1672 (which see for some discussion).
=> Editorial: Fix bug in Annex B defn of AtomEscape

spec.html
=> Editorial: fix number types in Array.prototype.findIndex / RegExp.prototype[Symbol.search] / {Map,Set}.prototype.size

spec.html
... i.e., by adding `[lookahead != 'else']` in the else-less `IfStatement` production.
=> Editorial: Resolve the 'dangling else' in Annex B.3.4 as in PR #1966

spec.html
It's probably wrong to call this editorial, but it's a fix for an oversight in #2164.
Integer-indexed [[[DefineOwnProperty]]](https://tc39.es/ecma262/#sec-integer-indexed-exotic-objects-defineownproperty-p-desc) is the only place where IsValidIntegerIndex is checked without being immediately preceded by an IsDetachedBuffer check, and I believe this to be a mistake.
The issue is that [IsValidIntegerIndex](https://tc39.es/ecma262/#sec-isvalidintegerindex) checks [[ArrayLength]] of the typed array itself, which is unaffected by calling [DetachArrayBuffer](https://tc39.es/ecma262/#sec-detacharraybuffer). This seems very silly and may warrant a more significant refactor, but the immediate fix is to avoid calling IsValidIntegerIndex on a typed array with a detached buffer.
=> Normative: IsDetachedBuffer should be checked before accessing [[ArrayLength]]

spec.html
This addresses the problem brought up in #2214 -- where the styles for normative optional changes were forgotten (by me) when the weakrefs merge pr was made. 
This likely isn't the best way to do this. This pr is here in case we need a stop gap solution until we clarify how best to add these styles in an accessible way. cc @bterlson, @ljharb, @michaelficarra, @syg and @bakkot.
=> Normative: add normative optional styling css override

spec.html
`[[AlreadyCalled]]` fields in `Promise.all` and `Promise.any` doesn't have to be a Record
Discussion https://github.com/tc39/ecma262/pull/2040#discussion_r454699178
=> Editorial: Simplify Promise.all and Promise.any

CONTRIBUTING.md
I couldn't find a link to this in the contributing doc.  I think it is a useful link.
=> Meta: Add link to tc39/template-for-proposals

spec.html
... according to the format set out in PR #1981.
(GitHub lists the commits out of order, but `git log` gets it right.)
----
The first 6 commits are for internal methods:
- The first 2 are a some preparatory work.
- The third is the main conversion.
- The next 3 fill in some missing parameter types.
For the last of these (`[[Construct]]`'s `_newTarget_`), I said "an Object", but we could use the more precise "a constructor function object".
----
The next 4 are for Environment Record concrete methods:
- The first two are some preparatory work.
- The third is the main conversion.
- The fourth moves the target-alias declaration from the algorithm up to the preamble.
----
The last 2 are for Module Record concrete methods:
- The first is the main conversion.
- The second moves the target-alias …
=> Editorial: Standardize preambles for internal methods and concrete methods

spec.html
Discovered [here](https://github.com/keithamus/proposal-array-last/pull/9#discussion_r164578959).
The spec seems to use `is 0` most often for comparing to zero, specifically with the results of a `ToLength` call, which can not return anything `<= 0` besides positive zero.
An equally valid and consistent alternative would be replacing all the `is 0` instances with `is zero`, if we'd find that clearer.
=> Editorial: use "is 0" instead of "is zero" for consistency

spec.html
Fixes https://github.com/tc39/ecma262/issues/2206. Quoting @michaelficarra there:
> As per today's editor call, we will mark this change as normative but make the change without asking for consensus (as a spec bugfix) since it matches with what we believe the intent of the committee to have been and with all known implementations.
I hope "when parsing text for JSON.parse" is sufficiently clear. I could make it more precise by labelling the step in JSON.parse which calls ParseText and then referring directly to that step, but that seemed like overkill.
This PR has two commits: the first makes the change, and the second rewords the prose list of conditions to be an HTML list, which I think reads better. I'm happy to back out the second if people dislike the style. If we keep it, the two …
=> Normative: do not apply Early Error for duplicate __proto__ properties when performing JSON.parse

spec.html
Resolves #2208.
This behavior is necessitated by web reality and tied to #2164 (although the OOB path is technically separate).
@syg and I chatted about whether the (non-normative) description of [[Set]] in [Table 6](https://tc39.es/ecma262/#table-essential-internal-methods) needs to be updated and concluded "no" for two reasons:
1. It is extremely difficult to update this verbiage to be exhaustive without explicit mention of typed arrays.
2. The meaning of the verb "set" is already ambiguous thanks to userland setters. In other words, it can be argued that the property value was "set" just by virtue of having entered IntegerIndexedElementSet.
=> Normative: IntegerIndexedElementSet should always indicate success

spec.html
The initial value of a 'length' property should be a Number, so use the appropriate notation, after PR #2007.
=> Editorial: Use Number-literal notation for a few 'length' values

spec.html
HTML doesn't allow a `<ul>` within a `<p>`.
=> Markup: Move ul-within-p to outside the p

spec.html
There's a few differences here:
- It talks about the referenced token sequences being a _prefix_ of the following sequence, which I believe was always the intent (resolving the issue mentioned in [this comment](https://github.com/tc39/ecma262/pull/2227#issuecomment-727093111)).
- It describes how to handle the case where the following token sequence is ambiguous, namely, by only allowing lookahead restrictions for which the ambiguity cannot matter (resolving the issue mentioned in [this comment](https://github.com/tc39/ecma262/pull/2227#issuecomment-727095436)).
- It only ever talks about sequences of tokens, never individual tokens (and therefore subsumes https://github.com/tc39/ecma262/pull/1828). 
- It removes the restriction that sequences be of length 1 or 2. I think the point of …
=> Editorial: reword definition of lookahead restrictions

spec.html
Closes #2231
@conrad-watt does this look like what you had in mind?
I am labeling this normative **but not** needs consensus because I don't believe there is a reasonable way to implement the currently specified strong behavior, nor do implementations implement the strong version. Neither ARM's load and store exclusive instructions nor x86's `cmpxchg` unconditionally perform a read-modify-write as the spec currently requires.
Let's merge this now and inform the committee at the next plenary.
=> Normative: Relax the strength of Atomics.compareExchange
